### ISSUE TITLE
runOnDemand stops after 10sec

### ISSUE THREAD

**Issue by NickSurin** [aler9/rtsp-simple-server#1000]
## Which version are you using?

v0.19.1

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

runOnDemand stops after 10sec

## Describe how to replicate the issue
1 get The Prodigy - 'Breathe'-rmHDhAohJlQ.mkv file)))
2. add to default config 
paths:
  prodigy:
    runOnDemand: ffmpeg -hide_banner -loglevel error  -re -stream_loop -1 -i "The Prodigy - 'Breathe'-rmHDhAohJlQ.mkv" -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnDemandRestart: yes

4. start rtsp-simple-server
5. go to http://localhost:8888/prodigy/

## Did you attach the server logs?
2022/06/22 14:48:30 INF rtsp-simple-server v0.19.1
2022/06/22 14:48:30 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/06/22 14:48:30 INF [RTMP] listener opened on :1935
2022/06/22 14:48:30 INF [HLS] listener opened on :8888
2022/06/22 14:48:31 INF [HLS] [muxer prodigy] created (requested by 127.0.0.1:60056)
2022/06/22 14:48:31 INF [path prodigy] runOnDemand command started
2022/06/22 14:48:31 INF [RTSP] [conn 127.0.0.1:60588] opened
2022/06/22 14:48:31 INF [RTSP] [session 105756949] created by 127.0.0.1:60588
2022/06/22 14:48:31 INF [RTSP] [session 105756949] is publishing to path 'prodigy', 2 tracks with UDP
2022/06/22 14:48:31 INF [HLS] [muxer prodigy] is converting into HLS
2022/06/22 14:48:41 INF [path prodigy] runOnDemand command stopped
2022/06/22 14:48:41 INF [RTSP] [session 105756949] destroyed (terminated)
2022/06/22 14:48:41 INF [HLS] [muxer prodigy] destroyed (terminated)
2022/06/22 14:48:41 INF [RTSP] [conn 127.0.0.1:60588] closed (session not found)
2022/06/22 14:48:41 INF [HLS] [muxer prodigy] created (requested by 127.0.0.1:60056)
2022/06/22 14:48:41 INF [path prodigy] runOnDemand command started
2022/06/22 14:48:41 INF [RTSP] [conn 127.0.0.1:60610] opened
2022/06/22 14:48:41 INF [RTSP] [session 684746594] created by 127.0.0.1:60610
2022/06/22 14:48:41 INF [RTSP] [session 684746594] is publishing to path 'prodigy', 2 tracks with UDP
2022/06/22 14:48:41 INF [HLS] [muxer prodigy] is converting into HLS
2022/06/22 14:48:46 INF shutting down gracefully
2022/06/22 14:48:46 INF [HLS] [muxer prodigy] destroyed (terminated)
2022/06/22 14:48:46 INF [path prodigy] runOnDemand command stopped
2022/06/22 14:48:46 INF [RTSP] [conn 127.0.0.1:60610] closed (terminated)
2022/06/22 14:48:46 INF [RTSP] [session 684746594] destroyed (terminated)
2022/06/22 14:48:46 INF [RTSP] listener is closing
2022/06/22 14:48:46 INF [HLS] listener is closing
2022/06/22 14:48:46 INF [RTMP] listener is closing
2022/06/22 14:48:46 INF waiting for external commands

**Comment by aler9** [comment]
fixed in v0.19.2.
