### ISSUE TITLE
Using libcamera-vid

### ISSUE THREAD

**Issue by cedricve** [aler9/rtsp-simple-server#1010]
## Describe the feature

Description

I'm trying to inject a raspberry pi camera (h264) stream into FFMPEG from within the `rtsp-simple-server.yaml` file. When running this from outside the container this works as expected, the stream is being forwarded to the rtsp server, and I can SETUP a connection from VLC.

    libcamera-vid -t 0 --inline -o - | ffmpeg -i pipe: -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH

However when trying to run this from within the config, I'm getting a series of `exit code 0`.

    cam:
      runOnInit: libcamera-vid -t 0 --inline -o - | ffmpeg -i pipe: -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
      runOnInitRestart: yes

Any thoughts? I looked at the examples here (https://github.com/aler9/rtsp-simple-server#from-a-raspberry-pi-camera) but this is no longer applicable I assume (dont work with latest version)

**Comment by stevewells20** [comment]
Here is what I have working:

`rtsp-simple-server.yml`
`paths:
  cam:
    runOnInit:
    runOnInitRestart: yes`

Then run in terminal:
`libcamera-vid -t 0 --width 1280 --height 1080 --codec h264 -n  --autofocus 1 --shutter 0 --vflip --hflip  --profile=high   --framerate 15 -o - | gst-launch-1.0 fdsrc ! h264parse  ! rtspclientsink location=rtsp://$SERVER_IP:$SERVER_PORT/cam`

That being said, it is extremely slow for me. I'm only getting like 1/7 FPS, not sure why.

**Comment by aler9** [comment]
moved here #1011

**Comment by aler9** [comment]
Raspberry Pi camera is supported natively since v0.20.0. Please take a look at the [README](https://github.com/aler9/rtsp-simple-server#from-a-raspberry-pi-camera) in order to enable the feature.
