### ISSUE TITLE
Implement native support for the Raspberry Pi Camera

### ISSUE THREAD

**Issue by aler9** [aler9/rtsp-simple-server#1011]
## Describe the feature

The method for using the Raspberry Pi camera with rtspss [described in the README](https://github.com/aler9/rtsp-simple-server#from-a-raspberry-pi-camera) doesn't work anymore due to a Raspberry Pi OS upgrade and the switch to 64 bits arch.

An optimal solution consists into implementing native support for the Raspberry Pi camera directly into server, by interfacing with the native API.

Steps:

1. find a way to interact with dynamic libraries. This is currently impossible since the server is compiled without clib support in order to improve compatibility. We have to find a way to interact with dynamic libraries and at the same time keep compatibility as broader as possible. Maybe the server can be released with two executables, one for generic aarch 64, and the other for the Raspberry Pi OS aarch 64.

2. interact with camera APIs / [MMAL interface](https://github.com/raspberrypi/userland/blob/master/interface/mmal/mmal.h) in order to extract H264 and make it available.

**Comment by DevelopDaily** [comment]
>Maybe the server can be released with two executables, one for generic aarch 64, and the other for the Raspberry Pi OS aarch 64.

I think that approach is quite reasonable. Just a friendly reminder. Raspberry Pi also had to compromise by releasing two distinct operating systems. 
![pios](https://user-images.githubusercontent.com/54299975/177375716-e6b4d6d8-d3f1-4950-a126-8807f24bfe6c.png)

Taking care of the compatibility may be too difficult or not worth the time. Raspberry Pi seems to focus on Pi OS. I guess Pi OS (Legacy) would eventually go away. https://www.raspberrypi.com/news/new-old-functionality-with-raspberry-pi-os-legacy/

**Comment by aler9** [comment]
Raspberry Pi camera is supported natively since v0.20.0. I chose to support the newer OS (bullseye), both 32-bit and 64-bit. Please take a look at the [README](https://github.com/aler9/rtsp-simple-server#from-a-raspberry-pi-camera) in order to enable the feature.
