### ISSUE TITLE
Need to open all UDP ports even when default UDP port is 8000

### ISSUE THREAD

**Issue by karanmartian** [aler9/rtsp-simple-server#1020]
Hi,

The server is configured by default to deal with UDP packets on port 8000. But on my ec2 server in the cloud i have to open all UDP ports in order for client to get video data. What is the exact range of UDP ports utilized and how can I keep it constant?

**Comment by aler9** [comment]
1) use the [issue template](https://github.com/aler9/rtsp-simple-server/issues/new?assignees=&labels=&template=bug.md&title=) otherwise the issue will be inevitably closed.

2) the server uses UDP ports 8000 and 8001 as clearly stated in the configuration file. There are no other UDP ports involved.

**Comment by karanmartian** [comment]
I am referring to this please, you can clearly see the server logs its using all higher order UDP ports with each client connection like 50066, 50068, 60564 etc

2022/07/08 19:37:12 INF [RTSP] [conn 3.110.231.76:50066] opened
2022/07/08 19:37:12 INF [RTSP] [session 940436013] created by 3.110.231.76:50066
2022/07/08 19:37:12 INF [RTSP] [session 940436013] is reading from path 'mystream', 2 tracks with UDP
2022/07/08 19:38:00 INF [RTSP] [session 940436013] destroyed (teared down by 3.110.231.76:50066)
2022/07/08 19:38:00 INF [RTSP] [conn 3.110.231.76:50066] closed (EOF)
2022/07/09 08:01:55 INF [RTSP] [conn 3.110.231.76:50068] opened
2022/07/09 08:01:55 INF [RTSP] [session 219357534] created by 3.110.231.76:50068
2022/07/09 08:01:55 INF [RTSP] [session 219357534] is reading from path 'mystream', 2 tracks with UDP
2022/07/09 08:02:18 INF [RTSP] [session 219357534] destroyed (teared down by 3.110.231.76:50068)
2022/07/09 08:02:18 INF [RTSP] [conn 3.110.231.76:50068] closed (EOF)
2022/07/09 08:03:23 INF [RTSP] [conn 127.0.0.1:60564] opened
2022/07/09 08:03:23 INF [RTSP] [session 774692581] created by 127.0.0.1:60564
2022/07/09 08:03:23 INF [RTSP] [session 774692581] is reading from path 'mystream', 2 tracks with TCP
2022/07/09 08:05:01 INF [RTSP] [conn 127.0.0.1:60564] closed (terminated)
2022/07/09 08:05:01 INF [RTSP] [session 774692581] destroyed (teared down by 127.0.0.1:60564)

**Comment by aler9** [comment]
Those are TCP client ports, not UDP sever ports, but again, i won't discuss it in an issue opened without following the rules.
