### ISSUE TITLE
Multiple UDP ports opening with each new client connection during RTSP

### ISSUE THREAD

**Issue by karanmartian** [aler9/rtsp-simple-server#1022]
## Which version are you using?

v0.19.2

## Which operating system are you using?

- [X] Linux amd64 standard - Ubuntu 22.04

## Describe the issue

Description

Multiple UDP ports are opening with each client connection. Only one TCP port is used definitely during RTSP but multiple UDP ports are opening.

1. start the server
2. start rtsp stream
3. have a client listen on the rtsp stream
4. See the server logs below for UDP ports that are being opened -> 50066, 50068, 60564 with each new client connection.

## Did you attach the server logs?
yes

2022/07/08 19:37:12 INF [RTSP] [conn 3.110.231.76:50066] opened
2022/07/08 19:37:12 INF [RTSP] [session 940436013] created by 3.110.231.76:50066
2022/07/08 19:37:12 INF [RTSP] [session 940436013] is reading from path 'mystream', 2 tracks with UDP
2022/07/08 19:38:00 INF [RTSP] [session 940436013] destroyed (teared down by 3.110.231.76:50066)
2022/07/08 19:38:00 INF [RTSP] [conn 3.110.231.76:50066] closed (EOF)
2022/07/09 08:01:55 INF [RTSP] [conn 3.110.231.76:50068] opened
2022/07/09 08:01:55 INF [RTSP] [session 219357534] created by 3.110.231.76:50068
2022/07/09 08:01:55 INF [RTSP] [session 219357534] is reading from path 'mystream', 2 tracks with UDP
2022/07/09 08:02:18 INF [RTSP] [session 219357534] destroyed (teared down by 3.110.231.76:50068)
2022/07/09 08:02:18 INF [RTSP] [conn 3.110.231.76:50068] closed (EOF)
2022/07/09 08:03:23 INF [RTSP] [conn 127.0.0.1:60564] opened
2022/07/09 08:03:23 INF [RTSP] [session 774692581] created by 127.0.0.1:60564
2022/07/09 08:03:23 INF [RTSP] [session 774692581] is reading from path 'mystream', 2 tracks with TCP
2022/07/09 08:05:01 INF [RTSP] [conn 127.0.0.1:60564] closed (terminated)
2022/07/09 08:05:01 INF [RTSP] [session 774692581] destroyed (teared down by 127.0.0.1:60564)

## Did you attach a network dump?
no not needed

Why is this important?
Because I am streaming from Raspberry Pi which is behind a firewall to a remote server and not able to get it working via ngrok. I want to restrict UDP port to one or a few ports only.

**Comment by karanmartian** [comment]
My main question is how do I get this to work via ngrok? when the rtsp server and client are behind different firewalls.

**Comment by aler9** [comment]
Again, you are mistaken, those are TCP ports and are client ports.
Client ports are chosen by the client, that's how the entire internet works.

**Comment by karanmartian** [comment]
Can you please not close topic like this, I am not understanding how to get this to work around firewalls. I have tried a lot of stuff so please help me. How do you get this to work via ngrok with client and server behind different firewalls?

**Comment by aler9** [comment]
In order to use rtsp-simple-server (or any other server) behind a firewall, you have to configure that firewall in order to:

- allow incoming connections to the server ports, that in this case are TCP 8554 UDP 8000, UDP 8001
- allow outgoing packets from existing connections

That's all, and it's a procedure valid for almost any server. Maybe you're missing the second point, anyway it's firewall specific so the procedure depends on the specific firewall.

**Comment by aler9** [comment]
Ngrok only allows to proxy TCP ports, not UDP ports.
You have to either bypass ngrok or use `protocols: [tcp]` inside the configuration, in order to force all traffic to pass through TCP port 8554.
Anyway, again, this is not a server issue.

**Comment by karanmartian** [comment]
I know its not server issue but its something I believe will be tremendously helpful to someone down the line because this is a common situation and your server is really good. I am forcing TCP only in the command line like this:
ffmpeg -re -stream_loop -1 -i test.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:8554/mystream

and having ngrok forward port 8554. I am just insanely puzzled by the fact that why would rtsp.me and other online players be able to read the stream fine but not with simple ffmpeg command line?
ffmpeg -i rtsp://0.tcp.in.ngrok.io:14736/mystream -c copy output.mp4

I would really appreciate any possible inputs/thoughts from your side.

**Comment by karanmartian** [comment]
Actually I figured it out and its working now over TCP. I have to do this on receiver side:

ffmpeg -rtsp_transport tcp -i rtsp://0.tcp.in.ngrok.io:14736/mystream -c copy output.mp4
