### ISSUE TITLE
"stdout" log destionation actually outputting to stderr

### ISSUE THREAD

**Issue by asdfisdffdg** [aler9/rtsp-simple-server#1042]
## Which version are you using?

v0.19.2

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

in rtsp-simple-server.yml log is set to "stdout"

```yaml
# Destinations of log messages; available values are "stdout", "file" and "syslog".
logDestinations: [stdout]
```

but apparently it's actually stderr
![image](https://user-images.githubusercontent.com/103386533/179120086-a25facb8-6b09-4a7b-90b0-d7274acae32a.png)

## Describe how to replicate the issue

start program with stdout piped to one file and stderr to other
```
./rtsp-simple-server >stdout 2>stderr
```
all output is in `stderr` file

## Did you attach the server logs?

 no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Thanks, this has been fixed.

**Comment by aler9** [comment]
added in v0.19.3
