### ISSUE TITLE
Improve HE-AAC support

### ISSUE THREAD

**Issue by aler9** [aler9/rtsp-simple-server#1068]
## Describe the feature

Originally discussed in #1067 

Missing features:

* [ ] ability to publish/read HE-AAC tracks from/to RTMP
* [ ] ability to parse HE-AAC into gortsplib and therefore convert tracks from RTSP to RTMP/HLS

**Comment by aler9** [comment]
@Kiennh could you prove a HE-AAC sample file? thanks

**Comment by Kiennh** [comment]
@aler9 
Sample file:
[h264_heaac.flv.zip](https://github.com/aler9/rtsp-simple-server/files/9259004/h264_heaac.flv.zip)


and command to push 

```
ffmpeg -stream_loop -1 -re -i h264_heaac.flv -c copy   -f flv rtmp://localhost:1935/live/abc

```

**Comment by aler9** [comment]
HE-AAC is now supported since v0.20.0
