### ISSUE TITLE
unhandled method 'PAUSE'

### ISSUE THREAD

**Issue by paken7620** [aler9/rtsp-simple-server#107]
## Which version are you using?

v0.12.0

## Which operating system are you using?

Linux

## Describe the problem

I am receiving a stream from ffmpeg and playing back on a network speaker. When the network speaker needs to interrupt the music, it sends a PAUSE command. When that happens, I get the following error in rtsp-simple-server:

2020/11/03 09:24:20 [2/1/1] [client 1.2.3.4:43098] PAUSE
2020/11/03 09:24:20 [2/1/1] [client 1.2.3.4:43098] ERR: unhandled method 'PAUSE'
2020/11/03 09:24:20 [1/1/0] [client 1.2.3.4:43098] disconnected
2020/11/03 09:24:25 [2/1/0] [client 1.2.3.4:43099] connected
2020/11/03 09:24:25 [2/1/0] [client 1.2.3.4:43099] PLAY
2020/11/03 09:24:25 [2/1/0] [client 1.2.3.4:43099] ERR: client is in state 'Initial' instead of 'PrePlay'
2020/11/03 09:24:25 [1/1/0] [client 1.2.3.4:43099] disconnected

Is there a setting I can put in the yml to handle this? Or anything you can change?

**Comment by aler9** [comment]
Hello, the PAUSE command is currently not supported but of course i'm interested in supporting it and i consider this a bug; could you tell me the name of the network speaker, or alternatively the name of a software which uses the PAUSE commands? thanks

**Comment by paken7620** [comment]
I am using the Grandstream GSC3505. It's a SIP speaker that can play music, and then pages, and announcements can barge in. When it's in manual mode it just sends a disconnect when something barges in, but in "auto" mode, it attempts to pause in order to resume when the interruption is finished. I would be happy to pull any kind of debugging that might help, just let me know what you need.

**Comment by aler9** [comment]
Hello, PAUSE has been implemented in master, but of course i can't test it against the Grandstream GSC3505 - please use one of the attached binaries and tell me if it works. Thanks.

[rtsp-simple-server_v0.12.0-9-gac032c4_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5505480/rtsp-simple-server_v0.12.0-9-gac032c4_windows_amd64.zip)
[rtsp-simple-server_v0.12.0-9-gac032c4_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5505481/rtsp-simple-server_v0.12.0-9-gac032c4_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.12.0-9-gac032c4_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5505482/rtsp-simple-server_v0.12.0-9-gac032c4_linux_arm7.tar.gz)
[rtsp-simple-server_v0.12.0-9-gac032c4_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5505483/rtsp-simple-server_v0.12.0-9-gac032c4_linux_arm6.tar.gz)
[rtsp-simple-server_v0.12.0-9-gac032c4_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5505484/rtsp-simple-server_v0.12.0-9-gac032c4_linux_amd64.tar.gz)
[rtsp-simple-server_v0.12.0-9-gac032c4_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5505485/rtsp-simple-server_v0.12.0-9-gac032c4_darwin_amd64.tar.gz)

**Comment by aler9** [comment]
added in v0.12.1

**Comment by paken7620** [comment]
That worked perfectly!

Thank you so much!

**Comment by paken7620** [comment]
Ok... so I should not have said perfectly. What you did worked, but apparently when this device get a call it pauses every time it wants to play the ringtone (I know this is stupid, and I'm working with Grandstream to get them to stop). The effect is that it's sending the PAUSE command multiple times in a row.

Here's the log message:

Nov 11 18:16:47 svc06 rtsp-simple-server[635]: 2020/11/11 18:16:47 [2/1/1] [client ] is reading from path 'GSStream', 1 track with udp
Nov 11 18:22:16 svc06 rtsp-simple-server[635]: 2020/11/11 18:22:16 [2/1/1] [client ] PAUSE
Nov 11 18:22:39 svc06 rtsp-simple-server[635]: 2020/11/11 18:22:39 [2/1/0] [client ] PAUSE
Nov 11 18:22:39 svc06 rtsp-simple-server[635]: 2020/11/11 18:22:39 [2/1/0] [client ] ERR: client must be in state [Play Record], while is in state PrePlay
Nov 11 18:22:39 svc06 rtsp-simple-server[635]: 2020/11/11 18:22:39 [1/1/0] [client ] disconnected

**Comment by aler9** [comment]
Since i didn't know about any other software that supports PAUSE, i just followed the specification, without knowing this behavior - i'm gonna post another nightly release here, please test it this time so i can produce a working release.

**Comment by aler9** [comment]
please test this nightly release
[rtsp-simple-server_v0.12.1-2-g584d2c9_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5527024/rtsp-simple-server_v0.12.1-2-g584d2c9_windows_amd64.zip)
[rtsp-simple-server_v0.12.1-2-g584d2c9_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5527025/rtsp-simple-server_v0.12.1-2-g584d2c9_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.12.1-2-g584d2c9_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5527026/rtsp-simple-server_v0.12.1-2-g584d2c9_linux_arm7.tar.gz)
[rtsp-simple-server_v0.12.1-2-g584d2c9_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5527027/rtsp-simple-server_v0.12.1-2-g584d2c9_linux_arm6.tar.gz)
[rtsp-simple-server_v0.12.1-2-g584d2c9_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5527028/rtsp-simple-server_v0.12.1-2-g584d2c9_linux_amd64.tar.gz)
[rtsp-simple-server_v0.12.1-2-g584d2c9_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5527029/rtsp-simple-server_v0.12.1-2-g584d2c9_darwin_amd64.tar.gz)

**Comment by paken7620** [comment]
ok, so far so good. 

with the nightly, I actually see that they send a pause to play the ringtone, and then when it stops, it sends pause again and then plays (that seems dumb, but rtsp-simple-server is handling it now). 

I will run this through the ringer for the next couple of days to see if I run into anything else, but so far it's good.

**Comment by paken7620** [comment]
I have been running this all day yesterday with the Grandstream sending several PAUSE commands and it worked without fail the entire time. 

It looks like your change has solved it.

Thank you again!

**Comment by paken7620** [comment]
Just and update that this is still working, with no further issues

**Comment by aler9** [comment]
added in v0.12.2
