### ISSUE TITLE
Unable to distinguish between rtmp and rtmps connections

### ISSUE THREAD

**Issue by tbnguyen1407** [aler9/rtsp-simple-server#1099]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

RTMP/RTMPS readers use same type (rtmpConn), unlike RTSP/RTSPS readers which use separate types (rtspSession/rtspsSession)

```
GET /v1/paths/list

{
  "items": {
    "9484f126384c31f6ac9fa89d0cc96b74": {
      ...
      "readers": [
        {
          "type": "rtspsSession",
          "id": "732443073"
        },
        {
          "type": "rtspSession",
          "id": "655152465"
        },
        {
          "type": "rtmpConn",
          "id": "271786808"
        },
        {
          "type": "rtmpConn",
          "id": "699334552"
        }
      ]
    }
  }
}
```

## Describe how to replicate the issue

1. start the server
2. publish/proxy with any valid stream
3. start 2 consumers for RTMP and RTMPS
4. call `GET /v1/paths/list`
5. Observe path has 2 readers of same type

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
This has been fixed, thanks
