### ISSUE TITLE
Feature Request: Basic Authentication Support

### ISSUE THREAD

**Issue by JeffIPvideo** [aler9/rtsp-simple-server#11]
Can we get support to use different modes of authentication. basic, digest, both.
VLC does not work with digest authentication

**Comment by aler9** [comment]
Hello, now authenticating with VLC is fully supported (v0.6.4)
Basic auth was implemented.
I also discovered that VLC does support digest authentication, just a very strict version of it.

**Comment by JeffIPvideo** [comment]
Is there a flag to switch authentication modes or does it try the password under both authentication modes?

**Comment by aler9** [comment]
Hi,
The server offers both authentication modes, the client can choose one of them and proceed. There's no flag to disable one of the modes.
Regarding VLC, if the server supports both Digest and Basic, VLC uses Digest, otherwise Basic. I did not checked if there's a flag to force a specific mode.
