### ISSUE TITLE
Cannot read a nest-rtsp stream

### ISSUE THREAD

**Issue by cad1231** [aler9/rtsp-simple-server#1114]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I am trying to have an output from the nest-rtsp project into rtsp-simple-server. I get the following error in my logs:

`2022/08/22 10:15:44 INF [path nest] [rtsp source] ERR: invalid transport header: invalid ports (undefined-undefined)`

For context, nest-rtsp is a nodeJS software that uses the Google Smart Device Management API to pull a stream from a Nest camera. Google requires a pretty complex authentication mechanism, re-authentication every five minutes and a new RTSP URL every hour. Nest-rtsp authomates all that and uses ffmpeg to publish its own continuous RTSP stream at a consistent path. The source code of the project can be found at this [gitlab repo](https://gitlab.jak.guru/jakg/nest-rtsp).

I want to take the stream from nest-rtsp and use rtsp-simple-server to save the video from my Nest camera. However, rtsp-simple-server seems not to be able to read the stream. I have two other cameras (non-nest) that rtsp-simple-server can handle correctly.

## Describe how to replicate the issue

1. start the server
2. add the following to rtsp-simple-server.yml under "paths":
`  nest:
       source: rtsp://nest-rtsp.home:554/driveway`

3. the stream fails to load with the message in the log described above.

## Did you attach the server logs?

yes

## Did you attach a network dump?

no

I have a network dump, but don't want to post the whole thing in case it gives away sensitive info about my network. I can send it via PM or, if you tell me what to look for in it, I can use wireshark to go through it and post the relevant bits.

**Comment by aler9** [comment]
Hello, send the network dump to aler9.dev@gmail.com - thanks

**Comment by cad1231** [comment]
Sent, thank you!

**Comment by aler9** [comment]
Hello, the network dump shows that nest-rtsp generates this SETUP response:

```
RTSP/1.0 200 OK 
CSeq: 3 
Date: Mon, 22 Aug 2022 14:37:04 GMT 
Session: 59b3dfd0-feae-4daf-966d-c348255a6099;timeout=30 
Transport: RTP/AVP;unicast;client_port=49080-49081;mode=play;server_port=undefined-undefined 
```

`server_port` values are `undefined` and therefore invalid, it's a `nest-rtsp` issue. Of course the server can be adapted to support ports with the `undefined` value, but in my opinion it would be better to edit `nest-rtsp`. BTW, by looking at `nest-rtsp` code, it looks like the `server_port` field got recently changed with [this commit](https://gitlab.jak.guru/jakg/nest-rtsp/-/commit/30fe58911d0079a4f8965cad13d8137e01d95bb2).

Try to upgrade `nest-rtsp`, and if it still doesn't work, contact its author.

**Comment by cad1231** [comment]
Thanks! I am using the master version and double checked my files -- they already contain the patch you linked to. This could be a bug in nest-rtsp -- I left a bug report for its creator here: https://bugs.jak.guru/show_bug.cgi?id=12. Thanks for looking into this!
