### ISSUE TITLE
Corrupt AAC decoding with Media Foundation Client

### ISSUE THREAD

**Issue by jazzy348** [aler9/rtsp-simple-server#112]
## Which version are you using?

v0.12.0

## Which operating system are you using?

Windows / Linux

## Describe the problem

When using a client built around the Media Foundation API, video comes through fine but audio is corrupt and glitchy, is there a work around for this?

Kind regards,
Jazzy.

**Comment by aler9** [comment]
Hello,
1. try disabling UDP and see if there's a difference:
```yml
protocols: [tcp]
```

2. i need additional details to replicate this:
    * is the Media Foundation API-based client publishing or reading?
    * if the Media Foundation API-based client is publishing, who is reading, or vice-versa?

**Comment by jazzy348** [comment]
Hi,

I've tried TCP only, this did not solve the issue.

Client is reading, FFMPEG is publishing. Command to publish is

ffmpeg -re -i sample.mp4 -c:a aac -c:v libx264 -f rtsp rtsp://xxxx

**Comment by aler9** [comment]
Can you post a sample code of the client in order to allow me to replicate the issue? it's not an easy task to build a client from scratch, so i need the code. Thanks

**Comment by jazzy348** [comment]
Hi,

The only client I have is Unity based, trial package can be downloaded from here: http://downloads.renderheads.com/2020/UnityPlugin-AVProVideo-Latest-Trial.unitypackage

Sorry for the work!

**Comment by asleeponduty** [comment]
Sorry to bump an old issue, but was this resolved on either of your ends? 
I am seeing the same issues @jazzy348 is having as well. 
Same setup as well - using the Media Foundation player in Unity via the AVPRO bindings. 
Like Jazzy, ffplay/vlc/mpv do not have any issues with playback. Likely this is because these don't use the media foundation api as their backend.

The simplest way to test if the stream is working is to install Unity2019 and import the package as linked above by Jazzy. 
I've confirmed this package can work with RTSP streams by opening one from a Wowza server with the same encoding.

**Comment by asleeponduty** [comment]
Attached, for convenience, is the PCAPS comparing this against wowza when the client is this Media Foundation player
[RTSP-PCAP.zip](https://github.com/aler9/rtsp-simple-server/files/6463024/RTSP-PCAP.zip)

Please reach out if you would like more information

**Comment by jazzy348** [comment]
Hi, we did manage to resolve the issue. In SDP set "MPEG4_GENERIC" to lower case and set track 0 to be audio, track 1 for video.

**Comment by asleeponduty** [comment]
@aler9 Looking through Jazzy's linked issue, it seems like the SDP is not in compliance for the mpeg4 MIME - 

From AndrewRH:

> [...] Unfortunately the code that handles RTSP is inside Microsoft's Media Foundation DLLs so we cannot change this behaviour. Hopefully your server can instead send lower-case version.
>
> I'm also not sure that uppercase is valid. Looking at the documentation:
>
> Here you can see the list of mime-types, and while many are uppercase, mpeg4-generic is lower-case:
> https://www.iana.org/assignments/media-types/media-types.xhtml
> https://www.iana.org/assignments/media-types/video/mpeg4-generic
> https://tools.ietf.org/html/rfc5691#section-5.2
>
> I'm not certain that RFC 2045 section 5.1 applies to SDP.

Would you consider renaming this issue to "MPEG-4 Generic MIME needs to be lowercase"?
Or, should I open this as an issue on the aler9/gortsplib repo?
