### ISSUE TITLE
UDP ports not released after shutdown on OS X

### ISSUE THREAD

**Issue by zevarito** [aler9/rtsp-simple-server#114]
## Which version are you using?

v0.12.0

## Which operating system are you using?

Mac

## Describe the problem

Start server, shutdown, try to start it again and server cannot re-bind to configured UDP ports.

**Comment by aler9** [comment]
Hello, unfortunately i don't have a Mac (well, i have, but it's running Linux) so i can't test this directly.
At the moment, the shutdown phase is handled entirely to Golang and is not implemented manually.
I'll post here a nightly release that handles the shutdown phase manually and shuts down manually all sockets, and we'll see if it solves the problem.

**Comment by zevarito** [comment]
@aler9 that would be great, thanks!

**Comment by aler9** [comment]
here is the nightly release
[rtsp-simple-server_v0.12.0-11-g6c112f3_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5505641/rtsp-simple-server_v0.12.0-11-g6c112f3_windows_amd64.zip)
[rtsp-simple-server_v0.12.0-11-g6c112f3_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5505643/rtsp-simple-server_v0.12.0-11-g6c112f3_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.12.0-11-g6c112f3_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5505644/rtsp-simple-server_v0.12.0-11-g6c112f3_linux_arm7.tar.gz)
[rtsp-simple-server_v0.12.0-11-g6c112f3_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5505645/rtsp-simple-server_v0.12.0-11-g6c112f3_linux_arm6.tar.gz)
[rtsp-simple-server_v0.12.0-11-g6c112f3_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5505646/rtsp-simple-server_v0.12.0-11-g6c112f3_linux_amd64.tar.gz)
[rtsp-simple-server_v0.12.0-11-g6c112f3_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5505647/rtsp-simple-server_v0.12.0-11-g6c112f3_darwin_amd64.tar.gz)

**Comment by zevarito** [comment]
@aler9 I've tested latest preview release and seems to still be failing:

* start server
* publish once
* stop server & restart

```
2020/11/09 09:31:55 [0/0/0] rtsp-simple-server v0.12.0-11-g6c112f3
2020/11/09 09:31:55 ERR: listen udp :8000: bind: address already in use
```

I wonder if this might be related to GStreamer somehow? But pipeline is closed and even if it was still running don't think this should be an issue.

**Comment by aler9** [comment]
Hello, i finally tried the server on macOS (11.0.1), and i have to say that UDP sockets are correctly shut down when the server closes.

I tried
* without publishers: the server is started, is closed with CTRL+C and started again
* with publishers: the server is started, a publisher connects and starts publishing, the server is closed wit CTRL+C and started again
* with hot reloading: the server is started, the configuration file is changed to disable udp, the is changed again th re-enable udp

To replicate the issue, i need additional informations:
* What publisher are you using?
* Does the issue appear only after someone publishes a stream or is present even when the server is closed before someone publishes something?
* Are you sure no one else is using the port? check with `lsof -i -P | grep UDP`

**Comment by zevarito** [comment]
Hi @aler9 nice you could try, let me answer your questions:

> What publisher are you using?
I am using a basic GStreamer pipeline which takes RTP packets and does RtspClientSink

> Does the issue appear only after someone publishes a stream or is present even when the server is closed before someone publishes something?

I will only happen after someone publishes, if I start/restart the server without publishing everything went ok.

> Are you sure no one else is using the port? check with lsof -i -P | grep UDP
I've checked this and it seems not.

I saw you've added lot of new commits, as soon as I can I will test nightly build and check again.

Thanks!

**Comment by aler9** [comment]
How can i install Gstreamer for macOS 11? it doesn't seem to be [supported](https://gstreamer.freedesktop.org/documentation/installing/on-mac-osx.html?gi-language=c).
Please tell me the macOS version you're using and how you installed Gstreamer for mac and i'll try again to replicate. Thanks.

**Comment by zevarito** [comment]
hi @aler9 sorry, I didn't see this until today. Did you were able to figure out?
Currently I got installed GStreamer 1.18.1 with HomeBrew, before that I've installed a little older official release that was supported. I have Catalina 10.15.7. I think Homebrew is the way to go right now. Let me know if I can help you any how. I wasn't able to jump into this again, I have a lot of new commits from you to try yet, as soon as I can I would report back, thank you for your hard work.

**Comment by bbnp91** [comment]
The following brew command worked for me.

brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad

**Comment by aler9** [comment]
@bbnp91 did you experienced the same issue on macOS? (ports not released after shutdown)

**Comment by bbnp91** [comment]
I'm not using Mac OS as my main server host but have just tried the highly release posted in this chain - with no issues. 

I used gstreamer to publish to rtsp-simple-server using:
gst-launch-1.0 osxaudiosrc ! audioconvert ! opusenc ! rtspclientsink location=rtsp://127.0.0.1:8554/gst debug=true 

I am able to CTRL+C Server and start it again without the reported issue.

**Comment by aler9** [comment]
I also tried on the mac and everything worked for me, i did the following:
1. update to macOS 11.1
2. install homebrew
3. brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-rtsp-server
5. start ./rtsp-simple-server
4. in another window, gst-launch-1.0 filesrc location=file.mp4 ! qtdemux ! rtspclientsink location=rtsp.//localhost:8554/mystream

![Screenshot 2020-12-01 at 21 06 46](https://user-images.githubusercontent.com/46489434/100791581-b75bb700-3419-11eb-8d3e-3d10acaeaa19.png)

we have to find a way to replicate the issue, otherwise it cannot be solved.

**Comment by zevarito** [comment]
I've just tried same pipeline as you and it worked, please feel free to close this issue until I am able to collect more information. As a note the only difference I see is the pipeline, I am using RtpBin instead, but hard to believe it could be the problem.

**Comment by aler9** [comment]
btw i've updated the README with an example that shows how to publish multiple tracks at one with Gstreamer - i don't know if it's your case, but anyway using Gstreamer should be simpler from today on.

**Comment by tiann** [comment]
I have met the issue again:

```
2021/09/04 11:11:35 I [0/0] rtsp-simple-server v0.17.2
2021/09/04 11:11:35 I [0/0] ERR: listen udp :8000: bind: address already in use
```

And here is the `lsof -i -P | grep UDP`:

```txt
loginwind  155 weishu    9u  IPv4 0x70e29bf9d988982b      0t0  UDP *:*
rapportd   473 weishu    7u  IPv4 0x70e29bf9dbb360ab      0t0  UDP *:*
rapportd   473 weishu    8u  IPv4 0x70e29bf9dbb3463b      0t0  UDP *:*
rapportd   473 weishu   12u  IPv4 0x70e29bf9d988868b      0t0  UDP *:*
identitys  488 weishu   23u  IPv4 0x70e29bf9d98880ab      0t0  UDP *:*
WiFiAgent  495 weishu    5u  IPv4 0x70e29bf9d988634b      0t0  UDP *:*
ARDAgent   497 weishu    6u  IPv6 0x70e29bf9dbb3668b      0t0  UDP *:3283
ARDAgent   497 weishu    7u  IPv4 0x70e29bf9dbb36f5b      0t0  UDP *:3283
sharingd   515 weishu    4u  IPv4 0x70e29bf9d6f3c24b      0t0  UDP *:*
sharingd   515 weishu    8u  IPv4 0x70e29bf9d6f3d6db      0t0  UDP *:*
sharingd   515 weishu    9u  IPv4 0x70e29bf9d988663b      0t0  UDP *:*
sharingd   515 weishu   10u  IPv4 0x70e29bf9d988692b      0t0  UDP *:*
sharingd   515 weishu   24u  IPv4 0x70e29bf9dbb33d6b      0t0  UDP *:*
sharingd   515 weishu   31u  IPv4 0x70e29bf9dbb80d6b      0t0  UDP *:*
sharingd   515 weishu   32u  IPv4 0x70e29bf9dbb8134b      0t0  UDP *:*
Bartender  657 weishu    4u  IPv4 0x70e29bf9d9887dbb      0t0  UDP *:*
CleanMyMa  996 weishu    6u  IPv4 0x70e29bf9d98877db      0t0  UDP *:*
WeChat    1041 weishu    7u  IPv4 0x70e29bf9d6f3b97b      0t0  UDP *:*
WeChat    1041 weishu   16u  IPv4 0x70e29bf9d6f3bf5b      0t0  UDP *:*
studio    1872 weishu  481u  IPv6 0x70e29bf9d988953b      0t0  UDP *:60441
java      2790 weishu  230u  IPv6 0x70e29bf9d6f3adbb      0t0  UDP *:65216
```

There isn't any 8000 port. simply reboot the pc can resolve this

**Comment by tiann** [comment]
When i run `netstat -anv | grep 8000`, this is output:

```
udp46      0      0  *.8000                 *.*                                524288   9216   1355      0 0x0100 0x00000020
```

But i use `ps -A | grep 1355` there is no such process, and i `kill -9 1355` there is no such process too.

**Comment by aler9** [comment]
It's probably a Golang, mac-specific issue with UDP, unfortunately there's nothing that can be done here.
