### ISSUE TITLE
runOnDemand environment variables doesn't work as expected

### ISSUE THREAD

**Issue by JamesPoon** [aler9/rtsp-simple-server#1141]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

runOnDemand environment variables didn't work as expected

> paths:
>   "~^rtsp/(.*)$":
>     ...
>     runOnDemand: wget -O- http://192.168.1.11:8124/rtsp/play --post-data "app=rtsp&name=$(env | grep '1=' | sed 's/1=//')&path=${RTSP_PATH}&port=${RTSP_PORT}&clientid=$$&env=$(env|base64)"
>    ...

I receive the post-data like this
> app=rtsp&name=$(env | grep '1=' | sed 's/1=//')&path=${RTSP_PATH}&port=${RTSP_PORT}&clientid=$$&env=$(env|base64)
the environment variables wasn't changed

on version v0.17.13

>     runOnPublish: wget -O- http://192.168.1.11:8124/rtsp/play --post-data "app=rtsp&name=$(env | grep '1=' | sed 's/1=//')&path=${RTSP_PATH}&port=${RTSP_PORT}&clientid=$$&env=$(env|base64)"

if work fine.

## Describe how to replicate the issue

1. config paths for all

> paths: 
>   all: 
>     ...
>     runOnDemand: echo "${RTSP_PATH}/${RTSP_PORT}"
>    ...

2. start the server
3. read with vlc

> rtsp://HOST:PORT/rtsp/any

4. expected result

> /rtsp/any/8554

## Did you attach the server logs?

yes 

> rtsp-simple  | 2022/09/09 17:50:03 INF [RTSP] [conn 192.168.11.1:61928] opened
> rtsp-simple  | 2022/09/09 17:50:03 INF [path rtsp/any] runOnDemand command started
> rtsp-simple  | ${RTSP_PATH}/${RTSP_PORT}
> rtsp-simple  | 2022/09/09 17:50:03 INF [path rtsp/any] runOnDemand command exited with code 0
> rtsp-simple  | 2022/09/09 17:50:13 INF [path rtsp/any] runOnDemand command stopped
> rtsp-simple  | 2022/09/09 17:50:13 INF [RTSP] [conn 192.168.11.1:61928] closed (source of path 'rtsp/any' has timed out)

## Did you attach a network dump?

no

**Comment by fragtion** [comment]
same problem here. using `a8d1f91`

**Comment by aler9** [comment]
the runOn* parameters accept an executable as value, not a shell command, therefore you have to prefix the shell command with `sh -c`:

```
runOnDemand: sh -c 'wget -O- http://192.168.1.11:8124/rtsp/play --post-data "app=rtsp&name=$(env | grep '1=' | sed 's/1=//')&path=${RTSP_PATH}&port=${RTSP_PORT}&clientid=$$&env=$(env|base64)"'
```
