### ISSUE TITLE
LL-HLS muxer provides corrupted parts

### ISSUE THREAD

**Issue by georgy-komarov** [aler9/rtsp-simple-server#1156]
## Which version are you using?

v0.20.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [x] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

RTSP -> LL-HLS convetion sometimes fails providing corrupted parts when trying to stream Webcam in h264 format without re-encoding.
FFmpeg command: `ffmpeg -f v4l2 -input_format h264 -framerate 30 -video_size 640x480 -i /dev/video0 -c:v copy -an -f rtsp rtsp://localhost:8554/cam`

## Describe how to replicate the issue

0. Download the file
https://user-images.githubusercontent.com/13136992/190446471-dc33b2b2-c0c7-4cf6-b361-b24a102f016b.mp4
1. Start the server with LL-HLS enabled
2. Publish with `ffmpeg -re -stream_loop -1 -i file.mp4 -c copy -f rtsp rtsp://localhost:8554/cam`
3. Try to read LL-HLS with https://hls-js.netlify.app/demo
4. You will recieve segments (HTTP 200), however it is impossible to decode them properly. The following message will appear:
`The video playback was aborted due to a corruption problem or because the video used features your browser did not support - PIPELINE_ERROR_DECODE: video decode error!`

## Did you attach the server logs?

no (nothing useful in server logs)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, i replicated the issue by following the steps you posted but i didn't encounter any error and i was able to play the file correctly, although i found a regression that causes a crash in recent versions. Basically, your file contains H264 access units that are not correctly spaced in time one from the other. FFmpeg reports the issue:

```
[rtsp @ 0x564116f01a00] Non-monotonous DTS in output stream 0:0; previous: 36995117, current: 36995113; changing to 36995118. This may result in incorrect timestamps in the output file.
[rtsp @ 0x564116f01a00] Non-monotonous DTS in output stream 0:0; previous: 37943705, current: 37943705; changing to 37943706. This may result in incorrect timestamps in the output file.
```

Adjacent DTSs (36995117 and 36995118) caused the HLS muxer to crash.

Anyway, please make sure that your browser and OS are updated and able to decode H264 correctly.

![Screenshot_20230118_160132](https://user-images.githubusercontent.com/46489434/213214334-19437b2e-193f-4bf0-acc2-01ab4be1b8ee.png)

![Screenshot_20230118_163120](https://user-images.githubusercontent.com/46489434/213214320-18b7a3d8-24a2-4d70-a8c4-108aabd8ad7c.png)
