### ISSUE TITLE
Implement log levels

### ISSUE THREAD

**Issue by bbnp91** [aler9/rtsp-simple-server#116]
## Which version are you using?

v0.12

## Enhancement request

Would it be possible to add an option to the config to allow printing of source SDP's into stdout or log file?
This would help with fault finding and confirming that the server and clients are being presented with the expected SDP from encoders. 

Thanks.

**Comment by aler9** [comment]
Hello, the most correct way to do this consists in implementing log levels (debug, info, warn, error) and print SDPs and responses if the log level is "debug".

**Comment by aler9** [comment]
log levels have been implemented; now SDPs appear into the log when the "logLevel" option is set to "debug".

**Comment by aler9** [comment]
added to v0.13.0
