### ISSUE TITLE
Path added via API, doesn't actually run runOnReady command

### ISSUE THREAD

**Issue by robertmielewczyk** [aler9/rtsp-simple-server#1184]
## Which version are you using?
v0.20.0
v0.19.3

## Which operating system are you using?
- [x] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
When adding a path **via API**, runOnReady command doesn't seem to be invoked.
I cannot see any logs about command errors, or the command being invoked

## Describe how to replicate the issue
1. Start rtsp-simple-server (v 0.20.0) with API control
2. Add a path via API (let's use curl)
```bash
curl localhost:9997/v1/config/paths/add/path_name \
  -X POST \
  -H "Content-Type: application/json" \
  -d {
    "source": "publisher",
    "runOnReady":"echo hello",
    "runOnReadyRestar": false
  }
```
3. Path is added succesfully
4. Publisher publishes to path
5. runOnReady command starts 
6. (BUG) Nothing happens a simple echo is not executed, command exits with code 0
7. Publisher stops publishing
8. runOnReady command stops SIGINT

I have tried changing runOnReady command to:  
"echo", "echo hello", <-- This should show logs as shown in this issue: https://github.com/aler9/rtsp-simple-server/issues/828
"curl nginx_server" <-- This should show logs on my nginx server
"ffmpeg -i rtsp path_from_rtsp_server output.mp4" <-- A quick exit with code 0
"sh -c 'echo hello'" <-- A quick exit with code 0
"sh -c 'sleep 5'" <-- A quick exit with code 0
"sleep 20" <-- A quick exit with code 0

I have checked path configuration before doing replication steps:
path output from GET /v1/paths/list
```json
"9cb696b6-6334-49cc-84f2-b72c534acda4": {
      "confName": "9cb696b6-6334-49cc-84f2-b72c534acda4",
      "conf": {
        "source": "publisher",
        "runOnReady": "echo please work",
        "runOnReadyRestart": false,
      },
      "source": {},
    },
```

## Did you attach the server logs?
```
backend_1                 | INFO:     172.18.0.7:52722 - "POST /api/paths/check_permission/ HTTP/1.1" 200 OK
rtsp-simple-server_1  | 2022/10/11 10:28:47 INF [path 9cb696b6-6334-49cc-84f2-b72c534acda4] runOnReady command started
rtsp-simple-server_1  | 2022/10/11 10:28:47 INF [RTSP] [session 820221963] is publishing to path '9cb696b6-6334-49cc-84f2-b72c534acda4', with TCP, 1 track (Generic)
rtsp-simple-server_1  | 2022/10/11 10:28:47 INF [path 9cb696b6-6334-49cc-84f2-b72c534acda4] runOnReady command exited with code 0
rtsp-simple-server_1  | 2022/10/11 10:55:37 INF [RTSP] [conn 172.18.0.10:55854] closed (terminated)
rtsp-simple-server_1  | 2022/10/11 10:55:37 INF [path 9cb696b6-6334-49cc-84f2-b72c534acda4] runOnReady command stopped
```

## Did you attach a network dump?
no

**Comment by saket424** [comment]
@robertmielewczyk and @aler9 ,
I am having the same issue as robert even without using the API. I never see the echo print in the docker logs
All i see is "runOnReady command started" and "runOnReady command exited with code 0" for the path

**Comment by saket424** [comment]
It appears the echo command is missing from my rtsp-simple-server docker container while it exists in a janus docker container
What am I missing?

ubuntu@oakb1:~/rtsp-simple-server$ docker exec -it janus echo hello
hello
ubuntu@oakb1:~/rtsp-simple-server$ docker exec -it rtsp-simple-server echo hello
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "echo": executable file not found in $PATH: unknown
ubuntu@oakb1:~/rtsp-simple-server$ docker exec -it rtsp-simple-server /bin/echo hello
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/echo": stat /bin/echo: no such file or directory: unknown
ubuntu@oakb1:~/rtsp-simple-server$ docker exec -it rtsp-simple-server /usr/bin/echo hello
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/echo": stat /usr/bin/echo: no such file or directory: unknown

**Comment by saket424** [comment]
Aha!
The default docker image does not have ffmpeg

I need a more full featured Dockerfile such as the one below for echo and ffmpeg to work

```
ubuntu@oakb1:~/rtsp-simple-server$ cat Dockerfile 
FROM aler9/rtsp-simple-server AS rtsp

FROM alpine:3.14
RUN apk add --no-cache ffmpeg

COPY --from=rtsp /rtsp-simple-server /
#COPY rtsp-simple-server.yml /

ENTRYPOINT [ "sh", "-c", "/rtsp-simple-server" ]

ubuntu@oakb1:~/rtsp-simple-server$ docker build -t asetlur13/rtsp-simple-server .

ubuntu@oakb1:~/rtsp-simple-server$ cat docker-compose.yml 
version: '3.6'

services:
  rtsp-simple-server:
    container_name: rtsp-simple-server
    network_mode: host
    volumes:
      - ./rtsp-simple-server.yml:/rtsp-simple-server.yml
    environment:
      - TZ=America/Chicago
      - RTSP_RTMPENABLE=true
    #image: aler9/rtsp-simple-server
    image: asetlur13/rtsp-simple-server
    restart: always
ubuntu@oakb1:~/rtsp-simple-server$ 

Now echo and ffmpeg work
ubuntu@oakb1:~/rtsp-simple-server$ docker-compose up -d
Creating rtsp-simple-server ... done
ubuntu@oakb1:~/rtsp-simple-server$ docker exec -it rtsp-simple-server echo hello
hello
ubuntu@oakb1:~/rtsp-simple-server$ 

```

**Comment by robertmielewczyk** [comment]
thank you @saket424 

Changes applied in order to fix the problem:
1. Changed docker-compose.yml
```yaml
rtsp-simple-server:
    build:
      context: config/dockerfiles/
      dockerfile: rtsp-simple-server.Dockerfile
    volumes:
      - type: bind
        source: ./config/rtsp-simple-server.yml
        target: /rtsp-simple-server.yml
    restart: always
```
2. Added rtsp-simple-server.Dockerfile
```dockerfile
FROM aler9/rtsp-simple-server:v0.20.0 AS video-server

FROM alpine:3.17
RUN apk add --no-cache ffmpeg
RUN apk --no-cache add curl

COPY --from=video-server /rtsp-simple-server /

ENTRYPOINT [ "sh", "-c", "/rtsp-simple-server" ]
```

logs after aplying fix
```
rtsp-simple-server_1  | 2022/11/30 14:16:15 INF [RTSP] [session 158779442] is publishing to path 'test', with TCP, 1 track (Generic)
rtsp-simple-server_1  | hello message from run_on_ready
rtsp-simple-server_1  | 2022/11/30 14:16:15 INF [path test] runOnReady command exited with code 0
rtsp-simple-server_1  | 2022/11/30 14:16:15 INF [RTSP] [conn 127.0.0.1:50524] closed (terminated)
```
