### ISSUE TITLE
error in 0.12.1 version.. rtsp source ERR: sdp: invalid syntax `o=

### ISSUE THREAD

**Issue by brixzen** [aler9/rtsp-simple-server#121]
source RTSP is TCP protocol, i test using VLC viewer working fine. before this version i test using 0.10 version, and this is the error from 0.10 version.
2020/11/12 03:11:06 [0/0/0] rtsp-simple-server v0.10.0
2020/11/12 03:11:06 [0/0/0] [UDP/RTP server] opened on :8000
2020/11/12 03:11:06 [0/0/0] [UDP/RTCP server] opened on :8001
2020/11/12 03:11:06 [0/0/0] [TCP server] opened on :8554
2020/11/12 03:11:06 [0/0/0] [path cam2] rtsp source started
2020/11/12 03:11:06 [0/0/0] [path cam2] connecting to rtsp source
2020/11/12 03:11:07 [0/0/0] [path cam2] rtsp source ERR: sdp: invalid numeric value `P`
2020/11/12 03:11:12 [0/0/0] [path cam2] connecting to rtsp source
2020/11/12 03:11:12 [0/0/0] [path cam2] rtsp source ERR: sdp: invalid numeric value `P`

in new version i test again, and still have error, with different code. this is : 

root@server1:~/rtsp-simple-proxy# ./rtsp-simple-server        
2020/11/12 03:11:19 [0/0/0] rtsp-simple-server v0.12.1
2020/11/12 03:11:19 [0/0/0] [UDP/RTP server] opened on :8000
2020/11/12 03:11:19 [0/0/0] [UDP/RTCP server] opened on :8001
2020/11/12 03:11:19 [0/0/0] [TCP server] opened on :8554
2020/11/12 03:11:19 [0/0/0] [path cam2] rtsp source started
2020/11/12 03:11:19 [0/0/0] [path cam2] connecting to rtsp source
2020/11/12 03:11:19 [0/0/0] [path cam2] rtsp source ERR: sdp: invalid syntax `o=[RTSP 16381619791249025353 16381619791249085483 IN IP4]` (o=RTSP 16381619791249025353 16381619791249085483 IN IP4 )

Thanks for hard work.!

**Comment by aler9** [comment]
Hello, this can be fixed in a very short time, but you have to provide a network dump (so i can see the full SDP), by doing this:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by brixzen** [comment]
Ok thanks for fast response, there is the result.

[port8554.pcap.zip](https://github.com/aler9/rtsp-simple-server/files/5528674/port8554.pcap.zip)

**Comment by aler9** [comment]
Hello, thanks for posting the dump, this SDP is now fully supported in master and will be supported in the next release.

**Comment by brixzen** [comment]
Ok thanks a lot.!!  @aler9

**Comment by aler9** [comment]
added in v0.12.2
