### ISSUE TITLE
On option to repeat the last received SPS,PPS and IDR

### ISSUE THREAD

**Issue by neilyoung** [aler9/rtsp-simple-server#1238]
## Describe the feature

This FR is a quick shot following this discussion https://github.com/aler9/rtsp-simple-server/discussions/1236

Would it be possible to have an option, that rtsp-simple-server streams out the last received SPS, PPS, IDR NAL unit in order to repeat that periodically (configurable?) for client sessions?

TIA

**Comment by aler9** [comment]
rtsp-simple-server already inserts SPS and PPS before I-frames in RTMP, HLS and WebRTC.
It doesn't do that in RTSP, since SPS and PPS are passed to clients during the handshake phase, inside the SDP.

Re-streaming IDRs is not a good idea as it would corrupt the stream, while it's a good idea to send the last IDR to clients that have just joined the stream - this feature is being tracked here: #1209

**Comment by neilyoung** [comment]
> Re-streaming IDRs is not a good idea as it would corrupt the stream, 

Sure agree on this. 

> while it's a good idea to send the last IDR to clients that have just joined the stream 

Not sure. You might see a bit of the past then :)  I would be just happy, if I wouldn't just have to sit and wait for the intra frame. But again, as said on the other thread - not a big issue anymore.

Maybe one day W3C finally confirms the "getKeyFrame" API which is in beginning standardisation and browsers will implement that. I would some indication of a beginning RTSP client session then (I think I have seen you are able to run a command on that?), so that I could use my signaling or data channels in order to "kick-ass" the browsers to send an intra frame as "clean sweep" :)

**Comment by aler9** [comment]
> Maybe one day W3C finally confirms the "getKeyFrame" API 

this is already implemented with RTCP's PictureLossIndication, please see the other discussion

**Comment by neilyoung** [comment]
> this is already implemented with RTCP's PictureLossIndication, please see the other discussion

Well, ok. But you would have to have access to this protocol layer, wouldn't you? I don't have that with KMS, unfortunately.
