### ISSUE TITLE
Possible combatibility issue with RTMP and with Streamlabs Mobile app Android version

### ISSUE THREAD

**Issue by notwildsystem** [aler9/rtsp-simple-server#1244]
## Which version are you using?

v0.20.2 (have tried 0.19.x too)

## Which operating system are you using?

- [X ] Linux amd64 standard

## Describe the issue

Streamlabs mobile Android version app ( https://play.google.com/store/apps/details?id=com.streamlabs )doesn't work with RTMP. Basically based on logs it tries to connect twice and does i/o timeout. Current Android version of it is 3.6.12.171. This issue has been at least since summer.

What works: Streamlabs Mobile and their iOS version of it. Also Camerafi Live on Android and Larix Android works.

I am using default settings out-of-the-box from RTSP-simple server or my custom. It doesn't matter, it acts like the same way. I am using the same network LAN and there is no firewall or network issue and their iOS version works and other similar Android apps works fine too.

## Describe how to replicate the issue

1. start the server
2. Try to Stream with Streamlabs Mobile Android app with RTMP 

## Did you attach the server logs?

yes

## Did you attach a network dump?

 no

**Comment by jaredkotoff** [comment]
Also been trying to stream to rtsp-simple-server using Streamlabs (v3.7.1.179) on Android (13) and getting weird results. 

<img width="466" alt="Screenshot 2023-01-18 at 5 50 32 PM" src="https://user-images.githubusercontent.com/3268576/213336799-2a52a89c-b1a4-49d3-948a-182e97248fd3.png">
`10.0.0.33` is my phone trying to stream to the server (`rtmp://10.0.0.6:8554/phone`)
`10.0.0.32` is my laptop trying to watch the stream via VLC

**Comment by aler9** [comment]
added in v0.21.2
