### ISSUE TITLE
Video playback issues with specific MP4 files

### ISSUE THREAD

**Issue by tsightler** [aler9/rtsp-simple-server#1250]
## Which version are you using?

v0.20.2

## Which operating system are you using?

- [X] Linux amd64 standard
- [X] Linux amd64 Docker
- [X] Linux arm64 standard
- [X] Linux arm64 Docker
- [X] Linux arm7 standard
- [X] Linux arm7 Docker

## Describe the issue

First, thanks for this terrific project.  I use rtsp-simple-server as part of the ring-mqtt project which allows users of Ring camera to access these devices and event records via standard RTSP, leverage run-on-demand and it works great for the most part.

For event recordings Ring offers two different types of MP4 files, one is the raw recording exactly as the camera took it, and a second one, referred to as the transcoded file, includes additional data such as a timestamp overlay and, based on the camera capabilities, potentially some pre-roll video to show the seconds leading up to the triggered event.

Currently the code can play back the recorded raw video just fine, but I had quite a few users that asked about playing back the transcoded video, but, when adding this capability I ran into an issue, for some reason the transcoded video, when streamed through rtsp-simple-server, many times the first 5-10 seconds of the video portion is black, then the video finally starts to play (audio starts immediately).  Weirdly, every now and then it will play correctly from the start, and this seemed to improve with 0.20.2 release, but it's still not quite working perfectly.

At first I thought this was some issue with ffmpeg, but I decided to try streaming the file with go2rtc instead of rtsp-simple-server and there the file always plays back perfectly.  Since the ffmpeg command used by go2rtc and rtsp-simple-server are nearly identical, the only significant variable is rtsp-simple-server.

To summarize:

test_event.mp4 -> ffmpeg -> rtsp-simple-server -> vlc = Playback via VLC stutters at points and/or black screen to start
test_event.mp4 -> ffmpeg -> go2rtc (RTSP module) -> vlc = Playback works perfectly, no different than directly opening mp4 file

## Describe how to replicate the issue

1. start the server with this config:
```
paths:
  file1:
    runOnDemand: ffmpeg -re -stream_loop -1 -i /media/test_event.mp4 -c copy -rtsp_transport tcp -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnDemandRestart: yes
```
2. read with vlc from rtsp://localhost:8554/file1

## Did you attach the server logs?

Yes, with debug enabled.
[rtsp-simple-server.log](https://github.com/aler9/rtsp-simple-server/files/10045981/rtsp-simple-server.log)

## Did you attach a network dump?

No, but I can do this if it would help somehow.  I will also put a link to the video to use to reproduce the issue.

**Comment by tsightler** [comment]
Here is a [test video](https://drive.google.com/file/d/1Fi-EYnFt_JrapB6rrMjbp297XA_lidDd/view?usp=share_link).  With 0.20.2 the behavior did improve.  Before that this video would almost always start off with a black screen for about 10-12 seconds, but with this new version it does seem to start streaming right away.

However, there is still an issue visible in this video, at about the 10-15 second mark the video pauses/stalls, and then suddenly jumps about 3 seconds.  This does not happen when using go2rtc or when playing the file directly in VLC.

**Comment by aler9** [comment]
Hello,

go2rtc only supports the TCP variant of RTSP, while rtsp-simple-server supports the UDP, TCP and UDP multicast variants.
in rtsp-simple-server, the UDP variant is the default one.

When you read a RTSP stream with VLC and the UDP variant, VLC pauses the video for some seconds in order to fill an internal buffer that allows to compensate network fluctuations. This is not pleasant but it's not a choice on which i have a say.

Just disable the UDP variant by setting the `protocols` parameter and the issue will disappear:

```yml
protocols: [tcp]
```

Alternatively you can tune the "caching" parameter of VLC.
