### ISSUE TITLE
Implement native support for the Raspberry Camera

### ISSUE THREAD

**Issue by max246** [aler9/rtsp-simple-server#126]
## Which version are you using?

v0.12.1

## Which operating system are you using?

Pi
## Describe the problem

Once I use the line provided in the readme, it says that rpicamsrc is not present, the issue probably is because gstream included that into the system and this command is not possible anymore. 
Would be great to update it to the correct one

**Comment by aler9** [comment]
Hello, Raspberry uses Raspbian OS, which is based on Debian Buster, which provides gstreamer 1.16.
The [rpicamsrc readme](https://github.com/thaytan/gst-rpicamsrc) says that the element is bundled into gstreamer 1.18, so it is not bundled into the Raspberry's gstreamer and must be manually compiled from scratch, by downloading the rpicamsrc and following the instructions in the readme.

I did it many times for cameras installed on rovers and UGVs, it's not difficult after the first time and latency is < 200ms.

If would be great to improve rtsp-simple-server to add native support for the Raspberry Camera, but it won't be done in the near future (of course PRs are always welcomed if someone wants to make the job).

**Comment by max246** [comment]
I see , I will have a look then. Thanks! Maybe I could give a try to implement it once the project is done.

I have to understand more what has to be done to implement it.

**Comment by aler9** [comment]
> I have to understand more what has to be done to implement it

I tried all the ways to access a Raspberry Camera (v4l2, raspivid, etc), and the fastest one is the one provided by rpicamsrc.
It basically performs a series of API calls to the [MMAL interface](https://github.com/raspberrypi/userland/blob/master/interface/mmal/mmal.h) and is able to get the stream directly in H264.

Therefore, to integrate the feature into rtsp-simple server, i'd

1. add a new source called "raspberry-camera" or similar

2. make this source call the MMAL interface, exactly like rpicamsrc does. This require calling C code from Go, or using syscalls, and is the most difficult part

**Comment by max246** [comment]
will it not be possible to run raspivid with the "-o" output and capture it via your system?  need to see how you build the whole thing.

At the moment I found a way to use raspivid to output the data and capture via obs.

**Comment by aler9** [comment]
> will it not be possible to run raspivid with the "-o" output and capture it via your system? need to see how you build the whole thing.

it would work, but it is less efficient than rpicamsrc and latency is much greater.
