### ISSUE TITLE
TPLink Camera RTSP Proxy Error

### ISSUE THREAD

**Issue by uioch** [aler9/rtsp-simple-server#1267]
TPLink camera like TL-IPC44AN RTSP Proxy Failed.

## Which version are you using?

v0.20.2

## Which operating system are you using?

- [X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

configuration:

s53:
    source: rtsp://admin:@192.168.1.5:554/stream1
    sourceOnDemand: no

but rtsp://localhost:8554/p1 can't be opened

## Describe how to replicate the issue

1. start the server
2. publish with the configuration
3. open rtsp://localhost:8554 with vlc

## Did you attach the server logs?

yes

2022/12/01 20:11:13 DEB [path s53] [rtsp source] s->c RTSP/1.0 200 OK
CSeq: 2
Content-Base: rtsp://192.168.1.5:554/stream1/
Content-Length: 486
Content-Type: application/sdp
Date: Wed, Jan 05 2022 07:22:43 GMT

v=0
o=- 14665860 31787219 1 IN IP4 192.168.1.5
s=Session streamed by "TP-LINK RTSP Server"
t=0 0
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:4096
a=range:npt=0-
a=control:track1
a=rtpmap:96 H264/90000

m=audio 0 RTP/AVP 8
a=rtpmap:8 PCMA/8000
a=control:track2
m=audio 0 RTP/AVP 8
a=rtpmap:8 PCMA/8000
a=control:track2
m=application/TP-LINK 0 RTP/AVP smart/1/90000
a=rtpmap:95 TP-LINK/90000
a=control:track3

2022/12/01 20:11:13 INF [path s53] [rtsp source] ERR: unable to parse track 3: s
trconv.ParseInt: parsing "smart/1/90000": invalid syntax

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Thanks for reporting the issue, it is being fixed with https://github.com/aler9/gortsplib/pull/174

**Comment by aler9** [comment]
added in v0.21.2
