### ISSUE TITLE
rtsp source ERR: sdp: invalid syntax `o=[RTSP Session 0 0 IN IP4 0.0.0.0]` (o=RTSP Session 0 0 IN IP4 0.0.0.0)

### ISSUE THREAD

**Issue by aeozyalcin** [aler9/rtsp-simple-server#127]
### Which version are you using?
 v0.10.0 and v0.12.1

### Which operating system are you using?
Raspbian Buster / Linux

### Describe the problem
When trying to proxy an Amcrest IP camera, I am getting the following error appearing in the rtsp-server output:
`rtsp source ERR: sdp: invalid syntax `o=[RTSP Session 0 0 IN IP4 0.0.0.0]` (o=RTSP Session 0 0 IN IP4 0.0.0.0)`

I have a 3 different models of the Amcrest cameras, and I am able to successfully proxy the 2 other models, but the 1 model is giving me the error above. Of this particular problematic model, I have 3 of these cameras, and they all give me the same error when I try to proxy them. Sorry, I don't have the exact model number of the problematic model right now.

My config yml file is simple. Here is what the paths section looks like:
`paths:`
`  front_sd:`
`    # url of the source stream, in the format rtsp://user:pass@host:port/path`
`    source: rtsp://user:pass@ip:port/cam/realmonitor?channel=1&subtype=1`
`    sourceProtocol: tcp`
`    sourceOnDemand: no`

^^ these settings work just fine for the other 2 models of Amcrest cameras. I am pretty sure this particular model must be different in how it's running its rtsp server that's causing the issue. I have tried both version v0.10.0 and v0.12.1, and they both yield the same error.

Is there any other logs/details I can provide to help solve this?

**Comment by aler9** [comment]
Hello, please do this

> The most helpful content you can provide to fix a communication issue between rtsp-simple-server and an external hardware or software, is a dump of the data exchanged between the server and the target (network dump), that can be generated in this way:
> 1) Download wireshark (https://www.wireshark.org/)
> 2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
> 3) Start the server and replicate the issue
> 4) Stop capturing, save the result in .pcap format
> 5) Attach

**Comment by aler9** [comment]
Fortunately the line you provided was enough to produce a fix, but i can't be sure that there won't be any more errors with your camera until you provide a network dump. Anyway, please try this nightly release and let me know if it solves the issue
[rtsp-simple-server_v0.12.2-15-g6e352ac_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5649382/rtsp-simple-server_v0.12.2-15-g6e352ac_windows_amd64.zip)
[rtsp-simple-server_v0.12.2-15-g6e352ac_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5649383/rtsp-simple-server_v0.12.2-15-g6e352ac_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.12.2-15-g6e352ac_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5649384/rtsp-simple-server_v0.12.2-15-g6e352ac_linux_arm7.tar.gz)
[rtsp-simple-server_v0.12.2-15-g6e352ac_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5649385/rtsp-simple-server_v0.12.2-15-g6e352ac_linux_arm6.tar.gz)
[rtsp-simple-server_v0.12.2-15-g6e352ac_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5649386/rtsp-simple-server_v0.12.2-15-g6e352ac_linux_amd64.tar.gz)
[rtsp-simple-server_v0.12.2-15-g6e352ac_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5649387/rtsp-simple-server_v0.12.2-15-g6e352ac_darwin_amd64.tar.gz)

**Comment by aeozyalcin** [comment]
@aler9 can confirm the privates you provided works with my problematic Amcrest IPM-722S cameras! Works like a charm, thank you for the fix!

**Comment by aler9** [comment]
added to v0.13.0
