### ISSUE TITLE
OBS Streaming Problem with Encoder NVENC HEVC

### ISSUE THREAD

**Issue by kgggggb** [aler9/rtsp-simple-server#1279]
## Which version are you using?

v0.20.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

server: i/o timeout
when i try to use obs streaming with encoder NVENC HEVC(H265)

## Describe how to replicate the issue

1. start the server
2. publish with OBS: settings: Encoder NVENC HEVC

## Did you attach the server logs?

yes

```
2022/12/08 05:26:53 INF rtsp-simple-server v0.20.2
2022/12/08 05:26:53 DEB path manager created
2022/12/08 05:26:53 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/12/08 05:26:53 INF [RTMP] listener opened on :1935
2022/12/08 05:26:53 INF [HLS] listener opened on :8888
2022/12/08 05:27:01 INF [RTMP] [conn PRIVACY_HIDDEN:61864] opened
2022/12/08 05:27:01 DEB [path live] created
2022/12/08 05:27:11 DEB [path live] destroyed (not in use)
2022/12/08 05:27:11 INF [RTMP] [conn PRIVACY_HIDDEN:61864] closed (read tcp PRIVACY_HIDDEN:1935->PRIVACY_HIDDEN:61864: i/o timeout)
2022/12/08 05:27:13 INF [RTMP] [conn PRIVACY_HIDDEN:61878] opened
2022/12/08 05:27:13 DEB [path live] created
2022/12/08 05:27:16 DEB [path live] destroyed (not in use)
2022/12/08 05:27:16 INF [RTMP] [conn PRIVACY_HIDDEN:61878] closed (EOF)
```

## Did you attach a network dump?

no

**Comment by aler9** [comment]
This is now supported since v0.21.1
