### ISSUE TITLE
Add option to "rotate 90" the image

### ISSUE THREAD

**Issue by aler9** [aler9/rtsp-simple-server#1285]
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/1275

<div type='discussions-op-text'>

<sup>Originally posted by **dudududodododedede** December  5, 2022</sup>
rtsp-simple-server already supports VFlip and HFlip from libcamera but would be amazing if it also support Rot90 from libcamera:

https://libcamera.org/api-html/namespacelibcamera.html#a371b6d17d531b85c035c4e889b116571ad5251a97af7b4036b4528a54405ea2ad</div>

**Comment by aler9** [comment]
@dudududodododedede after some testing it turned out that libcamera doesn't support rotation by 90 degrees.

From the docs:

> The Transform can take 8 distinct values, representing the usual 2D plane transforms listed below. Each of these transforms can be constructed out of 3 basic operations, namely a horizontal flip (mirror), a vertical flip, and a transposition (about the main diagonal). The transforms are encoded such that a single bit indicates the presence of each of the 3 basic operations:
>
>    bit 0 - presence of a horizontal flip
>    bit 1 - presence of a vertical flip
>    bit 2 - presence of a transposition.

There isn't a bit for 90-degrees rotation. Even if there is a `Rot90` and a `Rot270` constant, they can only be multiplied by other constants in order to flip horizontally or vertically.

**Comment by blastrock** [comment]
Combination of these flags should allow all rotations as we see [here](https://libcamera.org/api-html/transform_8h_source.html):

```
     Identity = 0,
     Rot0 = Identity,
     HFlip = 1,
     VFlip = 2,
     HVFlip = HFlip | VFlip,
     Rot180 = HVFlip,
     Transpose = 4,
     Rot270 = HFlip | Transpose,
     Rot90 = VFlip | Transpose,
     Rot180Transpose = HFlip | VFlip | Transpose
```

I think mediamtx should expose the transpose flag and users will be able to use it in combination with HFlip and VFlip to do all these rotations.

I also have a camera mounted 90° and I currently need to reencode the stream with ffmpeg to have it in the correct orientation, and that uses more CPU. This feature would be very useful.

**Comment by aler9** [comment]
@blastrock i tested again the Transpose flag and i can say that unfortunately it doesn't produce any effect on the video. I checked again the [libcamera-apps documentation](https://www.raspberrypi.com/documentation/computers/camera_software.html) and found out that:

> the --rotation option permits only the value 0 or 180, so note that 90 or 270 degree rotations are not supported

If you want to solve the issue, you can write to libcamera maintainers in order to find out whether the issue is a missing software feature or a hardware limitation.

**Comment by blastrock** [comment]
Indeed, looking at libcamera's code, the transpose flag seems to be here and there, but nothing useful seems to be done with it. I opened a bug upstream: https://bugs.libcamera.org/show_bug.cgi?id=192
