### ISSUE TITLE
rpi camera stream: insert date and time in the video stream

### ISSUE THREAD

**Issue by aler9** [aler9/rtsp-simple-server#1288]
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/1207

<div type='discussions-op-text'>

<sup>Originally posted by **vongillus** October 28, 2022</sup>
I just succeeded in configuring a rpi with its camera with both RTSP and HLS low latency. Thanks a lot for your work on this software!

I was wondering, is there any way to insert the date and time on the video? It will be a way to check that the video is not frozen. I mean in a more general way, to insert text on the video.
</div>

**Comment by lejibxl** [comment]
in picamera2 this feature is called via a pre_callback ex: picam2.pre_callback = apply_timestamp.

**Comment by jarrah31** [comment]
I am also interested in having the ability to add a timestamp to the video feed.
Thanks in advance!

**Comment by filby112** [comment]
Thank you very much for your fantastic work...
I'm also interested in having the ability to add a timestamp and a name to the video feed.
Thanks in advance

**Comment by aler9** [comment]
implemented in #1604

**Comment by aler9** [comment]
added in v0.22.0
