### ISSUE TITLE
Docker image missing for v0.20.3

### ISSUE THREAD

**Issue by tbnguyen1407** [aler9/rtsp-simple-server#1293]
## Which version are you using?

v0.20.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Docker image missing on DockerHub for latest version.

## Describe how to replicate the issue

1. check DockerHub for latest tag
2. latest tag not found
3. ...

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Thanks for reporting this, it has been fixed.
