### ISSUE TITLE
Stream Loop -1 not working: broken_pipe and conversion failed error

### ISSUE THREAD

**Issue by Saifer707** [aler9/rtsp-simple-server#1295]
## Which version are you using?

v0.20.3

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Starting to publish video with ffmeg -start_loop -1 command, i think that the server restart to publish when first one finished. Instead of this, i receveid an ffmpeg Broken Pipe Error like this:

```
av_interleaved_write_frame(): Broken pipe00:00:44.21 bitrate=N/A speed=   1x    
frame=  342 fps=7.7 q=-1.0 Lsize=N/A time=00:00:44.25 bitrate=N/A speed=   1x    
video:5388kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
```

Why? Is there a way to restart video publishing?

## Describe how to replicate the issue

1. start the server
2. publish with ffmpeg -re -stream_loop -1 -i *file.mp4* -c copy -f rtsp rtsp://localhost:8554/*port*
3. wait until publish finished 
4. see if broken pipe error comes

## Did you attach the server logs?

yes

```
2022/12/12 12:50:25 INF rtsp-simple-server v0.20.3
2022/12/12 12:50:25 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/12/12 12:50:25 INF [RTMP] listener opened on :1935
2022/12/12 12:50:25 INF [HLS] listener opened on :8888
2022/12/12 12:50:31 INF [RTSP] [conn 127.0.0.1:56816] opened
2022/12/12 12:50:31 INF [RTSP] [session 5910e470] created by 127.0.0.1:56816
2022/12/12 12:50:31 INF [RTSP] [session 5910e470] is publishing to path 'para', with UDP, 1 track (H264)
2022/12/12 12:50:52 INF [RTSP] [conn 127.0.0.1:56816] closed (terminated)
2022/12/12 12:50:52 INF [RTSP] [session 5910e470] destroyed (no UDP packets received in a while)
```

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, the server closes the connection since it doesn't receive packets from FFmpeg:

```
2022/12/12 12:50:52 INF [RTSP] [session 5910e470] destroyed (no UDP packets received in a while)
```

Make sure that FFmpeg and the server can exchange UDP packets, by opening the firewall or by using the explicit IPv4 IP instead of localhost:

```
ffmpeg -re -stream_loop -1 -i file.mp4 -c copy -f rtsp rtsp://127.0.0.1:8554/port
```

Otherwise, publish with the TCP transport protocol:


```
ffmpeg -re -stream_loop -1 -i file.mp4 -c copy -rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554/port
```
