### ISSUE TITLE
Proxy list does not update dynamically

### ISSUE THREAD

**Issue by ndaidong** [aler9/rtsp-simple-server#130]
## Which version are you using?

v0.12.1

## Which operating system are you using?

Linux

## Question

Hello, as the description said that hot reloading is supported.  I try to set proxy as below:

```yaml
  camera01:
    source: rtsp://admin:pass123@192.168.1.211/1
    sourceOnDemand: yes
```

`rstp://localhost:8854/camera01` works as well.

Then I add another entry:

```yaml
  camera01:
    source: rtsp://admin:pass123@192.168.1.211/1
    sourceOnDemand: yes
  camera02:
    source: rtsp://admin:pass123@192.168.1.212/1
    sourceOnDemand: yes
```

 `rstp://localhost:8854/camera02` doesn't work until I restart `rtsp-simple-server` service.

And the log output: `ERR: unable to find control attribute`

Is this a bug or normal behavior?

**Comment by aler9** [comment]
Hello, i tried to replicate the issue but without success - i did the following:

1. i write this configuration
   ```yml
   paths:
     proxied1:
       source: rtsp://admin:pass@localhost:8555/Streaming/Channels/101
       sourceProtocol: tcp
   ```

2. the server is started

3. i change the configuration to
   ```yml
   paths:
     proxied1:
       source: rtsp://admin:pass@localhost:8555/Streaming/Channels/101
       sourceProtocol: tcp
     proxied2:
       source: rtsp://admin:pass@localhost:8555/Streaming/Channels/101
       sourceProtocol: tcp
   ```

3. the server detects the change and reloads the configuration and successfully connects to the second camera too.

This is my log:
```
2020/11/25 22:26:26 [0/0/0] rtsp-simple-server v0.12.1
2020/11/25 22:26:26 [0/0/0] [UDP/RTP server] opened on :8000
2020/11/25 22:26:26 [0/0/0] [UDP/RTCP server] opened on :8001
2020/11/25 22:26:26 [0/0/0] [TCP server] opened on :8554
2020/11/25 22:26:26 [0/0/0] [path proxied1] rtsp source started
2020/11/25 22:26:26 [0/0/0] [path proxied1] connecting to rtsp source
2020/11/25 22:26:26 [0/0/0] [path proxied1] rtsp source ready
2020/11/25 22:26:34 [0/0/0] reloading configuration
2020/11/25 22:26:34 [0/0/0] [path proxied2] rtsp source started
2020/11/25 22:26:34 [0/0/0] [path proxied2] connecting to rtsp source
2020/11/25 22:26:35 [0/0/0] [path proxied2] rtsp source ready
```

please try to replicate and post the full log (if you're using systemd, it can be extracted with `journalctl -xeu rtsp-simple-server`). Thanks

**Comment by ndaidong** [comment]
@aler9 thank you for your reply. I've checked and didn't see the message "reloading configuration" like you.

Here I'm using `rtsp-simple-server` to simulate a set of cameras. 25 items which are already there worked. 

![Screenshot_2020-11-26_13-04-57](https://user-images.githubusercontent.com/1809619/100315649-934c4000-2feb-11eb-98cb-6a03cc8215d5.png)

When I add a new item, nothing happen in the log output:

![Screenshot_2020-11-26_13-25-10](https://user-images.githubusercontent.com/1809619/100315660-97785d80-2feb-11eb-8ba7-f27d7e045fae.png)

Camera 26 is only available until I restart the service. 

I also try to run directly the binary (`./rtsp-simple-server`) with yaml config file next to it.

**Comment by aler9** [comment]
Hello, during tests on MacOS i discovered that hot reloading didn't worked with text editors that delete and recreate the configuration file - it worked only with text editors that write to the original file.
I don't know if this is the case, but please try this nightly release and let me know if it works.
[rtsp-simple-server_v0.12.2-1-g0f11dd5_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5604921/rtsp-simple-server_v0.12.2-1-g0f11dd5_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.12.2-1-g0f11dd5_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5604922/rtsp-simple-server_v0.12.2-1-g0f11dd5_linux_amd64.tar.gz)
[rtsp-simple-server_v0.12.2-1-g0f11dd5_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5604923/rtsp-simple-server_v0.12.2-1-g0f11dd5_linux_arm6.tar.gz)
[rtsp-simple-server_v0.12.2-1-g0f11dd5_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5604924/rtsp-simple-server_v0.12.2-1-g0f11dd5_linux_arm7.tar.gz)
[rtsp-simple-server_v0.12.2-1-g0f11dd5_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5604925/rtsp-simple-server_v0.12.2-1-g0f11dd5_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.12.2-1-g0f11dd5_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5604926/rtsp-simple-server_v0.12.2-1-g0f11dd5_windows_amd64.zip)

**Comment by ndaidong** [comment]
@aler9 thank you, it seems there is no effect to my case.

I've tested in my local machine (Ubuntu 20.10) and server (Debian 10.6). For editor, I've tried vi, nano, neovim, Geany and Sublime 3.

**Comment by brandousov** [comment]
On release version and on the nightly rtsp-simple-server_v0.12.2-1-g0f11dd5_linux_amd64.tar.gz config hot-reloading not working correctly (Debian 10). VLC disconnects from stream and I must restart it by hand.

```
2020/12/09 06:58:42 [0/0/0] rtsp-simple-server v0.12.2-1-g0f11dd5
2020/12/09 06:58:42 [0/0/0] [UDP/RTP server] opened on :8000
2020/12/09 06:58:42 [0/0/0] [UDP/RTCP server] opened on :8001
2020/12/09 06:58:42 [0/0/0] [TCP server] opened on :8554
2020/12/09 06:58:57 [1/0/0] [client 176.15.89.162:4874] connected
2020/12/09 06:58:57 [1/0/0] [client 176.15.89.162:4874] OPTIONS
2020/12/09 06:58:57 [1/0/0] [client 176.15.89.162:4874] DESCRIBE
2020/12/09 06:58:57 [1/0/0] [path token2] rtsp source started
2020/12/09 06:58:57 [1/0/0] [path token2] connecting to rtsp source
2020/12/09 06:58:57 [1/0/0] [path token2] rtsp source ready
2020/12/09 06:58:57 [1/0/0] [client 176.15.89.162:4874] SETUP
2020/12/09 06:58:57 [1/0/0] [client 176.15.89.162:4874] PLAY
2020/12/09 06:58:57 [1/0/1] [client 176.15.89.162:4874] is reading from path 'token2', 1 track with udp

2020/12/09 06:59:09 [1/0/1] reloading configuration
2020/12/09 06:59:09 [1/0/1] ERR: EOF
2020/12/09 06:59:09 [0/0/0] [client 176.15.89.162:4874] disconnected
2020/12/09 06:59:09 [0/0/0] [path token2] rtsp source stopped
2020/12/09 06:59:09 [0/0/0] rtsp-simple-server v0.12.2-1-g0f11dd5
2020/12/09 06:59:09 [0/0/0] [UDP/RTP server] opened on :8000
2020/12/09 06:59:09 [0/0/0] [UDP/RTCP server] opened on :8001
2020/12/09 06:59:09 [0/0/0] [TCP server] opened on :8554
2020/12/09 06:59:22 [1/0/0] [client 176.15.89.162:4883] connected
2020/12/09 06:59:22 [1/0/0] [client 176.15.89.162:4883] OPTIONS
2020/12/09 06:59:22 [1/0/0] [client 176.15.89.162:4883] DESCRIBE
2020/12/09 06:59:22 [1/0/0] [path token2] rtsp source started
2020/12/09 06:59:22 [1/0/0] [path token2] connecting to rtsp source
2020/12/09 06:59:22 [1/0/0] [path token2] rtsp source ready
2020/12/09 06:59:22 [1/0/0] [client 176.15.89.162:4883] SETUP
2020/12/09 06:59:22 [1/0/0] [client 176.15.89.162:4883] PLAY
2020/12/09 06:59:22 [1/0/1] [client 176.15.89.162:4883] is reading from path 'token2', 1 track with udp
```

**Comment by ndaidong** [comment]
@aler9 @brandousov I would like to confirm that when I use Python script to manage config file, add and remove the `path` items, everything work well. That's enough for my program.

**Comment by brandousov** [comment]
I calling touch() function to config file for changes to take effect - it works for me :)

**Comment by aler9** [comment]
The hot reloading system was updated by @ey3ball ; please try this nightly release and let me know if there's any difference
[rtsp-simple-server_v0.13.2-4-g2052848_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5811050/rtsp-simple-server_v0.13.2-4-g2052848_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.13.2-4-g2052848_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5811052/rtsp-simple-server_v0.13.2-4-g2052848_linux_amd64.tar.gz)
[rtsp-simple-server_v0.13.2-4-g2052848_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5811053/rtsp-simple-server_v0.13.2-4-g2052848_linux_arm6.tar.gz)
[rtsp-simple-server_v0.13.2-4-g2052848_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5811054/rtsp-simple-server_v0.13.2-4-g2052848_linux_arm7.tar.gz)
[rtsp-simple-server_v0.13.2-4-g2052848_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5811055/rtsp-simple-server_v0.13.2-4-g2052848_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.13.2-4-g2052848_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5811056/rtsp-simple-server_v0.13.2-4-g2052848_windows_amd64.zip)

**Comment by ndaidong** [comment]
@aler9 thank you for your effort. I will try and give feedback later.

**Comment by ndaidong** [comment]
@aler9 it seems you have resolved the root cause. Now it always reloads the config even I update yml file with my script or regular editor (tested: vim,  sublime, geany, mousepad).

Should I close this issue?

**Comment by aler9** [comment]
added in v0.13.3
