### ISSUE TITLE
drawtext gmtime uses shell command

### ISSUE THREAD

**Issue by whitetiger21022014** [aler9/rtsp-simple-server#1313]
Ubuntu: 
Linux ubuntu 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
rtsp-simple-server version :  compiled

Thank for your program
I use gmtime (eg. $(date +%s -d '25190 seconds'), runOnDemand as below

**mystream2:**
        **runOnDemand:** ffmpeg -re -rtsp_transport tcp -i rtsp://admin:12345678@192.168.1.201:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif -preset
ultrafast  -vf "drawtext=text='%{pts\:gmtime\:\$(date +%s -d '25190 seconds')}':fontcolor=white:fontsize=60:x=10:y=10" -c:v hevc -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH

drawtext has problem: [Parsed_drawtext_0 @ 0x557e29dc60c0] Invalid delta '$(date +%s -d 25190 seconds)'
Because golang change from $(date +%s -d 25190 seconds) to  string '$(date +%s -d 25190 seconds)'

**Another test**
I tested as below and it works

func main() {
    cmdStr = `ffmpeg -re -rtsp_transport tcp -i rtsp://admin:12345678@192.168.1.201:554/cam/realmonitor?channel=1\&subtype=0\&unicast=true\&proto=Onvif -preset ultrafast  -vf "drawtext=text='%{pts\:gmtime\:$(date +%s -d '25190 seconds')}':fontcolor=white:fontsize=60:x=10:y=10" -c:v hevc -f rtsp rtsp://127.0.0.1:10010/mystream3`

    cmd := exec.Command("bash", "-c", cmdStr)
    err := cmd.Run()
    if err != nil {
	log.Println(err)
    }
}

Have to use: "bash", "-c",...
Thank you

**Comment by tmatth** [comment]
Previously discussed here: https://github.com/aler9/rtsp-simple-server/issues/828#issuecomment-1050652278

**Comment by aler9** [comment]
> Have to use: "bash", "-c",...
> Thank you

exactly
