### ISSUE TITLE
drawtext gmtime uses shell command

### ISSUE THREAD

**Issue by whitetiger21022014** [aler9/rtsp-simple-server#1314]
## Which version are you using?

v0.20.4

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I use gmtime (eg. $(date +%s -d '25190 seconds'), runOnDemand as below

**mystream2:**
        **runOnDemand:** ffmpeg -re -rtsp_transport tcp -i rtsp://admin:12345678@192.168.1.201:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif -preset
ultrafast  -vf "drawtext=text='%{pts\:gmtime\:\$(date +%s -d '25190 seconds')}':fontcolor=white:fontsize=60:x=10:y=10" -c:v hevc -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH

drawtext has problem: [Parsed_drawtext_0 @ 0x557e29dc60c0] Invalid delta '$(date +%s -d 25190 seconds)'
Because golang change date command to string

**Another test**
I tested an example as below and it works

func main() {
    cmdStr = `ffmpeg -re -rtsp_transport tcp -i rtsp://admin:12345678@192.168.1.201:554/cam/realmonitor?channel=1\&subtype=0\&unicast=true\&proto=Onvif -preset ultrafast  -vf "drawtext=text='%{pts\:gmtime\:$(date +%s -d '25190 seconds')}':fontcolor=white:fontsize=60:x=10:y=10" -c:v hevc -f rtsp rtsp://127.0.0.1:10010/mystream3`

    cmd := exec.Command("bash", "-c", cmdStr)
    err := cmd.Run()
    if err != nil {
	log.Println(err)
    }
}

Have to use: "bash", "-c",...
Thank you

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by whitetiger21022014** [comment]
It works if I change https://github.com/aler9/rtsp-simple-server/blob/main/internal/externalcmd/cmd_unix.go#L20
//cmd := exec.Command(cmdparts[0], cmdparts[1:]...)
cmd := exec.Command("bash", "-c", e.cmdstr)

mystream2:
        runOnDemand: ffmpeg -re -rtsp_transport tcp -i rtsp://admin:12345678@192.168.1.201:554/cam/realmonitor?channel=1\&subtype=0\&unicast=true\&proto=Onvif -preset ultrafast  -vf "drawtext=text='%{pts\:gmtime\:$(date +%s -d '25190 seconds')}':fontcolor=white:fontsize=60:x=10:y=10" -c:v hevc -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH

But have to use backslash in the link: eg: channel=1\&subtype=0\&unicast=true\&proto=Onvif

**Comment by andersondeoliveiramachado** [comment]
It works.

`paths:
  cam:
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -pix_fmt yuv420p -preset ultrafast -vf "drawtext=text='%{localtime\:%d\\\\\/%m\\\\\/%Y\\\\\ %H\\\\\:%M\\\\\:%S}':fontcolor=black:fontsize=60:x=10:y=10" -b:v 600k -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
`

**Comment by aler9** [comment]
If you want to use bash, use it:

```yml
paths:
  mystream:
    runOnDemand: bash -c '...'
```
