### ISSUE TITLE
Missing ID in WebRTC readers

### ISSUE THREAD

**Issue by tbnguyen1407** [aler9/rtsp-simple-server#1318]
## Which version are you using?

v0.21.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Session/Connection ID is not present in path readers (`v1/paths/list`) but present in connection list (`v1/webrtcconns/list`). Only HLS should have missing ID.

```
GET /v1/paths/list
{
    "items": {
        "fc958801-cac5-3601-9e6e-c9960b5dd3a7": {
            "readers": [
                {
                    "type": "rtmpConn",
                    "id": "e28190cf-e253-4ff4-a17c-e657c3d3d6ef"
                },
                {
                    "type": "rtmpConn",
                    "id": "a860cf9c-fe09-4512-a3d7-8306b4ece88d"
                },
                {
                    "type": "hlsMuxer"
                },
                {
                    "type": "webRTCConn"
                },
                {
                    "type": "rtspSession",
                    "id": "eca92f62-8fed-48bf-affb-2ff6677f789a"
                },
                {
                    "type": "rtspsSession",
                    "id": "02f9b15d-f7b6-4f2f-8969-9f057e6ec9e1"
                }
            ]
        }
    }
}
```

## Describe how to replicate the issue

1. start the server
2. publish with any stream
3. read WebRTC with browser
4. Call `v1/paths/list`

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Thanks for reporting the issue, it has been fixed.

**Comment by aler9** [comment]
Added in v0.21.1
