### ISSUE TITLE
WebRTC stream does not work for some web browsers

### ISSUE THREAD

**Issue by amoramar** [aler9/rtsp-simple-server#1319]
## Which version are you using?

v0.21.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When running the RTSP server with WebRTC enabled, I am not able to access the video stream from all web browsers. In my experience, Google Chrome works, but Mozilla Firefox doesn't. Logs hint at a possible difference between IPv4 and IPv6.

## Describe how to replicate the issue

1. Start the server with default parameters (WebRTC enabled).
2. Start an RTSP stream from a camera (e.g. laptop webcam) using FFMPEG, in `rtsp://127.0.0.1:8554/mystream`.
3. Open `http://localhost:8889/mystream` in Mozilla Firefox --> stream is **NOT** visible
4. Open `http://localhost:8889/mystream` in Google Chrome --> stream **IS** visible

## Did you attach the server logs?

Yes
[webrtc-ipv4-ipv6.txt](https://github.com/aler9/rtsp-simple-server/files/10268247/webrtc-ipv4-ipv6.txt)

## Did you attach a network dump?

No

**Comment by t3therdev** [comment]
Windows OS - Microsoft Edge. Stream "sometimes" opens but sometimes doesn't, sometimes takes up to 1 minute to load. Works always immediately in Chrome.

**Comment by aler9** [comment]
Hello, this has been fixed by 777860f7576dae5ad700c80a7842733811c6bcad.

**Comment by phit** [comment]
thank you!
