### ISSUE TITLE
Add RESOLUTION, BANDWIDTH, FRAME-RATE to HLS master playlist

### ISSUE THREAD

**Issue by scottf-tvw** [aler9/rtsp-simple-server#1320]
## Describe the feature
the HLS spec allows for the RESOLUTION attribute in the `EXT-X-STREAM-INF` as an option. 
Eg. `#EXT-X-STREAM-INF:BANDWIDTH=2246797,CODECS="avc1.428028,mp4a.40.2",RESOLUTION=1920x1080`
My parsers for HLS use this as an easy way to get information, including dimensions from a stream vs probing frames directly with RTMP. Even though this is optional in [rfc8216](https://datatracker.ietf.org/doc/html/rfc8216#page-30),  I rarely see it omitted by software that produce HLS via a transport conversion. You already have to get the codec information as a requirement..
I am not a go developer, however I can take a crack at it and submit a PR but any guidance would be helpful.

**Comment by scottf-tvw** [comment]
as an addendum. it seems that you are setting an arbitrary static value for `BANDWIDTH` = 200000bps 
[here](https://github.com/aler9/rtsp-simple-server/blob/bab5caee015ec7377104e394d464cc6da01f9925/internal/hls/muxer_primary_playlist.go#L64) which is more than likely not true of the actual calculated value of the bitrate of the stream. 
Which is not what the RFC states as the intent for `BANDWIDTH`. 

```
BANDWIDTH

      The value is a decimal-integer of bits per second.  It represents
      the peak segment bit rate of the Variant Stream.

      If all the Media Segments in a Variant Stream have already been
      created, the BANDWIDTH value MUST be the largest sum of peak
      segment bit rates that is produced by any playable combination of
      Renditions.  (For a Variant Stream with a single Media Playlist,
      this is just the peak segment bit rate of that Media Playlist.)
      An inaccurate value can cause playback stalls or prevent clients
      from playing the variant.

      If the Master Playlist is to be made available before all Media
      Segments in the presentation have been encoded, the BANDWIDTH
      value SHOULD be the BANDWIDTH value of a representative period of
      similar content, encoded using the same settings.
```

This is not a dig at you and the contributors, it just seems the hls implementation is not fully baked?

**Comment by aler9** [comment]
@scottf-tvw both the `RESOLUTION` and the `BANDWIDTH` attributes are two good enhancements that can be developed on.

Regarding the bandwidth attribute, developing it was impossible since a month ago, since bandwidth metrics were not available. Now bandwidth metrics are available for each path (and can be read with metrics or APIs), therefore implementing bandwidth shouldn't be much difficult.

**Comment by aler9** [comment]
RESOLUTION, FRAME-RATE and BANDWIDTH attributes are now filled correctly.
