### ISSUE TITLE
WebRTC has NO audio in browser

### ISSUE THREAD

**Issue by iesv** [aler9/rtsp-simple-server#1329]
## Which version are you using?

v0.21.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

WebRTC has no audio in browser.
OBS settings:
![image](https://user-images.githubusercontent.com/16969250/209420436-6aa0f19a-0543-42b4-8f32-bb2a13e93da4.png)
![image](https://user-images.githubusercontent.com/16969250/209420450-8d8f409f-cf88-4b1f-ab21-bb1da23b1564.png)

## Describe how to replicate the issue

1. start the server
2. publish with OBS27
3. read with Chrome: http://127.0.0.1:8889/live/test

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by t3therdev** [comment]
You need to use the supported audio codecs. Opus, G711, G722 (Per main page of project). Tested with G711 and its working.

**Comment by iesv** [comment]
Thanks. but, How can I use opus audio format on OBS when streaming?

**Comment by t3therdev** [comment]
OBS Studio by default uses AAC as the audio codec, which is not supported by WebRTC. What you need to do is use the RunOnReady command (See main page info) and transcode the audio to a webrtc supported coded like Opus. 

[https://github.com/aler9/rtsp-simple-server#remuxing-re-encoding-compression](url)

Example:

`paths:
  all:
  original:
    runOnReady: ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH  -vcodec copy -c:a libopus  -f rtsp rtsp://localhost:$RTSP_PORT/compressed
    runOnReadyRestart: yes`

Note, you will need to create another path for webrtc to hit with the re-encoded audio.

**Comment by iesv** [comment]
I tried this, but it cannot work.
ffmpeg -i rtsp://localhost:$RTSP_PORT/$RTSP_PATH -vcodec copy -c:a libopus -f rtsp rtsp://localhost:$RTSP_PORT/live/test2

2022/12/26 15:41:57 INF [RTSP] [conn [::1]:50865] opened
2022/12/26 15:41:57 INF [RTSP] [session c311eba0] created by [::1]:50865
2022/12/26 15:41:57 INF [RTSP] [session c311eba0] is reading from path 'live/test2', with UDP, 2 tracks (H264, Opus)
2022/12/26 15:41:59 INF [RTMP] [conn 127.0.0.1:50870] opened=N/A speed=2.98x
2022/12/26 15:41:59 INF [RTMP] [conn 127.0.0.1:50870] closed (no one is publishing to path 'live/andy')
Input #0, rtsp, from 'rtsp://localhost:8554/live/test2':rate=N/A speed=2.49x
  Metadata:
    title           : Stream
  Duration: N/A, start: 0.119146, bitrate: N/A
  Stream #0:0: Video: h264 (High), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
  Stream #0:1: Audio: opus, 48000 Hz, stereo, fltp
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (opus (native) -> opus (libopus))
Press [q] to stop, [?] for help
[libopus @ 00000127cb3709c0] No bit rate set. Defaulting to 96000 bps.
2022/12/26 15:41:59 INF [RTSP] [conn [::1]:50871] opened
2022/12/26 15:41:59 INF [RTSP] [session a9a5ce1d] created by [::1]:50871
2022/12/26 15:41:59 INF [path live/test2] closing existing publisher
2022/12/26 15:41:59 INF [path live/test2] runOnReady command stopped
2022/12/26 15:41:59 INF [RTSP] [conn [::1]:50864] closed (terminated)
2022/12/26 15:41:59 INF [RTSP] [conn [::1]:50865] closed (terminated)
2022/12/26 15:41:59 INF [RTSP] [session f5a01851] destroyed (terminated)
2022/12/26 15:41:59 INF [RTSP] [session c311eba0] destroyed (terminated)
2022/12/26 15:41:59 INF [RTSP] [conn [::1]:50871] closed (read tcp [::1]:8554->[::1]:50871: wsarecv: An existing connection was forcibly closed by the remote host.)
2022/12/26 15:41:59 INF [RTSP] [session a9a5ce1d] destroyed (not in use)
av_interleaved_write_frame(): Broken pipe
Error writing trailer of rtsp://localhost:8554/live/test2: Broken pipe
frame=   91 fps= 43 q=-1.0 Lsize=N/A time=00:00:05.07 bitrate=N/A speed= 2.4x
video:362kB audio:61kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
2022/12/26 15:41:59 INF [RTSP] [session 4b48b52f] destroyed (teared down by [::1]:50352)
2022/12/26 15:41:59 INF [RTSP] [conn [::1]:50352] closed (read tcp [::1]:8554->[::1]:50352: wsarecv: An existing connection was forcibly closed by the remote host.)
Conversion failed!
2022/12/26 15:41:59 INF [path live/yes] runOnReady command exited with code 1

**Comment by t3therdev** [comment]
you can't specify the output channel like this: rtsp://localhost:$RTSP_PORT/live/test2

you have to create another path on RTSP simple server config. 

if your first path is /test1
your transcoded path needs to be like /test1-transcoded or /test2 
the ffmpeg command is pushing the "new" stream to that new path
