### ISSUE TITLE
webRTC has a lot of audio noise when using the OBS recording push stream.

### ISSUE THREAD

**Issue by iesv** [aler9/rtsp-simple-server#1336]
## Which version are you using?

v0.21.0

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
webRTC has a lot of noise when using the OBS recording push stream.

![image](https://user-images.githubusercontent.com/16969250/209760957-fb033748-5e9f-4033-95b3-2c8b98ceea3f.png)

## Describe how to replicate the issue

1. start the server
2. publish with OBS
3. read with Chrome of Windows or Android（http://127.0.0.1:8889/live）

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Hello, these are the settings that i used and it worked perfectly. Try making sure that B-frames are disabled in order not to mess up timestamps:

![Capture](https://user-images.githubusercontent.com/46489434/216663954-d20dae7c-b68a-4af7-9ec8-e1c054de06b3.PNG)
