### ISSUE TITLE
Cannot start Docker container

### ISSUE THREAD

**Issue by projeto-arcanjo** [aler9/rtsp-simple-server#1359]
## Which version are you using?

v0.21.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Even when I fill these parameters the container still complaining and do not start.
The only things I've changed was:

```
webrtcICEHostNAT1To1IPs: [10.5.112.132]
# Address of a ICE UDP listener in format host:port.
# If filled, ICE traffic will come through a single UDP port,
# allowing the deployment of the server inside a container or behind a NAT.
webrtcICEUDPMuxAddress: :8189
# Address of a ICE TCP listener in format host:port.
# If filled, ICE traffic will come through a single TCP port,
# allowing the deployment of the server inside a container or behind a NAT.
# At the moment, setting this parameter forces usage of the TCP protocol,
# which is not optimal for WebRTC.
webrtcICETCPMuxAddress: :8190
```

My old version was working fine until I update to the latest today with WebRTC feature.

I'm in doubt if ```webrtcICEHostNAT1To1IPs``` is the container address or the Docker host address.

## Describe how to replicate the issue

Just start the container like this:

```
docker run --name midiaserver --hostname=midiaserver \
	-e RTSP_PROTOCOLS=tcp \
	-p 8554:8554 \
	-p 9997:9997 \
	-p 1935:1935 \
	-p 8888:8888 \
	-p 8889:8889 \
	-p 8189:8189/udp \
	-p 8189:8189 \
	--restart=always \
	-v /srv/midiaserver/rtsp-simple-server.yml:/rtsp-simple-server.yml \
	-d aler9/rtsp-simple-server:latest
```

## Did you attach the server logs?

yes 

```
ERR: non-existent parameter: 'webrtcICETCPMuxAddress'
ERR: non-existent parameter: 'webrtcICETCPMuxAddress'
ERR: non-existent parameter: 'webrtcICEUDPMuxAddress'
ERR: non-existent parameter: 'webrtcICEHostNAT1To1IPs'
ERR: non-existent parameter: 'webrtcICEHostNAT1To1IPs'
ERR: non-existent parameter: 'webrtcICETCPMuxAddress'
```

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, the new parameters you're trying to use are not yet included in an official release, you have to wait for a new release or build from source.

**Comment by projeto-arcanjo** [comment]
So please be more specific because ```ERR: non-existent parameter``` was not clear to me if it is asking for a parameter that I not fill or is telling me that I gave a parameter that it was not expecting.
