### ISSUE TITLE
rtsp source ERR: Content-Length exceeds 4096

### ISSUE THREAD

**Issue by zhaibin18** [aler9/rtsp-simple-server#136]
## Which version are you using?

v0.12.1

## Which operating system are you using?

Linux

## Describe the problem

2020/11/27 13:36:54 [0/0/0] rtsp-simple-server v0.12.1
2020/11/27 13:36:54 [0/0/0] [UDP/RTP server] opened on :8002
2020/11/27 13:36:54 [0/0/0] [UDP/RTCP server] opened on :8003
2020/11/27 13:36:54 [0/0/0] [TCP server] opened on :8554
2020/11/27 13:36:54 [0/0/0] [path tv01] rtsp source started
2020/11/27 13:36:54 [0/0/0] [path tv01] connecting to rtsp source
2020/11/27 13:36:54 [0/0/0] [path tv01] rtsp source ERR: Content-Length exceeds 4096

## Did you attach a network dump?

yes 
[4k_rtsp.zip](https://github.com/aler9/rtsp-simple-server/files/5606132/4k_rtsp.zip)

**Comment by aler9** [comment]
Hello, thanks for reporting the issue, the maximum length of content of RTSP requests/responses has been increased from 4k to 128k - the fix will be included in the next release.
Meanwhile, you can use this nightly release
[rtsp-simple-server_v0.12.2-3-g46265f9_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5607920/rtsp-simple-server_v0.12.2-3-g46265f9_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.12.2-3-g46265f9_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5607921/rtsp-simple-server_v0.12.2-3-g46265f9_linux_amd64.tar.gz)
[rtsp-simple-server_v0.12.2-3-g46265f9_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5607922/rtsp-simple-server_v0.12.2-3-g46265f9_linux_arm6.tar.gz)
[rtsp-simple-server_v0.12.2-3-g46265f9_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5607923/rtsp-simple-server_v0.12.2-3-g46265f9_linux_arm7.tar.gz)
[rtsp-simple-server_v0.12.2-3-g46265f9_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5607924/rtsp-simple-server_v0.12.2-3-g46265f9_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.12.2-3-g46265f9_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5607925/rtsp-simple-server_v0.12.2-3-g46265f9_windows_amd64.zip)

**Comment by zhaibin18** [comment]
thanks！there is no error about ‘Content-Length exceeds 4096’ but with error 
’rtsp source ERR: sdp: invalid syntax `b=RS:0` (b=RS:0)‘
[rtsp_4k_02.zip](https://github.com/aler9/rtsp-simple-server/files/5608293/rtsp_4k_02.zip)

**Comment by aler9** [comment]
Hello, your SDP is now supported, please try this nightly release
[rtsp-simple-server_v0.12.2-4-g716e2ed_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5610387/rtsp-simple-server_v0.12.2-4-g716e2ed_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.12.2-4-g716e2ed_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5610388/rtsp-simple-server_v0.12.2-4-g716e2ed_linux_amd64.tar.gz)
[rtsp-simple-server_v0.12.2-4-g716e2ed_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5610389/rtsp-simple-server_v0.12.2-4-g716e2ed_linux_arm6.tar.gz)
[rtsp-simple-server_v0.12.2-4-g716e2ed_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5610390/rtsp-simple-server_v0.12.2-4-g716e2ed_linux_arm7.tar.gz)
[rtsp-simple-server_v0.12.2-4-g716e2ed_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5610391/rtsp-simple-server_v0.12.2-4-g716e2ed_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.12.2-4-g716e2ed_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5610392/rtsp-simple-server_v0.12.2-4-g716e2ed_windows_amd64.zip)

**Comment by zhaibin18** [comment]
there is another error:
2020/12/01 08:44:35 [0/0/0] rtsp-simple-server v0.12.2-4-g716e2ed
2020/12/01 08:44:35 [0/0/0] [UDP/RTP server] opened on :8002
2020/12/01 08:44:35 [0/0/0] [UDP/RTCP server] opened on :8003
2020/12/01 08:44:35 [0/0/0] [TCP server] opened on :8554
2020/12/01 08:44:35 [0/0/0] [path tv01] rtsp source started
2020/12/01 08:44:35 [0/0/0] [path tv01] connecting to rtsp source
2020/12/01 08:44:35 [0/0/0] [path tv01] rtsp source ERR: transport header: invalid ports (8052)
2020/12/01 08:44:40 [0/0/0] [path tv01] connecting to rtsp source
2020/12/01 08:44:40 [0/0/0] [path tv01] rtsp source ERR: transport header: invalid ports (8052)
[rtsp_4k_03.zip](https://github.com/aler9/rtsp-simple-server/files/5619554/rtsp_4k_03.zip)

**Comment by aler9** [comment]
@zhaibin18 i've fixed that too :)
rtsp-simple-server and the underlying libraries gortsplib and pion/sdp are implemented by following the official RFC specifications, it seems like your TV (is it a TV?) is using a highly irregular syntax. Never mind. Let's see if this is the final fix or more are required.
[rtsp-simple-server_v0.12.2-18-ga6c06d3_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5649540/rtsp-simple-server_v0.12.2-18-ga6c06d3_windows_amd64.zip)
[rtsp-simple-server_v0.12.2-18-ga6c06d3_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5649541/rtsp-simple-server_v0.12.2-18-ga6c06d3_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.12.2-18-ga6c06d3_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5649542/rtsp-simple-server_v0.12.2-18-ga6c06d3_linux_arm7.tar.gz)
[rtsp-simple-server_v0.12.2-18-ga6c06d3_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5649543/rtsp-simple-server_v0.12.2-18-ga6c06d3_linux_arm6.tar.gz)
[rtsp-simple-server_v0.12.2-18-ga6c06d3_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5649545/rtsp-simple-server_v0.12.2-18-ga6c06d3_linux_amd64.tar.gz)
[rtsp-simple-server_v0.12.2-18-ga6c06d3_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5649546/rtsp-simple-server_v0.12.2-18-ga6c06d3_darwin_amd64.tar.gz)

**Comment by zhaibin18** [comment]
@aler9 many thank for your update,the input is IPTV from my ISP, I use the latest build and there are still errors:
2020/12/07 11:58:32 [0/0/0] rtsp-simple-server v0.12.2-18-ga6c06d3
2020/12/07 11:58:32 [0/0/0] [UDP/RTP server] opened on :8002
2020/12/07 11:58:32 [0/0/0] [UDP/RTCP server] opened on :8003
2020/12/07 11:58:32 [0/0/0] [TCP server] opened on :8554
2020/12/07 11:58:32 [0/0/0] [path tv01] rtsp source started
2020/12/07 11:58:32 [0/0/0] [path tv01] connecting to rtsp source
2020/12/07 11:58:32 [0/0/0] [path tv01] rtsp source ERR: bad status code: 405 (Method Not Allowed)
[rtst_4k_04.zip](https://github.com/aler9/rtsp-simple-server/files/5650361/rtst_4k_04.zip)

**Comment by aler9** [comment]
Hello, the client (rtsp-simple-server) is able to correctly setup the stream, but when it calls PLAY, the server (IPTV) suddenly responds with 405.

Here's what happens:
```
[client] DESCRIBE rtsp://61.135.88.174:554/PLTV/88888892/224/3221225968/10000100000000060000000000157831_0.smil?playseek=20201206090000-20201206100000 RTSP/1.0
[server] the stream has been moved to rtsp://61.135.88.174:554/refuse/unavailable_media.wmv
[client] DESCRIBE rtsp://61.135.88.174:554/refuse/unavailable_media.wmv
[server] ok, the path contains two tracks, one video, one application
[client] SETUP video
[server] ok
[client] SETUP application
[server] ok
[client] PLAY rtsp://61.135.88.174:554/refuse/unavailable_media.wmv
[server] 405 not allowed
```

Therefore, i have two hypothesis (which i can't verify since i don't have access to your IPTV):
* since the server redirects the client to a path that ends with "refuse/unavailable_media.wmv", it means that the stream is not available at the moment or the client did a wrong setup
* the client tries to setup both a video track and an application track, which contains a proprietary protocol; maybe it shouldn't setup the application track

Do the stream works with VLC? if this is the case, try attaching a network dump of 30 seconds of communication between the IPTV and VLC. Thanks

**Comment by zhaibin18** [comment]
maybe something wrong with the ISP,I can  not play the video from VLC, So please close the issue.
