### ISSUE TITLE
Change RTSP port

### ISSUE THREAD

**Issue by carlosib** [aler9/rtsp-simple-server#1397]
## Which version are you using?

v0.21.1-5-gfb06f6

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [X] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description
I tried to change the RTSP port in the file 'rtsp-simple-server.yml' but it always start using default port 8554

## Describe how to replicate the issue

Edit the file rtsp-simple-server.yml

Change the port from **8554** to **554**
Save the file rtsp-simple-server.ym

1. start the server
2. See the info: 2023/01/19 10:31:47 INF [RTSP] listener opened on :**8554** (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)

## Did you attach the server logs?

 no

## Did you attach a network dump?

 no

**Comment by tsightler** [comment]
I think the issue is clear, look at the second line which contains the warning that the configuration file was not found.  Make sure you have named the file the correctly and are passing the correct path to the configuration file.

**Comment by aler9** [comment]
It looks like the server is being used as a MultiStreamer integration, without a configuration file. In order to customize the server, you should contact MultiStreamer authors.
