### ISSUE TITLE
Support RPi Camera Autofocus

### ISSUE THREAD

**Issue by azsde** [aler9/rtsp-simple-server#1416]
## Describe the feature

Some camera modules (including the newest V3 module from Raspberry Pi) do support different autofocus mode, it would be a great addition to support them as parameters.

**Comment by azsde** [comment]
I implemented it myself as it was not too difficult.

As stated in the PR, the only parameter I did not include is the AutoFocus Window as I did not fully understand how it was supposed to work.

The documentation specifies a single rectangle but the libcamera defines multiple windows ?

`extern const Control<Span<const Rectangle>> AfWindows;`

**Comment by aler9** [comment]
Fixed by #1417
