### ISSUE TITLE
LL-HLS without cert requirement / https, for use behind reverse proxy or on edge servers

### ISSUE THREAD

**Issue by renzo-s** [aler9/rtsp-simple-server#1420]
## Describe the feature

Is it possible to not let the service check for certificates when serving an LL-HLS stream? It's pretty common to let edge servers or reverse proxy's manage this. Also scaling in such an architecture is far more difficult when the app needs the certs at init.

Thanks!

**Comment by aler9** [comment]
HTTPS with LL-HLS is currently mandatory since it's mandatory on Apply devices, but this may be a good enhancement.

**Comment by aler9** [comment]
fixed by #1530

**Comment by aler9** [comment]
added in v0.21.6
