### ISSUE TITLE
"deadline exceeded" error when stream is watched with a mobile connection

### ISSUE THREAD

**Issue by dbuscaino** [aler9/rtsp-simple-server#1422]
## Which version are you using?

v0.21.2 (the problem was also present in the previous version)

## Which operating system are you using?

- [x] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When I try to watch a stream using webrtc and a mobile connection the stream never loads and the server prints the error "deadline exceeded" (the problem occurs both if I try to watch the stream from my smartphone and if I try to watch it from the pc using the hotspot)

EDIT:
I found out that the problem occurs only when the server is not running in your local network. Let me explain: if I run rtsp-simple-server on a public ip machine with a wired or wireless internet connection (not mobile) then I can view the stream with webrtc from any other device connected to a wired or wireless network. If I try to watch this streaming using the connection provided by my sim (both from phone and pc) then the error in question occurs.
If I use my phone's hotspot and connect both the server and the device to stream from then I can view the stream correctly.

I tried downloading the rtsp server code and increasing the value of the constants `webrtcHandshakeDeadline` and `webrtcWsWriteDeadline` (declared in: `internal/core/webrtc_conn.go`) to avoid the deadline exceeded error. The connection now happens without the error being raised but new error is raised: `received sdp is not an offer webrtc`.

Unfortunately I have not saved the logs generated by the server but if you need I can regenerate them

## Describe how to replicate the issue

1. start the server on a machine with public ip

2. publish with any ffmpeg command (mine: `ffmpeg -input_format h264 -f video4linux2 -video_size 800x600 -framerate 30 -i /dev/video0 -c:v copy -an -preset ultrafast -tune zerolatency -rtsp_transport udp -f link_rtsp`

3. read with webrtc on firefox or chrome (or any browser I think) (both with encryption and without) from a smartphone or mobile connection in general 

## Did you attach the server logs?

yes
[rtsp-simple-server.log](https://github.com/aler9/rtsp-simple-server/files/10511720/rtsp-simple-server.log)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello,

> I found out that the problem occurs only when the server is not running in your local network. 

There are instructions in the [README](https://github.com/aler9/rtsp-simple-server#usage-inside-a-container-or-behind-a-nat) that describes how to establish a WebRTC connection when behind a NAT.

**Comment by dbuscaino** [comment]
A thousand thanks! I didn't know I had to configure that part. Now everything works perfectly, thanks again!
