### ISSUE TITLE
metrics not working in last versions

### ISSUE THREAD

**Issue by dmitrysdm** [aler9/rtsp-simple-server#1430]
## Which version are you using?

v0.21.1
v0.21.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
config:

```sh
metrics: yes
metricsAddress: 127.0.0.1:9998
```

but pages:
```sh
http://127.0.0.1:9998/metrics
or
http://localhost:9998/metrics
```
are empty

## Did you attach the server logs?
 no

## Did you attach a network dump?
 no

**Comment by zLucPlayZ** [comment]
this is still an issue, i dont have any metrics, it wont show anything on the api port and metrics port. Literally just stetted the config variable to "yes"
