### ISSUE TITLE
Support reading h265 with Webrtc

### ISSUE THREAD

**Issue by pikachu937** [aler9/rtsp-simple-server#1438]
## Describe the feature

Todo:

- [ ] add support for h265 into webrtc_conn
- [ ] or realtime transcode from h265 to h264 for playng video over webrtc

**Comment by aler9** [comment]
Hello, H265 inside WebRTC is currently supported by Safari only, therefore it's not much useful to add support for it at this precise time.

You can transcode from H265 to H264 at any moment by using FFmpeg, as described in the README:

https://github.com/aler9/rtsp-simple-server#remuxing-re-encoding-compression

**Comment by aler9** [comment]
Streaming H265 with WebRTC is now supported with #4003
