### ISSUE TITLE
Can't open h264 file saved with ffmpeg

### ISSUE THREAD

**Issue by Zwuwen** [aler9/rtsp-simple-server#1455]
## Which version are you using?

v0.21.2

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description
ffmpeg version : FFmpeg 5 get from https://johnvansickle.com/ffmpeg/
 get the below error when I read my saved h264 file.
non-existing PPS 0 referenced
decode_slice_header error
[h264 @ 0x7628340] no frame!
## Describe how to replicate the issue

1. start the server
2. publish with ...  ffmpeg -re -stream_loop -1 -i soccker.mp4 -c copy  -f rtsp  rtsp://192.168.50.57:8554/mystream
3. read with ...   ffmpeg -i rtsp://192.168.50.57:8554/mystream -c copy output.h264
4. read info  with ... ffprobe output.h264

## Did you attach the server logs?

yes 

## Did you attach a network dump?

[error.log](https://github.com/aler9/rtsp-simple-server/files/10673433/error.log)
no

**Comment by aler9** [comment]
Hello, this is a FFmpeg question, not a server question, anyway in order to save a file on disk you have to use a container like MP4, MPEG-TS or MKV:

```
ffmpeg -i rtsp://192.168.50.57:8554/mystream -c copy -f mp4 output.mp4
```
