### ISSUE TITLE
[Raspberry Pi] exec format error after building from source

### ISSUE THREAD

**Issue by azsde** [aler9/rtsp-simple-server#1457]
## Which version are you using?

master (from git)

## Which operating system are you using?

- [ X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

After following the steps to compile rtsp-simple-server and uploading the binary to my raspberry pi, i get the following error:

2023/02/07 19:05:58 INF [path cam] [rpicamera source] ERR: fork/exec /dev/shm/rtspss-embeddedexe-1675793158294883745: exec format error

## Describe how to replicate the issue

1. Clone the repo and follow the steps to build for a raspberry pi
2. Edit the configuration to use the rpi camera
3. Start the server

## Did you attach the server logs?

yes

```
2023/02/07 19:05:58 INF rtsp-simple-server v0.21.2-13-g50a3d33
2023/02/07 19:05:58 INF [path cam] [rpicamera source] started
2023/02/07 19:05:58 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/02/07 19:05:58 INF [RTMP] listener opened on :1935
2023/02/07 19:05:58 INF [HLS] listener opened on :8888
2023/02/07 19:05:58 INF [WebRTC] listener opened on :8889 (HTTP)
2023/02/07 19:05:58 INF [path cam] [rpicamera source] ERR: fork/exec /dev/shm/rtspss-embeddedexe-1675793158294883745: exec format error
```

## Did you attach a network dump?

no

**Comment by azsde** [comment]
I'm quite puzzled by this issue.

I've successfully compiled the app in the past, now for some reason I can't seem to do it...

**Comment by aler9** [comment]
Hello, instructions in the README are meant for compiling, not for cross-compiling.
You're trying to cross-compile, i.e. you're trying to build a binary for the Raspberry Pi on a amd64 machine.
In order to compile the server, you have to perform the operation on a Raspberry Pi.
If you want to cross compile, you can use Docker (`make binaries`) or you have to manually setup a gcc instance for cross-compiling.
