### ISSUE TITLE
TrojanDropper.Dapato.acbs

### ISSUE THREAD

**Issue by brandousov** [aler9/rtsp-simple-server#146]
## Which version are you using?

v0.12.2

## Which operating system are you using?

Windows (+Mac + Linux - no viruses)

## Question
There is trojan detection alert on VT:
https://www.virustotal.com/gui/file/f3bec6c7374b18ae8cc89ea8b9b97022d41bf6014a68e78f6d65f04d857fd43e/detection

**Comment by brandousov** [comment]
And one more report for nightly version (rtsp-simple-server_v0.12.2-1-g0f11dd5_windows_amd64.zip) -  https://www.virustotal.com/gui/file/165cda3d13efefbc1c88ca9c34513141b9d750d9bd6b79cdbcc7d43cf9ffc6ce/detection

**Comment by aler9** [comment]
Official releases are compiled the CI system (was Travis CI until now, will be GitHub Actions from the next release), not manually. The only input of this process is the source code, there's no human intervention nor external factors, so it's surely a false positive.

Regarding nightly releases, i usually post them to help people solve issues, but they're not intended for general usage and i think i better remove them it after a while.
