### ISSUE TITLE
Stream Status WebHook

### ISSUE THREAD

**Issue by usama-liaqat** [aler9/rtsp-simple-server#1462]
## Describe the feature

Description
Can you add WebHook Feature so server can now when stream is running or not to make some operations on the basis of stream status.

**Comment by aler9** [comment]
Hello, you can already send data to webhooks by using `wget` inside `runOnReady`, `runOnInit`, `runOnDemand`.

**Comment by EmadHelmi** [comment]
It's not enough. What should we do if we want to send data to a webhook when a stream ends. Is there any `runOn*` to run when a session or a stream end?

**Comment by aler9** [comment]
@EmadHelmi yes, you can launch a script in runOn* and listen on SIGINT, as explained here: https://github.com/bluenviron/mediamtx/discussions/554#discussioncomment-1282935

Furthermore there's an enhancement request to add runOn*stop commands in order to make the feature more user friendly: #1464
