### ISSUE TITLE
[0.21.3] It does NOT work by pushing like this url on 0.21.3. rtmp://localhost/live/stream

### ISSUE THREAD

**Issue by iesv** [aler9/rtsp-simple-server#1469]
## Which version are you using?

v0.21.3

## Which operating system are you using?

- [ x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
It does not support second-level URL by pushing, but previous versions were normal. If it is not supported, other streaming software, such as Larix broadcaster, will not work.
Description

## Describe how to replicate the issue

1. start the server
2. publish with rtmp://localhost/live/stream

**Comment by aler9** [comment]
thanks for reporting the issue, this is fixed in v0.21.4.
