### ISSUE TITLE
Server tears down session when RTSP TCP socket disconnected

### ISSUE THREAD

**Issue by billsimon** [aler9/rtsp-simple-server#149]
## Which version are you using?

v0.12.2

## Which operating system are you using?

Linux

## Describe the problem

If the TCP socket is disconnected, rtsp-simple-server ends the session. The session should remain active until timeout or explicitly ended with a TEARDOWN method.

**Comment by aler9** [comment]
Hello, this is a delicate subject - the specification does indeed says that sessions should remain active until a timeout or a TEARDOWN request, but the practice differs from the theory.

On the server side, closing the session with the TCP socket allows the server to detect invalid publishers immediately, allowing other publishers to take over, and at the same time allows the server to save bandwidth by avoiding sending frames to invalid readers.

On the client side, most clients stop reading or publishing when the TCP socket becomes invalid, without trying to recreate it. The TCP socket is kept open with periodic keep-alives.

The only pros i see in embracing the standard behavior is the ability for a publisher to restore the stream without disconnecting existing readers.

Therefore, this feature could be implemented with an optional parameter in the configuration.

**Comment by billsimon** [comment]
I agree that if you choose to implement it, it should be optional.

My intention was to begin reading a stream and disconnect, saving the session number and then reconnect later to issue a keep alive or teardown.

However the session numbers are not unique either. So I have since moved on to a more conventional approach of keeping the connection open.

**Comment by eLvErDe** [comment]
Hello,

Also interested in such feature, I have the feeling janus we etc gateway does not really like shutdown on RTSP server side. Would be interesting if its behavior would be different.

**Comment by aler9** [comment]
added in v0.16.0

**Comment by IqbalLx** [comment]
Hi, how can I use this features in the configuration file? My RTSP camera unexpectedly close its connection after several hours, I can't find the camera setting that control when the camera will restart, so I hope by using this proxy server whenever my rtsp camera close the connection my program still connect to the proxied url and retrieving black/empty frame, and when my rtsp back to live the frame can continue
