### ISSUE TITLE
WebRTC doesn't support H264 streams with B-frames

### ISSUE THREAD

**Issue by yggzs-xes** [aler9/rtsp-simple-server#1491]
## Which version are you using?

v0.21.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

After successful streaming, WebRTC cannot be previewed normally using the browser

## Describe how to replicate the issue

1. start the server
2. publish with OBS
3. open with Microsoft Edge http://127.0.0.1:8889/live/1

## Did you attach the server logs?

2023/02/19 16:47:25 INF [WebRTC] [conn 127.0.0.1:53276] opened
2023/02/19 16:47:26 INF [WebRTC] [conn 127.0.0.1:53276] peer connection established, local candidate: host/udp/192.168.203.1/51956, remote candidate: prflx/udp/192.168.203.1/51952
2023/02/19 16:47:26 INF [WebRTC] [conn 127.0.0.1:53276] is reading from path 'live/123456', 1 track (H264)
2023/02/19 16:47:26 INF [WebRTC] [conn 127.0.0.1:53276] closed (WebRTC doesn't support H264 streams with B-frames)

## Did you attach a network dump?

no

## Problems I need to solve

how to let the rtsp server support H264 streams with B-frames, or how to let html use other frames to play video

Solve one of them to meet my needs

**Comment by aler9** [comment]
It's a browser limitation, not a server one.
Disable B-frames or fill a bug into the Firefox, Chromium and Edge bug tracking system, but they will all reply that the WebRTC specification doesn't contemplate B-frames.
