### ISSUE TITLE
H265 on RTMP - no video, only sound

### ISSUE THREAD

**Issue by tekijiyuu** [aler9/rtsp-simple-server#1494]
## Which version are you using?

v0.21.4

## Which operating system are you using?

Windows 10 22H2

## Describe the issue
OBS with H265(NVIDIA NVENC HEVC) on RTMP give me only sound without video, with RTSP all working correct.

## Describe how to replicate the issue
OBS stream with NVIDIA NVENC HEVC

1. start the server
2. publish with OBS v29.0.2 (64bit)
stream settings: 
Encoder: NVIDIA NVENC HEVC
Rate Control: CBR
Bitrate: 2500
Keyframe interval: 2
Preset : P5 Slow (Good Quality)
Tuning: Low Latency
Multipass Mode: Single Pass
Profile: Main
Max B-frames: 0
3. VLC v3.0.18

## Did you attach the server logs?
with publishing:
 [RTMP] [conn 127.0.0.1:11594] is publishing to path 'Tengu', 2 tracks (H265, MPEG4-audio)
on RTMP read:
[RTMP] [conn 127.0.0.1:11772] is reading from path 'Tengu', 1 track (MPEG4-audio)
on RTSP read:
[RTSP] [session 92155e59] is reading from path 'Tengu', with UDP, 2 tracks (H265, MPEG4-audio)

## Did you attach a network dump?

 no

**Comment by aler9** [comment]
Use RTSP to read the stream:

rtsp://localhost:8554/Tengu

Nor VLC nor the server support reading H265 with RTMP, as explicitly written in the README.
