### ISSUE TITLE
Server does not issue a response for TEARDOWN method

### ISSUE THREAD

**Issue by billsimon** [aler9/rtsp-simple-server#151]
## Which version are you using?

v0.12.2

## Which operating system are you using?

Linux

## Describe the problem

When the server receives a TEARDOWN request it ends the session and closes the connection but does not respond to the client with a 200 OK. In the example from the RFC (https://tools.ietf.org/html/rfc2326#section-10.7) a response is shown.

**Comment by aler9** [comment]
Hello, thanks for reporting this issue, fortunately i was working on a [base class](https://github.com/aler9/gortsplib/blob/master/examples/server.go) that allows to build RTSP servers from scratch in Go, and one of the side effects is that teardown requests are handled correctly. I've added a unit test to ensure that this behavior is preserved:
https://github.com/aler9/gortsplib/blob/master/serverconf_test.go#L274

**Comment by aler9** [comment]
this was added to v0.13.0
