### ISSUE TITLE
 Clients unable to connect to RTSP using mobile network but able through WiFi

### ISSUE THREAD

**Issue by Computershik73** [aler9/rtsp-simple-server#1523]
## Which version are you using?

v0.21.5

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I use RealPlayer on Symbian and VLC Player on Android to connect to my stream. If I use Wi-Fi, the video plays well. If mobile network - for most cell providers - infinite loading and "unable to connect" after some time. Some cell providers work however.
If I re-stream the stream with live555 streaming proxy (from port 8554 to 8853, for example) - the stream over mobile network works

## Describe how to replicate the issue

1. start the server
2. publish with  ffmpeg -re -stream_loop -1 -i "http://78.25.155.47:1309/channel/Perv_SD.ts" -b:v 400k -f rtsp -rtsp_protocols tcp "rtsp://localhost:8554/perv"
3. read with RealPlayer or VLC - open the url "rtsp://localhost:8554/perv"

## Did you attach the server logs?

yes 

## Did you attach a network dump?

no

**Comment by Computershik73** [comment]
Logs through mobile network (playing fails)
[logg.txt](https://github.com/aler9/rtsp-simple-server/files/10859231/logg.txt)

**Comment by Computershik73** [comment]
Logs through WiFi (playing works) 
[loggwi.txt](https://github.com/aler9/rtsp-simple-server/files/10859234/loggwi.txt)

**Comment by Computershik73** [comment]
Changing port to 554 solved the issue. This was not mentioned in your guides.

**Comment by aler9** [comment]
Hello, from the logs it seems that you're publishing and reading a stream with the UDP protocol, which may be blocked by your mobile network provider or can't be used when there's a NAT between client and server. Disable support for UDP as mentioned in the README. The port has nothing to do with this.
