### ISSUE TITLE
New Version of libcamera0 produces known error #1195

### ISSUE THREAD

**Issue by madison8935** [aler9/rtsp-simple-server#1544]
## Which version are you using?

v0.21.5

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [X] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Same Problem as mentioned in Issue #1195. New Version of Libcamera.

## Describe how to replicate the issue

1. start the server as described for use with rpiCamera
2. publish with ./rtsp-simple-server
3. read with vlc-player

## Did you attach the server logs?

yes

> zero@zero1w1:~ $ ./rtsp-simple-server
2023/03/09 16:20:23 INF rtsp-simple-server v0.21.5
2023/03/09 16:20:23 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/03/09 16:20:23 INF [RTMP] listener opened on :1935
2023/03/09 16:20:23 INF [HLS] listener opened on :8888
2023/03/09 16:20:23 INF [path cam] [rpicamera source] started
2023/03/09 16:20:23 INF [WebRTC] listener opened on :8889 (HTTP)
/dev/shm/rtspss-embeddedexe-1678375223795615656: error while loading shared libraries: libcamera.so.0.0.3: cannot open shared object file: No such file or directory
2023/03/09 16:20:23 INF [path cam] [rpicamera source] ERR: process exited unexpectedly

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Thanks for reporting the issue, yes, they did it again. This is fixed by #1548.

**Comment by aler9** [comment]
fixed in v0.21.6
