### ISSUE TITLE
Issues with MPEGTS / RTSP

### ISSUE THREAD

**Issue by Syu-syusan** [aler9/rtsp-simple-server#155]
## Which version are you using?

rtsp-simple-server-0.12.2

## Which operating system are you using?

OS

- [〇] Linux
- [ ] Windows
- [ ] macOS

But i'm using wsl2.

Architecture

- [〇] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

i could use this rtsp-simple-server 2 weeks ago, by using ffmpeg.

`ffmpeg -re -stream_loop -1 -i test.mp4 -c copy -f rtsp rtsp://localhost:8554/mystream`

but today, i cant use this server with following error code.

`ERR: unable to find control attribute (rtsp://localhost:8554/mystream)`

![1608051067621](https://user-images.githubusercontent.com/74150680/102271084-3563a600-3f62-11eb-8a9a-cd4213366e0b.jpg)

i dont figure out why this problem has occured.
So please help me...
thank you.

## Describe how to replicate the issue

1. start the server 
2. publish with ffmpeg
3. read with

**Comment by aler9** [comment]
Hello, sorry but i need more details

* are you able to publish to the server, and then you are not able anymore to read from the server? which reader are you using?
* or alternatively, you can't publish anymore? from the logs it appears you're connecting again to the server, after a minute, so i don't know if this is the case

**Comment by dlueth** [comment]
Same problem here @aler9 . Publishing (as a simple testcase) mp4/ts via ffmpeg seems to work as server logs 'is publishing...'. But when client connects (TVHeadend in my case) I get the exact same message and nothing happens.

**Comment by aler9** [comment]
@dlueth to fix this i need a network dump, that can be generated in this way

> If the bug arises when using rtsp-simple-server with an external hardware or software, the most helpful content you can provide is a dump of the data exchanged between the server and the target (network dump), that can be generated in this way:
> 1) Download wireshark (https://www.wireshark.org/)
> 2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed on your pc, the interface is probably "loopback", otherwise it's the one of your network card)
> 3) Start the server and replicate the issue
> 4) Stop capturing, save the result in .pcap format
> 5) Attach

**Comment by dlueth** [comment]
@aler9 will debug a bit more tonight and see what I can do ;)

**Comment by dlueth** [comment]
@aler9 seems as if in my case TVHeadend is the problem. Although it should play rtsp natively it's implementation seems to be buggy. Requesting the stream via ffmpeg works.

Now I only have to find a working pipeline for GST to publish an incoming rtp (not rtsp) Iptv stream to the rtsp server... All my attempts failed so far @aler9 :(

**Comment by aler9** [comment]
> Now I only have to find a working pipeline for GST to publish an incoming rtp (not rtsp) Iptv stream to the rtsp server... All my attempts failed so far @aler9 :(

gstreamer is hard, keep trying :D

In the meanwhile i'll try with TVHeadend

**Comment by dlueth** [comment]
Hehe, thx @aler9 - let's see what we both can achieve ;)

**Comment by aler9** [comment]
Ok, i've checked and
* rtsp-simple-server works as TVHeadend mux when the URL is a pipe://ffmpeg like

   ```
   pipe:///usr/bin/ffmpeg -loglevel fatal -i rtsp://user:password@192.168.1.195:554/videoMain -vcodec copy -acodec copy -metadata service_provider=Foscam -metadata service_name=FB836 -f mpegts -tune zerolatency pipe:1
   ```

* rtsp-simple-server doesn't work as TVHeadend mux when a RTSP url is used natively; the TVHeadend RTSP implementation is too minimal and sends this

```
SETUP rtsp://localhost:8554/stream RTSP/1.0
CSeq: 1
Transport: RTP/AVP;unicast;client_port=48474-48475
```

Instead of this

```
SETUP rtsp://localhost:8554/stream/trackID=0 RTSP/1.0
CSeq: 1
Transport: RTP/AVP;unicast;client_port=48474-48475
```

I'll evaluate whether i can add support for the minimal syntax

**Comment by dlueth** [comment]
@aler9 That would be so awesome! ffmpeg was my planned workaround for the moment - if I manage to get that damn gstreamer pipeline done ;) But guess that a potential fix within TVHeadend would be beneficial for switching times, so I would greatly appreciate that!

**Comment by aler9** [comment]
tvheadend is now supported natively; keep in mind that it supports only streams encoded in MPEG2, encapsuled in MPEGTS, encapsuled again in RTP, that can be generated only with Gstreamer. This is the pipeline i used for testing

```
gst-launch-1.0 -v filesrc location=VTS_01_3.VOB ! mpegpsdemux name=d d. ! 'video/mpeg' ! mpegvideoparse ! mpegtsmux ! queue ! rtspclientsink location=rtsp://localhost:8554/stream
```

**Comment by dlueth** [comment]
Awesome @aler9 ! 1000 thanks ;) I had no problem getting gstreamer pipeline into rtsp-simple-server at all - just that TVHeadend could not read it. ATM my flow is as follows

TVHeadend => rtsp-simple-server => dumpstream => gstreamer => rtsp-simple-server => TVHeadend (via ffmpeg-pipe)

If you could have a look at #185 and either solve it or help me find my error I guess I am 100% happy ;)

**Comment by dlueth** [comment]
@aler9 hm, just cloned the repo, built the binary and tested it: seems as if onDemand does not work at all with this version...

... and I switched TVHeadend to rtsp-simple-server directly (instead of via ffmpeg) but kodi-client still reports "no signal"

**Comment by dlueth** [comment]
@aler9 OK, I see, your wrote "MPEG2" - my streams are MPEGTS containing H264 video + MP2 audio

**Comment by aler9** [comment]
It works with 

* video: MPEG2 / H264 streams
* audio: MP2 streams

they have to be encapsuled in MPEGTS - usually MPEGTS is not used with RTSP, since it's a mux format that contains multiple tracks, while RTSP supports multiple tracks natively.

Here are the instructions for anyone wishing to use rtsp-simple-server together with tvheadend:

1. i started rtsp-simple-server

2. i published a stream to rtsp-simple-server, by using gstreamer and one of the pipelines below. It's necessary to wait about 15 seconds before Gstreamer starts publishing to rtsp-simple-server.

   **MPEG2 video only**

   ```
   gst-launch-1.0 -v filesrc location=VTS_01_3.VOB ! mpegpsdemux ! 'video/mpeg' ! mpegvideoparse ! mpegtsmux ! rtspclientsink location=rtsp://localhost:8554/stream
   ```

   **H264 video only** (please look at the config-interval parameter)

   ```
   gst-launch-1.0 -v filesrc location=myfile.mp4 ! qtdemux ! 'video/x-h264' ! h264parse config-interval=1 ! mpegtsmux ! rtspclientsink location=rtsp://localhost:8554/stream
   ```

3. i started tvheadend, i went to http://localhost:9981

4. in configuration -> DVB inputs -> muxes, i added a new mux called "test" with URL `rtsp://localhost:8554/stream` and status `active`

5. in configuration -> DVB inputs -> services, there's an automatically-generated service; i clicked the "map services -> map all services" button

6. i opened this URL in VLC

   ```
   http://localhost:9981/playlist/channels
   ```

Regarding the streaming of muxes with video AND audio, it's a GStreamer problem, unfortunately i can't do anything.

**Comment by dlueth** [comment]
Thanks @aler9 it works like this for source-paths! I forgot the mpegtsmux as it is not required for conforming clients. Funny enoug this works for TVHeadend directly, but my other mux there with an ffmpeg-pipe to the same URI does not work with MPEGTS.

In my case the pipeline (for TVHeadend) looks like this (on an NVidia Jetson Nano using HW-acceleration where possible):
```
gst-launch-1.0 \
    mpegtsmux name=out ! rtspclientsink location=rtsp://127.0.0.1:8554/${CHANNEL} latency=500 udp-buffer-size=5000000 \
    fdsrc \
      ! video/mpegts \
      ! tsparse set-timestamps=true \
      ! tsdemux name=in \
      in. \
        ! queue \
        ! h264parse config-interval=1 \
        ! nvv4l2decoder \
        ! nvvidconv interpolation-method=5 \
        ! 'video/x-raw(memory:NVMM), width=(int)720, height=(int)576, format=(string)I420' \
        ! nvv4l2h264enc iframeinterval=25 preset-level=1 profile=4 control-rate=1 bitrate=4000000 insert-sps-pps=1 cabac-entropy-coding=1 \
        ! video/x-h264, stream-format=byte-stream \
        ! queue \
        ! out.sink_0 \
      in. \
        ! queue \
        ! mpegaudioparse \
        ! audio/mpeg, stream-format=byte-stream \
        ! queue \
        ! out.sink_1
```

**Comment by dlueth** [comment]
@aler9 Still, one thing I just found out:
While non MPEGTS-streams (meaning push video+audio seperately into rtspclientsink) trigger `runOnDemand` commands MPEGTS streams do not, for some reason. Instead I get `no one is publishing to path` message.

**Comment by dlueth** [comment]
@aler9 digging a bit deeper in the sources and adding a some debugging to the related `fmt.Errorf` shows that MPEGTS-requests seem to end up in `internal/path/path.go` line 677 without ever calling any onDemand commands like the default way does.

**Comment by aler9** [comment]
> @aler9 digging a bit deeper in the sources and adding a some debugging to the related fmt.Errorf shows that MPEGTS-requests seem to end up in internal/path/path.go line 677 without ever calling any onDemand commands like the default way does.

This means, if i understood correctly, that the publisher request is being interpreted as a reader request.

To replicate (and fix) this i need a Gstreamer pipeline that causes the issue, based on videotestsrc and audiotestsrc - if you want to use Jetson elements it's ok, i have a lot of Xavier AGXs / NXs at my disposal.

**Comment by dlueth** [comment]
Here you go @aler9 - used omxh264enc if that is OK for you:

```
gst-launch-1.0 \
  rtspclientsink name=out location=rtsp://127.0.0.1:8554/test latency=500 udp-buffer-size=5000000 \
  videotestsrc is-live=true \
    ! queue \
    ! 'video/x-raw, width=(int)1280, height=(int)720, framerate=(fraction)25/1, format=(string)NV12' \
    ! omxh264enc insert-aud=1 iframeinterval=25 preset-level=0 profile=8 control-rate=2 EnableTwopassCBR=true bitrate=4000000 insert-sps-pps=true cabac-entropy-coding=true \
    ! video/x-h264, stream-format=byte-stream \
    ! queue \
    ! out.sink_0 \
  audiotestsrc \
    ! queue \
    ! out.sink_1
```

The pipeline works for me if I start it onDemand and request it through an ffmpeg-pipe within TVHeadend like this

```
pipe:///usr/bin/ffmpeg -loglevel fatal -hide_banner -fflags +genpts -i rtsp://x.x.x.x:8554/test -c copy -tune zerolatency -f mpegts pipe:1
```

It does not start onDemand if I directly put `rtsp://x.x.x.x:8554/test` in TVHeadend + it does also not start if I set it to `source: record` and publish it manually before requesting it via `rtsp://x.x.x.x:8554/test` in TVHeadend (although rtsp-server logs it is indeed being published).

Let me know if the info is sufficient or you need anything more ;)

**Comment by aler9** [comment]
@dlueth thanks for the info, the issue with onDemand should be fixed, please try this nightly release and let me know if it works
[rtsp-simple-server_v0.13.3-5-gd0590e6_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5889825/rtsp-simple-server_v0.13.3-5-gd0590e6_windows_amd64.zip)
[rtsp-simple-server_v0.13.3-5-gd0590e6_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5889826/rtsp-simple-server_v0.13.3-5-gd0590e6_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.13.3-5-gd0590e6_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5889827/rtsp-simple-server_v0.13.3-5-gd0590e6_linux_arm7.tar.gz)
[rtsp-simple-server_v0.13.3-5-gd0590e6_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5889828/rtsp-simple-server_v0.13.3-5-gd0590e6_linux_arm6.tar.gz)
[rtsp-simple-server_v0.13.3-5-gd0590e6_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5889829/rtsp-simple-server_v0.13.3-5-gd0590e6_linux_amd64.tar.gz)
[rtsp-simple-server_v0.13.3-5-gd0590e6_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5889830/rtsp-simple-server_v0.13.3-5-gd0590e6_darwin_amd64.tar.gz)

**Comment by dlueth** [comment]
@aler9 connection seems to get established just fine, onDemand command is started correctly, but kodi does not display anything from TVHeadend and ouputs "no signal". What I can see in the rtsp-simple-server service output is the following:

![grafik](https://user-images.githubusercontent.com/1613163/106214227-a687b180-61ce-11eb-9dc6-d151621a12d4.png)

This is a bit different to what gets logged when I put an ffmpeg-pipe into TVHeadend, which is:
`is reading from path 'test', 2 tracks with udp`

**Comment by dlueth** [comment]
@aler9 looks as if the new version does not stop the command automatically when no client is connected, in addition

**Comment by aler9** [comment]
> This is a bit different to what gets logged when I put an ffmpeg-pipe into TVHeadend, which is:
is reading from path 'test', 2 tracks with udp

This means that

* ffmpeg is reading TWO separate mpegts streams, probably one with the video, the other with the audio
* tvheadend is able to read only a single mpegts stream, that must contain both the video and the audio

**Comment by dlueth** [comment]
@aler9 So something like this should work and can be properly handled by rtsp-simple-server?
```
gst-launch-1.0 \
  mpegtsmux name=out ! rtspclientsink location=rtsp://127.0.0.1:8554/test latency=500 udp-buffer-size=5000000 \
  videotestsrc is-live=true \
    ! queue \
    ! 'video/x-raw, width=(int)1280, height=(int)720, framerate=(fraction)25/1, format=(string)NV12' \
    ! omxh264enc insert-aud=1 iframeinterval=25 preset-level=0 profile=8 control-rate=2 EnableTwopassCBR=true bitrate=4000000 insert-sps-pps=true cabac-entropy-coding=true \
    ! video/x-h264, stream-format=byte-stream \
    ! queue \
    ! out. \
  audiotestsrc \
    ! queue \
    ! out.
```

**Comment by dlueth** [comment]
@aler9 tried the pipeline above: works without TVHeadend ffmpeg-pipe, just rtsp-url pointing to rtsp-simple-server directly! Big thx ;)

**Comment by dlueth** [comment]
@aler9 This might not be an rtsp-simple-server issue: Just realized that this works perfect for h264 video + mp2 audio streams but when doing the same with h264 + ac3 the audio channel does not exist or is empty. Gstreamer pipeline is running fine though, and it works with the ffmpeg pipe in TVHeadend.

Any idea?

**Comment by aler9** [comment]
Well, i can solve one problem at a time :)
Regarding the runOnDemand problem, please try this nightly release and let me know if the custom command is shutdown down properly.
[rtsp-simple-server_v0.13.3-11-gb30dbc1_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5899592/rtsp-simple-server_v0.13.3-11-gb30dbc1_windows_amd64.zip)
[rtsp-simple-server_v0.13.3-11-gb30dbc1_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5899593/rtsp-simple-server_v0.13.3-11-gb30dbc1_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.13.3-11-gb30dbc1_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5899594/rtsp-simple-server_v0.13.3-11-gb30dbc1_linux_arm7.tar.gz)
[rtsp-simple-server_v0.13.3-11-gb30dbc1_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5899595/rtsp-simple-server_v0.13.3-11-gb30dbc1_linux_arm6.tar.gz)
[rtsp-simple-server_v0.13.3-11-gb30dbc1_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5899596/rtsp-simple-server_v0.13.3-11-gb30dbc1_linux_amd64.tar.gz)
[rtsp-simple-server_v0.13.3-11-gb30dbc1_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5899597/rtsp-simple-server_v0.13.3-11-gb30dbc1_darwin_amd64.tar.gz)

**Comment by dlueth** [comment]
@aler9 Seems to work just fine - have not had any leftover custom commands not getting shutdown properly ;)

**Comment by aler9** [comment]
> @aler9 This might not be an rtsp-simple-server issue: Just realized that this works perfect for h264 video + mp2 audio streams but when doing the same with h264 + ac3 the audio channel does not exist or is empty. Gstreamer pipeline is running fine though, and it works with the ffmpeg pipe in TVHeadend.

the working diagram is

```
gstreamer (mux into mpegts) --> rtsp-simple-server --> ffmpeg (demux from mpegts, mux into mpegts) --> std pipe --> tvheadend
```

while the not-working diagram is

```
gstreamer (mux into mpegts) --> rtsp-simple-server --> tvheadend
```

in my opinion, tvheadend is unable to demux properly the mpegts generated by gstreamer, while is able to demux the mpegts generated by ffmpeg. Anyway, not a server problem.

**Comment by dlueth** [comment]
@aler9 agreed, not a server problem

**Comment by pigubaoza** [comment]
Hi @dlueth, 

are there any alternatives to using **omxh264enc** and **nvv4l2h264enc**?
I tried using the default x264enc plugin but it does not have the following parameters you used: insert-aud=1 iframeinterval=25 preset-level=0 profile=8 control-rate=2 EnableTwopassCBR=true bitrate=4000000 insert-sps-pps=true cabac-entropy-coding=true

I am working on something and think that SPS/PPS might be the issue, so I would still like them to be present. 
I am on an x86 machine.

**Comment by dlueth** [comment]
@pigubaoza You can always use something like `gst-inspect-1.0 x264enc` to get all available properties of a gstreamer element

**Comment by pigubaoza** [comment]
@dlueth Yup. What I'm trying to say is that the x264enc element does not have the same properties, especially insert-sps-pps. Does this mean it is not inserting the SPS/PPS? Are there any alternative h264 encoder elements on x86 that would have this capability?

**Comment by billythedummy** [comment]
> @dlueth Yup. What I'm trying to say is that the x264enc element does not have the same properties, especially insert-sps-pps. Does this mean it is not inserting the SPS/PPS? Are there any alternative h264 encoder elements on x86 that would have this capability?

`h264parse` inserts sps and pps if you set the `config-interval` property. You should put it after your h264 encoder plugin

**Comment by hhackbarth** [comment]
Thanks for that valuable discussion. I do not see, why this should be limited to h.264 with MP2 audio only?

The following example pipeline also muxes h.264 + aac with GStreamer and packs this MPEGTS into RTSP:

gst-launch-1.0 -e videotestsrc is-live=true ! video/x-raw, width=1280, height=720, framerate=30/1, format=NV12 ! queue ! videoconvert ! queue ! x264enc bitrate=2500 ! mux. audiotestsrc ! queue ! audioconvert ! queue ! avenc_aac bitrate=128000 ! mux. mpegtsmux name=mux alignment=7 ! rtspclientsink location=rtsp://localhost:8554/live latency=1000 protocols=tcp+udp-mcast+udp rtx-time=0

Beside vlc, I could also play it e.g. with mpv, like:

mpv rtsp://localhost:8554/live

But the tone was not "clean". With avenc_ac3 it was clean and also with mfaacenc instead of avenc_aac it was clean. mfaacenc is an hardware accelerated "Media Foundation" encoder available in the Windows version of GStreamer.

My problem is, that it can not be requested using HLS but this is another discussion at #788
