### ISSUE TITLE
Support multiple rpiCameras at once

### ISSUE THREAD

**Issue by aler9** [aler9/rtsp-simple-server#1573]
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/1539

<div type='discussions-op-text'>

<sup>Originally posted by **marksutheran** March  7, 2023</sup>
Is it possible to have multiple paths which are paired to multiple cameras on the RPi module (e.g. using CM4)?

Libcamera seems happy enough to run both simultaneously and using rtsp-simple-server I can switch the camera id to select each camera independently using only one path. However, if I attempt to create two paths each pointing to a different camera I get the following error:

  ERR: 'rpiCamera' is used as a source in multiple paths ('cam0' and 'cam1') 

Which appears to be by design looking @ path.go - but maybe I just don't understand the configuration?

As a workaround I can use a publisher endpoint and libcamera/ffmpeg to feed the second camera it but I was wondering if there is a cleaner way?

Thanks!

ps) This is an awesome media server!</div>

**Comment by marksutheran** [comment]
Thanks! Let me know if I can help test out any configurations (using a CM4 on the IO Board)

ps. I wanted to try and test this by commenting out the checks in /internal/conf/path.go (lines 197-201) but haven't got the rpi build working yet due to some linking issue with libcamera

**Comment by aler9** [comment]
added in v0.22.0
