### ISSUE TITLE
buffer length exceeds 64

### ISSUE THREAD

**Issue by yarete03** [aler9/rtsp-simple-server#1589]
## Which version are you using?

rtsp-simple-server v0.21.6

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

The app works fine when I use RTMP but, when I try to use RTSP it shows an error: closed (buffer length exceeds 64)

## Describe how to replicate the issue

I just edited the conf file dissabling the protocols that won't be used as HLS and WebRTC. I also tried changing the value of readBufferCount to other ones like 2048, 8192... It didn't work. I used streamlabs to record the screen, and the pc that is recording is the same as the one hosting the app. This problem happened me ussing streamlabs, however using obs is not possible to obtain this error because obs dont entablish connection reporting an error of invalid URL or route. My route was exactly the same in both apps: rtsp://localhost:8554/live. I tried changing rtsp by rtsp in the URL of OBS and it solved the error menssage from OBS but rtsp-simple-server reported the same error: closed (buffer length exceeds 64). I tried too to set the app on debug mode, but no report file was generated.

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by Docteh** [comment]
Does stream labs actually support rtsp or is it just trying to use a different protocol instead?

**Comment by aler9** [comment]
The StreamLabs app uses RTMP. This is not a server issue. Please check the list of supported protocols of the apps you want to use (StreamLabs, OBS)
