### ISSUE TITLE
Segmentation Fault on YAML boolean alternative

### ISSUE THREAD

**Issue by dorinclisu** [aler9/rtsp-simple-server#160]
## Which version are you using?

v0.13.0

## Which operating system are you using?

OS
- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture
- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

Using YAML "false" instead of "no" results in `panic: runtime error: invalid memory address or nil pointer dereference`. It is very simple to replicate, just edit `encryption: false`.

Version v0.12.2 does not suffer from this bug.

**Comment by aler9** [comment]
Hello, thanks for reporting the bug, it has been fixed and the fill will be added to the next release.

**Comment by aler9** [comment]
added to v0.13.1
