### ISSUE TITLE
Prometheus Metrics into Grafana dashboard?

### ISSUE THREAD

**Issue by bbnp91** [aler9/rtsp-simple-server#163]
## Which version are you using?

v0.13.01

## Question

Has anyone managed to get the prometheus metrics into a grafana dashboard and is willing to make a dashboard template available?

Although I can see the metrics at http://serveraddress:9998/metrics, my attempts to get this into grafana are failing. 

Thanks

**Comment by golak** [comment]
I think you should run Prometheus server for grabbing this metrics

cat prometheus.yml 

```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
    
rule_files:
      # - "first.rules"

scrape_configs:
  - job_name: rtspserver
    static_configs:
      - targets: ['serveraddress:9998']
```

run prometheus

`docker run -p 9090:9090  -v $PWD/prometheus.yml:/etc/prometheus/prometheus.yml  prom/prometheus`

**Comment by bbnp91** [comment]
Thanks for your help. This solution worked as expected.
