### ISSUE TITLE
API access problem.

### ISSUE THREAD

**Issue by fpaiva36834** [aler9/rtsp-simple-server#1634]
## Which version are you using?

v0.21.6

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When i try to make the webserver get the api information it receives an error of CORS 
"Access to XMLHttpRequest at 'http://localhost:9997/v1/paths/list' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." I already tryed some ways to get around in the frontend but nothing.

## Describe how to replicate the issue

It happens when i have the api on normal port 9997 and webserver on 3000 and if webserver sends a fetch to api receives that error but if i do CURL on console to the api it works as normal.

## Did you attach the server logs?

"2023/03/31 15:35:50 DEB [API] [conn 127.0.0.1] GET /v1/paths/list
2023/03/31 15:35:50 DEB [API] [conn 127.0.0.1] [c->s] GET /v1/paths/list HTTP/1.1
Host: localhost:9997
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-PT,pt
Connection: keep-alive
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Ch-Ua: "Brave";v="111", "Not(A:Brand";v="8", "Chromium";v="111"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-Gpc: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

2023/03/31 15:35:50 DEB [API] [conn 127.0.0.1] [s->c] HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Server: rtsp-simple-server

(body of 12 bytes)"

## Did you attach a network dump?

no

**Comment by Docteh** [comment]
port 3000? is that a nodejs application? You could have your node application proxy the api

https://dev.to/bornfightcompany/bypassing-cors-via-custom-proxy-backend-2po

**Comment by fpaiva36834** [comment]
Yes that must be the problem the link you sent is quite right. I will test when i can and thanks.
