### ISSUE TITLE
Read authentication not enforced

### ISSUE THREAD

**Issue by dorinclisu** [aler9/rtsp-simple-server#164]
## Which version are you using?

 v0.12.2

## Which operating system are you using?

OS
- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture
- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Bug
- Tested with VLC client.
- Security enforced with `readUser` and `readPass` is not working as expected.
- Client can still receive a video stream even if the password is wrong.
- Strange thing, if the user is wrong client is rejected (correct behavior).

The server seems to check the password, because I see this in the logs, but it fails to reject access to the client (except when the user is wrong).
```
2020/12/20 21:31:02 [1/0/0] [client 172.18.0.1:42632] connected
2020/12/20 21:31:02 [1/0/0] [client 172.18.0.1:42632] OPTIONS
2020/12/20 21:31:02 [1/0/0] [client 172.18.0.1:42632] DESCRIBE
2020/12/20 21:31:02 [1/0/0] [client 172.18.0.1:42632] DESCRIBE
2020/12/20 21:31:02 [1/0/0] [client 172.18.0.1:42632] WARN: unauthorized: wrong response
2020/12/20 21:31:02 [1/0/0] [client 172.18.0.1:42632] OPTIONS
2020/12/20 21:31:02 [1/0/0] [client 172.18.0.1:42632] DESCRIBE
2020/12/20 21:31:02 [1/0/0] [client 172.18.0.1:42632] WARN: unauthorized: authorization header not provided
2020/12/20 21:31:02 [1/0/0] [client 172.18.0.1:42632] DESCRIBE
2020/12/20 21:31:02 [1/0/0] [path 29b6ee50] rtsp source started
2020/12/20 21:31:02 [1/0/0] [path 29b6ee50] connecting to rtsp source
2020/12/20 21:31:03 [1/0/0] [path 29b6ee50] rtsp source ready
2020/12/20 21:31:03 [1/0/0] [client 172.18.0.1:42632] SETUP
2020/12/20 21:31:03 [1/0/0] [client 172.18.0.1:42632] ERR: UDP streaming is disabled
2020/12/20 21:31:03 [1/0/0] [client 172.18.0.1:42632] SETUP
2020/12/20 21:31:03 [1/0/0] [client 172.18.0.1:42632] PLAY
2020/12/20 21:31:03 [1/0/1] [client 172.18.0.1:42632] is reading from path '29b6ee50', 1 track with tcp
```
I also tested with v0.13.1 and it also doesn't reject wrong password, the difference being that there are no warnings in the logs! Pretty nasty.

**Comment by aler9** [comment]
Hello, i tried in every possible way but i wasn't able to replicate the issue.

1. I started the server with this conf:

```yml
paths:
  all:
    readUser: test
    readPass: tast
```

2. i published a video with ffmpeg

3. i opened the stream with VLC and the command line; the stream was blocked
    ```
    vlc rtsp://test:tast@localhost:8554/stream
    ```

4. i opened the stream with VLC and the command line, without providing the password; i then filled the dialog that was asking for the credentials, and the stream was blocked
    ```
    vlc rtsp://localhost:8554/stream
    ```

5. i opened the stream with VLC, "media", "open network stream", and again, no results

please provide the exact steps to replicate the issue.

**Comment by dorinclisu** [comment]
Trying to replicate the issue, I figured it only happens when testing with vlc GUI (MacOS app), while everything works correctly when testing with vlc cli.

It turns out the GUI tries to be "smart" and whenever it gets a 401 it retries with previously used credentials.

<img width="673" alt="Screenshot 2021-01-02 at 20 25 17" src="https://user-images.githubusercontent.com/13818396/103463975-0eb2b700-4d39-11eb-860f-5dd6ea2ac6e8.png">

I am closing the issue because it's exclusively related to VLC behavior.

**Comment by aler9** [comment]
That's good, i was worried :)
