### ISSUE TITLE
Bind specific IP

### ISSUE THREAD

**Issue by chaminaud** [aler9/rtsp-simple-server#166]
## Which version are you using?

v0.13.1

## Question

I have seveval ethernet interfaces on my machine, and I would like to bind an instance on a specific ip.
It does not seems to be possible or do I miss something?
If not possible do you plan to implement it?

thanks, again the very good piece of software
regards

**Comment by aler9** [comment]
This feature is coming soon

**Comment by aler9** [comment]
added in master, will be added to the next release

**Comment by aler9** [comment]
added in v0.13.3
