### ISSUE TITLE
RTMP to RTSP

### ISSUE THREAD

**Issue by t3therdev** [aler9/rtsp-simple-server#168]
## Which version are you using?

v0.13.1

## Question

We have a number of devices that publish RTMP streams out to RTMP target servers as a normal function (to wowza, youtube, twitch,etc.). We are looking to see how we can use your server to act as an RTMP server (Recieve rtmp inbound stream) instead of using nginx or other. Our goal is to point the rtmp publisher (phone, device, etc) at aler9 server and output RTSP streams. Please let us know. It seems there is rtmp support only as a client to another rtmp server.

**Comment by aler9** [comment]
Hello, yes, this is under development and when it's done i'll post the results in the dedicated issue here

https://github.com/aler9/rtsp-simple-server/issues/132
