### ISSUE TITLE
sourceProtocol: automatic option not handles TCP-only stream

### ISSUE THREAD

**Issue by brandousov** [aler9/rtsp-simple-server#173]
## Which version are you using?

v0.12.1

## Enhancement request

Hi!
If camera streams from NAT/FW network, rtsp-ss reports `UDP timeout, retrying with TCP`, then `method PAUSE failed: 551 Option not supported`, then stops. But if I change `sourceProtocol: automatic` to `sourceProtocol: tcp` all works fine! :)  

VLC player correctly works with same situations and automatically switches to TCP only protocol. I think if I choose `sourceProtocol: automatic` rtsp-ss must apply the same logic.

This is an example of the same task execution with ffmpeg (stream from HikVision IPC):
```
$ ffmpeg -hide_banner -i rtsp://xxx:zzz@example.com:503/Streaming/Channels/102 -c copy -f null -
[rtsp @ 000001ea47e8d800] UDP timeout, retrying with TCP
[rtsp @ 000001ea47e8d800] method PAUSE failed: 551 Option not supported
[rtsp @ 000001ea47e8d800] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://xxx:zzz@example.com:503/Streaming/Channels/102':
  Metadata:
    title           : Media Presentation
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn, 180k tbc
Output #0, null, to 'pipe:':
Output file #0 does not contain any stream
```

**Comment by aler9** [comment]
Hello, i always disliked the ffmpeg behavior, because it doesn't allow users to recognize if the stream is being pulled with UDP or TCP, and therefore doesn't allow to catch eventual firewall problems.

BUT since the server has a `streamProtocol: automatic` parameter, it should probably switch to TCP automatically to solve these kind of problems - users that want to force UDP can use `streamProtocol: udp`

**Comment by dorinclisu** [comment]
I don't get it, what is the current purpose of "automatic" if it doesn't switch automatically to tcp?

**Comment by aler9** [comment]
The `automatic` value switches protocol automatically if the server replies with `451 - unsupported protocol` - currently it doesn't switches if there's a NAT problem - this 2nd case must be handled with an enhancement.

**Comment by aler9** [comment]
This feature is implemented in main and will be added to the next release.

**Comment by aler9** [comment]
added in v0.15.2
