### ISSUE TITLE
Firewall/NAT

### ISSUE THREAD

**Issue by InSpectrumed** [aler9/rtsp-simple-server#179]
## Which version are you using?

rtsp-simple-server v0.12.2

## Question

**[1/1/0] [client 195.x.x.x:50922] ERR: no packets received recently (maybe there's a firewall/NAT in between)**

My system is Ubuntu 18.04.5

When I add source from **localhost** ( gst-launch-1.0 videotestsrc ! clockoverlay halignment=right valignment=top text=\"SERVER h264 \" shaded-background=true font-desc=\"Sans, 36\" !  videoconvert ! videoscale ! video/x-raw,format=I420 ! x264enc tune=zerolatency bitrate=2000 speed-preset=ultrafast  ! h264parse ! queue !  rtspclientsink location=rtsp://**localhost**:8554/mystream ) - rtsp server works well.

When I add source from **external, white IP** ( gst-launch-1.0 videotestsrc ! clockoverlay halignment=right valignment=top text=\"SERVER h264 \" shaded-background=true font-desc=\"Sans, 36\" !  videoconvert ! videoscale ! video/x-raw,format=I420 ! x264enc tune=zerolatency bitrate=2000 speed-preset=ultrafast  ! h264parse ! queue !  rtspclientsink location=rtsp://**195.x.x.x**:8554/mystream ) - I have error: [1/1/0] [client 195.x.x.x:50922] ERR: _no packets received recently (maybe there's a firewall/NAT in between)_

How can I add a resource from external, white IP?

Thanks!

**Comment by aler9** [comment]
Hello, the problem with UDP mode is that it works only if the server and the client are both on the same LAN.

You can either
* use a VPN
* toggle TCP mode with `rtspclientsink location=location protocols=tcp`

**Comment by InSpectrumed** [comment]
Thank you. rtspclientsink location = location protocols = tcp, it worked.
