### ISSUE TITLE
Official docker image on hub.docker.com

### ISSUE THREAD

**Issue by x-jokay** [aler9/rtsp-simple-server#18]
Hellu

Any plans on providing official Docker images on [hub.docker.com](https://hub.docker.com)?

[Automated builds](https://docs.docker.com/docker-hub/builds/) from your GitHub releases would be great 👍

**Comment by x-jokay** [comment]
Not automated, but exists on `hub.docker.com` ...

[https://hub.docker.com/r/aler9/rtsp-simple-server](https://hub.docker.com/r/aler9/rtsp-simple-server)

**Comment by aler9** [comment]
Hello, docker images are a WIP, of course i intend to finish them as soon as possible.

**Comment by aler9** [comment]
Docker images are ready and available at
https://hub.docker.com/r/aler9/rtsp-simple-server
