### ISSUE TITLE
Configuration appearing to be ignored in docker

### ISSUE THREAD

**Issue by MattInternet** [aler9/rtsp-simple-server#183]
## Which version are you using?

v0.13.2

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

I am mounting a volume with a configuration in it that works locally. Once the volume is mounted it appears to be picked up because the container runs and stars putting out logs. It also says `reloading configuration` if I edit the config, so im quite sure it is getting the configuration. When I connect a stream to it it says connected and `is publishing to path` and everything looks fine except it isnt running my command in `runOnPublish`

Its strange because if I just download the binary and run it it with this same config it works perfectly. The current content in `runOnPublished` uses ffmpeg to output a file but it also does nothing in the container if i replace it with very simple things like `echo 'cat'`

## Describe how to replicate the issue

1. Make a directory and put the attached `config.txt`file in it (rename it to `config.yml` because GitHub wont let me attach a `.yml` file. [config.txt](https://github.com/aler9/rtsp-simple-server/files/5817516/config.txt)
2. `cd` into the directory and run `docker run --rm -it -e RTSP_PROTOCOLS=tcp -v ${PWD}:/app -w /app -p 8554:8554 aler9/rtsp-simple-server ./config.yml`

**Comment by MattInternet** [comment]
Super awesome project btw, thank you so much :D

**Comment by aler9** [comment]
Hello,

1. I've added to the README the right command to replace the configuration file when using Docker
    https://github.com/aler9/rtsp-simple-server#configuration

2. anyway, this is not your issue: the issue is that you're trying to use ffmpeg, but the Docker image doesn't contain ffmpeg, since there would be license issues and the image would become huge. You have to generate an image that contains both rtsp-simple-server and ffmpeg, in this way

```
FROM aler9/rtsp-simple-server AS rtsp
FROM alpine:3.12
RUN apk add --no-cache ffmpeg
COPY --from=rtsp /rtsp-simple-server /
ENTRYPOINT [ "/rtsp-simple-server" ]
```

**Comment by AndBondStyle** [comment]
@aler9 maybe you can CI-build an alternative docker tag with ffmpeg included? That would be very convenient
