### ISSUE TITLE
Permanent cpu usage with no clients connected and also default config

### ISSUE THREAD

**Issue by fragger42** [aler9/rtsp-simple-server#184]
## Which version are you using?

v0.13.2

## Which operating system are you using?

OS

- [X] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ ] amd64
- [ ] arm64
- [X] arm7
- [ ] arm6

Raspberry PI on Raspbian Buster

## Describe the issue

It seems like there has been a permanent cpu usage introduced in some of the later versions. I get between 2-5% permanent usage with the current v0.13.2 when there is no client connected (and also no server connected because I use sourceOnDemand=yes. The older v0.9.15 (yes, I skipped some versions ;)) used no cpu at all when there was no client connected. The same happens with the default config that is shipped with the release tar which has no streams defined. I tracked it down that v0.13.1 is the last version with low cpu usage on idle.
Another thing I noticed is that pmap of the process shows a pretty high memory reservation (not used actually, I know) but that is also in older versions:
00010000   3848K r-x-- rtsp-simple-server
003e0000   3188K r---- rtsp-simple-server
00700000    256K rw--- rtsp-simple-server
00740000     88K rw---   [ anon ]
01800000   4096K rw---   [ anon ]
01c00000 524288K -----   [ anon ]
66bb1000   1732K rw---   [ anon ]
66d62000 264128K -----   [ anon ]
76f52000    268K rw---   [ anon ]
7ed3e000    132K rw---   [ stack ]
7efcb000      4K r-x--   [ anon ]
7efcc000      4K r----   [ anon ]
7efcd000      4K r-x--   [ anon ]
ffff0000      4K r-x--   [ anon ]
 **total   802040K**

## Describe how to replicate the issue

Just start the server and watch "top".

**Comment by aler9** [comment]
Yes, this is caused by the new ring buffer introduced in v0.13.2, that allows to decouple the routine that reads frame from the routine that writes frames - tests revealed that this is the most performant way to pull frames and write them:

```go
for {
    frame := receiveFrameFromReaderWithoutBlocking()
    if frame == nil {
        time.Sleep(10 * time.Millisecond)
        continue
    }

    ...
}
```

This is always running when UDP is used, since UDP uses a single socket for every reader (in UDP, there isn't the concept of "connection", while in TCP there is)

Therefore, every 10 milliseconds the UDP writer checks for new frames. This uses CPU.
Of course if there's a more performant way, i'll immediately replace this.

**Comment by aler9** [comment]
Regarding reserved memory, it's Go that manages it, i can't do much other than reducing actual memory :)
If you want more free memory, try reducing the `readBufferCount` parameter.

**Comment by fragger42** [comment]
Maybe you could double the sleeptime each time you get a nil (until a maximum of for example 640ms) and set it to 10 again if there is something received? This way if there is no data, it should sleep a lot more and if there is a lot of data it should not be affected at all?

**Comment by fragger42** [comment]
So in code it would look something like this (sorry if I made an error but I don't know go in detail).
```go
sleeptime := 10
for {
    frame := receiveFrameFromReaderWithoutBlocking()
    if frame == nil {
        time.Sleep(sleeptime * time.Millisecond)
        sleeptime := sleeptime * 2
        if(sleeptime > 640) {
             sleeptime := 640
        }
        continue
    }
    sleeptime := 10
```

**Comment by aler9** [comment]
Yes it's a good idea, i need to test it

**Comment by aler9** [comment]
Idle load has been completely eliminated by replacing sleep() with a condition variable. Performance seems even better than the previous version.

**Comment by fragger42** [comment]
That sounds very good, thanks! I'm only wondering about one thing in commit 29265dc:
sleeptime is 10 *time.Millisecond. Shouldn't it be compared with 640*time.Millisecond (maybe also saved in a variable then) instead of just 640? I have no idea what it is really doing this way...

**Comment by aler9** [comment]
i completely eliminated that commit after performing some tests with the nearly-unknown sync.Cond:

https://github.com/aler9/gortsplib/commit/0b43bd2f19767baf9d506070909cd86162845ea7

**Comment by aler9** [comment]
added in v0.15.0
