### ISSUE TITLE
Be able to drop existing connection on path

### ISSUE THREAD

**Issue by OlegGavrilov** [aler9/rtsp-simple-server#187]
## Which version are you using?

v0.13.2

## Enhancement request

When my streaming clients are on the bad connections, they tend to restart streaming to the same rtsp path, but rtsp-simple-server refuses their connections with `someone is already publishing to path` error. 

I would like to have a configuration option to be able to drop existing connection of the rtsp path if there is a new client connected with that path.

**Comment by aler9** [comment]
That's interesting and of course it can be considered as a future enhancement. Of course a PR is always welcome.

**Comment by aler9** [comment]
this is implemented in master and will be added to the next release

**Comment by aler9** [comment]
added in v0.14.2

**Comment by OlegGavrilov** [comment]
> added in v0.14.2

Thank you! Sorry that I could not provide a PR for this tho.
