### ISSUE TITLE
Publishing second stream cause stuttering video

### ISSUE THREAD

**Issue by golfterminator** [aler9/rtsp-simple-server#189]
First let me say great job here.  Very easy to use tool and great features.

I am running the server executable on a proprietary encoder platform based on a Hisilicon encoder SOC.

I start one ffmpeg to send publish a rtsp stream and it works fine.  The ffmpeg command is:

/bin/ffmpeg -thread_queue_size 256 -copyts -vcodec h264 -analyzeduration 250000 -nostats -i /var/lcast/encpipe1 -acodec mp2 -blocksize 576 -thread_queue_size 256 -i /var/lcast/audiopipe1 -acodec copy -vcodec copy -copyinkf -muxdelay .4 -max_interleave_delta 0 -f rtsp rtsp://localhost:554/DFMX2-1
avformat_find_stream_info: video codec 28 interval 16667
Input #0, h264, from '/var/lcast/encpipe1':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, Closed Captions, 60 fps, 60 tbr, 1200k tbn, 120 tbc
avformat_find_stream_info: MP2 set to 24ms
Input #1, mp3, from '/var/lcast/audiopipe1':
  Duration: N/A, start: 0.000000, bitrate: 192 kb/s
    Stream #1:0: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s
outputName rtsp://localhost:554
Output #0, rtsp, to 'rtsp://localhost:554/DFMX2-1':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, q=2-31, 60 fps, 60 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)

I see this in the server logs:
Jan 20 22:41:52 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:41:52 [2/0/0] [client [::1]:58979] connected
Jan 20 22:41:52 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:41:52 [2/0/0] [client [::1]:58979] OPTIONS
Jan 20 22:41:52 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:41:52 [1/0/0] [client [::1]:58979] ANNOUNCE
Jan 20 22:41:52 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:41:52 [1/0/0] [client [::1]:58979] SETUP
Jan 20 22:41:52 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:41:52 [1/0/0] [client [::1]:58979] SETUP
Jan 20 22:41:52 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:41:52 [1/0/0] [client [::1]:58979] RECORD
Jan 20 22:41:52 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:41:52 [1/1/0] [client [::1]:58979] is publishing to path 'DFMX2-1', 2 tracks with udp

I view using VLC and it all looks great.  I leave the VLC playing the this first stream.

I then start up a second stream:

/bin/ffmpeg -thread_queue_size 256 -copyts -vcodec h264 -analyzeduration 250000 -nostats -i /var/lcast/encpipe0 -acodec mp2 -blocksize 576 -thread_queue_size 256 -i /var/lcast/audiopipe0 -acodec copy -vcodec copy -copyinkf -muxdelay .4 -max_interleave_delta 0 -f rtsp rtsp://localhost:554/DFMX2-2
avformat_find_stream_info: video codec 28 interval 16667
Input #0, h264, from '/var/lcast/encpipe0':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, Closed Captions, 60 fps, 60 tbr, 1200k tbn, 120 tbc
avformat_find_stream_info: MP2 set to 24ms
Input #1, mp3, from '/var/lcast/audiopipe0':
  Duration: N/A, start: 0.000000, bitrate: 192 kb/s
    Stream #1:0: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s
outputName rtsp://localhost:554
Output #0, rtsp, to 'rtsp://localhost:554/DFMX2-2':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, q=2-31, 60 fps, 60 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)

I see this in the server logs:
Jan 20 22:54:25 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:54:25 [3/1/1] [client [::1]:59225] connected
Jan 20 22:54:25 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:54:25 [3/1/1] [client [::1]:59225] OPTIONS
Jan 20 22:54:25 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:54:25 [3/1/1] [client [::1]:59225] ANNOUNCE
Jan 20 22:54:25 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:54:25 [3/1/1] [client [::1]:59225] SETUP
Jan 20 22:54:25 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:54:25 [3/1/1] [client [::1]:59225] SETUP
Jan 20 22:54:25 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:54:25 [3/1/1] [client [::1]:59225] RECORD
Jan 20 22:54:25 ZeeVee_ZZ58JA00083F local1.debug rtsp-simple-server: 2021/01/20 22:54:25 [3/2/1] [client [::1]:59225] is publishing to path 'DFMX2-2', 2 tracks with udp

As soon as I do that I see the VLC playback of the first stream starting to break up and distort.  Audio then goes away.  I am not connecting any VLC client to the second stream.

Any suggestions on where I should start looking to understand what the issue is?  I looked at the system performance and the processor does not look overloaded with the second stream running.

thanks,
Dave

**Comment by golfterminator** [comment]
I am using v0.12.1

**Comment by golfterminator** [comment]
Update: I started a second instance of rtsp-simple-server on a different set of ports for the second input stream.  This seems to work fine.

**Comment by aler9** [comment]
Hello, in my opinion the problem lays in the UDP protocol: the server uses a SINGLE socket to receive all UDP streams from publishers, and the same socket to send all UDP streams to readers. It saturates very easily.

Since UDP support has been enhanced a lot in the latest version, my advice is to

1. switch to the latest version (v0.13.3)
2. tune the `readBufferCount` parameter: when you increase it, you use more RAM but the UDP throughput increases

**Comment by golfterminator** [comment]
thanks you for the reply.  I updated to v0.13.3 and increased the readBufferCount to 16384.  This has solved the dual stream corruption issue.  Excellent.

I am seeing very frequent disconnects from my players.  I use VCL 3.0.12 and an Android media player.  I will investigate that and open another issue once I have more data.

BTW, enjoy the coffee :-).

thanks,
Dave
