### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by privatesam** [aler9/rtsp-simple-server#19]
Had the server working fine and recently a specific stream keeps erroring with:

    ERR: wrong magic byte (0x54)

**Comment by photostorm** [comment]
I got the same error when I got response frame from the camera instead interleaved frame

https://github.com/aler9/rtsp-simple-server/blob/master/streamer.go#L602

**Comment by aler9** [comment]
Hi, the server was not able to read requests while receiving TCP frames, please try again with v0.8.4 and let me know.
I don't know if this is fixed, but log messages should be much more accurate now.

**Comment by privatesam** [comment]
Ok will do thanks.

**Comment by Classsic** [comment]
Hi, I get this error when try to pull rtsp stream:
`2020/07/11 15:09:22 [0/0/0] [streamer proxied] ERR: transport header does not have interleaved=2-3 (RTP/AVP/TCP;unicast;interleaved=8-9;ssrc=2A27A3FB)`
Version v0.8.6.

**Comment by aler9** [comment]
@Classsic please open a dedicated issue and provide the name of the source RTSP server/camera, and also a packet dump in .pcap format would be very helpful.

**Comment by aler9** [comment]
This bug is solved since the `wrong magic byte (0x54)` error was caused by lack of support for interleaved frames. Now they are fully supported.
