### ISSUE TITLE
Relay "constantly changing URL"

### ISSUE THREAD

**Issue by scottgrobinson** [aler9/rtsp-simple-server#192]
## Which version are you using?

N/A / Latest

## Question

Google Nest cameras have a way of viewing there RTSP stream, but only via a URL which has limited life/avaliability until it stops. A new URL can be obtained to "keep it going". I have a simple script that gets the latest URL for me, but is there a way of create a relay stream where I can occasionally say "Hey - You have a new URL to relay, please switch to this"

**Comment by aler9** [comment]
Hello, unfortunately i don't have a Google Nest to replicate the issue, but my advice is to run a script that 

1. fetches the new URL
2. writes the URL to the server configuration, while the server is running

Since the server supports hot reloading, the configuration is reloaded after every change, so it does exactly what you're asking - switching to a new URL.

**Comment by scottgrobinson** [comment]
@aler9 That makes perfect sense - I'll give that a try and feedback. Thanks for the suggestion!

**Comment by scottgrobinson** [comment]
Hmm. It didn't seem to like the nest URLs. Debug log below.

Any initial thoughts? Hot reloading didn't work for me either, not sure if I need to enable that somehow...

{code}
nestrelay    | 2021/01/28 20:23:43 [D] [0/0/0] [path nestproxy] [rtsp source] s->c RTSP/1.0 200 OK
nestrelay    | CSeq: 4
nestrelay    | Cache-Control: no-cache
nestrelay    | Date: Thu, 28 Jan 2021 20:23:43 UTC
nestrelay    | Expires: Thu, 28 Jan 2021 20:23:43 UTC
nestrelay    | Server: Wowza Streaming Engine 4.7.4 build21380
nestrelay    | Session: 584747539;timeout=60
nestrelay    | Transport: RTP/AVP/TCP;unicast;interleaved=2-3;mode=play
nestrelay    |
nestrelay    |
nestrelay    | 2021/01/28 20:23:43 [D] [0/0/0] [path nestproxy] [rtsp source] c->s PLAY rtsps://stream-eu1-bravo.dropcam.com:443/sdm_live_stream/CiQA2vuxr7yGxbwRxHG0mvtky1uWxpIfDUbotpuz7PuDG44A6Q0ScQBMPhen3S61SMY0UFPMLXg1BCroDa2qnO6W0K8WxnXDhR2jLcUZlQQs5QZSqHil00ruYuHfbZarC31z5rZb80sjoQjy5DVmt11t9HRmhOL_r6ObEUpMfJHaig81fytSSAwAzb5X-ILk6_LGrqmn_XrH?auth=g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJuZXN0X2lkOm5lc3QtcGhvZW5peC1wcm9kOjE1NTQ1Nzk2IiwiaXNzIjoibmVzdC1zZWN1cml0eS1hdXRocHJveHkiLCJwb2wiOiIzcC1vYXV0aC1zY29wZS1BUElfU0RNX1NFUlZJQ0UtY2xpZW50LTQ1OTc4OTAxNzAwNy1kbjIxMDloZGp2OWhyYTNjbXRhaDFoaW4wZjVvajRkZC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImV4cCI6MTYxMTg2NTQ1Mn0.aGBQFdshz0bHQzOT4tCGcnZLrfXJlv9H3wt8PTSZf_Iegf7rYlEFFbmnsM2mpnvdlJMtVF3_yvkOzgRS1z7164qthh9TJsPmJTW719vVoWdRoUBL6ECoAyIPN_Hn7TAj01vx2NZgoKOI2qb7x0tY1Fw4zUnlcWNxZ1AOmeziX_nNvOU6SYvDYGSuqLmZZ9v_oDQvVP70i31BD-TNDeUDwFubty5vAlPloWXw5Tpo_NrVBRNdhXcRlE7SUhHlv44J0KYMBJj9LhvCIw4B6njliwYHHtSerr-iJHXjHowKFqs8xGTQcHB4MlG41P17CWtsEat833uj96RKL35LLhx2rw RTSP/1.0
nestrelay    | CSeq: 5
nestrelay    | Session: 584747539
nestrelay    | User-Agent: gortsplib
nestrelay    |
nestrelay    |
nestrelay    | 2021/01/28 20:23:43 [I] [0/0/0] [path nestproxy] [rtsp source] ERR: buffer length exceeds 1024
{code}

**Comment by aler9** [comment]
Please try this nightly release
[rtsp-simple-server_v0.13.3-6-g1d08cd2_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5889880/rtsp-simple-server_v0.13.3-6-g1d08cd2_windows_amd64.zip)
[rtsp-simple-server_v0.13.3-6-g1d08cd2_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5889882/rtsp-simple-server_v0.13.3-6-g1d08cd2_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.13.3-6-g1d08cd2_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5889884/rtsp-simple-server_v0.13.3-6-g1d08cd2_linux_arm7.tar.gz)
[rtsp-simple-server_v0.13.3-6-g1d08cd2_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5889885/rtsp-simple-server_v0.13.3-6-g1d08cd2_linux_arm6.tar.gz)
[rtsp-simple-server_v0.13.3-6-g1d08cd2_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5889886/rtsp-simple-server_v0.13.3-6-g1d08cd2_linux_amd64.tar.gz)
[rtsp-simple-server_v0.13.3-6-g1d08cd2_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5889887/rtsp-simple-server_v0.13.3-6-g1d08cd2_darwin_amd64.tar.gz)

**Comment by scottgrobinson** [comment]
Sadly that performed the same with the same error. Slightly "larger" log here if it helps. I could probably provide the stream if you were interested!

```
2021/01/28 23:19:44 [I] [0/0/0] rtsp-simple-server v0.13.3-6-g1d08cd2
2021/01/28 23:19:44 [I] [0/0/0] [UDP/RTP listener] opened on :8000
2021/01/28 23:19:44 [I] [0/0/0] [UDP/RTCP listener] opened on :8001
2021/01/28 23:19:44 [I] [0/0/0] [TCP/RTSP listener] opened on :8554
2021/01/28 23:19:44 [I] [0/0/0] [path nestproxy] [rtsp source] started
2021/01/28 23:19:44 [I] [0/0/0] [path nestproxy] [rtsp source] connecting
2021/01/28 23:19:44 [D] [0/0/0] [path nestproxy] [rtsp source] c->s OPTIONS rtsps://stream-eu1-bravo.dropcam.com:443/sdm_live_stream/CiQA2vuxrwaCRGREulSRy1rG1gLdVfl62t9mDrtqElyAn87Qn6MScQBMPhenwoYu9u9k-T2QuH1oUl-9TbbysCVaDfbShvYXx6qs8RT2yK_A9tj2kZRbZrll78WNMwpOIW1AccJmPjoAnCtrxatHdUSvrQj6zB7AN-fvTzy0gdY37l3enxUcpl0giC0-uaML_Cbb1PiCZ-XU?auth=g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJuZXN0X2lkOm5lc3QtcGhvZW5peC1wcm9kOjE1NTQ1Nzk2IiwiaXNzIjoibmVzdC1zZWN1cml0eS1hdXRocHJveHkiLCJwb2wiOiIzcC1vYXV0aC1zY29wZS1BUElfU0RNX1NFUlZJQ0UtY2xpZW50LTQ1OTc4OTAxNzAwNy1kbjIxMDloZGp2OWhyYTNjbXRhaDFoaW4wZjVvajRkZC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImV4cCI6MTYxMTg3NjI4NH0.OdVO6iZtVd3VSUZavwxiHlOjC1FszMudIaEYTr-8kFpnEES53vN48912TkWIAT-yBviZlamEGUjYgUFu7_pbRKe45-nPLDSRYUVNezlVBQoo-kw0DhOFIIuV166e38r4y7q7jJubIoJUQiSHithKBJA1Q9NlAH86DlEUP3opfVbipdbVvthgXUK4P1Gny_7egtAhKJI1FXmTJaY4Ub_xoX5X-6IiVZvAMGI4-E_QVWNp5FMk_XCsC5pShFhNAnIO-BG1k3Dw9B_vI2ssyAVbyaWB2mp_S5cLF9TbPHYpfIXrz9W-2DKoDLlffdLd8MJOuzDgVyYMpAOyHOINulwleA RTSP/1.0
CSeq: 1
User-Agent: gortsplib


2021/01/28 23:19:44 [D] [0/0/0] [path nestproxy] [rtsp source] s->c RTSP/1.0 200 OK
CSeq: 1
Cache-Control: no-cache
Public: DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, OPTIONS, ANNOUNCE, RECORD, GET_PARAMETER
Server: Wowza Streaming Engine 4.7.4 build21380
Supported: play.basic, con.persistent


2021/01/28 23:19:44 [D] [0/0/0] [path nestproxy] [rtsp source] c->s DESCRIBE rtsps://stream-eu1-bravo.dropcam.com:443/sdm_live_stream/CiQA2vuxrwaCRGREulSRy1rG1gLdVfl62t9mDrtqElyAn87Qn6MScQBMPhenwoYu9u9k-T2QuH1oUl-9TbbysCVaDfbShvYXx6qs8RT2yK_A9tj2kZRbZrll78WNMwpOIW1AccJmPjoAnCtrxatHdUSvrQj6zB7AN-fvTzy0gdY37l3enxUcpl0giC0-uaML_Cbb1PiCZ-XU?auth=g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJuZXN0X2lkOm5lc3QtcGhvZW5peC1wcm9kOjE1NTQ1Nzk2IiwiaXNzIjoibmVzdC1zZWN1cml0eS1hdXRocHJveHkiLCJwb2wiOiIzcC1vYXV0aC1zY29wZS1BUElfU0RNX1NFUlZJQ0UtY2xpZW50LTQ1OTc4OTAxNzAwNy1kbjIxMDloZGp2OWhyYTNjbXRhaDFoaW4wZjVvajRkZC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImV4cCI6MTYxMTg3NjI4NH0.OdVO6iZtVd3VSUZavwxiHlOjC1FszMudIaEYTr-8kFpnEES53vN48912TkWIAT-yBviZlamEGUjYgUFu7_pbRKe45-nPLDSRYUVNezlVBQoo-kw0DhOFIIuV166e38r4y7q7jJubIoJUQiSHithKBJA1Q9NlAH86DlEUP3opfVbipdbVvthgXUK4P1Gny_7egtAhKJI1FXmTJaY4Ub_xoX5X-6IiVZvAMGI4-E_QVWNp5FMk_XCsC5pShFhNAnIO-BG1k3Dw9B_vI2ssyAVbyaWB2mp_S5cLF9TbPHYpfIXrz9W-2DKoDLlffdLd8MJOuzDgVyYMpAOyHOINulwleA RTSP/1.0
Accept: application/sdp
CSeq: 2
User-Agent: gortsplib


2021/01/28 23:19:46 [D] [0/0/0] [path nestproxy] [rtsp source] s->c RTSP/1.0 200 OK
CSeq: 2
Cache-Control: no-cache
Content-Base: rtsps://stream-eu1-bravo.dropcam.com:443/sdm_live_stream/CiQA2vuxrwaCRGREulSRy1rG1gLdVfl62t9mDrtqElyAn87Qn6MScQBMPhenwoYu9u9k-T2QuH1oUl-9TbbysCVaDfbShvYXx6qs8RT2yK_A9tj2kZRbZrll78WNMwpOIW1AccJmPjoAnCtrxatHdUSvrQj6zB7AN-fvTzy0gdY37l3enxUcpl0giC0-uaML_Cbb1PiCZ-XU/
Content-Length: 590
Content-Type: application/sdp
Date: Thu, 28 Jan 2021 23:19:46 UTC
Expires: Thu, 28 Jan 2021 23:19:46 UTC
Server: Wowza Streaming Engine 4.7.4 build21380
Session: 1389028595;timeout=60

v=0
o=- 1389028595 1389028595 IN IP4 127.0.0.1
s=SDM
c=IN IP4 0.0.0.0
t=0 0
a=sdplang:en
a=range:npt=now-
a=control:*
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/48000/2
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1190
a=control:trackID=1
m=video 0 RTP/AVP 97
a=rtpmap:97 H264/90000
a=fmtp:97 packetization-mode=1;profile-level-id=4D0029;sprop-parameter-sets=Z00AKZpkAyAS/+AtwEBAUAAAPoAAB1MOhgC3QALci7y40MAW6ABbkXeXCg==,aO48gA==
a=cliprect:0,0,1200,1600
a=framesize:97 1600-1200
a=framerate:15.0
a=control:trackID=2

2021/01/28 23:19:46 [D] [0/0/0] [path nestproxy] [rtsp source] c->s SETUP rtsps://stream-eu1-bravo.dropcam.com:443/sdm_live_stream/CiQA2vuxrwaCRGREulSRy1rG1gLdVfl62t9mDrtqElyAn87Qn6MScQBMPhenwoYu9u9k-T2QuH1oUl-9TbbysCVaDfbShvYXx6qs8RT2yK_A9tj2kZRbZrll78WNMwpOIW1AccJmPjoAnCtrxatHdUSvrQj6zB7AN-fvTzy0gdY37l3enxUcpl0giC0-uaML_Cbb1PiCZ-XU?auth=g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJuZXN0X2lkOm5lc3QtcGhvZW5peC1wcm9kOjE1NTQ1Nzk2IiwiaXNzIjoibmVzdC1zZWN1cml0eS1hdXRocHJveHkiLCJwb2wiOiIzcC1vYXV0aC1zY29wZS1BUElfU0RNX1NFUlZJQ0UtY2xpZW50LTQ1OTc4OTAxNzAwNy1kbjIxMDloZGp2OWhyYTNjbXRhaDFoaW4wZjVvajRkZC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImV4cCI6MTYxMTg3NjI4NH0.OdVO6iZtVd3VSUZavwxiHlOjC1FszMudIaEYTr-8kFpnEES53vN48912TkWIAT-yBviZlamEGUjYgUFu7_pbRKe45-nPLDSRYUVNezlVBQoo-kw0DhOFIIuV166e38r4y7q7jJubIoJUQiSHithKBJA1Q9NlAH86DlEUP3opfVbipdbVvthgXUK4P1Gny_7egtAhKJI1FXmTJaY4Ub_xoX5X-6IiVZvAMGI4-E_QVWNp5FMk_XCsC5pShFhNAnIO-BG1k3Dw9B_vI2ssyAVbyaWB2mp_S5cLF9TbPHYpfIXrz9W-2DKoDLlffdLd8MJOuzDgVyYMpAOyHOINulwleA/trackID=1 RTSP/1.0
CSeq: 3
Session: 1389028595
Transport: RTP/AVP/TCP;unicast;interleaved=0-1;mode=play
User-Agent: gortsplib


2021/01/28 23:19:46 [D] [0/0/0] [path nestproxy] [rtsp source] s->c RTSP/1.0 200 OK
CSeq: 3
Cache-Control: no-cache
Date: Thu, 28 Jan 2021 23:19:46 UTC
Expires: Thu, 28 Jan 2021 23:19:46 UTC
Server: Wowza Streaming Engine 4.7.4 build21380
Session: 1389028595;timeout=60
Transport: RTP/AVP/TCP;unicast;interleaved=0-1;mode=play


2021/01/28 23:19:46 [D] [0/0/0] [path nestproxy] [rtsp source] c->s SETUP rtsps://stream-eu1-bravo.dropcam.com:443/sdm_live_stream/CiQA2vuxrwaCRGREulSRy1rG1gLdVfl62t9mDrtqElyAn87Qn6MScQBMPhenwoYu9u9k-T2QuH1oUl-9TbbysCVaDfbShvYXx6qs8RT2yK_A9tj2kZRbZrll78WNMwpOIW1AccJmPjoAnCtrxatHdUSvrQj6zB7AN-fvTzy0gdY37l3enxUcpl0giC0-uaML_Cbb1PiCZ-XU?auth=g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJuZXN0X2lkOm5lc3QtcGhvZW5peC1wcm9kOjE1NTQ1Nzk2IiwiaXNzIjoibmVzdC1zZWN1cml0eS1hdXRocHJveHkiLCJwb2wiOiIzcC1vYXV0aC1zY29wZS1BUElfU0RNX1NFUlZJQ0UtY2xpZW50LTQ1OTc4OTAxNzAwNy1kbjIxMDloZGp2OWhyYTNjbXRhaDFoaW4wZjVvajRkZC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImV4cCI6MTYxMTg3NjI4NH0.OdVO6iZtVd3VSUZavwxiHlOjC1FszMudIaEYTr-8kFpnEES53vN48912TkWIAT-yBviZlamEGUjYgUFu7_pbRKe45-nPLDSRYUVNezlVBQoo-kw0DhOFIIuV166e38r4y7q7jJubIoJUQiSHithKBJA1Q9NlAH86DlEUP3opfVbipdbVvthgXUK4P1Gny_7egtAhKJI1FXmTJaY4Ub_xoX5X-6IiVZvAMGI4-E_QVWNp5FMk_XCsC5pShFhNAnIO-BG1k3Dw9B_vI2ssyAVbyaWB2mp_S5cLF9TbPHYpfIXrz9W-2DKoDLlffdLd8MJOuzDgVyYMpAOyHOINulwleA/trackID=2 RTSP/1.0
CSeq: 4
Session: 1389028595
Transport: RTP/AVP/TCP;unicast;interleaved=2-3;mode=play
User-Agent: gortsplib


2021/01/28 23:19:46 [D] [0/0/0] [path nestproxy] [rtsp source] s->c RTSP/1.0 200 OK
CSeq: 4
Cache-Control: no-cache
Date: Thu, 28 Jan 2021 23:19:46 UTC
Expires: Thu, 28 Jan 2021 23:19:46 UTC
Server: Wowza Streaming Engine 4.7.4 build21380
Session: 1389028595;timeout=60
Transport: RTP/AVP/TCP;unicast;interleaved=2-3;mode=play


2021/01/28 23:19:46 [D] [0/0/0] [path nestproxy] [rtsp source] c->s PLAY rtsps://stream-eu1-bravo.dropcam.com:443/sdm_live_stream/CiQA2vuxrwaCRGREulSRy1rG1gLdVfl62t9mDrtqElyAn87Qn6MScQBMPhenwoYu9u9k-T2QuH1oUl-9TbbysCVaDfbShvYXx6qs8RT2yK_A9tj2kZRbZrll78WNMwpOIW1AccJmPjoAnCtrxatHdUSvrQj6zB7AN-fvTzy0gdY37l3enxUcpl0giC0-uaML_Cbb1PiCZ-XU?auth=g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJuZXN0X2lkOm5lc3QtcGhvZW5peC1wcm9kOjE1NTQ1Nzk2IiwiaXNzIjoibmVzdC1zZWN1cml0eS1hdXRocHJveHkiLCJwb2wiOiIzcC1vYXV0aC1zY29wZS1BUElfU0RNX1NFUlZJQ0UtY2xpZW50LTQ1OTc4OTAxNzAwNy1kbjIxMDloZGp2OWhyYTNjbXRhaDFoaW4wZjVvajRkZC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImV4cCI6MTYxMTg3NjI4NH0.OdVO6iZtVd3VSUZavwxiHlOjC1FszMudIaEYTr-8kFpnEES53vN48912TkWIAT-yBviZlamEGUjYgUFu7_pbRKe45-nPLDSRYUVNezlVBQoo-kw0DhOFIIuV166e38r4y7q7jJubIoJUQiSHithKBJA1Q9NlAH86DlEUP3opfVbipdbVvthgXUK4P1Gny_7egtAhKJI1FXmTJaY4Ub_xoX5X-6IiVZvAMGI4-E_QVWNp5FMk_XCsC5pShFhNAnIO-BG1k3Dw9B_vI2ssyAVbyaWB2mp_S5cLF9TbPHYpfIXrz9W-2DKoDLlffdLd8MJOuzDgVyYMpAOyHOINulwleA RTSP/1.0
CSeq: 5
Session: 1389028595
User-Agent: gortsplib


2021/01/28 23:19:46 [I] [0/0/0] [path nestproxy] [rtsp source] ERR: buffer length exceeds 1024
```

**Comment by aler9** [comment]
Evidently it isn't the path, but it's a header value that exceeds the maximum allowed length.
Try again with this
[rtsp-simple-server_v0.13.3-9-gb20a726_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5893671/rtsp-simple-server_v0.13.3-9-gb20a726_windows_amd64.zip)
[rtsp-simple-server_v0.13.3-9-gb20a726_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5893672/rtsp-simple-server_v0.13.3-9-gb20a726_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.13.3-9-gb20a726_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5893673/rtsp-simple-server_v0.13.3-9-gb20a726_linux_arm7.tar.gz)
[rtsp-simple-server_v0.13.3-9-gb20a726_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5893674/rtsp-simple-server_v0.13.3-9-gb20a726_linux_arm6.tar.gz)
[rtsp-simple-server_v0.13.3-9-gb20a726_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5893675/rtsp-simple-server_v0.13.3-9-gb20a726_linux_amd64.tar.gz)
[rtsp-simple-server_v0.13.3-9-gb20a726_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5893676/rtsp-simple-server_v0.13.3-9-gb20a726_darwin_amd64.tar.gz)

**Comment by scottgrobinson** [comment]
That's working perfectly :)

I will give it a try with the hot loading and feedback again. Thank you!

**Comment by t3therdev** [comment]
@scottgrobinson can i ask what url format/schema you are using to access the dropcams? we are definitely interested in trying this out. thanks!

**Comment by scottgrobinson** [comment]
@t3therdev Yes - Using the NEST API there. The trickiest part is setting up the google authentication side of things. This script dumps out a URL that lasts for 5 minutes that you can load in VLC, I haven't got to the part of integrating it with a renewing URL. https://pastebin.com/62VQqb6R

@aler9 Every time I paste in a new URL, the relay disconnects my client. Is that expected? If I load it up again, the URL works, but I was hoping it wouldn't disconnect me. Not sure if what I'm asking for is possible here without transcoding to a new stream entirley? Tried with VLC & MPV.

19:28:20 - Ready
19:28:33 - Connect with VLC
19:28:52 - Load in new URL, VLC disconnects

https://pastebin.com/zA8i5zXi

**Comment by aler9** [comment]
added in v0.14.0
