### ISSUE TITLE
Docker: can't use --network=host

### ISSUE THREAD

**Issue by iamnague** [aler9/rtsp-simple-server#194]
## Which version are you using?

v0.13.3

```
2021/01/26 15:04:01 [I] [0/0/0] rtsp-simple-server v0.13.3
2021/01/26 15:04:01 [I] [0/0/0] [UDP/RTP listener] opened on :8000
2021/01/26 15:04:01 [I] [0/0/0] [UDP/RTCP listener] opened on :8001
2021/01/26 15:04:01 [I] [0/0/0] [TCP/RTSP listener] opened on :8554
```

## Question

Docker image running on photon 3.0. If I run docker with -p 8554:8554/tcp, I can reach RSTP port 8554, but I'm not able to use UDP. If I run docker with --network=host, I'm not able to open any connection remotely with rstp-simple-server. 

However, ports seems to be correctly redirect on host:

```
 netstat -tulpn
[...]
tcp6       0      0 :::8554                 :::*                    LISTEN      704/rtsp-simple-ser
udp6       0      0 :::8000                 :::*                                704/rtsp-simple-ser
udp6       0      0 :::8001                 :::*                                704/rtsp-simple-ser
```

I'm running with this command:
 docker run --rm -it --network=host -v $PWD/rtsp-simple-server.yml:/rtsp-simple-server.yml aler9/rtsp-simple-server

What's wrong ? How can I troubleshoot ?

Edit: actually, it works localy
```
nc -vzz localhost 8554
localhost [127.0.0.1] 8554 (rtsp-alt) open
```

but I can't access remotly to port tcp 8554

**Comment by aler9** [comment]
Hello, try listening to ipv4 only with

```yml
listenIP: 0.0.0.0
```

or try to use directly the local IP of your pc

```yml
listenIP: 192.168.x.x
```

(but i could be wrong and the issue could be completely unrelated)

**Comment by iamnague** [comment]
Hello, thanks for your help. I tried to change listenIP but didn't help.

I've just figured out that my issue might be related to default firewall with photon os.

This fix the issue for remote connection on TCP port 8554:
`iptables -I INPUT -p tcp --dport 8554 -j ACCEPT`

But I'm still facing the "ERR: no UDP packets received recently" for my stream. Off course, I added something to allow udp:
`iptables -I INPUT -p udp  -j ACCEPT`

I've check, udp dest ports of the stream are correctly opened on host :

```
 netstat -tulpn | grep rtsp-simple-ser
tcp        0      0 192.168.4.17:8554       0.0.0.0:*               LISTEN      984/rtsp-simple-ser
udp        0      0 192.168.4.17:8000       0.0.0.0:*                           984/rtsp-simple-ser
udp        0      0 192.168.4.17:8001       0.0.0.0:*                           984/rtsp-simple-ser
udp6       0      0 :::55960                :::*                                984/rtsp-simple-ser
udp6       0      0 :::55961                :::*                                984/rtsp-simple-ser
```
No more idea at this time.

**Comment by iamnague** [comment]
Actually, it works with a different RSTP source, the issue is related to the source I was using for my tests. I'll open a new thread for that.

The answer to my intial question : to use --network=host with Photon OS host, you have to open firewall:
`iptables -I INPUT -p tcp --dport 8554 -j ACCEPT`
and, if UDP needed:
`iptables -I INPUT -p udp -j ACCEPT`
