### ISSUE TITLE
Data too Big warning in console

### ISSUE THREAD

**Issue by HackmanSlim** [aler9/rtsp-simple-server#206]
## Which version are you using?

v0.14.1

## Question

Every now and then, I will get this error in the console using a Debian based install.

ERR: data is too big

This causes the source to disconnect, and all clients in the process. The source is OBS Studio, connecting via RTMP, however, the clients are connected on the RTSP port (this is vital, as the infrastructure we are using only supports RTSP playback)

OBS will reconnect, and our clients can toggle to resume playback. I have had a look around, and really cannot find much on the issue. I was wondering if this would be something I could fix on OBS itself, I have tried reducing the bitrate, but it seems to have no effect. I think it might be related to another issue on here (UDP/TCP packet sizes maybe being too big)

Other than that, the software is incredible!

Description

Latest version of OBS Studio (at the time of posting) setup to stream via RTMP, using the Intel Quicksync Encoder

Clients are connecting on the RTSP port of your proxy.

**Comment by aler9** [comment]
Hello, in my opinion the issue is related to publishing with RTMP and is caused by this hardcoded error that is triggered when a packet has a size > 4MB

https://github.com/notedit/rtmp/blob/f9ebc32ae90a41b45163df73ef0807bab53d42e3/format/rtmp/msg.go#L94

What's the exact message? "data is too big" or "MsgDataTooBig"?

**Comment by HackmanSlim** [comment]
The console message is "data is too big"

I must admit, it rarely does it, scrolling back  through the logs, I can't seem to find that message.

But at the time of posting this, the message was definitely "data is too big"

**Comment by aler9** [comment]
i finally found the reason, the error is raised by the RTP/AAC encoder:

https://github.com/aler9/gortsplib/blob/main/pkg/rtpaac/encoder.go#L63

**Comment by HackmanSlim** [comment]
Ahhh nice one.

Not too long after I reported this issue, I noticed your repo had been updated, so I compiled that, and that error is completely gone now.

Thankyou for solving this issue.

**Comment by aler9** [comment]
unfortunately the error is not gone, but is raised every time an AAC frame has a size > 1440 bytes - i have to improve the encoder to support bigger sizes

**Comment by HackmanSlim** [comment]
If there's anything I can do to help, I'd be glad to help.

Thankyou so much, for your continued efforts, and hard work on the Rtsp Simple Server project.

**Comment by aler9** [comment]
The encoder was improved to fragment AAC frames bigger than 1460 bytes into multiple RTP packets:

https://github.com/aler9/gortsplib/blob/2df57fbf752549ea7065829cebd648ed149252bc/pkg/rtpaac/decoder.go

The RTP specification doesn't explain how to fragment AAC frames, therefore i took inspiration from the FFmpeg code, hoping that they're right:

https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/rtpenc_aac.c#L77

This feature will be available in the next release, eliminating the error forever.

**Comment by aler9** [comment]
added in v0.15.2
