### ISSUE TITLE
Support SRT

### ISSUE THREAD

**Issue by aler9** [aler9/rtsp-simple-server#207]
## Which version are you using?

v0.0.0

## Enhancement request

SRT is the newer protocol in the family of video/audio streaming, and it's the protocol of choice with 4k/8k professional cameras.

Supporting it would make the server future-proof.

A couple of implementation exists, none of them in Go:

* https://github.com/Haivision/srt
* https://github.com/russelltg/srt-rs

**Comment by virtualrobotix** [comment]
SRT Library for go 
https://github.com/openfresh/gosrt
