### ISSUE TITLE
ERR: buffer length exceeds 2048

### ISSUE THREAD

**Issue by jakowenko** [aler9/rtsp-simple-server#211]
## Which version are you using?

v0.14.1

## Which operating system are you using?

OS

- [ ] Linux
- [ ] Windows
- [X] macOS

Architecture

- [X] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

I'm trying to use the RTSPS livestream URL that I've been generating from the Google SDM API. When I start the container this is the error I receive.

```
rtsp-simple-server    | 2021/02/16 06:05:55 [I] [0/0/0] rtsp-simple-server v0.14.1
rtsp-simple-server    | 2021/02/16 06:05:55 [I] [0/0/0] [UDP/RTP listener] opened on :8000
rtsp-simple-server    | 2021/02/16 06:05:55 [I] [0/0/0] [UDP/RTCP listener] opened on :8001
rtsp-simple-server    | 2021/02/16 06:05:55 [I] [0/0/0] [TCP/RTSP listener] opened on :8554
rtsp-simple-server    | 2021/02/16 06:05:55 [I] [0/0/0] [path front-door] [rtsp source] started
rtsp-simple-server    | 2021/02/16 06:05:55 [I] [0/0/0] [path front-door] [rtsp source] connecting
rtsp-simple-server    | 2021/02/16 06:05:57 [I] [0/0/0] [path front-door] [rtsp source] ERR: buffer length exceeds 2048
```

My config looks like this.

```
paths:
  front-door:
    source: rtsps://stream-us1.dropcam.com
```

**Comment by aler9** [comment]
Hello, this is caused by RTP packets that are bigger than the maximum allowed, that is the UDP MTU (~1400). The internal buffer is sized accordingly.

The problem is that some servers / publishers don't respect this limit.

i'll add an option to set the buffer size, that you can try to tune to solve the problem, at cost of using much more RAM (the server allocates at least 2048 * readBufferCount bytes).

**Comment by aler9** [comment]
a parameter `readBufferSize` has been added to the configuration - please try this nightly release, try to tune the parameter and let me know if it solves the issue
[rtsp-simple-server_v0.14.1-6-ga938554_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6006294/rtsp-simple-server_v0.14.1-6-ga938554_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.14.1-6-ga938554_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6006295/rtsp-simple-server_v0.14.1-6-ga938554_linux_amd64.tar.gz)
[rtsp-simple-server_v0.14.1-6-ga938554_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6006296/rtsp-simple-server_v0.14.1-6-ga938554_linux_arm6.tar.gz)
[rtsp-simple-server_v0.14.1-6-ga938554_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6006297/rtsp-simple-server_v0.14.1-6-ga938554_linux_arm7.tar.gz)
[rtsp-simple-server_v0.14.1-6-ga938554_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6006299/rtsp-simple-server_v0.14.1-6-ga938554_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.14.1-6-ga938554_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/6006300/rtsp-simple-server_v0.14.1-6-ga938554_windows_amd64.zip)

**Comment by jakowenko** [comment]
Awesome, thank you. I'll try it out this weekend and report back.

**Comment by dorinclisu** [comment]
This is a bit strange as I'm also running v0.14.1 but the error is slightly different:
`2021/02/23 16:40:14 [I] [0/0/0] [path test] [rtsp source] ERR: frame length greater than maximum allowed (8206 vs 2048)`

What's also strange is that I have `sourceProtocol: tcp` so it should have nothing to do UDP packet size.
Should I open a separate issue?

**Comment by dorinclisu** [comment]
My problem is solved by v0.14.1-6-ga938554.

**Comment by aler9** [comment]
> What's also strange is that I have sourceProtocol: tcp so it should have nothing to do with UDP packet size.

The buffer length applies to the RTP packet size and is the same in both UDP and TCP in order to allow routing between them (rtsp-simple-server is basically a router, and must be able to route packets from TCP to UDP; therefore, TCP packets must have a size compatible with UDP packets).

**Comment by aler9** [comment]
added in v0.14.2

**Comment by aeozyalcin** [comment]
@aler9 running v0.14.2, I am still running into the `[rtsp source] ERR: frame length greater than maximum allowed (6800 vs 2048)` issue.

I have increased readBufferSize but it does not seem to have an effect. The error always suggests that the maximum allowed length stays at 2048. The camera I am trying to read from is a Reolink RLC-410 with ridiculously large packet sizes.
