### ISSUE TITLE
RTSP Control and seekable streaming

### ISSUE THREAD

**Issue by iolumbaram** [aler9/rtsp-simple-server#216]
**## Which version are you using?**

v0.14.1

**## Question**

How to create a seekable streaming and have controls using RTSP such that a playback can pause (this works), or seek to a different position, or enter fast forward or rewind mode.

**Description**

I have a RTSP streaming that is published to RTSP server at localhost:8554. I can pull the stream from rtsp://localhost:8554/mystream on VLC player. I have tested VLC player to pull the stream, it is showing but only is able to pause and not not able to perform other controls. 

For your helps, thank you!

**Comment by aler9** [comment]
Hello,

RTSPSS is not a media server, is a live server that works with live streams.

There's a RTSP media server called live555 media server that serves files and supports RTSP seeking (like http://www.live555.com/mediaServer/).

Therefore, RTSPSS can be adapted, in the future, in the future, to proxy seek requests to a RTSP source, but not to a RTSP publisher, i don't think there exists RTSP publishers that support seeking.
