### ISSUE TITLE
"ERR: client is not publishing" when RTMP streaming

### ISSUE THREAD

**Issue by SSL0** [aler9/rtsp-simple-server#218]
## Which version are you using?

v0.14.1

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

I'm running a server and streaming with OBS. When I try to connect to the stream via VLC I get an error:  `"ERR: client is not publishing" `

1. change in config `rtmpEnable` to `yes`
2. start the server 
3. publish with OBS on address "rtmp://localhost:1935/mystream"
4. read with VLC "rtmp://localhost:1935/mystream"

**Comment by aler9** [comment]
Hello, currently reading with RTMP is not supported, but will be added in the future. In the meanwhile, you can read with RTSP

```
rtsp://localhost:8554/mystream
```

**Comment by aler9** [comment]
Reading with RTMP is now supported in main and will be added to the next release

**Comment by aler9** [comment]
added in v0.15.0
