### ISSUE TITLE
After switching to fallback stream, how to switch back once real stream is publishing again?

### ISSUE THREAD

**Issue by golfterminator** [aler9/rtsp-simple-server#226]
## Which version are you using?

v0.14.2

## Question

I have about fallback stream switching.  I've searched the Issues database and read all the fallback documentation.  I'm thinking there's something I'm not understanding on configuring fallback streams.  I have a fallback stream configured as follows:
  idlepath:
    runOnInit: /var/lcast/images/ffmpeg_std  -re -stream_loop -1 -i /lcast/data/ZVmaxconnect_10s.ts -c copy -f rtsptsp://localhost:554/idlepath -nostats -hide_banner
    runOnInitRestart: yes

I see the fallback stream being started at start of server:
   2021/03/01 05:12:52 [I] [0/0/0] [path idlepath] on init command started

I start my real stream coming from the camera:
   2021/03/01 11:48:40 [I] [2/1/0] [client 127.0.0.1:55708] connected (plain)
   2021/03/01 11:48:40 [I] [2/2/0] [client 127.0.0.1:55708] is publishing to path '4HE3-1', 2 tracks with udp

I start VLC to play the real stream '4HE3-1' and it plays fine:
   2021/03/01 11:48:51 [I] [3/2/0] [client 172.16.3.104:57179] connected (plain)
   2021/03/01 11:48:51 [I] [3/2/1] [client 172.16.3.104:57179] is reading from path '4HE3-1', 2 tracks with udp

I stop my '4HE3-1' stream from the camera:
   2021/03/01 11:49:05 [I] [1/1/0] [client 127.0.0.1:55708] disconnected

It redirects the VLC player to the fallback stream:
   2021/03/01 11:49:05 [I] [1/1/0] [client 172.16.3.104:57179] disconnected
   2021/03/01 11:49:13 [I] [2/1/0] [client 172.16.3.104:57182] connected (plain)
   2021/03/01 11:49:13 [I] [1/1/0] [client 172.16.3.104:57182] disconnected
   2021/03/01 11:49:13 [I] [2/1/0] [client 172.16.3.104:57183] connected (plain)
   2021/03/01 11:49:13 [I] [2/1/1] [client 172.16.3.104:57183] is reading from path 'idlepath', 2 tracks with udp

I restart the '4HE3-1' stream from the camera:
   2021/03/01 11:49:35 [I] [3/1/1] [client 127.0.0.1:55709] connected (plain)
   2021/03/01 11:49:35 [I] [3/2/1] [client 127.0.0.1:55709] is publishing to path '4HE3-1', 2 tracks with udp

At this point the VLC player continues to play the fallback stream.  Is there a way to force the client VLC to switch back to the real publishing stream?

thanks,

Dave

**Comment by aler9** [comment]
we're discussing this feature here https://github.com/aler9/rtsp-simple-server/issues/225
