### ISSUE TITLE
ERR: sdp: invalid syntax `c=IN c=IN IP4 0.0.0.0` (c=IN c=IN IP4 0.0.0.0)

### ISSUE THREAD

**Issue by dorinclisu** [aler9/rtsp-simple-server#227]
## Which version are you using?

v0.14.2 

## Which operating system are you using?

OS
- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

The description is quite simple, the error happens when connecting to a certain hikvision rebranded camera.
```ERR: sdp: invalid syntax `c=IN c=IN IP4 0.0.0.0` (c=IN c=IN IP4 0.0.0.0)```

FFMPEG and VLC have no trouble connecting, probably because they were designed with non-conformant servers in mind (which seems to be the majority unfortunately).

## Did you attach a network dump?
Not yet, but I will if it's not obvious how to fix.

**Comment by aler9** [comment]
Hello, this can be fixed in a very short period of time, but i need a network dump or a full SDP, that will be supported and inserted into the list of non-conformat SDPS here:
https://github.com/aler9/gortsplib/blob/main/pkg/sdp/sdp_test.go

**Comment by dorinclisu** [comment]
Is this ok? I masked the sensitive parts.
```
OPTIONS rtsp://<ADDRESS>/Streaming/Channels/402 RTSP/1.0
CSeq: 1
User-Agent: gortsplib

RTSP/1.0 401 Unauthorized
CSeq: 1
WWW-Authenticate: Digest realm="Embedded Net DVR", nonce="1157e9bff", algorithm="MD5"
WWW-Authenticate: Basic realm="/"

OPTIONS rtsp://<ADDRESS>/Streaming/Channels/402 RTSP/1.0
Authorization: Digest username="<USER>", realm="Embedded Net DVR", nonce="1157e9bff", uri="rtsp://<ADDRESS>/Streaming/Channels/402", response="525e192e8bccd05759a63b89fb6874d1"
CSeq: 2
User-Agent: gortsplib

RTSP/1.0 200 OK
CSeq: 2
Public: OPTIONS, DESCRIBE, SETUP, PLAY, TEARDOWN, PAUSE

DESCRIBE rtsp://<ADDRESS>/Streaming/Channels/402 RTSP/1.0
Accept: application/sdp
Authorization: Digest username="<USER>", realm="Embedded Net DVR", nonce="1157e9bff", uri="rtsp://<ADDRESS>/Streaming/Channels/402", response="509defd6c784ad2b2e5290c3b68cd697"
CSeq: 3
User-Agent: gortsplib

RTSP/1.0 200 OK
CSeq: 3
Content-Type: application/sdp
Content-Length: 522

v=0
o=- 1109162014219182 0 IN IP4 0.0.0.0
s=HIK Media Server V3.1.3
i=HIK Media Server Session Description : standard
e=NONE
c=IN c=IN IP4 0.0.0.0
t=0 0
a=control:*
a=range:npt=now-
m=video 0 RTP/AVP 96
i=Video Media
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=4D0014;packetization-mode=0;sprop-parameter-sets=Z01AHppmBYHv81BgYGQAAA+gAAF3ABA=,aO48gA==
a=control:trackID=video
a=Media_header:MEDIAINFO=494D4B48010100000400000100000000000000000000000000000000000000000000000000000000;
a=appversion:1.0
```

**Comment by dorinclisu** [comment]
Also, is it possible that such errors are better handled in the future?
Bacause right now, after the error is logged, the server continues to run but internally it's not working anymore, all other sources and paths are dead. At least, the process should exit if the error is unrecoverable, this way the container orchestrator can restart it and maintain at least some functionality.

I am saying this because we can always have a new kind of non-conformant device popping up so it'd be desirable to self contain the failures.

**Comment by markus805** [comment]
Hello, we get the following error connectin to a 'Fritzbox 6951 Cable':
2022/04/12 21:43:26 INF [path xxx] [rtsp source] ERR: sdp: invalid syntax `c=In IP4 0.0.0.0` (c=In IP4 0.0.0.0)
  xxx:
    source: rtsp://192.168.178.1:554/?avm=1&freq=314& ....
    sourceOnDemand: yes

Is it the same issue? Version is v0.18.0 on Linux xxx1 4.9.0-18-amd64 #1 SMP Debian 4.9.303-1 (2022-03-07) x86_64 GNU/Linux

**Comment by aler9** [comment]
@markus805 open a dedicated issue and provide required data.
