### ISSUE TITLE
Crashing on watchdog timeout when idle or connected

### ISSUE THREAD

**Issue by gherlein** [aler9/rtsp-simple-server#228]
## Which version are you using?
HEAD

## Which operating system are you using?
gherlein@nuc3:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

- [X ] amd64

## Describe the issue

Just run it and it crashes

Description
Mar  3 14:30:22 nuc3 systemd[1]: rtsp-simple-server.service: Watchdog timeout (limit 30s)!
Mar  3 14:30:22 nuc3 systemd[1]: rtsp-simple-server.service: Killing process 6237 (rtsp-simple-ser) with signal SIGABRT.
Mar  3 14:30:22 nuc3 rtsp-simple-server[6237]: SIGABRT: abort
Mar  3 14:30:22 nuc3 rtsp-simple-server[6237]: PC=0x4725c1 m=0 sigcode=0
Mar  3 14:30:22 nuc3 rtsp-simple-server[6237]: goroutine 0 [idle]:
Mar  3 14:30:22 nuc3 rtsp-simple-server[6237]: runtime.futex(0xcb0868, 0x80, 0x0, 0x0, 0x0, 0x47219c, 0x38936d, 0x2540f024, 0x7ffd16656728, 0x40db5f, ...)
Mar  3 14:30:22 nuc3 rtsp-simple-server[6237]: #011/usr/local/go/src/runtime/sys_linux_amd64.s:587 +0x21
...

## Describe how to replicate the issue
just run it with the following config

[rtsp-simple-server.yml.zip](https://github.com/aler9/rtsp-simple-server/files/6076782/rtsp-simple-server.yml.zip)

**Comment by gherlein** [comment]
Downloaded current release and tried that too.  Used the included yaml file and just added my two sources.  Same behavior once I try to connect.  The watchdog is not getting reset and it's just restarting

**Comment by aler9** [comment]
Hello, can you post the systemd unit file you're using to launch the server?

**Comment by gherlein** [comment]
[Unit]
Description=Simple RTSP Server/Proxy
After=network.target

[Service]
ExecStart=/usr/local/bin/rtsp-simple-server /usr/local/etc/rtsp-simple-server.yml
WatchdogSec=30s
Restart=on-failure

[Install]
WantedBy=multi-user.target

**Comment by gherlein** [comment]
I was stupid.  

WatchdogSec=30s
Restart=on-failure

The code does not hit the watchdog, of course.
