### ISSUE TITLE
Deny connection to push client if path is in use.

### ISSUE THREAD

**Issue by riccardocagnasso** [aler9/rtsp-simple-server#230]
v0.14.2

At the moment if some path is in use, e.g. someone is publishing to it, and another client connects and starts to publish, both clients are disconnected and the stream ends.

What should happen is that in case a path is in use if another client tries to connect, the connection is denied (error 403?)

**Comment by aler9** [comment]
Hello,
* the desired behavior is to allow new publishers to override old ones (#187). You can protect publishing by setting credentials
* the new publisher doesn't get disconnected, but is allowed to publish. I rewrote the tests to make sure of this

**Comment by aler9** [comment]
Yes, this can be added as option

**Comment by aler9** [comment]
This is implemented in master and will be added to the next release.

**Comment by aler9** [comment]
added in v0.15.1
