### ISSUE TITLE
problem with RTSP timestamps

### ISSUE THREAD

**Issue by rho-sk** [aler9/rtsp-simple-server#233]
## Which version are you using?

v0.14.2

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ ] amd64
- [x] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Seems there is serious problem with RTSP timestamps

Variant 1
1. producing RTSP with gstreamer  (gstreamer has RTSPServer on port 18554)
2. rtsp-simple-server has one entry with source: rtsp://localhost:18554/deepstream
3. VLC (on windows) is able to play video
4. but vlc is not producing correct MediaPlayerTimeChanged event, there is always 0 
5. when i do direct connect to 18554 vlc has no problem

Variant 2
1. publish RTSP with gstreamer  (gstreamer has rtspclientsink )
2. rtsp-simple-server has one entry with source: record
3. VLC (on windows) is able to play video
4. but vlc is not producing correct MediaPlayerTimeChanged event, there is always 0 

Variant 2.1
points 1,2 are the same like in Variant 2
ffmepg is producing 
<pre>
[segment @ 0x558e77af40] Non-monotonous DTS in output stream 0:0; previous: 28210895, current: 28209301; changing to 28210896. This may result in incorrect timestamps in the output file.
[segment @ 0x558e77af40] Non-monotonous DTS in output stream 0:0; previous: 28210896, current: 28209325; changing to 28210897. This may result in incorrect timestamps in the output file.
[segment @ 0x558e77af40] Non-monotonous DTS in output stream 0:0; previous: 28210897, current: 28209344; changing to 28210898. This may result in incorrect timestamps in the output file.
[segment @ 0x558e77af40] Non-monotonous DTS in output stream 0:0; previous: 28210898, current: 28209361; changing to 28210899. This may result in incorrect timestamps in the output file.
[segment @ 0x558e77af40] Non-monotonous DTS in output stream 0:0; previous: 28210899, current: 28209442; changing to 28210900. This may result in incorrect timestamps in the output file.
[segment @ 0x558e77af40] Non-monotonous DTS in output stream 0:0; previous: 28210900, current: 28209442; changing to 28210901. This may result in incorrect timestamps in the output file.
[segment @ 0x558e77af40] Non-monotonous DTS in output stream 0:0; previous: 28212995, current: 28212995; changing to 28212996. This may result in incorrect timestamps in the output file.
[rtsp @ 0x558e7756d0] RTP: PT=60: bad cseq 8fe1 expected=93e1
[segment @ 0x558e77af40] Non-monotonous DTS in output stream 0:0; previous: 28214103, current: 28214103; changing to 28214104. This may result in incorrect timestamps in the output file.
</pre>

## Describe how to replicate the issue

Please check the difference between dumps, because seems that gortsplib must be enhanced/changed.

## Did you attach a network dump?

Just "http" headers
[direct_connection.txt](https://github.com/aler9/rtsp-simple-server/files/6128988/direct_connection.txt)
[proxy_connection.txt](https://github.com/aler9/rtsp-simple-server/files/6128991/proxy_connection.txt)

Complete wireshark dumps
[dumps.zip](https://github.com/aler9/rtsp-simple-server/files/6130355/dumps.zip)
Dump from "direct connection" to the gstreamer server, shows correct working communication.

**Comment by rho-sk** [comment]
From brief analyze of dumps i see 2 diffs
1. In PLAY reply there is no RTP-Info: url=rtsp://158.195.164.55:18554/deepstream/stream=0;**seq=62064;rtptime=4163771172**
2. RTP packets has all still same Timestamp: 4110585821

And because of point 2, logically vlc is not calculating time movement, and still returns 0

**Comment by aler9** [comment]
Hello, thanks for the detailed explanation, this is an issue i've been looking forward to solve.

Let's start by considering that RTSP is used for both real-time and playback streams.

* the former don't use `RTP-Info` or use it to show the time elapsed from the initialization of the camera or initialization of the stream
* the latter use `RTP-Info` to show the time elapsed from the start of the playback file.

Therefore, in my opinion `RTP-Info` fields should be gathered from the source stream and stored. In case they're not provided, the server should generate them by using the first incoming RTP packet, and anyway store them once.

**Comment by aler9** [comment]
And of course this could be the starting point in supporting seeking and pausing.

**Comment by rho-sk** [comment]
Hi,
Thank you for including this issue in the implementation list.
Another important comment:
To maintain the functionality of the proxy, it is necessary to use the host and port that was sent in the PLAY request (not what is sent by the background server, or the address and port on which rtsp-simple-server listens) when generating RTP-Info.

Example:
<pre>
PLAY rtsp://localhost:28554/deepstream/ RTSP/1.0
CSeq: 5
User-Agent: LibVLC/3.0.11 (LIVE555 Streaming Media v2016.11.28)
Session: 12345678
Range: npt=0.000-
</pre>

so in reply, RTP-Info must contain  **rtsp://localhost:28554/deepstream/**  even when proxy server is configured to listen on 8554.

**Comment by rho-sk** [comment]
> And of course this could be the starting point in supporting seeking and pausing.

Hi,
Thank you for including this issue in the implementation list.
Another important comment:
To maintain the functionality of the proxy, it is necessary to use the host and port that was sent in the PLAY request (not what is sent by the background server, or the address and port on which rtsp-simple-server listens) when generating RTP-Info.

Example:
<pre>
PLAY rtsp://localhost:28554/deepstream/ RTSP/1.0
CSeq: 5
User-Agent: LibVLC/3.0.11 (LIVE555 Streaming Media v2016.11.28)
Session: 12345678
Range: npt=0.000-
</pre>

so in reply, RTP-Info must contain  **rtsp://localhost:28554/deepstream/**  even when proxy server is configured to listen on 8554.

**Comment by aler9** [comment]
RTP-Info is now filled when source is a publisher; what remains to do is filling it when source is a proxied rtsp or rtmp stream.

**Comment by aler9** [comment]
RTP-Info is now filled even when the source is a proxied RTSP stream. The feature will be available in the next release

**Comment by rho-sk** [comment]
When the new relase is planned ?

**Comment by aler9** [comment]
Please try this nightly release and let me know whether the feature is implemented correctly
[rtsp-simple-server_v0.15.0-22-gad63f7d_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/6181867/rtsp-simple-server_v0.15.0-22-gad63f7d_windows_amd64.zip)
[rtsp-simple-server_v0.15.0-22-gad63f7d_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6181868/rtsp-simple-server_v0.15.0-22-gad63f7d_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.15.0-22-gad63f7d_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6181869/rtsp-simple-server_v0.15.0-22-gad63f7d_linux_arm7.tar.gz)
[rtsp-simple-server_v0.15.0-22-gad63f7d_linux_arm6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6181870/rtsp-simple-server_v0.15.0-22-gad63f7d_linux_arm6.tar.gz)
[rtsp-simple-server_v0.15.0-22-gad63f7d_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6181871/rtsp-simple-server_v0.15.0-22-gad63f7d_linux_amd64.tar.gz)
[rtsp-simple-server_v0.15.0-22-gad63f7d_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/6181872/rtsp-simple-server_v0.15.0-22-gad63f7d_darwin_amd64.tar.gz)

**Comment by rho-sk** [comment]
Implementation looks strange,
i tested situation when the source is publisher.

- RTSP server started ~ 13:41:31
- publisher connected ~ 13:41:33

On the client side, now there is calculated position (thats fine), but
1. at client there is 14:18.30, but calculated real timestamp is 2193736 (2021-03-22T13:54:51.546941+00:00),
2. when player session is closed, and opened again in the same process - it return again zeros. But i think it's side effect of situation that player is confused, because for the same session it receives again the same rtptime.


What i realized is that, rtptime is always the same (based on what was at publish time) - a thats the problem.
3 separate play requests have the same rtptime

RTP-Info: url=rtsp://158.195.164.55:8554/deepstream/trackID=0;seq=24833;rtptime=2428492610
RTP-Info: url=rtsp://158.195.164.55:8554/deepstream/trackID=0;seq=24833;rtptime=2428492610
RTP-Info: url=rtsp://158.195.164.55:8554/deepstream/trackID=0;seq=24833;rtptime=2428492610


Conclusion:
rtptime, must be calculated at PLAY real time, not time of publishing.

**Comment by aler9** [comment]
> rtptime, must be calculated at PLAY real time, not time of publishing.

After reading again and again the specification, i'm pretty sure you're right. The time of publishing can be provided with the Range header, while the RTP-Info header provides time corresponding to the start of the presentation, i.e. time of the PLAY request. The implementation will be changed accordingly.

**Comment by aler9** [comment]
now rtptime points to the calculated RTP time of the PLAY request, and seqnum points to the last sequence number.

**Comment by aler9** [comment]
The feature was added to v0.15.1, please try it and let me know if the implementation is right or there is any problem.

**Comment by rho-sk** [comment]
Tested
- server ubuntu 18.04 arm64
- rtsp publisher - gstreamer,  publish mode with  rtspclientsink 
- client windows 10, libvlc 3.0.11-0-gdc0c5ced72

Works as expected, thank you !

![sync](https://user-images.githubusercontent.com/74427858/112309923-41b77780-8ca4-11eb-8b98-7323bf4b49ed.png)
