### ISSUE TITLE
Implement an API for listing and kicking clients

### ISSUE THREAD

**Issue by swarup-e** [aler9/rtsp-simple-server#234]
## Which version are you using?

v0.15.0

## Question
How to forcefully disconnect a client who is reading stream?

Description
I wanted to know like if I need to monitor a connected stream and I want to force the connection is there an API to do that. 
How can I build feature like [nginx rtmp control module](https://github.com/arut/nginx-rtmp-module/wiki/Control-module)

**Comment by aler9** [comment]
Actually you can see the count of connected clients through the metrics exporter, but there isn't a way to list or disconnect existing clients. This can be a future enhancement.

**Comment by swarup-e** [comment]
Hi @aler9 I would like to contribute on this feature. If you can guide me on right path I will try to build and raise a pull request.

**Comment by aler9** [comment]
@swarup-e the problem of this feature is that at the moment there isn't any HTTP API, therefore, we must

1. first implementing the HTTP API with a basic set of features (getting the configuration),
2. then augmenting this set (setting the configuration)
3. then adding advanced features (listing clients, kicking clients)
