### ISSUE TITLE
ERR: unable to setup authentication: unable to parse key-value 

### ISSUE THREAD

**Issue by PedroC1999** [aler9/rtsp-simple-server#25]
Getting the following issue. I am running using the Docker image and the following yml file

`  proxied:
    source: rtsp://user:password@192.168.1.22:554/onvif1
    # if the source is an RTSP url, this is the protocol that will be used to pull the stream
    #sourceProtocol: udp
`

The stream works in ZoneMinder and VLC using the exact same URL.

`2020/07/03 13:13:13 [0/0/0] rtsp-simple-server v0.8.1
2020/07/03 13:13:13 [0/0/0] [UDP/RTP listener] opened on :8000
2020/07/03 13:13:13 [0/0/0] [UDP/RTCP listener] opened on :8001
2020/07/03 13:13:13 [0/0/0] [TCP listener] opened on :8554
2020/07/03 13:13:13 [0/0/0] [streamer proxied] initializing with protocol udp
2020/07/03 13:13:14 [0/0/0] [streamer proxied] ERR: unable to setup authentication: unable to parse key-value (,nonce="c7ebda6058fed5422476c9d8667376fb")`

**Comment by aler9** [comment]
Hello, this should have been fixed in v0.8.3; please try the new release and let me know
