### ISSUE TITLE
Problems encountered in using proxy mode

### ISSUE THREAD

**Issue by wzl16** [aler9/rtsp-simple-server#251]
## Which version are you using?

v0.15.2

## Question

When I use proxy mode as follows:

![image](https://user-images.githubusercontent.com/31687104/112792199-92104a00-9095-11eb-8544-333690e291e3.png)

When the first client accesses rtsp://192.168.98.28 : 8554 / proxied1, one function is normal, but at this time, if two clients are opened to access at the same time rtsp://192.168.98.28 : 8554 / proxied1 cannot be opened and the following error is reported:

![image](https://user-images.githubusercontent.com/31687104/112792357-e0254d80-9095-11eb-824d-d5996febfe13.png)

**Comment by wzl16** [comment]
Thank you for your reply. When I set the value of sourceondemand to no, multiple clients can access it rtsp://192.168.98.28:8554 proxied1 or rtsp://192.168.98.28:8554 proxied2 is normal and there is no error log. But this is not what I want, because I have a lot of streams, and I don't want them to work all the time, which is a waste of bandwidth.

**Comment by wzl16** [comment]
> Hello, from the log you provided, it seems that the proxied1 source is not working properly, and therefore clients cannot read from it. In my opinion you have to find out why the source is not working, by setting `sourceOnDemand` to `no` and reviewing the logs.
> 
> The number of clients have no influence on the fact that the source works or not, since clients don't interact with the camera, but only with the server.

Thank you for your reply. When I set the value of sourceondemand to no, multiple clients can access it rtsp://192.168.98.28:8554 proxied1 or rtsp://192.168.98.28:8554 proxied2 is normal and there is no error log. But this is not what I want, because I have a lot of streams, and I don't want them to work all the time, which is a waste of bandwidth.

**Comment by aler9** [comment]
Just noticed that this is the same issue of #334 - a fix is available and has been added to v0.15.4

**Comment by wzl16** [comment]
I’m truly grateful for your help.
