### ISSUE TITLE
24 hour time incorrect

### ISSUE THREAD

**Issue by benbullnz** [aler9/rtsp-simple-server#33]
Hi, 

I have noticed a minor issue; that the running log of connected users is reporting 24hr time but it seems to be round the wrong way. 

The following connection was made at 09:48:52 (AM)
2020/07/13 21:48:52 [3/2/0] [client 123.xxx.xxx.x:58957] PLAY

The issue is also apparent in the afternoon/evening when the log file reports the connection as being in the morning.
## Tested with v0.9.1

As a side note, I really appreciate this project and how well it is maintained! Consider setting up sponsorship or posting a link so we can buy you a coffee/beer.

**Comment by aler9** [comment]
Hello, thanks for the comment, this software was created for a project in which live555proxy was eating 60% of the CPU for 10 cameras, now the cameras are 44 and CPU is less than 10% :)

Regarding logs timestamp, i'm just using the standard `log` Go library, without any customization, so:
* if you're using the software outside docker, it's either a misconfiguration or a Go bug
* if you're using the software inside docker, you can try mounting timezone and localtime with
   ```
   docker run -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro ...
   ```

**Comment by benbullnz** [comment]
Thanks for this. 

I can confirm, as you say, this isn't an issue. It just happens that the server time is in UTC, which happens to be 12 hours difference from my local time.
