### ISSUE TITLE
ERR: no one is publishing to path (regression for v0.15.1 - v0.15.3)

### ISSUE THREAD

**Issue by dorinclisu** [aler9/rtsp-simple-server#334]
## Which version are you using?

v0.15.1 - v0.15.3

## Which operating system are you using?

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture
- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue
In RTSP proxy mode, some camera streams stopped working for no obvious reason. Server configuration stayed exactly the same, I had to roll back the version to v0.15.0 to restore functionality. The only error is `ERR: no one is publishing to path 'abc123'`

This is different than https://github.com/aler9/rtsp-simple-server/issues/250 

Unfortunately I cannot enable debug output because the system cannot deal with the huge log thoroughput. And if I enabled debug output locally it wouldn't help, because **locally the same problematic streams work fine**. So this is not reproducible as it happens only in production with many streams and clients involved.

Here are the production logs. It seems as if the first client might be able to read (A.B.C.D), but the second and subsequent ones cannot (W.X.Y.Z).
```
2021-04-03T07:37:50.910773665Z [I] [4/0/0] [path abc123] [rtsp source] started
2021-04-03T07:37:50.912440932Z [I] [4/0/0] [path abc123] [rtsp source] connecting
2021-04-03T07:37:52.032790618Z [I] [4/0/3] [path abc123] [rtsp source] ready
2021-04-03T07:37:52.103725075Z [I] [4/0/4] [client A.B.C.D:28643] is reading from path 'abc123', 1 track with tcp
2021-04-03T07:38:30.223700286Z [I] [5/0/4] [client W.X.Y.Z:63262] ERR: no one is publishing to path 'abc123'
```

It might be related to the fact that connecting with VLC to these streams takes a bit longer than usual (more than 10s), but I am not sure.

**Comment by aler9** [comment]
Hello, is `sourceOnDemand` enabled?

**Comment by dorinclisu** [comment]
Yes
```
abc123:
    readIps:
    - A.B.C.D
    - W.X.Y.Z
    readPass: skHAJM67UKe7wmiz
    readUser: user_YpNX
    source: rtsp://user:pass@address:port/path
    sourceOnDemand: true
    sourceProtocol: tcp

**Comment by dorinclisu** [comment]
I think I figured how to replicate:
```
authMethods:
- basic
- digest
encryption: false
logDestinations:
- stdout
logFile: rtsp-simple-server.log
logLevel: info
metrics: false
paths:
  test:
    source: rtsp://SOME_VALID_STREAM
    sourceOnDemand: true
    sourceProtocol: tcp
pprof: false
protocols:
- tcp
readTimeout: 10s
rtmpDisable: true
rtcpPort: 8001
rtpPort: 8000
rtspPort: 8554
rtspsPort: 555
runOnConnectRestart: false
serverCert: server.crt
serverKey: server.key
writeTimeout: 10s
```

In one terminal run `vlc rtsp://localhost:8554/test`, and wait for video. Then in another terminal run the same thing.

Logs:
```
2021/04/03 08:37:34 [I] [0/0/0] rtsp-simple-server v0.15.3
2021/04/03 08:37:34 [I] [0/0/0] [RTSP/TCP listener] opened on :8554
2021/04/03 08:38:22 [I] [1/0/0] [client 172.18.0.1:60826] connected (RTSP/TCP)
2021/04/03 08:38:22 [I] [1/0/0] [path test] [rtsp source] started
2021/04/03 08:38:22 [I] [1/0/0] [path test] [rtsp source] connecting
2021/04/03 08:38:24 [I] [1/0/0] [path test] [rtsp source] ready
2021/04/03 08:38:24 [I] [1/0/1] [client 172.18.0.1:60826] is reading from path 'test', 1 track with tcp
2021/04/03 08:38:37 [I] [2/0/1] [client 172.18.0.1:60832] connected (RTSP/TCP)
2021/04/03 08:38:37 [I] [2/0/1] [client 172.18.0.1:60832] ERR: no one is publishing to path 'test'
2021/04/03 08:38:37 [I] [1/0/1] [client 172.18.0.1:60832] disconnected
```

If vlc is started at the same time in both terminals, then it seems to work as expected.

**Comment by aler9** [comment]
Thank you very much for reporting this issue, it is fixed in main and i'll publish a new release as soon as it's possible

**Comment by aler9** [comment]
added in v0.15.4
