### ISSUE TITLE
ERR invalid RTP-Info: invalid key: ssrc

### ISSUE THREAD

**Issue by louisr0608** [aler9/rtsp-simple-server#336]
## Which version are you using?

v0.15.3

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Receiving error "[path proxied1] [rtsp source] ERR: invalid RTP-Info: invalid key: ssrc" for a proxied RTSP stream. rtps-simple-server is running in Docker.

The stream is coming directly from a Reolink RLC-410-5MP camera. Streams from Reolink 4k cameras on the same network are working well.

## Log

Starting rtsp_server ... done
Attaching to rtsp_server
rtsp_server      | 2021/04/04 01:49:54 [I] [0/0/0] rtsp-simple-server v0.15.3
rtsp_server      | 2021/04/04 01:49:54 [I] [0/0/0] [RTSP/TCP listener] opened on :8554
rtsp_server      | 2021/04/04 01:49:54 [I] [0/0/0] [RTMP listener] opened on :1935
rtsp_server      | 2021/04/04 01:49:54 [I] [0/0/0] [path proxied1] [rtsp source] started
rtsp_server      | 2021/04/04 01:49:54 [I] [0/0/0] [path proxied1] [rtsp source] connecting
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] c->s OPTIONS rtsp://192.168.1.230:554/h264Preview_01_main RTSP/1.0
rtsp_server      | CSeq: 1
rtsp_server      | User-Agent: gortsplib
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] s->c RTSP/1.0 200 OK
rtsp_server      | CSeq: 1
rtsp_server      | Date: Sun, Apr 04 2021 01:49:55 GMT
rtsp_server      | Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER, SET_PARAMETER
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] c->s DESCRIBE rtsp://192.168.1.230:554/h264Preview_01_main RTSP/1.0
rtsp_server      | Accept: application/sdp
rtsp_server      | CSeq: 2
rtsp_server      | User-Agent: gortsplib
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] s->c RTSP/1.0 401 Unauthorized
rtsp_server      | CSeq: 2
rtsp_server      | Date: Sun, Apr 04 2021 01:49:55 GMT
rtsp_server      | WWW-Authenticate: Digest realm="LIVE555 Streaming Media", nonce="80074a8537bf7b64699e10dc31fafa49"
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] c->s DESCRIBE rtsp://192.168.1.230:554/h264Preview_01_main RTSP/1.0
rtsp_server      | Accept: application/sdp
rtsp_server      | Authorization: Digest username="admin", realm="LIVE555 Streaming Media", nonce="80074a8537bf7b64699e10dc31fafa49", uri="rtsp://192.168.1.230:554/h264Preview_01_main", response="26236022c971999fd541ac31ce9930d1"
rtsp_server      | CSeq: 3
rtsp_server      | User-Agent: gortsplib
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] s->c RTSP/1.0 200 OK
rtsp_server      | CSeq: 3
rtsp_server      | Content-Base: rtsp://192.168.1.230/h264Preview_01_main/
rtsp_server      | Content-Length: 734
rtsp_server      | Content-Type: application/sdp
rtsp_server      | Date: Sun, Apr 04 2021 01:49:55 GMT
rtsp_server      |
rtsp_server      | v=0
rtsp_server      | o=- 1617472609688179 1 IN IP4 192.168.1.230
rtsp_server      | s=Session streamed by "preview"
rtsp_server      | i=h264Preview_01_main
rtsp_server      | t=0 0
rtsp_server      | a=tool:LIVE555 Streaming Media v2013.04.08
rtsp_server      | a=type:broadcast
rtsp_server      | a=control:*
rtsp_server      | a=range:npt=0-
rtsp_server      | a=x-qt-text-nam:Session streamed by "preview"
rtsp_server      | a=x-qt-text-inf:h264Preview_01_main
rtsp_server      | m=video 0 RTP/AVP 96
rtsp_server      | c=IN IP4 0.0.0.0
rtsp_server      | b=AS:500
rtsp_server      | a=rtpmap:96 H264/90000
rtsp_server      | a=range:npt=0-
rtsp_server      | a=fmtp:96 packetization-mode=1;profile-level-id=640033;sprop-parameter-sets=Z2QAM6zoAoAPGQ==,aO48sA==
rtsp_server      | a=control:trackID=1
rtsp_server      | m=audio 0 RTP/AVP 97
rtsp_server      | c=IN IP4 0.0.0.0
rtsp_server      | b=AS:256
rtsp_server      | a=rtpmap:97 MPEG4-GENERIC/16000
rtsp_server      | a=fmtp:97 streamtype=5;profile-level-id=15;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1408; profile=1;
rtsp_server      | a=control:trackID=2
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] c->s SETUP rtsp://192.168.1.230:554/h264Preview_01_main/trackID=1 RTSP/1.0
rtsp_server      | Authorization: Digest username="admin", realm="LIVE555 Streaming Media", nonce="80074a8537bf7b64699e10dc31fafa49", uri="rtsp://192.168.1.230:554/h264Preview_01_main/trackID=1", response="07642977bdcaef387434052d129efdde"
rtsp_server      | CSeq: 4
rtsp_server      | Transport: RTP/AVP;unicast;client_port=14186-14187;mode=play
rtsp_server      | User-Agent: gortsplib
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] s->c RTSP/1.0 200 OK
rtsp_server      | CSeq: 4
rtsp_server      | Date: Sun, Apr 04 2021 01:49:55 GMT
rtsp_server      | Session: 6B577790
rtsp_server      | Transport: RTP/AVP;unicast;destination=192.168.1.229;source=192.168.1.230;client_port=14186-14187;server_port=6978-6979
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] c->s SETUP rtsp://192.168.1.230:554/h264Preview_01_main/trackID=2 RTSP/1.0
rtsp_server      | Authorization: Digest username="admin", realm="LIVE555 Streaming Media", nonce="80074a8537bf7b64699e10dc31fafa49", uri="rtsp://192.168.1.230:554/h264Preview_01_main/trackID=2", response="2055ba0496fb99df41bf3c2496be696b"
rtsp_server      | CSeq: 5
rtsp_server      | Session: 6B577790
rtsp_server      | Transport: RTP/AVP;unicast;client_port=48230-48231;mode=play
rtsp_server      | User-Agent: gortsplib
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] s->c RTSP/1.0 200 OK
rtsp_server      | CSeq: 5
rtsp_server      | Date: Sun, Apr 04 2021 01:49:55 GMT
rtsp_server      | Session: 6B577790
rtsp_server      | Transport: RTP/AVP;unicast;destination=192.168.1.229;source=192.168.1.230;client_port=48230-48231;server_port=6980-6981
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] c->s PLAY rtsp://192.168.1.230:554/h264Preview_01_main RTSP/1.0
rtsp_server      | Authorization: Digest username="admin", realm="LIVE555 Streaming Media", nonce="80074a8537bf7b64699e10dc31fafa49", uri="rtsp://192.168.1.230:554/h264Preview_01_main", response="96658613d51e12dd62346504361096de"
rtsp_server      | CSeq: 6
rtsp_server      | Session: 6B577790
rtsp_server      | User-Agent: gortsplib
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [D] [0/0/0] [path proxied1] [rtsp source] s->c RTSP/1.0 200 OK
rtsp_server      | CSeq: 6
rtsp_server      | Date: Sun, Apr 04 2021 01:49:55 GMT
rtsp_server      | RTP-Info: url=trackID=1;seq=55664;rtptime=254718369;ssrc=56597976,url=trackID=2;seq=43807;rtptime=1702259566;ssrc=ee839a80
rtsp_server      | Range: npt=0.000-
rtsp_server      | Server: Rtsp Server/2.0
rtsp_server      | Session: 6B577790
rtsp_server      |
rtsp_server      |
rtsp_server      | 2021/04/04 01:49:54 [I] [0/0/0] [path proxied1] [rtsp source] ERR: invalid RTP-Info: invalid key: ssrc

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed in main and will be added to the next release

**Comment by aler9** [comment]
added in v0.15.4
