### ISSUE TITLE
RTSP proxy fails to connfig - DESCRIBE invalid request / empty header value

### ISSUE THREAD

**Issue by jamesbraid** [aler9/rtsp-simple-server#34]
Hey, I'm getting two different error when I test with two different IP cameras. 

The first camera (test1) is an Amcrest unit, the second (test2) is a no-name IP camera. Both camera paths work fine in ffmpeg and VLC for playback. It seems like the rtsp-simple-server is making some requests that these units don't support and failing hard instead of continuing?

Let me know if I can provide any more debug info, is there a more verbose logging mode or anything?

Output from console:

```
$ ./rtsp-simple-server test.yaml
2020/07/14 19:31:35 [0/0/0] rtsp-simple-server v0.9.1
2020/07/14 19:31:35 [0/0/0] [UDP/RTP listener] opened on :8000
2020/07/14 19:31:35 [0/0/0] [UDP/RTCP listener] opened on :8001
2020/07/14 19:31:35 [0/0/0] [TCP listener] opened on :8554
2020/07/14 19:31:35 [0/0/0] [streamer test1] initializing with protocol udp
2020/07/14 19:31:35 [0/0/0] [streamer test2] initializing with protocol udp
2020/07/14 19:31:35 [0/0/0] [streamer test2] ERR: DESCRIBE: bad status code: 551 (Invalid Method)
2020/07/14 19:31:35 [0/0/0] [streamer test1] ERR: empty header value
2020/07/14 19:31:40 [0/0/0] [streamer test2] initializing with protocol udp
2020/07/14 19:31:40 [0/0/0] [streamer test2] ERR: DESCRIBE: bad status code: 551 (Invalid Method)
2020/07/14 19:31:40 [0/0/0] [streamer test1] initializing with protocol udp
2020/07/14 19:31:40 [0/0/0] [streamer test1] ERR: empty header value
2020/07/14 19:31:45 [0/0/0] [streamer test2] initializing with protocol udp
2020/07/14 19:31:45 [0/0/0] [streamer test2] ERR: DESCRIBE: bad status code: 551 (Invalid Method)
2020/07/14 19:31:45 [0/0/0] [streamer test1] initializing with protocol udp
2020/07/14 19:31:46 [0/0/0] [streamer test1] ERR: empty header value
```

Config file:

```
paths:
  test1:
    source: rtsp://user:pass@camera1:554/cam/realmonitor?channel=1&subtype=0
    sourceProtocol: tcp
  test2:
    source: rtsp://user:pass@camera2:554
    sourceProtocol: tcp
```

**Comment by aler9** [comment]
Hello, thanks for reporting the bug. Communication issues between the server and cameras are unfortunately common since there are myriad of RTCP implementations, especially in embedded systems.
To fix this, i need a network dump of the data exchanged between the server and the target, that can be generated in this way:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by aler9** [comment]
Furthermore, i'm noticing that you didn't provide a path in the second camera url:
```
rtsp://user:pass@camera2:554
```

are you sure this is the right url?

**Comment by aler9** [comment]
without further data i can't work on this, sorry
