### ISSUE TITLE
Support Prometheus metrics when using loadbalancer/multiple instances bound to the same IP.

### ISSUE THREAD

**Issue by bbnp91** [aler9/rtsp-simple-server#343]
## Which version are you using?

v0.15.4

## Which operating system are you using?

OS

- [X ] Linux
- [ ] Windows
- [ X] macOS

Architecture

- [ X] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

Hi, 

I have a unique issue where by I have RTSS running on multiple VM instances in proxy mode. All of these instances are assigned to a cloud load balancer which distributes traffic based on health/status of the respective VM's. 

In order to make the rtsp streaming work I have needed to edit the config.yml file to assign the listenIP of each instance to be that of public facing load balancer address. (Each VM in my pool of proxy vm's are bound to the same external IP). 
This works as expected for the actual RTSP streaming but doesn't allow me access to the respective prometheus metrics from each instance as they are being bound to the loadbalancer address by virtue of the ListenIP being set in the rtss.yml

Is there an obvious solution which would still allow me to access the :9998/metrics from each instance on their own external IP's while still continuing to bind the rtps streaming to the load balancer IP? 

Maybe you could implement a seperate bind IP for the prometheus metrics in the config file, or point me in the right direction for modifying the source to solve this problem. 

Thanks

**I can provide access (privately) to VM's to replicate issue if this will help**

**Comment by aler9** [comment]
> Maybe you could implement a seperate bind IP for the prometheus metrics in the config file

Yes, probably is better to allow the user to set the bind IP for each listener, unfortunately we have to wait for a major release, since it's a breaking change.

**Comment by aler9** [comment]
now it's possible to set a different IP for each listener. The feature will be available in the next release.

**Comment by aler9** [comment]
added in v0.16.0
