### ISSUE TITLE
ERR: buffer length exceeds 128

### ISSUE THREAD

**Issue by CNchence** [aler9/rtsp-simple-server#35]
Testing 0.9.1 with OBS publishing, I get frequent and disconnects

**Comment by aler9** [comment]
Hello, OBS studio does not support publishing to RTSP, so i suppose you're talking about the "Media Source" source. Can you describe better the problem? what is your pipeline? for example:
ffmpeg -> rtsp-simple-server -> obs -> rtmp

thanks

**Comment by aler9** [comment]
This is surely solved, since all buffers have a size greater than 128. If you still have problems, please open another issue.
