### ISSUE TITLE
Is on-demand supported?

### ISSUE THREAD

**Issue by smallnetbuilder** [aler9/rtsp-simple-server#36]
I'm running the server on Win10 with ffmpeg as publisher.

Is there a way to support on-demand, i.e. the server/publisher starts only when a player connects?

**Comment by aler9** [comment]
Hello, on-demand is not supported yet but i think it would be a good enhancement, and it can be easily done by adding a `runOnRequest` option to the configuration. I'll work on it.

**Comment by smallnetbuilder** [comment]
That would be great. Thanks!

**Comment by frankville** [comment]
Hi, this on demand feature would be great for the proxy functionality. Now the proxy is actually permanently consuming the proxied stream even if there are no clients connected. So +1 for this feature. Keep the great work

**Comment by aler9** [comment]
Hello all, two new features have been implemented:
* the option `sourceOnDemand` to pull a source only when there are connected clients
* the option `runOnDemand` to run a script (for instance, ffmpeg) when a path is requested by a client

They will be available from v0.9.5.

**Comment by smallnetbuilder** [comment]
Thanks for adding on demand. Could you add an example use to the ReadMe please?

**Comment by aler9** [comment]
https://github.com/aler9/rtsp-simple-server#on-demand-publishing

**Comment by smallnetbuilder** [comment]
<blush> Sorry that I missed that! Thanks again, Alessandro!
