### ISSUE TITLE
HLS streaming error:  first NALU does not contain the start bit

### ISSUE THREAD

**Issue by t3therdev** [aler9/rtsp-simple-server#374]
## Which version are you using?

v0.16.0

## Which operating system are you using?

OS

- [ ] Linux
- [X] Windows
- [ ] macOS

## Describe the issue

Description
Pushing stream to server. 
Connecting to HLS stream.
Errors are:

`2021/05/10 12:02:47 I [1/0] [HLS] [converter 9999] opened
2021/05/10 12:02:47 I [1/1] [HLS] [converter 9999] is converting into HLS
2021/05/10 12:02:47 W [1/1] [HLS] [converter 9999] unable to decode video track: first NALU does not contain the start bit
2021/05/10 12:02:47 W [1/1] [HLS] [converter 9999] unable to decode video track: first NALU does not contain the start bit
2021/05/10 12:02:47 W [1/1] [HLS] [converter 9999] unable to decode video track: first NALU does not contain the start bit
2021/05/10 12:02:47 W [1/1] [HLS] [converter 9999] unable to decode video track: first NALU does not contain the start bit
`

**Comment by t3therdev** [comment]
For another camera i am getting this error:

2021/05/10 12:18:58 W [1/2] [HLS] [converter ch999] unable to decode video track: Packet is not FU-A

**Comment by gnubit-au** [comment]
This issue is also happening on my setup with linux using proxied sourced camera streams.

`[0/1] [HLS] [converter proxied1] unable to decode video track: first NALU does not contain the start bit
2021/05/11 11:08:07 W [0/1] [HLS] [converter proxied1] unable to decode video track: Packet is not FU-A`

**Comment by aler9** [comment]
Hello, to test HLS you can use this configuration:
```yml
paths:
  proxied:
    source: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov
```

I know that the conversion can fail with some streams (and this can be improved); in particular, at the moment the converter starts converting as soon as possible, and this happens: big frames are usually split into many packets, and if a packet of a previously-existing frame is received, the converter prints errors like the one you reported:

```
[0/1] [HLS] [converter proxied1] unable to decode video track: first NALU does not contain the start bit 
```

Therefore a first step could be improving the converter to wait for the start of a frame before running.

**Comment by t3therdev** [comment]
Have you tested it with a record type stream that is pushing to the server? instead of a proxy stream?

**Comment by gnubit-au** [comment]
> Have you tested it with a record type stream that is pushing to the server? instead of a proxy stream?

Thanks, I have tested it with a record type stream and it works fine (tested by connecting directly to the HLS streams remotely). I have 2 rstp-simple-servers (the remote location set as record and the local server set as proxied). I would like this setup as I wish to have just one connection to the remote and stream to many locally.

**Comment by aler9** [comment]
This error should be fixed with newer releases. In case it reappears, feel free to post again. A sample .mp4 file would be helpful to replicate the issue.
