### ISSUE TITLE
Blur when publish streams via UDP

### ISSUE THREAD

**Issue by CNchence** [aler9/rtsp-simple-server#38]
I use ffmpeg to grab the screen and use rtsp to push the stream. When I use TCP, the video is normal, but when using UDP, the received picture will have mosaic and blur

**Comment by gustavobsch** [comment]
I have the same issue. I first thought it was the network camera but when using VLC the frames look fine no corruption.

**Comment by Hyperopic** [comment]
Same here, output is significantly better when using a TCP stream. This is over loopback and then out over gigabit LAN.
ffmpeg (looping MP4 file) ---> 127.0.0.1:8554 ---> rtsp-simple-server ---> :8554 gigabit LAN ---> Hikvision NVR (RTSP client)
Running Ubuntu 18.04.04
It may be coincidental, but rtsp-simple-server has replaced an install of chriswiggins/rtsp-streaming-server typescript module which stopped working with issues regarding UDP port binding. It had been working fine, then after an update of various (haven't dug into what yet) it stopped working.
TCP is much better, but still seeing some odd artefacts with moving backgrounds and text overlays (in original video file, not added by me) and particularly noticeable where the original video has transition effects.

**Comment by aler9** [comment]
Hello, i'm unable to replicate the issue.
I'm doing the following (v0.9.1):
* pc 1 is running the server and streaming the screen with UDP
  ```
  ./rtsp-simple-server &
  ffmpeg -video_size 1280x720 -framerate 25 -f x11grab -i :0 -c:v libx264 -preset ultrafast -b:v 500k -g 100 -keyint_min 100 -f rtsp rtsp://localhost:8554/mystream
  ```

* pc 2 is receiving with UDP
   ```
   vlc rtsp://192.168.x.x:8554/mystream
   ```

The stream is received correctly with both UDP and TCP (by adding the --rtsp-tcp flag to VLC).
Please provide more details (like a set of replicable commands).

**Comment by gustavobsch** [comment]
In my case it was an opencv+ffmpeg issue. After switching to opencv+gstreamer I don't get corrupted frames using UDP

**Comment by smallnetbuilder** [comment]
I am also experiencing this. using version 0.9.1 running on Windows 10.
Here's the ffmpeg publish. Using Big Buck Bunny file, publishing only mp3 audio

ffmpeg.exe  -re -stream_loop -1 -i c:\\users\\octoscope\\testfolder\\bbb_sunflower_1080p_30fps_normal.mp4 -map 0:0 -map 0:1 -c copy -f  rtsp rtsp://localhost:8554/testfile

Using MPV or ffplay as player results in very distorted video

**Comment by smallnetbuilder** [comment]
Setting the player to read either UDP or TCP RTSP stream makes no difference.

**Comment by Liroy2003** [comment]
I have the same issue, when using tcp the stream is clear but when using udp i get mosaic or blur. I watch the stream via internet so the client is in another network then the server. Maybe it has something to do with the MTU when using UDP?

**Comment by smallnetbuilder** [comment]
I do not have the experience of TCP fixing the problem. I can find the problem when I run ffmpeg, rtsp-simple-server and mpv ad player on the same system. 

As far as I can tell, the problem is likely due to something in ffmpeg and depends on the bitrate of the file being streamed. I can get up to around 20 Mbps H.264, video only without smear. Above that, I get smear. At any rate I don't think it is a problem with rtsp-simple-server. So I think this bug should be closed.

**Comment by aler9** [comment]
The issue is still present, it depends on the server; discussion has been moved here: https://github.com/aler9/rtsp-simple-server/issues/125
