### ISSUE TITLE
Support SSRC in transport header 

### ISSUE THREAD

**Issue by Keviento** [aler9/rtsp-simple-server#380]
Hi, recently my team and I found the rtsp-simple-server and it helped us alot with simulating stream. However, we found that when sending a SETUP to the server, the response never contains the SSRC for unicast transmission. Here is an example of the response. 

```
Real Time Streaming Protocol
    Response: RTSP/1.0 200 OK\r\n
        Status: 200
    CSeq: 0\r\n
    Server: gortsplib\r\n
    Session: 3461776667
    Transport: RTP/AVP;unicast;client_port=15000-15001;server_port=8000-8001
    \r\n
```

I've quickly searched the pkg/headers/transport.go file and the field seems missing. 

Would it be possible to add it to the transport header and defining it for ? It would  be helpful to identify the synchronization source before the stream starts.

If you need any more information I would be pleased to share them.

Thanks

**Comment by aler9** [comment]
SSRC is now filled in the `Transport` header provided to readers during `SETUP` requests.

**Comment by Keviento** [comment]
First of all, thanks for the quick code changes. No I don't have any additional information about the issue or about the behavior. Filling the SSRC with the one given by the stream at setup is good enough to cover the vast majority of cases. 

Also, if I understand correctly, now you take the track and get the last SSRC provided by the track and return it in the SETUP . Is that correct ?

**Comment by aler9** [comment]
> now you take the track and get the last SSRC provided by the track and return it in the SETUP . Is that correct ?

yes, the solution is the same of the one adopted to fill the RTP-Info header of PLAY responses: required data is taken from the stream as soon as it arrives. In the meanwhile, Transport's SSRC and RTP-Info are not available.

**Comment by Keviento** [comment]
Perfect, thanks. Do you have any idea when the enhancement will be released ?

**Comment by aler9** [comment]
added in v0.16.1
