### ISSUE TITLE
HLS stream not working with paths containing "/" 

### ISSUE THREAD

**Issue by dorinclisu** [aler9/rtsp-simple-server#381]
## Which version are you using?

v0.16.0

## Which operating system are you using?

OS
- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue
config.yaml
```yaml
...
paths:
  test/path:
    source: rtsp://...
```

```
2021/05/18 17:02:03 I [0/0] rtsp-simple-server v0.16.0
2021/05/18 17:02:03 I [0/0] [RTSP] TCP listener opened on :8554
2021/05/18 17:02:03 I [0/0] [HLS] listener opened on :8888
2021/05/18 17:02:03 I [0/0] [path test/path] [rtsp source] started
2021/05/18 17:02:03 I [0/0] [path test/path] [rtsp source] ready
2021/05/18 17:02:08 I [0/0] [HLS] [conn 172.18.0.1:63864] GET /test/path
2021/05/18 17:02:08 I [0/0] [HLS] [converter test] opened
2021/05/18 17:02:08 I [0/0] [HLS] [converter test] ERR: unable to find a valid configuration for path 'test'
2021/05/18 17:02:08 I [0/0] [HLS] [converter test] closed
```

Slashes are perfectly legal characters for url paths, and it works fine with RTSP, but fails with HLS.

I suppose the reason is that the HLS converter / server does not properly handle nested directories for the stream fragment files.

Theoretically, as far as the server is concerned, it is easy to work around by replacing slashes with dashes for example, but from a system integration point of view it's a lot of work for me, to maintain backwards compatibility as the path is shared with RTSP.

Please let me know if it's possible to fix it, so I can wait for the upgrade, otherwise I will apply the workaround.

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed in main and will be added to the next release.

**Comment by aler9** [comment]
added to v0.16.2
