### ISSUE TITLE
ERR: username and password must be both provided

### ISSUE THREAD

**Issue by eljefe80** [aler9/rtsp-simple-server#395]
## Which version are you using?

v0.16.1 from dockerhub

## Which operating system are you using?

OS

- [ x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

I have a couple of no-name ip cameras that require basic auth, without a password. IE, the paths: would look something like:

>   front_room_large:
>     source: rtsp://admin:@10.200.12.53:8001

regrettably, rtsp-simple-server refuses to start saying only:

> rtspproxy    | ERR: username and password must be both provided

The issue appears to be [here](https://github.com/aler9/rtsp-simple-server/blob/cfbea7eedcaca6bdc15bf50ad4372d46ec41607d/internal/conf/path.go#L145)

vlc and ffplay (among other rtsp ingesters) appear to accept this URL format.

## Describe how to replicate the issue

1. configure a paths: entry url with a username, but no password
2. start the server

This failure occurs before network is initiated. 
 no

**Comment by dorinclisu** [comment]
Would the cameras refuse authentication with a dummy password? If not, this would be an easy workaround.

**Comment by eljefe80** [comment]
Yes, using anything but an empty password results in a 401 unauthorized from the camera and I cannot change the password through the interface.

**Comment by aler9** [comment]
Thanks for reporting the issue, sources with empty passwords are now supported in main and will be added to the next release.

**Comment by aler9** [comment]
added to v0.16.2
