### ISSUE TITLE
rtsp-simple-server crashes when HLS client connects

### ISSUE THREAD

**Issue by gnubit-au** [aler9/rtsp-simple-server#399]
v0.16.1 linux_arm7 , see attached snippet of the log:

I`m reverting to previous version with bug  #374 for now, thanks.

`journalctl` -u `rtsp-simple-server`

May 23 16:11:47 streamerbox rtsp-simple-server[5516]: 2021/05/23 16:11:47 I [0/8] [HLS] [conn 1xx.1xx.x.xxx:34532] GET /proxied2/
May 23 16:11:47 streamerbox rtsp-simple-server[5516]: 2021/05/23 16:11:47 I [0/8] [HLS] [converter proxied2] opened
May 23 16:11:47 streamerbox rtsp-simple-server[5516]: 2021/05/23 16:11:47 I [0/9] [HLS] [converter proxied2] is converting into HLS
May 23 16:11:47 streamerbox rtsp-simple-server[5516]: panic: runtime error: invalid memory address or nil pointer dereference
May 23 16:11:47 streamerbox rtsp-simple-server[5516]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12098]
May 23 16:11:47 streamerbox rtsp-simple-server[5516]: goroutine 210 [running]:
May 23 16:11:47 streamerbox rtsp-simple-server[5516]: github.com/aler9/rtsp-simple-server/internal/hlsconverter.(*Converter).runRequestHandler(0x310e070, 0x3505d00, 0x3
May 23 16:11:47 streamerbox rtsp-simple-server[5516]:         /s/internal/hlsconverter/converter.go:538 +0x14c
May 23 16:11:47 streamerbox rtsp-simple-server[5516]: created by github.com/aler9/rtsp-simple-server/internal/hlsconverter.(*Converter).runInner
May 23 16:11:47 streamerbox rtsp-simple-server[5516]:         /s/internal/hlsconverter/converter.go:320 +0x62c
May 23 16:11:47 streamerbox systemd[1]: rtsp-simple-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 23 16:11:47 streamerbox systemd[1]: rtsp-simple-server.service: Failed with result 'exit-code'.

**Comment by aler9** [comment]
Hello, to fix this i need to be able to replicate the issue, can you post a procedure that allows to replicate the issue? example:

1. start the server
2. publish with ...
3. read with ...

thanks

**Comment by gnubit-au** [comment]
Thanks for having a look into this.

1. I start the server via systemd [https://github.com/aler9/rtsp-simple-server#start-on-boot-with-systemd](https://github.com/aler9/rtsp-simple-server#start-on-boot-with-systemd) Same issue if started manually with server binary located in /home/$USER dir.

2. RTSP published streams are dahua ip cameras.

3. I read the HLS converted streams with a web browser (firefox/chromium) . When I try to connect to HLS via the browser the server crashes.  The server crashes both on record or proxy type streams.

The log below is from the record type stream rtsp-simple-server (linux_arm7 Raspberry Pi OS Lite), and the crash when I try to connect to it with a web browser.
It also crashes on my proxied rtsp-simple-server (inux_arm7 armbian, the log above from my first post)

`journalctl` -u `rtsp-simple-server`

May 29 19:02:04 cambox rtsp-simple-server[21537]: 2021/05/29 19:02:04 I [0/0] [RTSP] [session 2036600912] opened by 192.168.x.xxx:50352
May 29 19:02:04 cambox rtsp-simple-server[21537]: 2021/05/29 19:02:04 I [0/0] [RTSP] [session 1680903592] opened by 192.168.x.xxx:50348
May 29 19:02:04 cambox rtsp-simple-server[21537]: 2021/05/29 19:02:04 I [0/0] [RTSP] [session 2311638656] opened by 192.168.x.xxx:50354
May 29 19:02:04 cambox rtsp-simple-server[21537]: 2021/05/29 19:02:04 I [0/0] [RTSP] [session 3761458806] opened by 192.168.x.xxx:50350
May 29 19:02:04 cambox rtsp-simple-server[21537]: 2021/05/29 19:02:04 I [0/1] [RTSP] [session 2036600912] is reading from path 'cam1', 2 tracks with UDP
May 29 19:02:04 cambox rtsp-simple-server[21537]: 2021/05/29 19:02:04 I [0/2] [RTSP] [session 1680903592] is reading from path 'cam4', 2 tracks with UDP
May 29 19:02:04 cambox rtsp-simple-server[21537]: 2021/05/29 19:02:04 I [0/3] [RTSP] [session 2311638656] is reading from path 'cam3', 2 tracks with UDP
May 29 19:02:04 cambox rtsp-simple-server[21537]: 2021/05/29 19:02:04 I [0/4] [RTSP] [session 3761458806] is reading from path 'cam2', 2 tracks with UDP
May 30 21:18:29 cambox rtsp-simple-server[21537]: 2021/05/30 21:18:29 I [0/4] [HLS] [conn 192.168.x.xx:32854] GET /cam1
May 30 21:18:29 cambox rtsp-simple-server[21537]: 2021/05/30 21:18:29 I [0/4] [HLS] [conn 192.168.x.xx:32854] GET /cam1/
May 30 21:18:29 cambox rtsp-simple-server[21537]: 2021/05/30 21:18:29 I [0/4] [HLS] [converter proxied1] opened
May 30 21:18:29 cambox rtsp-simple-server[21537]: panic: runtime error: invalid memory address or nil pointer dereference
May 30 21:18:29 cambox rtsp-simple-server[21537]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12098]
May 30 21:18:29 cambox rtsp-simple-server[21537]: goroutine 371 [running]:
May 30 21:18:29 cambox rtsp-simple-server[21537]: github.com/aler9/rtsp-simple-server/internal/hlsconverter.(*Converter).runRequestHandler(0x3f362a0, 0x3553640, 0x3553680)
May 30 21:18:29 cambox rtsp-simple-server[21537]:         /s/internal/hlsconverter/converter.go:538 +0x14c
May 30 21:18:29 cambox rtsp-simple-server[21537]: created by github.com/aler9/rtsp-simple-server/internal/hlsconverter.(*Converter).runInner
May 30 21:18:29 cambox rtsp-simple-server[21537]:         /s/internal/hlsconverter/converter.go:320 +0x62c
May 30 21:18:29 cambox systemd[1]: rtsp-simple-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 30 21:18:29 cambox systemd[1]: rtsp-simple-server.service: Failed with result 'exit-code'.

**Comment by gnubit-au** [comment]
I quickly fired up an rtsp-simple-server_v0.16.2_linux_amd64 (debian) and the server does not crash as either record or proxied, but I get lots of `unable to decode video track: first NALU does not contain the start bit` and `unable to decode video track: Packet is not FU-A` errors.

The stream is virtually unwatchable with lots of buffering and artifacts as a proxy, but as a record stream there is less buffering and artifacts.

It may be an arm7 issue ?

**Comment by aler9** [comment]
Ok, that's better. Regarding the latest issue, follow the development here: #374
