### ISSUE TITLE
publishing with gstreamer?

### ISSUE THREAD

**Issue by miesgre** [aler9/rtsp-simple-server#40]
Can I publish the stream using gstreamer instead of ffmpeg?

**Comment by JeffIPvideo** [comment]
Yes you can use gstreamer. Just set the location to where you configured
It is mentioned in the README

gst-launch-1.0 -v rtspsrc location=rtsp://localhost:8554/mystream ! rtph264depay ! decodebin ! autovideosink

**Comment by aler9** [comment]
I think that @miesgre meant publishing, not reading.
Unfortunately gstreamer doesn't provide yet a rtspsink element that allows publish, there's only a proprietary and very expensive addon
https://developer.ridgerun.com/wiki/index.php?title=GstRtspSink

**Comment by miesgre** [comment]
@aler9 Yes, I want to publish using gstreamer.

I discovered the `rtspclientsink` (https://gstreamer.freedesktop.org/documentation/rtspclientsink/plugin-index.html)

I tested it with:
```
gst-launch-1.0 videotestsrc ! queue ! x264enc ! rtspclientsink location=rtsp://localhost:8554/mystream
```

but the `rtsp-simple-server` logs an error:

```
2020/07/17 15:03:14 [0/0/0] rtsp-simple-server v0.9.1
2020/07/17 15:03:14 [0/0/0] [UDP/RTP listener] opened on :8000
2020/07/17 15:03:14 [0/0/0] [UDP/RTCP listener] opened on :8001
2020/07/17 15:03:14 [0/0/0] [TCP listener] opened on :8554
2020/07/17 15:03:24 [1/0/0] [client [::1]:41376] connected
2020/07/17 15:03:24 [1/0/0] [client [::1]:41376] OPTIONS
2020/07/17 15:03:24 [1/0/0] [client [::1]:41376] ANNOUNCE
2020/07/17 15:03:24 [1/0/0] [client [::1]:41376] SETUP
2020/07/17 15:03:24 [1/0/0] [client [::1]:41376] ERR: transport header does not contain mode=record
2020/07/17 15:03:24 [0/0/0] [client [::1]:41376] disconnected
```

there is something I'm doing wrong or the `rtspclientsink`is not able to stream to `rtsp-simple-server`?

**Comment by aler9** [comment]
@miesgre thanks for letting me know about this plugin, i need it too.
I'll add support for it as soon as possible.

**Comment by miesgre** [comment]
If I add the `debug=true` to the `rtsmpclientsink` I can view the rtsp calls and i found
```
Progress: (request) SETUP stream 0
RTSP request message 0x7ff488972d30
 request line:
   method: 'SETUP'
   uri:    'rtsp://localhost:8554/mystream/stream=0'
   version: '1.0'
 headers:
   key: 'User-Agent', value: 'GStreamer/1.14.5'
   key: 'Transport', value: 'RTP/AVP/UDP;unicast;client_port=49174-49175;mode=RECORD'
 body:
RTSP response message 0x7ff488972d90
 status line:
   code:   '400'
   reason: 'Bad Request'
   version: '1.0'
 headers:
   key: 'CSeq', value: '3'
 body: length 0
```

and i can view the `Transport Header` with `mode=RECORD`. maybe there is because the uppercase?

**Comment by aler9** [comment]
yes, that's probably the reason :)

**Comment by aler9** [comment]
publishing with gstreamer is now fully supported.
