### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by brothercorvo** [aler9/rtsp-simple-server#404]
We plan to integrate rtsp-simple-server as a video component for FreeTAKServer see https://freetakteam.github.io/FreeTAKServer-User-Docs/.
To do so we need an API that would allow to:
- Start/stop server
- get streams information (bradcaster, publisher)

in a more advanced scenario we would also need to create a stream .

**Comment by aler9** [comment]
Hello, this is already planned but a little long to implement; of course a PR is always welcome.

**Comment by aler9** [comment]
Configuration API is available in v0.17.0
