### ISSUE TITLE
RTSP to HLS - "Unable to decode video track: Packet is not FU-A"

### ISSUE THREAD

**Issue by t3therdev** [aler9/rtsp-simple-server#406]
## Which version are you using?

v0.16.2

## Which operating system are you using?

OS

- [ ] Linux
- [X] Windows
- [ ] macOS

## Describe the issue

Streaming RTSP to 16.2 simple server and pulling HLS , stream starts and then stop with errors in log:

2021/05/30 12:58:18 W [1/2] [HLS] [converter ch999] unable to decode video track: Packet is not FU-A

See log

## Describe how to replicate the issue

1. start the server
2. publish with RTSP 
3. read with HLS (example players, can only do http and not https)
For example this one:  http://stream-tester.jwplayer.com/

[hls_issues.log](https://github.com/aler9/rtsp-simple-server/files/6566583/hls_issues.log)

**Comment by aler9** [comment]
This error should be solved in newer releases, please try the latest one, and in case the error reappear, please post the log and a sample file that allows to replicate the issue.
