### ISSUE TITLE
HLS manifest incorrect target duration and #EXTINF values

### ISSUE THREAD

**Issue by dorinclisu** [aler9/rtsp-simple-server#418]
## Which version are you using?
v0.16.2

## Which operating system are you using?
OS
- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture
- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue
stream.m3u8:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:20
#EXTINF:10,
1623165674.ts
#EXTINF:10,
1623165687.ts
#EXTINF:10,
1623165699.ts
```

We can see that `EXT-X-TARGETDURATION` and `#EXTINF` are always 10, regardless of `hlsSegmentDuration` config setting (default 1s), while the timestamp of .ts files seems to respect hlsSegmentDuration.

This means that streaming behavior is correct only when setting `hlsSegmentDuration: 10s`, and in any other case the HLS player is incapable of smoothly playing the stream.

Moreover I have a suggestion after solving this bug, #EXTINF should probably be a float matching the actual duration of the segment, because it most likely cannot be an integer number of seconds due to the uncontrolled source framerate. I didn't notice anything wrong after the workaround but I expect that at some point the decimals will matter.

## Describe how to replicate the issue
Easily replicable, see above.

**Comment by aler9** [comment]
Hello, thanks for reporting the issue, now both fields are filled correctly.

**Comment by aler9** [comment]
added in v0.16.3
