### ISSUE TITLE
HLS crash on arm7

### ISSUE THREAD

**Issue by technicaldesign** [aler9/rtsp-simple-server#440]
## Which version are you using?

v0.16.3

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ ] amd64
- [ ] arm64
- [x] arm7
- [ ] arm6

## Describe the issue

When I try to open the HLS stream in Chromium on an AMD64 machine which is running OBS on Linux Mint 20.1 and publishing to a BeagleBone Black (TI Sitara arm7 32-bit, otherwise running the arm7 version perfectly) running RtspSimpleServer, using the http://xxx.xxx.xxx.xxx:8888/mystream address), I get this on the server side:

2021/07/02 14:20:05 I [1/0] [HLS] [conn 10.42.0.1:36890] GET /mystream/
2021/07/02 14:20:05 I [1/0] [HLS] [converter mystream] opened
2021/07/02 14:20:05 I [1/1] [HLS] [converter mystream] is converting into HLS
panic: unaligned 64-bit atomic operation

goroutine 53 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x1086874, 0x60df2095, 0x0)
	/usr/local/go/src/runtime/internal/atomic/asm_arm.s:278 +0x14
github.com/aler9/rtsp-simple-server/internal/hlsconverter.(*Converter).runRequestHandler(0x1086800, 0x1336480, 0x13364c0)
	/s/internal/hlsconverter/converter.go:557 +0x1d0
created by github.com/aler9/rtsp-simple-server/internal/hlsconverter.(*Converter).runInner
	/s/internal/hlsconverter/converter.go:322 +0x644
 
## Describe how to replicate the issue

1. Publish RTMP stream from AMD64 machine running OBS on Linux Mint 20.1 to arm7 server running Rtsp Simple Server on Debian Buster on the network at address rtmp://xxx.xxx.xxx.xxx;
2. open RTSP stream with VLC at rtsp://xxx.xxx.xxx.xxx/mystream on AMD64 machine to check everything is OK (and it is);
3. try to open http://xxx.xxx.xxx.xxx:8888/mystream in Chromium on the AMD64 machine  >>> RtspSimpleServer crashes 

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Thanks for reporting the crash, it is fixed in main and will be added to the next release.

**Comment by technicaldesign** [comment]
Awesome! Thank you for fixing.

**Comment by aler9** [comment]
added in v0.16.4
