### ISSUE TITLE
Illegal #EXTM3U formatting

### ISSUE THREAD

**Issue by dorinclisu** [aler9/rtsp-simple-server#448]
## Which version are you using?

v0.16.2 - v0.16.4

## Which operating system are you using?
OS
- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture
- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue
I just noticed that the #EXTINF lines are not compliant to the HLS spec, because they have trailing commas.
For example `#EXTINF:5,` instead of `#EXTINF:5`.

The hls.js player seems to ignore the commas and works just fine, but the Safari native player is not so tolerant and fails to play, and likely other hls players might also refuse to work.

I believe this can be easily fixed in `cnt += "#EXTINF:" + strconv.FormatFloat(f.Duration().Seconds(), 'f', -1, 64) + ",\n"`.

As a side issue, I also noticed that #EXT-X-TARGETDURATION is often smaller than the maximum #EXTINF, which is also illegal according to spec. I am not sure how this can affect the quality of the play, but ideally the segmenter should somehow finish the segment before its float duration exceeds the int duration of the target.

**Comment by aler9** [comment]
The comma is needed to separate duration and an optional title field and is present in the specification:

https://datatracker.ietf.org/doc/html/draft-pantos-http-live-streaming#section-4.3.2.1
https://developer.apple.com/documentation/http_live_streaming/enabling_low-latency_hls

> I also noticed that #EXT-X-TARGETDURATION is often smaller than the maximum #EXTINF

that's not possible, there's a specific code that ensures this condition

https://github.com/aler9/rtsp-simple-server/blob/d89d650739d322d339c370f0af2b9b3c2ebbc501/internal/hlsconverter/converter.go#L610-L622

**Comment by dorinclisu** [comment]
You are right about the comma, I mistakenly took it for the reason it doesn't play in Safari. Basically it should play directly from http://localhost:8888/test/stream.m3u8 and it doesn't. Unfortunately the developer console doesn't provide any reason why other than `Failed to load resource: Plug-in handled load` and a blank video player that is loading forever. Strange is that it makes the requests for the .ts files and also keeps requesting the manifest.

The problem with the target duration is unclear. Do you have a spec reference where it mentions the rounding? As far as I read, it said it must always be smaller, and for me 8.231 is not smaller than 8. But I saw many servers with segment durations of TARGET.00x and working perfectly.  But in our case the error is at the level of the first decimal point. 
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:32
#EXTINF:8.231,
1625489176.ts
#EXTINF:8.231,
1625489184.ts
#EXTINF:6.498,
1625489192.ts
```

**Comment by aler9** [comment]
> Do you have a spec reference where it mentions the rounding?

yes

https://datatracker.ietf.org/doc/html/draft-pantos-http-live-streaming#section-4.3.3.1

> The EXTINF duration of each Media Segment in the Playlist
> file, when rounded to the nearest integer, MUST be less than or equal
> to the target duration;
