### ISSUE TITLE
UDP timeout with Flir cameras, pcap available

### ISSUE THREAD

**Issue by eLvErDe** [aler9/rtsp-simple-server#449]
## Which version are you using?

Latest release from yesterday as well as old ones

## Which operating system are you using?

- [ X] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ X] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Flir camera ends up with "UDP timeout" while they are working perfectly fine with VLC, mplayer or Janus WebRTC gateway:

Jul  5 12:24:41 janus-test rtsp-simple-server[5477]: 2021/07/05 12:24:41 I [0/0] [path 10316] [rtsp source] started
Jul  5 12:24:41 janus-test rtsp-simple-server[5477]: 2021/07/05 12:24:41 I [0/0] [path 10316] [rtsp source] ready
Jul  5 12:24:41 janus-test rtsp-simple-server[5477]: 2021/07/05 12:24:41 I [0/0] [RTSP] [session 236878452] opened by 10.13.69.112:60642
Jul  5 12:24:41 janus-test rtsp-simple-server[5477]: 2021/07/05 12:24:41 I [0/1] [RTSP] [session 236878452] is reading from path '10316', 2 tracks with TCP
Jul  5 12:25:19 janus-test rtsp-simple-server[5477]: 2021/07/05 12:25:19 I [0/1] [path 10316] [rtsp source] ERR: UDP timeout
Jul  5 12:25:19 janus-test rtsp-simple-server[5477]: 2021/07/05 12:25:19 I [0/0] [RTSP] [conn 1.2.3.4:60642] closed
Jul  5 12:25:19 janus-test rtsp-simple-server[5477]: 2021/07/05 12:25:19 I [0/0] [RTSP] [session 236878452] closed
Jul  5 12:25:24 janus-test rtsp-simple-server[5477]: 2021/07/05 12:25:24 I [0/0] [path 10316] [rtsp source] ready

## Describe how to replicate the issue

Well sadly, that's going to be hard to replicate unless you're having a Flir camera. But I attached a dump and have a working sandbox 100% reproducible so feel free to ask me any test you need.

## Did you attach a network dump?

Pcap not attached but I'm sending it to you by email. It includes traffic from the server to the camera as well as from the server to the mplayer client.

Thanks in advance,

Best regards, Adam.

**Comment by aler9** [comment]
Hello, what's the value of `sourceProtocol`?

**Comment by eLvErDe** [comment]
Hello,

Unset

**Comment by sshaikh** [comment]
I was seeing a similar issue up to 0.16.4 but unable to reproduce since. I will update this issue with logs if it ever comes back

**Comment by eLvErDe** [comment]
Hello,

Interesting, was it flir devices too ?
I'll give latest release a try soon.

**Comment by sshaikh** [comment]
I should have elaborated - no not FLIR devices, but a cheapo chinese Ingenic device over WIFI. I'll explain how to reproduce in case you find it handy.

I use the following to capture keyframes from a variety of proxied sources:

`ffmpeg -y -hide_banner -skip_frame nokey -i rtsp://localhost:8554/proxy1 -vsync 0 -f image2 -update 1 keyframe.jpg`

The "direct" version is then:

`ffmpeg -y -hide_banner -skip_frame nokey -i rtsp://server:554/unicast -vsync 0 -f image2 -update 1 keyframe.jpg`

The direct command is always rock solid, whereas going via the proxy used to result in what looked like UDP timeout errors - the rtsp server sees a client disconnect and ffmpeg would quit as the proxy also shut down. 

Starting the ffmpeg command again works without needing to restart the proxy.

I was unable to reproduce with 0.16.4 (and 0.17.0), so this may not be the same issue as here (I'm not sure what versions were out on July 5th).

**Comment by sshaikh** [comment]
So eventually I do see the timeout:

```
2021/08/09 09:29:07 I [0/21] [path proxy] [rtsp source] ERR: dial tcp x.x.x.x:554: i/o timeout
```

Meanwhile on the RTSP server:
```
2021-08-09 09:28:54.147 (476784.785s) [main thread     ]       DeviceSource.cpp:118      0|V4L2DeviceSource::doStopGettingFrames
2021-08-09 09:28:54.147 (476784.786s) [main thread     ]       DeviceSource.cpp:118      0|V4L2DeviceSource::doStopGettingFrames
2021-08-09 09:28:54.148 (476784.786s) [main thread     ]       DeviceSource.cpp:118      0|V4L2DeviceSource::doStopGettingFrames
2021-08-09 09:29:12.374 (476803.013s) [main thread     ]ServerMediaSubsession.c:25       0|Creating Source...
2021-08-09 09:29:12.374 (476803.013s) [main thread     ]ServerMediaSubsession.c:33       0|Creating H264 Source...
2021-08-09 09:29:12.381 (476803.019s) [main thread     ]ServerMediaSubsession.c:25       0|Creating Source...
2021-08-09 09:29:12.382 (476803.020s) [main thread     ]ServerMediaSubsession.c:49       0|Creating normal Source...
```

Looks like a different problem to this one, so happy to create a new issue if required. IN the meantime, I see a new timeout parameter I'm happy to try.

**Comment by sshaikh** [comment]
Setting the timeout to 60s seems to have done the trick for me.

**Comment by eLvErDe** [comment]
Hello @aler9 

We tried again with latest release and the issue is still here.
I think we sent you a pcap dump by email, but this is definitely something we can do again if it can help.

Best regards, Adam.

**Comment by aler9** [comment]
@eLvErDe i saw the dump again, it contains an exchange between the camera and VLC.
Please generate another dump, this time by using the server instead of VLC.

**Comment by eLvErDe** [comment]
Sorry about that, I'll make a new one.
Do you need client to proxy too or proxy to camera is enough ?

**Comment by aler9** [comment]
only from proxy to camera

**Comment by eLvErDe** [comment]
Okay, I just made a new capture and sent it to your email address directly

**Comment by eLvErDe** [comment]
For the record, I tested the keepalive patched version you published on #702 but it does not help

**Comment by aler9** [comment]
> Okay, I just made a new capture and sent it to your email address directly

i didn't received anything

**Comment by eLvErDe** [comment]
Well that's really weird, I just re-send it now to your gmail address, got something ?

**Comment by aler9** [comment]
Hello @eLvErDe - i received and analyzed the dump. It seems that the server sends keepalive requests once every 30secs, while the camera requires keepalives to be sent within 20 secs:

```
RTSP/1.0 200 OK
CSeq: 4
Server: Siqura RTSPServer/1.0
Session: 851006239;timeout=20
Transport: RTP/AVP;unicast;client_port=32632-32633;server_port=5610-5611
Accept-Ranges: NPT
```

are you sure you tried with the nightly released attached in #702? i recompiled the server again, please try with this:

[rtsp-simple-server_v0.17.14-19-g9bc364f_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/7965981/rtsp-simple-server_v0.17.14-19-g9bc364f_windows_amd64.zip)
[rtsp-simple-server_v0.17.14-19-g9bc364f_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7965982/rtsp-simple-server_v0.17.14-19-g9bc364f_linux_armv7.tar.gz)
[rtsp-simple-server_v0.17.14-19-g9bc364f_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7965983/rtsp-simple-server_v0.17.14-19-g9bc364f_linux_armv6.tar.gz)
[rtsp-simple-server_v0.17.14-19-g9bc364f_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7965985/rtsp-simple-server_v0.17.14-19-g9bc364f_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.17.14-19-g9bc364f_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7965986/rtsp-simple-server_v0.17.14-19-g9bc364f_linux_amd64.tar.gz)
[rtsp-simple-server_v0.17.14-19-g9bc364f_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7965987/rtsp-simple-server_v0.17.14-19-g9bc364f_darwin_amd64.tar.gz)

**Comment by eLvErDe** [comment]
Well yeah I'm pretty sure I deployed version linked in #702 but I'll check again today by comparing checksum :D

I'll test the new version again on Monday, thanks !

**Comment by eLvErDe** [comment]
I think I understand what you mean, yes I deployed the new version and it's still failing, but ko, this dump is a resent from last year, before the new version. So maybe you corrected a first issue that unlocked another one hiding behind. Will do a new capture on monday

**Comment by eLvErDe** [comment]
Works with 0.17.15 thanks a lot :-)

**Comment by sshaikh** [comment]
I still see disconnects - should I open a new issue?
