### ISSUE TITLE
HLS not streaming

### ISSUE THREAD

**Issue by bottlehall** [aler9/rtsp-simple-server#461]
## Which version are you using?

v0.16.4 - precompiled binary for arm64v8 

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ ] amd64
- [x] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

First time using rtsp-simple-server, so it may be my lack of understanding.

Configured RTSP from the example in the documentation using a USB webcam attached to /dev/video0 on a raspberry pi running ubuntu 21.4 and it worked at the first attempt: browser opens up VLC and all is good.

```
 cam:
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -f rtsp rtsp://192.168.68.123:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
```

I actually want to embed the stream in a web page, so thought I should be able to use something like:

```html
<html>
    <head>
        <title>video tag test page</title>
    </head>
    <body>
         <video src="http://192.168.68.123:8888/cam">
            no video
        </video>
    </body>
</html>
```

However, this just gives a blank page in the browser and generates the errors below on the console:

```
2021/07/08 14:43:28 I [1/0] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:50263] GET /cam     
2021/07/08 14:43:28 I [1/0] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:50263] GET /cam/
2021/07/08 14:43:28 I [1/0] [HLS] [converter cam] opened
2021/07/08 14:43:28 I [1/0] [HLS] [converter cam] ERR: unable to find a video or audio track
2021/07/08 14:43:28 I [1/0] [HLS] [converter cam] closed
```

More than happy to believe I've missed something, but can't spot what it is!

**Comment by bottlehall** [comment]
I have made some progress. I've never so much as looked at go code before, but having looked at it, I wondered if it was looking for a track with h264 format, so I changed my configuration to:
```
  cam:
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -c:v libx264 -preset ultrafast -b:v 500k -max_muxing_queue_size 1024 -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnInitRestart: yes
  proxied:
    source: rtsp://localhost:8554/cam
```

This now makes a stable connection using HLS (and the RTSP continues to work as before), but the video is still not showing up in the browser. This is the log:
```  
2021/07/14 12:34:48 I [1/0] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:62483] GET /cam/    
2021/07/14 12:34:48 I [1/0] [HLS] [converter cam] opened
2021/07/14 12:34:48 I [1/1] [HLS] [converter cam] is converting into HLS
2021/07/14 12:38:26 I [1/0] [HLS] [converter cam] closedrate=N/A dup=12 drop=1 speed=   1x 
```
The session closes after exactly a minute consistently.

BTW,  using a better html video tag:
```html
<html>
<head>
  <title>video tag test page</title>
</head>
<body>
  <video width="320" height="240" controls>
      <source src="http://192.168.68.120:8888/cam/" type="video/mp4">
      no video
  </video>
</body>
```

It almost seems like the browser-client is not doing something now.

**Comment by bottlehall** [comment]
By chance, I tried accessing the HLS URI directly from my iPhone and noticed it was appending `stream.m3u8` to the path. Adding this explicitly in the above video tag (and changing the mime type to application/x-mpegurl) now shows that the html5 player is trying to download (i.e. the activity wheel is running continuously). There's still no video though and the link gets dropped after a minute.

**Comment by dmzlingyin** [comment]
I think that the streaming protocol you have published is rtsp, and the browser doesn't support it.

**Comment by bottlehall** [comment]
@dmzlingyin, thank you, but I am fairly sure it is attempting to do HLS. Yes, I am publishing RTSP on the original path and if I try to read it in a browser it opens up VLC. However, unless I've misunderstood the documentation, it automatically makes this stream available via HLS as well. The log messages appear to show it is using the HLS component of the server.

**Comment by dorinclisu** [comment]
You are not embedding the source correctly.
Fire up the browser developer tools and notice that `http://192.168.68.120:8888/cam/` actually serves a HTML page. Inspect the html code to see how the player works.
Te actual HLS stream source is at `http://192.168.68.120:8888/cam/stream.m3u8` but is not directly playable using the plain video tag except in Safari under certain circumstances. The example HTML page embedded in the server uses hls.js player.

**Comment by bottlehall** [comment]
@dorinclisu, thanks, but if you look back in my comment on 14 July, you will see I spotted my error, corrected it and it still doesn't work.

**Comment by dorinclisu** [comment]
Yeah that's why I said "certain circumstances" and actually I've looked into this very issue and couldn't yet figure out why the server manifest it doesn't work directly in Safari.

But anyway hls.js should definitely work regardless of browser choice.

**Comment by bottlehall** [comment]
@dorinclisu , I have got hls.js working, I think. There is one odd error on the java console saying it can't download a file from jsdelivr but it seems to download the main script. I have adapted the sample page on the hls.js home page:

```html
<html>
<head>
<title>hlsjs test page</title>
<script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
</head>
<body>
<video id="video"></video>
<script>
  if (Hls.isSupported()) {
    var video = document.getElementById('video');
    var hls = new Hls();
    // bind them together
    hls.attachMedia(video);
    hls.on(Hls.Events.MEDIA_ATTACHED, function () {
      console.log('video and hls.js are now bound together !');
      hls.loadSource('http://localhost:8888/cam/stream.m3u8');
      hls.on(Hls.Events.MANIFEST_PARSED, function (event, data) {
        console.log(
          'manifest loaded, found ' + data.levels.length + ' quality level'
        );
        video.play();
      });
    });
  }
</script>
</body>
```

This now gives more promising output on the server console:
```
2021/07/21 15:10:45 I [1/0] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51025] GET /cam/stream.m3u8
2021/07/21 15:10:45 I [1/0] [HLS] [converter cam] opened
2021/07/21 15:10:45 I [1/1] [HLS] [converter cam] is converting into HLS
2021/07/21 15:10:45 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51025] GET /cam/stream.m3u8
2021/07/21 15:10:45 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51025] GET /cam/1626876645.ts
2021/07/21 15:10:46 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51026] GET /cam/stream.m3u8
2021/07/21 15:10:47 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51026] GET /cam/stream.m3u8
2021/07/21 15:10:48 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51026] GET /cam/stream.m3u8
2021/07/21 15:10:50 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51026] GET /cam/stream.m3u8
2021/07/21 15:10:52 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51026] GET /cam/stream.m3u8
2021/07/21 15:10:54 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51026] GET /cam/stream.m3u8
2021/07/21 15:10:57 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51026] GET /cam/stream.m3u8
2021/07/21 15:11:00 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51025] GET /cam/stream.m3u8
2021/07/21 15:11:00 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51025] GET /cam/1626876659.ts
2021/07/21 15:11:04 I [1/1] [HLS] [conn [fe80::10e1:dbda:adff:c409%wlan0]:51026] GET /cam/stream.m3u8
```
I can't spot a pattern to the inclusion of the numeric .ts links. The javascript console in the browser shows:
```
video and hls.js are now bound together!
manifest loaded, found 1 quality level
```
After a minute or so, the following appears in the log, but there's no link to suggest where the error arises:
```
Unhandled Promise Rejection: AbortError: The operation was aborted.
``` 

And... you've guessed it, no video in the browser at any point!

**Comment by bottlehall** [comment]
Using hls.js does get me further in Chrome but no other browser. It loads and displays a still image, and continues to poll the server but doesn't use updated images.

**Comment by bottlehall** [comment]
No substantive help available on this issue, so I've tried nginx and got what I need working.
