### ISSUE TITLE
HLS video playback not working on many players

### ISSUE THREAD

**Issue by Adam1901** [aler9/rtsp-simple-server#466]
## Which version are you using?

v0.16.4

## Which operating system are you using?

OS

- [ ] Linux
- [X] Windows
- [X] macOS

Architecture

- [X] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Description playback is not streaming with any video player apart from hls.js, i've tried VideoJs & shaka-player.
I have tried on a mac and windows machine for playback and cannot get an output on the HLS feed.

## Describe how to replicate the issue

1. start the server with docker or running the code GO
2. publish stream with OBS (rtmp)
3. https://jsfiddle.net/tLe5u96h/
4. Player fails to display video

**Comment by bottlehall** [comment]
I have used your attempt and am getting the same outcome - see https://github.com/aler9/rtsp-simple-server/issues/461.

**Comment by aler9** [comment]
video.js is now supported in main (6ad638d).

**Comment by Adam1901** [comment]
I’ve not been able to test it yet, but thank you :)

**Comment by Adam1901** [comment]
Can confrim fully working with videoJs7

**Comment by aler9** [comment]
side note: shaka-player doesn't support HLS with TS segments, therefore it can't be used with rtsp-simple-server.
