### ISSUE TITLE
ERR: not all tracks have been setup

### ISSUE THREAD

**Issue by R4KE5H** [aler9/rtsp-simple-server#48]
## Which version are you using?

rtsp-simple-server v0.9.4

## Describe the problem

I could stream a mp4 video in vlc player but after getting connected i am receiving the error message "ERR: not all tracks have been setup" while running the  rtsp-simple-server.exe file.Any help!!

**Comment by mattheys** [comment]
I see you've closed this, what was the solution, as I'm getting the same error when trying to use TinyCam on Android.

**Comment by ACrazyConcept** [comment]
Same here. TinyCam in Android TV.

**Comment by aler9** [comment]
I'm gonna debug TinyCam in the next days.

**Comment by mattheys** [comment]
Thats great news, I think TinyCam only loads the video stream unless you select Audio as well (bandwidth savings?). Unfortunatly I didn't know how to do any wireshark tracing on TinyCam to record any logs.

**Comment by aler9** [comment]
The question is that most RTSP servers require clients to setup all tracks, i did not know that there were some clients that supported pulling single tracks, until now, so i can finally implement this.

**Comment by aler9** [comment]
This should have been fixed in v0.9.8.
Please try and let me know.
