### ISSUE TITLE
Allow publishing to UDP while reading from TCP

### ISSUE THREAD

**Issue by gluedots** [aler9/rtsp-simple-server#482]
## Describe the feature
Hello,
Would it be possible to split the `protocols` parameter into two: one for publishing and another for reading?

I would like to publish to UDP and read from TCP. 
While this works with the default config, it always attempts to read from UDP first before falling back to TCP:
```
publishing to path 'cam', 1 track with UDP
reading from path 'cam', 1 track with UDP
reading from path 'cam', 1 track with TCP
```
Setting `protocols: tcp` prevents publishing to UDP, but allows for default reading from TCP.
Setting `protocols: udp` allows publishing to UDP, but only allows reading from UDP.

**Comment by aler9** [comment]
Sorry but this is not technically possible for the moment; if i were you, i'd create two instances of rtsp-simple-server:

* one for the publishers, with protocols: udp
* one for the readers, with protocols: udp and configured to request streams to the publisher's instance by using `source: rtsp://publisher-server-ip:/...`
