### ISSUE TITLE
example on creating a stream does not work

### ISSUE THREAD

**Issue by tadam98** [aler9/rtsp-simple-server#484]
## Which version are you using?

v0.16.4

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

on ubuntu 18.04.05 LTS the official ffmpeg version is:
```
apt list -a ffmpeg
Listing... Done
ffmpeg/bionic-updates,bionic-security 7:3.4.8-0ubuntu0.2 amd64
```

`ffmpeg -re -stream_loop -1 -i file.mp4 -c copy -f rtsp rtsp://localhost:8554/mystream`
Does not loop it sends the file just **once**.
The same with the gstreamer example.

## Describe how to replicate the issue

Just play the example with mp4 file.

**Comment by aler9** [comment]
Hello, sorry but the FFmpeg command does loop the file, i've used it countless times.
Regarding Gstreamer, to loop a file you have to convert it to TS and use multifilesrc, as explained here #476

**Comment by tadam98** [comment]
Thanks. Could you kindly add a note to the read.me file at the gst example advising that (a) file has to be file.ts for looking and add the gst looping example ?

The server is great.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
