### ISSUE TITLE
Prometheus metrocs no longer generated with 0.17.0

### ISSUE THREAD

**Issue by sshaikh** [aler9/rtsp-simple-server#491]
## Which version are you using?

v0.17.0

## Which operating system are you using?

OS

- [x ] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Prometheus metrics no longer hosted using `metrics: true`

## Describe how to replicate the issue

1. start the server with `metrics: true` or `metrics: yes`
2. visit http://server:9998/metrics
3. receive unable to connect error via firefox, Prometheus reports `connection refused`

This worked up to 1.16.4, although even then all rtsp sources were listed as `idle`

**Comment by sshaikh** [comment]
Issue was change in default:

`metricsAddress: 127.0.0.1:9998`

adding `metricsAddress: 0.0.0.0:9998` fixes the issue for me.

**Comment by aler9** [comment]
yes, default IP address of metrics listener was changed to localhost for security purposes.
