### ISSUE TITLE
All streams seen as idle in metrics

### ISSUE THREAD

**Issue by sshaikh** [aler9/rtsp-simple-server#492]
## Which version are you using?

v0.17.0

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Metrics output always counts streams as idle, eg:

```
rtsp_clients{state="publishing"} 0 1628434566517
rtsp_clients{state="reading"} 24 1628434566517
rtsp_sources{type="rtsp",state="idle"} 8 1628434566517
rtsp_sources{type="rtsp",state="running"} 0 1628434566517
rtsp_sources{type="rtmp",state="idle"} 0 1628434566517
rtsp_sources{type="rtmp",state="running"} 0 1628434566517
```
In at least version 0.10.0, we would see `running` have value 8 instead.

## Describe how to replicate the issue

Activate metrics with `metrics: yes` and check http://localhost:9998/metrics for output.

**Comment by aler9** [comment]
metrics have been rewritten to provide more data. Tests have been added in order to make sure that returned data is correct.

**Comment by aler9** [comment]
added in v0.17.1. Metrics documentation is available in the README.

**Comment by sshaikh** [comment]
The new metrics are much more useful thank, although I may suggest renaming them to include your domain (eg `paths` looks ripe for a conflict).

Many thanks.
