### ISSUE TITLE
Feature Request: add option to control compression

### ISSUE THREAD

**Issue by givo** [aler9/rtsp-simple-server#5]
Hi,

Currently I'm using [rtspatt](https://github.com/Ullaakut/RTSPAllTheThings) as my RTSP server for testing purposes, and it's working pretty good. One of the things that I'm missing is an option to control the compression level. Out of the box the [rtspatt](https://github.com/Ullaakut/RTSPAllTheThings) compression level is a bit too much for my purposes, so I wish to have a simple RTSP server with an option to control the compression level.

Is it possible to add this option?

Thank you :)

**Comment by aler9** [comment]
Hello, thanks for your interest in this project.

An RTSP server can only propagate already-existing streams, that are left untouched with respect to the original source. It differs from a media server, which is a more complex software that usually performs both re-encoding (editing of the streams, that allows compression) and propagation.

Theferore, compression is not part of the RTSP protocol (nor it was part of rtspatt); if we want to be more specific, it is indeed part of the RTSP protocol, but it only covers the initial handshake, so i don't think this is what you're looking for.

To achieve compression you must use an external software, together with `rtsp-simple-server`, for instance `ffmpeg`, in this way:

1. start `rtsp-simple-server`:
```
./rtsp-simple-server
```

2. connect your source to `rtsp://localhost:8554/original`

3. link `rtsp://localhost:8554/original` to `ffmpeg`, then link `ffmpeg` to `rtsp://localhost:8554/compressed`:
```
ffmpeg -i rtsp://localhost:8554/original -c:v libx264 -preset ultrafast -tune zerolatency -b 600k -f rtsp rtsp://localhost:8554/compressed
```

now if you open `rtsp://localhost:8554/compressed` you'll see the compressed stream, while if you open `rtsp://localhost:8554/original` you'll see the original stream.

Hope this is what you're looking for. Bye
