### ISSUE TITLE
ERR: transport header does not have valid client ports ([RTP/AVP/UDP;unicast;client_port=0-0;mode=RECORD])

### ISSUE THREAD

**Issue by JustToan** [aler9/rtsp-simple-server#50]
## Which version are you using?

v0.9.4

## Describe the problem
Hi there, 
I'm using your rtsp-simple-server package. It's very great and helpful. I'm using good with ffmpeg. But ffmpeg uses a lot of CPU. So I switch to use gstreamer as a publish stream client. And I got this problem: 
ERR: transport header does not have valid client ports ([RTP/AVP/UDP;unicast;client_port=0-0;mode=RECORD])
Here is more details in my case. 
This is the log from server side: 

> 2020/08/01 04:24:41 [1/0/0] [client ] connected
> 2020/08/01 04:24:41 [0/0/0] [client ] disconnected
> 2020/08/01 04:33:53 [1/0/0] [client ] connected
> 2020/08/01 04:33:53 [1/0/0] [client ] OPTIONS
> 2020/08/01 04:33:54 [1/0/0] [client ] ANNOUNCE
> 2020/08/01 04:33:54 [1/0/0] [client ] SETUP
> 2020/08/01 04:33:54 [1/0/0] [client ] ERR: transport header does not have valid client ports ([RTP/AVP/UDP;unicast;client_port=0-0;mode=RECORD])
> 2020/08/01 04:33:54 [0/0/0] [client ] disconnected
> 2020/08/01 04:33:54 [1/0/0] [client ] connected
> 2020/08/01 04:33:54 [1/0/0] [client ] OPTIONS
> 2020/08/01 04:33:55 [0/0/0] [client ] disconnected
> 

With publish stream side, I run: gst-launch-1.0 imxv4l2src device=/dev/video0 ! "video/x-raw, width=1280, height=720, framerate=(fraction)30/1" ! rtspclientsink location=rtsp://192.168.1.5:8999/vnet/id-stream=1 sync=false
And this is the log: 

> ====== IMXV4L2SRC: 4.1.6 build on Jul 31 2020 16:13:16. ======
> Setting pipeline to PAUSED ...
> Pipeline is live and does not need PREROLL ...
> Progress: (open) Opening Stream
> Progress: (connect) Connecting to rtsp://192.168.1.5:8999/vnet/id-stream=1
> Progress: (open) Retrieving server options
> Progress: (open) Opened Stream
> Setting pipeline to PLAYING ...
> New clock: GstSystemClock
> Progress: (request) Sending RECORD request
> Progress: (record) Sending server stream info
> Progress: (request) SETUP stream 0
> ERROR: from element /GstPipeline:pipeline0/GstRTSPClientSink:rtspclientsink0: Could not write to resource.
> Additional debug info:
> ../../../gst-rtsp-server-1.8.1/gst/rtsp-sink/gstrtspclientsink.c(3952): gst_rtsp_client_sink_setup_streams (): /GstPipeline:pipeline0/GstRTSPClientSink:rtspclientsink0:
> Error (400): Bad Request
> Execution ended after 0:00:00.720799667
> Setting pipeline to PAUSED ...
> Setting pipeline to READY ...
> Setting pipeline to NULL ...
> Freeing pipeline ...
> 

Can I change client_port manually ? If not, what should I do now to fix this ? 
Again, I very like your package.

**Comment by aler9** [comment]
Hi, while i investigate the problem, try using the UDP protocol by changing the pipeline to
```
gst-launch-1.0 imxv4l2src device=/dev/video0 ! "video/x-raw, width=1280, height=720, framerate=(fraction)30/1" ! rtspclientsink location=rtsp://192.168.1.5:8999/mystream protocols=tcp sync=false
```

and let me know if it works.

**Comment by JustToan** [comment]
Thank you for your reply, I'm very appreciate that. I will try and reply
you as soon as possible.

**Comment by JustToan** [comment]
It's work like a charm. Thank you so much for your support and your product.
