### ISSUE TITLE
Version not populated correctly

### ISSUE THREAD

**Issue by andrew-d** [aler9/rtsp-simple-server#503]
## Which version are you using?

v0.17.1

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

The `Makefile` sets the link flag `main.version` [here](https://github.com/aler9/rtsp-simple-server/blob/v0.17.1/Makefile#L233), but the correct variable is `github.com/aler9/rtsp-simple-server/internal/core.version`, since it now lives [here](https://github.com/aler9/rtsp-simple-server/blob/v0.17.1/internal/core/core.go#L18) and is used [here](https://github.com/aler9/rtsp-simple-server/blob/v0.17.1/internal/core/core.go#L56-L59).

Discovered here: https://github.com/NixOS/nixpkgs/pull/133690

## Describe how to replicate the issue

Build the program, and run `./rtsp-simple-server --version`

**Comment by aler9** [comment]
Thanks, fixed

**Comment by aler9** [comment]
added in v0.17.2
