### ISSUE TITLE
Support external authentication servers

### ISSUE THREAD

**Issue by aler9** [aler9/rtsp-simple-server#517]
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/504

<div type='discussions-op-text'>

<sup>Originally posted by **swarup-e** August 16, 2021</sup>
I have a use case where I want to authenticate each read stream request by token (not just by using username and password). I want to send the request to authentication server and on authorization rtsp server should be able send streams. 

I have been using Nginx RTMP module so I am trying achieve same things with rtsp simple server. 

For example [nginx on play directive](https://github.com/arut/nginx-rtmp-module/wiki/Directives#on_play) allows redirect request to auth server and on 201 response it sends streams. 
</div>

**Comment by aler9** [comment]
JWT authentication

**Comment by aler9** [comment]
LDAP, Oauth

**Comment by aler9** [comment]
SASL

**Comment by aler9** [comment]
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/

**Comment by eLvErDe** [comment]
Would love to see this happening and will definitely sponsor it :-)

**Comment by aler9** [comment]
added in v0.17.12
