### ISSUE TITLE
REST API does not appear to be thread safe

### ISSUE THREAD

**Issue by tsightler** [aler9/rtsp-simple-server#542]
## Which version are you using?

v0.17.2

## Which operating system are you using?
OS

- [X] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [X] amd64
- [X] arm64
- [X] arm7
- [ ] arm6

## Describe the issue
First of all, let me just say thanks to you for this great project.  I had started down the path of using an RTSP library in Node to add streaming support to my project and then I found out about rtsp-simple-server and I believe it has saved me a significant amount of work implementing capabilities that are built in here.

One issue I did run into, I'm using the REST API to dynamically add paths for cameras during startup and it works well, however, because my project is in Javascript and the initial creation of objects uses async methods, if a user has more than a few cameras the API can get hit with quite a few calls that are nearly at the same instant.  I've found that if you do two or three calls at nearly the same instant you will sometimes see one of the paths being "created" and then immediately "destroyed" because it appears the configuration reload for one API call somehow interferes with the call in progress from another.  The more calls made concurrently the more likely the problem is to occur.

For now I've worked around the issue on by moving the path creation logic to a synchronous function and adding a 100ms delay between API calls (perhaps could be significantly less, I haven't tried to see how low it could go, my guess is probably just a few ms is enough).  After that, path creation works 100% of the time.

## Describe how to replicate the issue

Just try to create 3-5 paths via the API at nearly the same instant, I can whip up some sample Javascript if you really need it, but the problem is pretty easy to reproduce although it was a little hard to troubleshoot as it exhibited as just random paths being not available for some users, but looking at the logs the issue was clear.

**Comment by aler9** [comment]
Thanks for the issue, i've found a way to replicate and a fix is coming soon.

```
for i in $(seq 1 50); do (curl -d '{}' http://localhost:9997/v1/config/paths/add/testing$i &); done
```

**Comment by aler9** [comment]
This is fixed in main and will be added to the next release.

**Comment by aler9** [comment]
added in v0.16.3

**Comment by tsightler** [comment]
Thanks a lot for addressing this so quickly and thanks again for this excellent project, really made including live video in my project possible, something that users had been asking me to do for ages but I just wasn't excited about implementing this directly in Node or by spawning a bunch of ffmpeg processes or whatever other hackish method I came up with.  Now I just spawn an rtsp-simple-server process and use the API to configure and control it from node and it works perfectly!  Really great project!
