### ISSUE TITLE
ERR: unexpected packet: 4 when receiving RTMP stream

### ISSUE THREAD

**Issue by wizenink** [aler9/rtsp-simple-server#577]
When I push an RTMP Stream generated by a panasonic P2HD camera, RTSPSS closes the connection with the error "ERR: unexpected packet: 4".
I can receive the stream with an ffmpeg acting as a listener without a problem.
Checking the generated stream, it seems like some extra metadata is generated, and that can't be parsed by RTSPSS.

If i show packets with ffprobe, I can see the extra metadata that is probably causing the issue.
Attached are a pcap capture of the stream, and the ffprobe packet output (show_packets)

[probe.log](https://github.com/aler9/rtsp-simple-server/files/7191995/probe.log)

[rtmp_panasonic.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7191990/rtmp_panasonic.tar.gz)

**Comment by aler9** [comment]
Thanks for providing data needed to replicate the issue, this is fixed in main and will be added to the next release.

**Comment by aler9** [comment]
added in v0.17.4
