### ISSUE TITLE
Stream aliases

### ISSUE THREAD

**Issue by sshaikh** [aler9/rtsp-simple-server#59]
## Which version are you using?

v0.9.10

## Describe the problem

It might be useful to provide alternative paths for the same stream, without creating a new entry in the config (depending on the implementation this may save some memory/cpu too).

**Comment by aler9** [comment]
Hello, there is a pending PR that implements wildcard paths; i'm waiting for the author to do some changes, otherwise after a while i'll implement the feature myself.

**Comment by aler9** [comment]
Paths with regular expressions have been implemented into master; this does not allow stream aliases but allows to share a configuration between two paths.

**Comment by sshaikh** [comment]
Good enough! The main concern was to not duplicate the processing on the backend so regexps work.

**Comment by aler9** [comment]
added in v0.10.0
