### ISSUE TITLE
panic: runtime error: slice bounds out of range [:4] with capacity 0

### ISSUE THREAD

**Issue by zhangzj03** [aler9/rtsp-simple-server#590]
## Which version are you using?

v0.17.3

## Which operating system are you using?

OS

- [X] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [X] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Description
[root@e90c2c3f7117 howtoRtspSimpleServer]# ./rtsp-simple-server
2021/09/26 07:53:37 I [0/0] rtsp-simple-server v0.17.3
2021/09/26 07:53:37 I [0/0] [RTSP] UDP/RTP listener opened on :8000
2021/09/26 07:53:37 I [0/0] [RTSP] UDP/RTCP listener opened on :8001
2021/09/26 07:53:37 I [0/0] [RTSP] TCP listener opened on :8554
2021/09/26 07:53:37 I [0/0] [RTMP] listener opened on :1935
2021/09/26 07:53:37 I [0/0] [HLS] listener opened on :8888
2021/09/26 07:53:49 I [0/0] [RTMP] [conn 172.17.0.2:47802] opened
panic: runtime error: slice bounds out of range [:4] with capacity 0

goroutine 27 [running]:
github.com/aler9/gortsplib.NewTrackH264(0xaef960, 0xc000325838, 0x0, 0x1074040, 0x0)
	/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20210825171651-d744a2e0d3c4/track.go:147 +0x59d
github.com/aler9/rtsp-simple-server/internal/rtmp.(*Conn).ReadMetadata(0xc0000be018, 0xc04c27a5ec7a2264, 0x51266a321, 0x1042f40, 0x0)
	/s/internal/rtmp/metadata.go:135 +0x6e5
github.com/aler9/rtsp-simple-server/internal/core.(*rtmpConn).runPublish(0xc00063a0c0, 0xcaba38, 0xc00029f1c0, 0x0, 0x0)
	/s/internal/core/rtmp_conn.go:412 +0xc9
github.com/aler9/rtsp-simple-server/internal/core.(*rtmpConn).runInner(0xc00063a0c0, 0xcaba38, 0xc00029f1c0, 0x0, 0x0)
	/s/internal/core/rtmp_conn.go:195 +0x191
github.com/aler9/rtsp-simple-server/internal/core.(*rtmpConn).run.func1(0xc000094180, 0xc00063a0c0, 0xcaba38, 0xc00029f1c0)
	/s/internal/core/rtmp_conn.go:160 +0x3f
created by github.com/aler9/rtsp-simple-server/internal/core.(*rtmpConn).run
	/s/internal/core/rtmp_conn.go:159 +0x18b

## Describe how to replicate the issue

1. start the server
 ./rtsp-simple-server
2. publish with ...
send 1280x720 h264 nal stream  
3. read with ...
ffmpeg -i rtmp://172.17.0.2/live/h264flv -c copy haha33.flv

but when i  scale the frame size from 1280x720 to 512x288, it's ok

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Thanks for reporting the issue, the crash is now fixed in main, anyway your stream contains a H264 track with an invalid SPS, that can't be decoded.

**Comment by aler9** [comment]
added in v0.17.4
