### ISSUE TITLE
ipv6 break

### ISSUE THREAD

**Issue by midicase** [aler9/rtsp-simple-server#6]
Thanks for this software.  I've been trying it out for a couple days with great success.   

Sometimes when I connect using zeroconf, ipv6 is used to establish a connection but fails to stream:

 rtsp-simple-server --rtsp-port=554
2020/05/01 05:34:40 rtsp-simple-server v0.5.3
2020/05/01 05:34:40 [UDP/RTP listener] opened on :8000
2020/05/01 05:34:40 [UDP/RTCP listener] opened on :8001
2020/05/01 05:34:40 [TCP listener] opened on :554
2020/05/01 05:35:07 [RTSP client 127.0.0.1:53242] connected
2020/05/01 05:35:07 [RTSP client 127.0.0.1:53242] OPTIONS
2020/05/01 05:35:07 [RTSP client 127.0.0.1:53242] ANNOUNCE
2020/05/01 05:35:07 [RTSP client 127.0.0.1:53242] SETUP
2020/05/01 05:35:07 [RTSP client 127.0.0.1:53242] RECORD
2020/05/01 05:35:07 [RTSP client 127.0.0.1:53242] is publishing on path 'mystream', 1 track via udp
2020/05/01 05:35:55 [RTSP client [fe80::dc4b:a4c9:f63e:e05b%!e(MISSING)th0]:34088] connected
2020/05/01 05:35:55 [RTSP client [fe80::dc4b:a4c9:f63e:e05b%!e(MISSING)th0]:34088] OPTIONS
2020/05/01 05:35:55 [RTSP client [fe80::dc4b:a4c9:f63e:e05b%!e(MISSING)th0]:34088] DESCRIBE
2020/05/01 05:35:55 [RTSP client [fe80::dc4b:a4c9:f63e:e05b%!e(MISSING)th0]:34088] SETUP
2020/05/01 05:35:55 [RTSP client [fe80::dc4b:a4c9:f63e:e05b%!e(MISSING)th0]:34088] PLAY
2020/05/01 05:35:55 [RTSP client [fe80::dc4b:a4c9:f63e:e05b%!e(string=mystream)th0]:34088] is receiving on path '%!s(int=1)', %!d(string=track) udp via %!s(MISSING)
2020/05/01 05:36:05 [RTSP client [fe80::dc4b:a4c9:f63e:e05b%!e(MISSING)th0]:34088] PAUSE
2020/05/01 05:36:05 [RTSP client [fe80::dc4b:a4c9:f63e:e05b%!e(MISSING)th0]:34088] paused
2020/05/01 05:36:05 [RTSP client [fe80::dc4b:a4c9:f63e:e05b%!e(MISSING)th0]:34088] SETUP
2020/05/01 05:36:05 [RTSP client [fe80::dc4b:a4c9:f63e:e05b&{%!e(string=client want to send tracks with different protocols)}th0]:34088] ERR: %!s(MISSING)
2020/05/01 05:36:05 [RTSP client [fe80::dc4b:a4c9:f63e:e05b%!e(MISSING)th0]:34088] disconnected

Not familiar with Go, else I'd do a PR.  
Consider adding an optional address to the port argument:
--rtsp-port=[ADDRESS:]PORT

This could allow binding to ipv4 only and force use a specific interface in multi-homed systems.  
"0.0.0.0" would binding to all ipv4 interfaces but no ipv6.

Thanks

**Comment by aler9** [comment]
Hi, thanks for the report, i think this issue is caused by multiple bugs, so i'll try to address them one by one.

The first bug is caused by the ipv6 link-local address:
```
fe80::dc4b:a4c9:f63e:e05b%eth0
```

i never used ipv6 link-local addresses (in fact i usually disable ipv6 in the kernel to avoid security issues), so i had to gather some informations, and i must say that the zeroconf feature is quite handy. The problem was that the address above was inserted into the first argument of a `printf()`, so the % was causing problems.

This (first) bug is fixed in v0.5.4, please try again and let me know.

**Comment by aler9** [comment]
Hi, this should be definitively fixed in v0.5.5. The zone field of the ipv6 link-local address (i.e. the interface name) is now propagated correctly to all the components.
Please let me know if it worked for you too.

**Comment by midicase** [comment]
5.5 fixed it, thanks!
