### ISSUE TITLE
[tcp @ 0x55a5837aa0] Connection to tcp://127.0.0.1:8080?timeout=0 failed: Connection refused

### ISSUE THREAD

**Issue by seabass1217** [aler9/rtsp-simple-server#605]
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/604

<div type='discussions-op-text'>

<sup>Originally posted by **seabass1217** September 30, 2021</sup>
Hi,
I'm new to video streaming and I trying to implement rtsp-simple-sever to publish object detection results to a rstp server running on a jetson Ubuntu 18.04.

The  python script is attached:
[results_rtsp.txt](https://github.com/aler9/rtsp-simple-server/files/7263965/results_rtsp.txt)
:

When I run the script I receive the following output

![Screenshot from 2021-09-30 23-40-53](https://user-images.githubusercontent.com/86954802/135562015-b0407222-491d-4aa3-bd50-03266e852f6a.png)
:
Any help is greatly appreciated
Thanks</div>

**Comment by m44soroush** [comment]
I have the same issue, any help?

**Comment by strickinato** [comment]
I'm also running into this issue :( 

The relevant part of my `rtsp-simple-server.yml` looks like:

```yml
# Made no other changes to the document
paths:
  cam:
    runOnInit: ffmpeg -f v4l2 -i /dev/video0 -c:v libx264 -preset ultrafast -tune zerolatency -b:v 600k -f rtsp rtsp://127.0.0.1:8544/cam
    runOnInitRestart: yes
```

The error I'm getting is:
```
Dec 18 23:47:40 music-strick rtsp-simple-server[1988]: [tcp @ 0x1fa1e10] Connection to tcp://127.0.0.1:8544?timeout=0 failed: Connection refused
Dec 18 23:47:40 music-strick rtsp-simple-server[1988]: Could not write header for output file #0 (incorrect codec parameters ?): Connection refused
Dec 18 23:47:40 music-strick rtsp-simple-server[1988]: Error initializing output stream 0:0 --
Dec 18 23:47:40 music-strick rtsp-simple-server[1988]: [libx264 @ 0x1e527c0] final ratefactor: 28.13
Dec 18 23:47:40 music-strick rtsp-simple-server[1988]: Conversion failed!
```

The strange bit is even when I don't run this as a service `rtsp-simple-server`, I'm able to connect with 127.0.0.1:8544

Running: `echo testing | nc 127.0.0.1 8554` I see the following in the logs:

```
2021/12/18 23:51:24 INF [RTSP] [conn 127.0.0.1:37220] opened
```

**Comment by aler9** [comment]
```
Connection to tcp://127.0.0.1:8544?
```

You've mispelled the port, that is 8544...

**Comment by strickinato** [comment]
🤦 omg. 😭 -- i can't believe it. A typo!! You're absolutely right lol. That totally fixed it.

Thank you so much. (Also, in browsing some other issues, you're generally so helpful!! So thank's so much!!).
