### ISSUE TITLE
Rename Prometheus metrics

### ISSUE THREAD

**Issue by sshaikh** [aler9/rtsp-simple-server#61]
## Which version are you using?

v0.9.11

## Describe the problem

Metrics are currently published as:

clients 
publishers 
readers 

ie with no global qualifier. My suggestion is to rename them to:

rtsp-simple-server_client_count
rtsp-simple-server_publisher_count
rtsp-simple-server_reader_count

(note the singular nouns)

**Comment by sshaikh** [comment]
Perhaps as an extension to this, add documentation to describe what the metrics mean. For example in:

```
clients 23 1596122687740
publishers 15 1596122687740
readers 8 1596122687740
```

What is a client, publisher and reader?

**Comment by aler9** [comment]
1. i'll add documentation
2. the [prometheus guidelines](https://prometheus.io/docs/practices/naming/) aren't much clear about metric prefixes, but they recommend to use single words, so i'd use `rtsp_`
2. metrics can be renamed in this way
    * `rtsp_clients{state="idle"}` - clients that aren't doing anything
    * `rtsp_clients{state="publishing"}` clients that are publishing
    * `rtsp_clients{state="reading"}` clients that are reading
2. two new metrics can be added:
    * `rtsp_sources{active="yes"}` - active sources
    * `rtsp_sources{active="no"}` - non-active sources (when onDemand is on and no one is pulling)

**Comment by sshaikh** [comment]
These sound great, and the labels are good. Thanks for looking!

**Comment by aler9** [comment]
added in v0.10.0
