### ISSUE TITLE
Error when setting RTSP_PROTOCOLS

### ISSUE THREAD

**Issue by anlexmatos** [aler9/rtsp-simple-server#612]
Running in Docker, I'm getting the following error message:

`ERR: RTSP_PROTOCOLS: json: cannot unmarshal string into Go value of type []string`

**Comment by edwardnguyen1705** [comment]
I have the same issue. If someone knows please give a hint.

**Comment by aler9** [comment]
fixed in v0.17.5

**Comment by djsamlb** [comment]
Still getting the same error with v.0.17.5

**Comment by aler9** [comment]
@djsamlb clear the docker image cache and the error will disappear:

```
docker image prune -a -f
docker pull aler9/rtsp-simple-server
```

**Comment by pcwii** [comment]
I think I am having the same issue.
I tried pruning the image and also tried the latest tag. Also using portainer.
Continuously getting this error in my docker log.
```
ERR: json: cannot unmarshal bool into Go struct field Conf.encryption of type string
```
