### ISSUE TITLE
RunOnDemand (and RunOnInit) don't work in the docker version

### ISSUE THREAD

**Issue by rmwiseman** [aler9/rtsp-simple-server#621]
## Which version are you using?

v0.17.3

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

It appears that, in the docker version, commands don't run on init or on demand because, I think, the executable doesn't exist in the docker image/container.

## Describe how to replicate the issue

1. configure a path to run on demand using `runOnDemand: ffmpeg ...(whatever)...`
2. start the server
3. connect to the path with e.g. VLC
4. server says `on demand command started` for the path, but no `ffmpeg` actually runs
5. client (VLC) stops with an error, and server reports a bad request (400) and, it seems, complains that the path must end with a slash

The same sequence works fine on the non-docker version.  I did try to connect to a shell in the container, but there don't seem to be any shells (e.g. bash or even sh) to use; I also tried to run `ffmpeg` to get its version (i.e. `docker exec -it <container name> ffmpeg -version`), but that failed too (`OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "ffmpeg": executable file not found in $PATH: unknown`).

In the docker version, the same problem happens if I use `runOnInit` instead of `runOnDemand`.

## Did you attach a network dump?

no

**Comment by udatny** [comment]
https://github.com/aler9/rtsp-simple-server/issues/183

**Comment by aler9** [comment]
This is as intended, the Docker image doesn't contain FFmpeg for legal reasons and for performance reasons (it is as smallest as possible). I've added a note to the README that explains how to build a Docker image that contains both:

https://github.com/aler9/rtsp-simple-server#docker
