### ISSUE TITLE
Incorrect rpttime triggering ffmpeg 13h14m dts rollover

### ISSUE THREAD

**Issue by Vrazzer** [aler9/rtsp-simple-server#622]
## Which version are you using?

v0.17.3 & v0.17.5

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [ ] amd64
- [ ] arm64
- [x] arm7
- [ ] arm6

## Describe the issue

When an RTSP client connects to an rtsp-simple-server instance that is being sourced from another RTSP stream, the timestamp in the rtp-info packet is often incorrect. It contains a timestamp "in the future" relative to the first frame the client will receive. (Looks like a calculation or timebase conversion error as the timestamp does not correspond to any actual frame.) Regardless of the cause, a future referencing rtptime in the rpt-info packet causes an ffmpeg client to calculate the first frames timestamp as negative that in turn enables some rather dubious "rollover prevention code" (see update_wrap_reference in ffmpeg demux.c) that causes a rollover at 13h15.3m-1m that can lead to a disconnected client and/or other issues.

## Describe how to replicate the issue

I am sending a live feed from a Raspberry Pi configured as a network camera to some DVR software (Channels DVR).
1: Run rtsp-simple-server in the background
2: Source video: ./ffmpeg-static -f v4l2 -input_format h264 -video_size 1280x720 -i /dev/video0 -c:v copy -f rtsp rtsp://localhost:8554/stream
3: Connect client: ./ffmpeg -nostats -fflags discardcorrupt -probesize 8000000 -i rtsp://192.168.1.22:8554/stream -enc_time_base -1 -max_muxing_queue_size 4096 -muxdelay 0 -ignore_unknown -map 0:v:0? -map 0:a? -map 0:s? -c:v copy -c:a copy -c:s copy -f mpegts -y /dev/null 2>&1
4: Wait ~13.25 hours and the ffmpeg client wills start spewing "Non-monotonous DTS in output stream" errors.

Did not attach a network dump as the there are two different streams involved-- the RTSP control stream and the UDP RTP packet stream. Not sure I could get both synchronized to easily show this. I built ffmpeg from source and added diagnostic code to dump the timestamps at key points to debug the issue. Below is sample annotated output showing the issue:
```
sdp: v='0'
sdp: o='- 0 0 IN IP4 127.0.0.1'
sdp: s='Stream'
sdp: c='IN IP4 0.0.0.0'
sdp: t='0 0'
sdp: m='video 0 RTP/AVP 96'
sdp: a='rtpmap:96 H264/90000'
sdp: a='fmtp:96 packetization-mode=1; sprop-parameter-sets=J2QAKKwrQCgC3QDxImo=,KO4CXLAA; profile-level-id=640028'
sdp: a='control:trackID=0'
**Below is reception of the rtp-info packet containing the incorrect timestamp**
rtppri: url=rtsp://192.168.1.22:8554/stream/trackID=0;seq=26273;rtptime=899435726
**Below is the ffmpeg parsed fields-- 899435726 becomes the base-timestamp**
rtpinf: base=0 time=899435726 ctl_url=rtsp://192.168.1.22:8554/stream/trackID=0 url=rtsp://192.168.1.22:8554/stream/trackID=0
**The first video frame is received. Note the timestamp predates rtptime**
rtpde0: pkt_pts:NOPTS time=899433786 s->time=0 s->base=899435726 s->unwrap=0 s->start=0
**The ffmpeg rtp decoder calculates the negative timestamp**
rtpdec: pkt_pts:-1940 time=899433786 s->time=899433786 s->base=899435726 s->unwrap=899433786 s->start=0
**The wraparound detector is now incorrectly enabled-- 4289565356 is 13h15m-1m.**
upwrap0: old_how=0 new_how=-1 old_ref=NOPTS new_ref=4289565356 tmp_ref=4294965356
rdpkt0: pkt_pts:-1940 pkt_dst:NOPTS wrap_how:-1 wrap_ref:4289565356 wrap_bits:32
**The next video frame is received. It has a future timestamp compared to rtp-info/rtptime.**
rtpde0: pkt_pts:NOPTS time=899442785 s->time=899433786 s->base=899435726 s->unwrap=899433786 s->start=0
rtpdec: pkt_pts:7059 time=899442785 s->time=899442785 s->base=899435726 s->unwrap=899442785 s->start=0```
**Wait 13.25 hours and then the rollover prevention code creates a rollover**
```
ffmpeg sets the "base_timestamp" from either rtp-info/rpttime or from the first frame (if no rpttime received). In the latter case, the base_timestamp and first-frame timestamp match and the offset is guaranteed to be zero. As my own temporary fix and confirmation of my diagnosis, I modified the executable and changed rtptime= to rtqtime= to prevent ffmpeg from parsing it. With that hack, I have run 30+ hours without issues. Below is ffmpeg output using the hack: 
```
sdp: v='0'
sdp: o='- 0 0 IN IP4 127.0.0.1'
sdp: s='Stream'
sdp: c='IN IP4 0.0.0.0'
sdp: t='0 0'
sdp: m='video 0 RTP/AVP 96'
sdp: a='rtpmap:96 H264/90000'
sdp: a='fmtp:96 packetization-mode=1; sprop-parameter-sets=J2QAKKwrQCgC3QDxImo=,KO4CXLAA; profile-level-id=640028'
sdp: a='control:trackID=0'
**Below shows rpttime= has been changed to rtqtime=**
rtppri: url=rtsp://192.168.1.22:8554/stream/trackID=0;seq=2665;rtqtime=2012285198
**The rtpinf: line is missing because rpttime could not be parsed**
rtpde0: pkt_pts:NOPTS time=2012205597 s->time=0 s->base=0 s->unwrap=0 s->start=0
**The frame0 timestamp is saved as the base and the first pts is zero**
rtpdec: pkt_pts:0 time=2012205597 s->time=2012205597 s->base=2012205597 s->unwrap=2012205597 s->start=0
**The rollover schedules at negative 1m (scaled) which apparently disables it**
upwrap0: old_how=0 new_how=1 old_ref=NOPTS new_ref=-5400000 tmp_ref=0
rtpde0: pkt_pts:NOPTS time=2012205597 s->time=2012205597 s->base=2012205597 s->unwrap=2012205597 s->start=0
rtpdec: pkt_pts:0 time=2012205597 s->time=2012205597 s->base=2012205597 s->unwrap=2012205597 s->start=0
```
Passing "-correct_ts_overflow 0" to the ffmpeg consumer might be another workaround, but I don't control the consumer and that would just mask the issue. Even though much of this is caused by ffmpeg, rtsp-simple-server should never send a future timestamp relative to the first frame. It has the potential to cause too many problems for individual clients.

Hope this helps you resolve the issue. The self-contained binary downloadable aspect of rtsp-simpler-server makes it a good fit for pi-camera style applications. Appreciate your efforts.

**Comment by aler9** [comment]
Hello, thanks for the detailed explanation. At the moment, RTP-Info's rtptime is computed by taking the RTP time of the last packet and by adding to it the amount of time passed since the reception of the last packet:

https://github.com/aler9/gortsplib/blob/c084f1b0f3b7fd5af833140ba341d4b08b99fe32/serverstream.go#L98

This is surely error prone, since:

* the clock of the machine that is running rtsp-simple-server could be slightly faster than the one that is generating the stream
* PTS can be non-monotonically increasing (unfortunately rtptime is PTS, not DTS)
* there could be truncation errors since it's a uint32

Therefore, we have to think another algorithm.

**Comment by Vrazzer** [comment]
Appreciate the prompt reply and explanation of the underlying calculation. Since you are using last-packet plus elapsed time, wonder if you could just suppress sending last-packet as it has served its purpose by providing a timestamp for the rtptime calculation. The subsequent packet timestamp will be >= rtptime and guessing that will also sidestep the issue.

There is no easy way for me to directly test this from the ffmpeg side-- once a packet is received, discarding without side-effects is difficult. However, I could take a shot at modifying the incoming timestamp to be greater than starting rtptime to see how ffmpeg behaves.

> PTS can be non-monotonically increasing

It can, but I think the potential of negative PTS (that ultimately translates to DTS) may be related to joining live streams in progress. When viewing a stream from the beginning, the first frame must be an IDR or equivalent. No subsequent frame can go backwards from that point. Likewise, I assume (maybe incorrectly) that the PTS for each GOP starting frame increases relative to the prior GOP-starting frame, though PTS may go forward/backwards within each GOP.

Live joining and indeed much of the ffmpeg timestamp handling seems to happen

**Comment by Vrazzer** [comment]
Forcing the frame 0 timestamp beyond rtp-info/rtptime appears to make the ffmpeg wrap-correction code happy (sets it to a negative wraparound similar to the matching case). Unfortunately, I cannot perform the full 13 hour test since I cannot modify the actual ffmpeg client pulling my stream.

For my purposes, will stick with the hacked rtsp-simple-server w/o rtptime as need these cameras running reliably 24x7. Thanks.

**Comment by aler9** [comment]
> When viewing a stream from the beginning, the first frame must be an IDR or equivalent

At the moment, the server doesn't check whether the first frame sent to a reader is a IDR or not (at least in case of RTSP, while it does in case of RTMP and HLS).

Anyway, the algorithm must be changed, the problem is doing it by taking into consideration all supported codecs (H264, H264, VP8, VP9, etc).

**Comment by Bod1985** [comment]
I am experiencing this despite passing "-correct_ts_overflow 0" and modifying the executable is a bit more than I’m wanting to do.

Any suggestions how I can manage this until the algorithm is changed?

**Comment by aler9** [comment]
In version 0.18.0, the RTP-Info timestamp is updated only if current frame is a IDR frame. All IDR frames have PTS = PTS. This should prevents RTP-Info from having a timestamp greater than the one of the following RTP packet, and should fix the problem. Please reopen the issue if the new version doesn't work.

**Comment by ajkq** [comment]
I successfully ran multiple streams on version v0.17.17 for several days with `-correct_ts_overflow 0`.

After upgrading to v0.18.0, I removed that option.

FFmpeg instances processing video only (-allowed_media_types video) stalled at approx. 13h:13m (out_time_ms from -progress stopped changing), spamming the log with the following lines.

```
[verbose] *** dropping frame 856737 from stream 0 at ts 4270400
```

These instances decode the video on the GPU (nvenc or vaapi) and output rawvideo to v4l2 loopback.
The sources for these instances are three different IP cameras.

Another instance, which processes both audio and video, kept on running but spammed the log with the following lines:

```
[warning] DTS 5127706578, next:294457848156 st:1 invalid dropping
[warning] PTS 5127706578, next:294457848156 invalid dropping st:1
```

The source for this instance is an Axis Q1635.
This instance decodes the video on the GPU, runs filters, uploads/encodes on the GPU, and outputs mpegts.

After adding the option `-correct_ts_overflow 0` again, streams are running for 27h so far.

**Comment by aler9** [comment]
What was done was making sure that  rtpinfo's timestamp is less or equal to the first packet's timestamp, like the author suggested. Regarding the 13:13h issue, please contact the ffmpeg team.

**Comment by ajkq** [comment]
The issue doesn't happen when using the camera streams directly with ffmpeg, hence I thought to report it here.
It also didn't happen with older versions of rtsp-simple-server. I can't recall the version, probably v0.16.x

**Comment by aler9** [comment]
@ajkq open another issue and provide required data.

**Comment by aler9** [comment]
Problem still persist despite the work and is being tracked here #922
