### ISSUE TITLE
getting wrong types / signatures in generated java client

### ISSUE THREAD

**Issue by udatny** [aler9/rtsp-simple-server#626]
## Which version are you using?
latest docker version / v0.17.3

## Which operating system are you using?
any

Architecture
any

Description
getting wrong types / signature in api in generated java client / api

since openapi generator code generator does not support openapi 3.0 "oneOf" constructs yet, we're using the swagger codegen plugin

```
        <groupId>io.swagger.codegen.v3</groupId>
        <artifactId>swagger-codegen-maven-plugin</artifactId>
        <version>3.0.27</version>

```
"items" is a keyword specifing arrays in openapi. 
https://swagger.io/docs/specification/data-models/data-types/#array

the response from the api: 
```
{
  "items": {
    "somepath": {
      "confName": "somepath",
      "conf": {
        "sourceProtocol": "tcp",
		....
```

obviously returns an object as defined in the openapi apidocs: 
https://github.com/aler9/rtsp-simple-server/blob/ae0d9598925dfdfe529dc6af1ad95d787d861452/apidocs/openapi.yaml#L421

but the swagger-codegen-maven-plugin seems to intreprete the apidocs in a way, that an array is beeing returned from the api. generating a signature such as: 

`    default ResponseEntity<List<Map<String, Path>>> pathsList() 
`
which does not match the actual response. 

this issue occurs for the list api operation, where "items" property is defined as an object, such as: pathsList, rtspSessionsList, rtspsSessionsList, rtmpConnsList

when specifying a dedicated response entitiy schema in the openapi spec, the generated classes and signatures get correct.

see apidoc changes here: https://github.com/aler9/rtsp-simple-server/compare/main...udatny:main which lead to usable generated java client classes

## Describe how to replicate the issue
there is working code here with the modified apidocs.
https://github.com/udatny/rtsp-simple-server-api-client
switching back to the original apidoc will break parts of the code and will generate the client api classes with the wrong signature

## Did you attach a network dump?
no

**Comment by aler9** [comment]
Open a PR with https://github.com/aler9/rtsp-simple-server/compare/main...udatny:main and it will get merged.

**Comment by udatny** [comment]
https://github.com/aler9/rtsp-simple-server/pull/639/files
