### ISSUE TITLE
Send a TEARDOWN command to the Source

### ISSUE THREAD

**Issue by msamitahir** [aler9/rtsp-simple-server#63]
Hi Devs,

I was testing the sourceOnDemand by setting up two rtsp-simple-server. My test shows that the server does not send a TEARDOWN Command to the source.
I would like to request if the server can send a TEARDOWN command to the source before the source is stopped.
Also would it be possible to do the same if the program is interrupted by Ctrl C on windows.

Thank you,
Best Regards,
![sourceondemand_no_teardown](https://user-images.githubusercontent.com/10954372/90724524-4cb2bf80-e2f1-11ea-9aa2-c2f45ad7acf9.png)

**Comment by aler9** [comment]
Hello, since the RTSP specification prescribes to send the TEARDOWN to the server when a session ends, this can be classified as bug and will be solved as soon as possible.

**Comment by aler9** [comment]
Hello, this is fixed in master and will be added to the next release.

**Comment by aler9** [comment]
added in v0.9.12
