### ISSUE TITLE
"Hot reload" destroys paths but does not re-create them

### ISSUE THREAD

**Issue by rmwiseman** [aler9/rtsp-simple-server#637]
## Which version are you using?

v0.17.5

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

"Hot reload" of configuration appears to work but sometimes puts the server into a state where it will not serve up any paths.

## Describe how to replicate the issue

1. configure some paths
2. start the server
3. check the paths work
4. edit the configuration to add/edit a path (I simply change the source for a path)
5. try to access that path - and an error occurs immediately
6. stop the server
7. start the server
8. try to access the same path - and it works

## Observations

What I saw (with debug enabled and two streams playing) and I saved the configuration file is that it:
1. reloaded the configuration
2. closed the two streams I had running (one was the one I changed in the configuration; the other, I had not changed, so I would not expect that to be closed)
3. destroyed **all** the paths
4. closed RTSP sessions
5. opened three listeners (ports 8000, 8001 and 8554)

**BUT it did not (re)create any of the paths!**

Then, when I try to access a path, it creates it but discovers that nothing is publishing to it, so aborts.

## Did you attach a network dump?

no

**Comment by rmwiseman** [comment]
Thanks for taking a look at this.  I've tried again with the configuration file I was using last week -- where I tried lots of times and it always failed and I always had to restart the server to make it start working again -- and today, it works fine all the time.  I'm changing exactly the same two lines in the file, just swapping which of the two is commented out, and it's working flawlessly.  I have no idea why this is...  Sorry to have wasted your time.  I'll keep an eye on it an let you know if it happens again.

**Comment by rmwiseman** [comment]
The `ffmpeg` commands that run when those paths are requested all use RTSP streams from an external server (a Milestone XProtect VMS).

**Comment by rmwiseman** [comment]
Just to say, I'm still seeing this issue.  It seems to happen every time I reload the configuration file, even if the configuration file itself hasn't changed!

For example, just now:
```
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] reloading configuration (file changed)
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 160-12fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 480-12fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 160-12fps/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 720-25fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 160/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 480-12fps/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 480-25fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path full/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path full-12fps/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 160-25fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 480/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path full-12fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path full/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 160/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 720-12fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 720/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path full-25fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] destroyed
Nov 24 13:33:04 mk5g-dx-docker go[24533]: 2021/11/24 13:33:04 I [0/0] [path 480/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] destroyed
Nov 24 13:33:14 mk5g-dx-docker systemd[1]: Stopping Service that keeps resized video streams available for video analytics....
Nov 24 13:33:14 mk5g-dx-docker systemd[1]: Stopped Service that keeps resized video streams available for video analytics..
Nov 24 13:33:14 mk5g-dx-docker systemd[1]: Started Service that keeps resized video streams available for video analytics..
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] rtsp-simple-server v0.0.0
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 160-12fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 160-12fps/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 480-12fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 480/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path full-12fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path full/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 160/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 480-25fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 480/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path full/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 160/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 480-12fps/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 720-12fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 160-25fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 720-25fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path 720/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path full-12fps/f193e51a-85d4-4b1d-a1e6-4a0cdcbd0d57] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [path full-25fps/d7da9745-f2e1-4ec3-bf4f-eb63fb7e6305] created
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [RTSP] TCP listener opened on :8554
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [RTMP] listener opened on :1935
Nov 24 13:33:14 mk5g-dx-docker go[26133]: 2021/11/24 13:33:14 I [0/0] [HLS] listener opened on :8888
```
The paths should be recreated immediately, but aren't.  So I restarted the server and all was well again!

**Comment by rmwiseman** [comment]
Another, more positive update... :-)

I've now upgraded to v0.17.9 and this behaviour has not yet happened.  I even started a stream, modified the configuration file (adding new paths); it reloaded the file, created the new paths, and kept streaming the unchanged path.

I'd say that's fixed.  Thanks!

**Comment by aler9** [comment]
fingers crossed. Feel free to reopen the issue if it reappears.

**Comment by rmwiseman** [comment]
> fingers crossed. Feel free to reopen the issue if it reappears.

Thanks.  It hasn't reappeared as such, but I just experienced it again but I think I might know what the cause is (even if I don't understand what the reason is!).  If I edit the `rtsp-simple.server.yml` file and save it, it gets reloaded and that's when it fails.  But if I edit `rtsp-simple-server.yml`, save it as something else (e.g. `rtsp-simple-server.yml.new`), and then move that file so it replaces `rtsp-simple-server.yml`, it seems to work.

Perhaps when my editor (Emacs, in case that's significant) saves a file, the sequence or timing of changes as seen by something like `inotifywait` is different from when the file is simply replaced with another?
