### ISSUE TITLE
Kubernetes deployment - RTSP connection got closed after x seconds

### ISSUE THREAD

**Issue by cedricve** [aler9/rtsp-simple-server#638]
Hello,

I'm using your Docker file, to read in an MP4 and loop/stream through RTSP. (https://github.com/kerberos-io/virtual-rtsp)
Next to that I've deployed it in Kubernetes using a deployment and service.

It looks like working, but after a while I'm getting these kind of errors. 

`2021/10/07 09:35:10 I [1/0] [RTSP] [conn 10.2.3.155:43564] openedspeed=   1x
2021/10/07 09:35:10 I [1/0] [RTSP] [session 799690789] opened by 10.2.3.155:43564
2021/10/07 09:35:10 I [1/1] [RTSP] [session 799690789] is reading from path 'stream', 1 track with TCP
2021/10/07 09:35:15 I [1/1] [RTSP] [conn 10.2.3.155:43564] ERR: connection is linked to another session
2021/10/07 09:35:15 I [1/1] [RTSP] [conn 10.2.3.155:43564] closed
2021/10/07 09:35:15 I [1/0] [RTSP] [session 799690789] closed
2021/10/07 09:35:34 I [1/0] [RTSP] [conn 10.2.3.155:43688] openedspeed=   1x
2021/10/07 09:35:34 I [1/0] [RTSP] [session 740056387] opened by 10.2.3.155:43688
2021/10/07 09:35:34 I [1/1] [RTSP] [session 740056387] is reading from path 'stream', 1 track with TCP
2021/10/07 09:35:39 I [1/1] [RTSP] [conn 10.2.3.155:43688] ERR: connection is linked to another session
2021/10/07 09:35:39 I [1/1] [RTSP] [conn 10.2.3.155:43688] closed
2021/10/07 09:35:39 I [1/0] [RTSP] [session 740056387] closed
2021/10/07 09:35:58 I [1/0] [RTSP] [conn 10.2.3.155:43802] openedspeed=   1x
2021/10/07 09:35:58 I [1/0] [RTSP] [session 362549701] opened by 10.2.3.155:43802
2021/10/07 09:35:58 I [1/1] [RTSP] [session 362549701] is reading from path 'stream', 1 track with TCP
2021/10/07 09:36:03 I [1/1] [RTSP] [conn 10.2.3.155:43802] ERR: connection is linked to another session
2021/10/07 09:36:03 I [1/0] [RTSP] [conn 10.2.3.155:43802] closed
2021/10/07 09:36:03 I [1/0] [RTSP] [session 362549701] closed
2021/10/07 09:36:22 I [1/0] [RTSP] [conn 10.2.3.155:43922] openedspeed=   1x`

What basically happens is the connection got closed after x seconds and then reopens from the listener. The kubernetes yaml file can be found here.  https://github.com/kerberos-io/virtual-rtsp/blob/master/deployment.yaml

Any thoughts?

**Comment by aler9** [comment]
I have to amend the previous answer: disabling the IP check would benefit only RTSP via UDP, but RTSP via UDP can't be used in Kubernetes, since there must be no routing between the client and the server, otherwise UDP doesn't work. In your case, clients try to use UDP, they don't receive any packet and then disconnects from the server after 5 secs, and use TCP. The error message you're seeing is caused by the disconnection request.

Just disable UDP and use TCP by adding the environment variable `RTSP_PROTOCOLS=tcp`

**Comment by cedricve** [comment]
Another update to rule out either Kubernetes and Docker. I pulled the project locally, build it, ran the rtsp-simple-server.
Next I started the FFMPEG command to forward an MP4 to the rtsp server. All works properly from VLC, I'm opening the RTSP stream.

As soon as I use our own RTSP client, it will behave the same as we have with Docker and Kubernetes. So no side-effects in the different deployments.

What I noticed in our lib is that we are opening a single connection, and send RTP keep alives to the RTSP connection, to verify if it is still on. As soon as we do that the previous mentioned error will show up. Is there something special happening?

    2021/12/10 10:24:01 INF [RTSP] [session 300970535] opened by [::1]:55757
    2021/12/10 10:24:01 INF [RTSP] [session 300970535] is reading from path 'stream', 1 track with TCP
    2021/12/10 10:24:06 INF [RTSP] [conn [::1]:55757] closed (connection is linked to another session)
    2021/12/10 10:24:06 INF [RTSP] [session 300970535] closed (not in use)
    2021/12/10 10:24:23 INF [RTSP] [conn [::1]:55824] opened
    2021/12/10 10:24:23 INF [RTSP] [session 312129881] opened by [::1]:55824
    2021/12/10 10:24:23 INF [RTSP] [session 312129881] is reading from path 'stream', 1 track with TCP
    2021/12/10 10:24:28 INF [RTSP] [conn [::1]:55824] closed (connection is linked to another session)
    2021/12/10 10:24:28 INF [RTSP] [session 312129881] closed (not in use)

The session is opened properly, then we send a heartbeat and then the server disconnects. Any thoughts? 

https://github.com/kerberos-io/joy4/blob/master/format/rtsp/client.go#L200

**Comment by aler9** [comment]
Hello, RTSP/TCP doesn't need keep-alives, they are needed only with RTSP/UDP. When the transport protocol is TCP, the session is closed only after the main TCP connection is closed.
