### ISSUE TITLE
Feature Request: Dynamic updating of config file

### ISSUE THREAD

**Issue by bbnp91** [aler9/rtsp-simple-server#64]
Hi, 

I'm wondering if it would be possible to allow updating of the configuration file while the server is running?
I have a use case where I need to run multiple (proxy) server instances on different VM's. These all operate from the same config file (which is copied to each server instance) and then the proxy server array sits below a load balancer. Any subscribe request made to the load balancer is divided up amongst the attached proxy servers. This works well.

At the moment I edit the the config file on a file storage server and it is then downloaded from the central file storage to each VM as part of the rtsp-simple-server startup script. If I need to add a path to the config file, I must edit it on the file server and then restart the script which gets the latest config file and starts rtsp-simple-server. 
Obviously this is fine when no one is connected the proxy servers but if other streams are active then I must kill the server/kick the clients in order to restart the server with the next updated config file.

Would it be possible to implement regular checking of the config file for changes while the server is running?

Maybe this is related to or resolved by the wildcard path project which you are working on?

Any suggestions would be appreciated. 
Thanks

**Comment by aler9** [comment]
Hello, this has been requested multiple times and will be added soon. Two approaches have been proposed:
* using an HTTP REST API to update the configuration, but i think it's redundant
* allow hot reloading of the configuration, by sending the software a system signal (SIGUSR1); after receiving the signal, the software reloads the configuration, finds out the changes and applies them without touching the unchanged parts

**Comment by benbullnz** [comment]
That sounds great - thanks.

I'd be supportive of a REST API but also wouldn't be too hard to integrate the system signal into an API to do the same thing if you don't choose to implement the API. 

Cheers.

**Comment by aler9** [comment]
Dynamic update has been implemented and merged to master; it works by detecting changes of the configuration file.
The feature will be released after extensive tests.

**Comment by aler9** [comment]
added in v0.11.0

**Comment by bbnp91** [comment]
Again, thanks very much. 
This works great and is exactly what was needed.
