### ISSUE TITLE
HLS on HTTPS

### ISSUE THREAD

**Issue by rhapsodyv** [aler9/rtsp-simple-server#641]
## Describe the feature

Is there any plans for HLS on HTTPS?

**Comment by ddmills** [comment]
:wave: is this still in the works, or are there any suggestions for getting this to work?

**Comment by rhapsodyv** [comment]
> :wave: is this still in the works, or are there any suggestions for getting this to work?

Proxy it with nginx

**Comment by brunobaraobr** [comment]
Here I am using proxy passing through apache and it is working fine

**Comment by KieranDevvs** [comment]
Would really like to have this out of the box rather than having to have a proxy server and terminate the TLS and forward the requests. Makes life much simpler.

**Comment by aler9** [comment]
fixed by #938
