### ISSUE TITLE
Streaming with ASF

### ISSUE THREAD

**Issue by jazzy348** [aler9/rtsp-simple-server#65]
## Which version are you using?

v0.9.11

## Describe the problem

When streaming to the server I'm getting errors regarding the ASF format, not too sure how to resolve these.
---------update

Scratch that, not an issue with the server but more an issue with the format. Would it be possible to be able to play over RTSPT though?

Thanks in advance,
Jazzy.

**Comment by aler9** [comment]
Hello, RTSP is codec-agnostic, hence i suppose it's possible to broadcast ASF with RTSP.
Unfortunately i don't have any ASF source and ffmpeg does not support streaming ASF files, they need to be converted.
If you provide an ASF file or live stream, i can test if it can be used with rtsp-simple-server.

**Comment by jazzy348** [comment]
Hi,

Thanks for your response, apologies for the confusing question. I'm trying to get the Unity asset AVPro to work with your code as I know streaming over RTSP would give the lowest latency from other types it supports (HLS, Dash, weirdly no RTMP though) but for some reason it demands files with an ASF container. This isn't an issue with your code (really nice by the way) but an issue with the Unity asset.

Kind regards,
Jazzy.

**Comment by jazzy348** [comment]
Hi again,

Not too sure what changed but on the latest build of the server it now works with AVPro in Unity, well almost. Connecting to the server over RTSPT works a treat, big thank you for that! video comes through with no issues. Audio on the other had either doesn't come through or is heavily corrupt and I can't figure out why. This seems to be a common problem with most RTSP servers except the VERY expensive commercial ones and one JS one, but sadly the JS one crashes just if you look at it funny. I know this is a very specific and niche issue but I'm at a loss.

Kind regards,
Jazzy.
