### ISSUE TITLE
http:localhost:9997/v1/paths/list sometimes when rtmp streams stops streaming it still stays in items

### ISSUE THREAD

**Issue by mrki00** [aler9/rtsp-simple-server#664]
## Which version are you using?

v0.17.6

## Which operating system are you using?

OS

- [x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

when using api http:localhost:9997/v1/paths/list sometimes when rtmp streams stops streaming it still stays in items 
(wrote \ in confName before \~ because markdown)
example:

{
  "items": {
    "application1/key1": {
      "confName": "\~^.*$",
      "conf": {
        "source": "publisher",
        "sourceProtocol": "automatic",
        "sourceAnyPortEnable": false,
        "sourceFingerprint": "",
        "sourceOnDemand": false,
        "sourceOnDemandStartTimeout": "10s",
        "sourceOnDemandCloseAfter": "10s",
        "sourceRedirect": "",
        "disablePublisherOverride": false,
        "fallback": "",
        "publishUser": "",
        "publishPass": "",
        "publishIPs": [],
        "readUser": "",
        "readPass": "",
        "readIPs": [],
        "runOnInit": "",
        "runOnInitRestart": false,
        "runOnDemand": "",
        "runOnDemandRestart": false,
        "runOnDemandStartTimeout": "10s",
        "runOnDemandCloseAfter": "10s",
        "runOnPublish": "",
        "runOnPublishRestart": false,
        "runOnRead": "",
        "runOnReadRestart": false
      },
      "source": null,
      "sourceReady": false,
      "readers": []
    },
    "application2/key2": {
      "confName": "\~^.*$",
      "conf": {
        "source": "publisher",
        "sourceProtocol": "automatic",
        "sourceAnyPortEnable": false,
        "sourceFingerprint": "",
        "sourceOnDemand": false,
        "sourceOnDemandStartTimeout": "10s",
        "sourceOnDemandCloseAfter": "10s",
        "sourceRedirect": "",
        "disablePublisherOverride": false,
        "fallback": "",
        "publishUser": "",
        "publishPass": "",
        "publishIPs": [],
        "readUser": "",
        "readPass": "",
        "readIPs": [],
        "runOnInit": "",
        "runOnInitRestart": false,
        "runOnDemand": "",
        "runOnDemandRestart": false,
        "runOnDemandStartTimeout": "10s",
        "runOnDemandCloseAfter": "10s",
        "runOnPublish": "",
        "runOnPublishRestart": false,
        "runOnRead": "",
        "runOnReadRestart": false
      },
      "source": null,
      "sourceReady": false,
      "readers": []
    }
  }
}

those streams are being captured by vlc media player inside obs

## Describe how to replicate the issue

1. start the server
2. publish with 
3. read with

**Comment by aler9** [comment]
Thanks for reporting the issue, this is fixed in main and will be added to the next release.

**Comment by aler9** [comment]
added in v0.17.8
