### ISSUE TITLE
Support skipping default validation of HTTPS certificates

### ISSUE THREAD

**Issue by aler9** [aler9/rtsp-simple-server#665]
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/656

<div type='discussions-op-text'>

<sup>Originally posted by **ichinm** October 20, 2021</sup>
Hi,

Just tried this using docker. Thank you for this, it solved most of my issues.

I have another problem with proxied source:

x509: cannot validate certificate for because it doesn't contain any IP SANs

conf:

paths:
  pineway-sub:
    source: https://192.168....
    sourceOnDemand: yes

cert is issued to reo-link but I used IP. Not try host name "reo-link" yet, even it works I cannot use it because I have many of them.

Is there any way to disable validation?

Thanks,

</div>

**Comment by aler9** [comment]
This has been added in v0.17.7

**Comment by ichinm** [comment]
Thanks. No more error :)
