### ISSUE TITLE
Reporting to log [file] no longer shows time of day. 

### ISSUE THREAD

**Issue by bbnp91** [aler9/rtsp-simple-server#67]
## Which version are you using?

v0.9.11

## Describe the problem

.Log reporting to file no longer shows time of day when connections/requests are made. Stdout still prints time, but log file doesn't. To get around this for now I am just piping stdout to file. 

Has any thought be given to integrating syslog? https://golang.org/pkg/log/syslog/

Thanks.

**Comment by aler9** [comment]
Two features will be added:
* ability to customize log format
* a log destination to syslog, so all the cases should be covered

**Comment by aler9** [comment]
The enhancements have been moved here: https://github.com/aler9/rtsp-simple-server/issues/83
The bug will be fixed soon.

**Comment by aler9** [comment]
added in v0.914
