### ISSUE TITLE
Update FFMPEG version 

### ISSUE THREAD

**Issue by AdiAbuAli** [aler9/rtsp-simple-server#678]
Hi,
Is it possible to update the FFMPEG APK to latest version (4.4.1)....?

**Comment by aler9** [comment]
in rtsp-simple-server there's no ffmpeg and no APK, i don't know your problem but i think you posted in the wrong place.

**Comment by AdiAbuAli** [comment]
Maybe, but under rtsp-simple-server-main\testimages\ffmpeg\Dockerfile:

 

 

FROM amd64/alpine:3.12

 

RUN apk add --no-cache \

    ffmpeg

 

COPY *.mkv /

 

COPY start.sh /

RUN chmod +x /start.sh

 

ENTRYPOINT [ "/start.sh" ]

**Comment by aler9** [comment]
That's a test image and is in no way included in the release bundle or Docker image.
