### ISSUE TITLE
ERR: sdp: invalid syntax `c=`

### ISSUE THREAD

**Issue by jbittner1002** [aler9/rtsp-simple-server#68]
Any idea on how to fix. ?

2020/08/28 23:26:27 [0/0/0] rtsp-simple-server v0.9.11
2020/08/28 23:26:27 [0/0/0] [UDP/RTP listener] opened on :8000
2020/08/28 23:26:27 [0/0/0] [UDP/RTCP listener] opened on :8001
2020/08/28 23:26:27 [0/0/0] [TCP listener] opened on :8554
2020/08/28 23:26:27 [0/0/0] [source proxied] started
2020/08/28 23:26:27 [0/0/0] [source proxied] connecting
2020/08/28 23:26:28 [0/0/0] [source proxied] ERR: sdp: invalid syntax `c=`
2020/08/28 23:26:33 [0/0/0] [source proxied] connecting
2020/08/28 23:26:34 [0/0/0] [source proxied] ERR: sdp: invalid syntax `c=`

**Comment by aler9** [comment]
Hello, please reopen the issue by using the "Communication issue with an external camera or software" template, and follow the instructions.
