### ISSUE TITLE
Proxy graceful shutdown with TEARDOWN

### ISSUE THREAD

**Issue by denissabramovs** [aler9/rtsp-simple-server#682]
Using latest `v0.17.7`
Was testing it and noticed that no `TEARDOWN` message is sent to source ip camera in case of `proxy` shutdown.
Would be nice if there would be graceful shutdown with proper `shutdown of source connection with rtsp server`, sending TEARDOWN to it, to properly free its channel and resources.

**Comment by aler9** [comment]
Hello, TEARDOWN is sent when `sourceOnDemand` is true, is not sent when server is shut down with CTRL+C.
Handling the CTRL+C case would be a good improvement.

**Comment by denissabramovs** [comment]
Will retry with TERM signal.

**Comment by aler9** [comment]
the server now sends TEARDOWN requests when it is shut down with CTRL+C or SIGINT.
This feature will be added to the next release.

**Comment by denissabramovs** [comment]
Thank you.

**Comment by aler9** [comment]
added in v0.17.9

**Comment by denissabramovs** [comment]
```
^C2021/11/30 09:17:29 INF shutting down gracefully
2021/11/30 09:17:29 INF [path proxied7] [rtsp source] stopped
2021/11/30 09:17:29 INF [RTSP] listener closed
2021/11/30 09:17:29 INF [path proxied6] [rtsp source] stopped
2021/11/30 09:17:29 INF [path proxied4] [rtsp source] stopped
2021/11/30 09:17:29 INF [path proxied3] [rtsp source] stopped
2021/11/30 09:17:29 INF [path proxied2] [rtsp source] stopped
2021/11/30 09:17:29 INF [path proxied5] [rtsp source] stopped
2021/11/30 09:17:29 INF [path proxied8] [rtsp source] stopped
2021/11/30 09:17:29 INF [path proxied1] [rtsp source] stopped
2021/11/30 09:17:29 INF [path proxied9] [rtsp source] stopped
```

All rtsp streams were stopped, but process/program itself didn't exit.

**Comment by aler9** [comment]
@denissabramovs this is evidently another problem, open another issue and provide configuration and logs.

**Comment by denissabramovs** [comment]
I will, a bit later. I have noticed that this is not an issue if there is a single rtsp source stream. Will try to find the source of problem when i get to test all our cameras at once again.
