### ISSUE TITLE
Can't proxy AXIS "Companion" cameras

### ISSUE THREAD

**Issue by rmwiseman** [aler9/rtsp-simple-server#683]
## Which version are you using?

v0.17.5

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When I try to proxy an RTSP stream from an AXIS Companion camera (I've got three, a mix of "AXIS Companion Eye LVE Network Camera" and "AXIS Companion Bullet LE Network Camera") it fails, but the exact same RTSP URL works fine direct in VLC.

I wonder if the problem stems from the necessity of retaining a particular part of the query string (specifically the `Axis-Orig-Sw=true` bit) for this family of cameras, without which the camera denies access even if you've got the credentials correct.  It's a rather strange way that they've decided to implement preventing access from non-AXIS products.  They don't tell you about the parameter, but all their own requests have it and if you include it from a non-AXIS client such as VLC, it works fine!

## Describe how to replicate the issue

1. start the server
2. publish with an RTSP stream for an AXIS Companion camera
3. read with VLC

## Did you attach a network dump?

No, because I didn't want to make it public, but I have got network dumps when accessing the camera direct (which works) and when accessing it via the server (which doesn't work).

I have looked at the RTSP requests and responses recorded by Wireshark, however, and I have noticed that some things are different.  In the sections below, I've included the DESCRIBE, SETUP and PLAY commands for directly accessing the camera and for the proxied access (i.e. via the server).

The RTSP URL I'm accessing is `rtsp://viewer:password@10.255.34.131/axis-media/media.amp?Axis-Orig-Sw=true` (though I've changed the password here).

#### Direct

Request:
```
DESCRIBE rtsp://10.255.34.131:554/axis-media/media.amp?Axis-Orig-Sw=true RTSP/1.0
CSeq: 4
Authorization: Digest username="viewer", realm="AXIS_ACCC8ECA8B08", nonce="033017acY30208188b73af39421a9621d81ba422946b26", uri="rtsp://10.255.34.131:554/axis-media/media.amp?Axis-Orig-Sw=true", response="c777c21dc146f59569861c7bdf2588b1"
User-Agent: LibVLC/3.0.9.2 (LIVE555 Streaming Media v2020.01.19)
Accept: application/sdp
```

Response:
```
RTSP/1.0 200 OK
CSeq: 4
Content-Type: application/sdp
Content-Base: rtsp://10.255.34.131:554/axis-media/media.amp/
Server: GStreamer RTSP server
Date: Wed, 03 Nov 2021 14:36:53 GMT
Content-Length: 670

v=0
o=- 1600574595065185240 1 IN IP4 10.255.34.131
s=Session streamed with GStreamer
i=rtsp-server
t=0 0
a=tool:GStreamer
a=type:broadcast
a=range:npt=now-
a=control:rtsp://10.255.34.131:554/axis-media/media.amp?Axis-Orig-Sw=true
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:50000
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4d0029;sprop-parameter-sets=Z00AKeKQLgo8vgLcBAQGkHiRFQ==,aO48gA==
a=ts-refclk:local
a=mediaclk:sender
a=control:rtsp://10.255.34.131:554/axis-media/media.amp/stream=0?Axis-Orig-Sw=true
a=framerate:12.000000
a=transform:0.000000,1.000000,0.000000;-1.000000,0.000000,0.000000;0.000000,0.000000,1.000000
```

#### Proxied

Request:
```
DESCRIBE rtsp://10.255.34.131/axis-media/media.amp?Axis-Orig-Sw=true RTSP/1.0
Accept: application/sdp
Authorization: Digest username="viewer", realm="AXIS_ACCC8ECA8B08", nonce="03301702Y062186e3d65399a1038ceb733b12838c02f54", uri="rtsp://10.255.34.131/axis-media/media.amp?Axis-Orig-Sw=true", response="a49c304cadbc987b97762d94869189fe"
CSeq: 3
User-Agent: gortsplib
```

Response:
```
RTSP/1.0 200 OK
CSeq: 3
Content-Type: application/sdp
Content-Base: rtsp://10.255.34.131/axis-media/media.amp/
Server: GStreamer RTSP server
Date: Wed, 03 Nov 2021 14:34:04 GMT
Content-Length: 662

v=0
o=- 6649241262828239032 1 IN IP4 10.255.34.131
s=Session streamed with GStreamer
i=rtsp-server
t=0 0
a=tool:GStreamer
a=type:broadcast
a=range:npt=now-
a=control:rtsp://10.255.34.131/axis-media/media.amp?Axis-Orig-Sw=true
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:50000
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4d0029;sprop-parameter-sets=Z00AKeKQLgo8vgLcBAQGkHiRFQ==,aO48gA==
a=ts-refclk:local
a=mediaclk:sender
a=control:rtsp://10.255.34.131/axis-media/media.amp/stream=0?Axis-Orig-Sw=true
a=framerate:12.000000
a=transform:0.000000,1.000000,0.000000;-1.000000,0.000000,0.000000;0.000000,0.000000,1.000000
```

#### Direct

Request:
```
SETUP rtsp://10.255.34.131:554/axis-media/media.amp/stream=0?Axis-Orig-Sw=true RTSP/1.0
CSeq: 5
Authorization: Digest username="viewer", realm="AXIS_ACCC8ECA8B08", nonce="033017acY30208188b73af39421a9621d81ba422946b26", uri="rtsp://10.255.34.131:554/axis-media/media.amp/", response="83be1dd06032c8f3a4e71f9c8073e217"
User-Agent: LibVLC/3.0.9.2 (LIVE555 Streaming Media v2020.01.19)
Transport: RTP/AVP;unicast;client_port=48844-48845
```

Response:
```
RTSP/1.0 200 OK
CSeq: 5
Transport: RTP/AVP;unicast;client_port=48844-48845;server_port=50008-50009;ssrc=A80CED16;mode="PLAY"
Server: GStreamer RTSP server
Session: -90.mFkNh7w5U6If;timeout=60
Date: Wed, 03 Nov 2021 14:36:53 GMT
```

#### Proxied

Request
```
SETUP rtsp://10.255.34.131/axis-media/media.amp/stream=0?Axis-Orig-Sw=true RTSP/1.0
Authorization: Digest username="viewer", realm="AXIS_ACCC8ECA8B08", nonce="03301702Y062186e3d65399a1038ceb733b12838c02f54", uri="rtsp://10.255.34.131/axis-media/media.amp/stream=0?Axis-Orig-Sw=true", response="548b4a7ad1c9536c82c7fec8ed58aa8d"
CSeq: 4
Transport: RTP/AVP;unicast;client_port=46972-46973;mode=play
User-Agent: gortsplib
```

Response:
```
RTSP/1.0 200 OK
CSeq: 4
Transport: RTP/AVP;unicast;client_port=46972-46973;server_port=50008-50009;ssrc=FB7709A7;mode="PLAY"
Server: GStreamer RTSP server
Session: jHR1f_K_.7Y.GSqf;timeout=60
Date: Wed, 03 Nov 2021 14:34:04 GMT
```

#### Direct

Request:
```
PLAY rtsp://10.255.34.131:554/axis-media/media.amp?Axis-Orig-Sw=true RTSP/1.0
CSeq: 6
Authorization: Digest username="viewer", realm="AXIS_ACCC8ECA8B08", nonce="033017acY30208188b73af39421a9621d81ba422946b26", uri="rtsp://10.255.34.131:554/axis-media/media.amp/", response="814713c0c5eb04e78d551835b1f915d6"
User-Agent: LibVLC/3.0.9.2 (LIVE555 Streaming Media v2020.01.19)
Session: -90.mFkNh7w5U6If
Range: npt=0.000-
```

Response:
```
RTSP/1.0 200 OK
CSeq: 6
RTP-Info: url=rtsp://10.255.34.131:554/axis-media/media.amp/stream=0?Axis-Orig-Sw=true;seq=6803;rtptime=3915899637
Range: npt=now-
Server: GStreamer RTSP server
Session: -90.mFkNh7w5U6If;timeout=60
Date: Wed, 03 Nov 2021 14:36:53 GMT
```

#### Proxied

Request:
```
PLAY rtsp://10.255.34.131/axis-media/media.amp/ RTSP/1.0
Authorization: Digest username="viewer", realm="AXIS_ACCC8ECA8B08", nonce="03301702Y062186e3d65399a1038ceb733b12838c02f54", uri="rtsp://10.255.34.131/axis-media/media.amp/", response="b93fdbd26819dc5e7fe5d92c07f3c72f"
CSeq: 5
Range: npt=0-
Session: jHR1f_K_.7Y.GSqf
User-Agent: gortsplib
```

Response:
```
RTSP/1.0 403 Forbidden
CSeq: 5
Server: GStreamer RTSP server
Session: jHR1f_K_.7Y.GSqf;timeout=60
Date: Wed, 03 Nov 2021 14:34:04 GMT
```
I think the significant difference here might be the absence of the `Axis-Orig-Sw=true` in the PLAY URL.

**Comment by aler9** [comment]
Hello, the URL in PLAY and PAUSE requests is provided by the camera through the `Content-Base` header, that in this case is the following one:

```
Content-Base: rtsp://10.255.34.131:554/axis-media/media.amp/
```

It doesn't contain `Axis-Orig-Sw=true` , while the individual track URLs do contain it:

```
a=control:rtsp://10.255.34.131/axis-media/media.amp?Axis-Orig-Sw=true
a=control:rtsp://10.255.34.131/axis-media/media.amp/stream=0?Axis-Orig-Sw=true
```

I don't know why VLC uses the track URL in the PLAY request, or the stream URL (in this case they're equal), but both are wrong, and if used they could cause a lot of cameras to stop working.

We need to find out why VLC uses this specific behavior.

**Comment by rmwiseman** [comment]
Hi, thanks for looking at this.  I assume there must be a good reason why VLC behaves in this way...  I guess it can't be a bad thing if this is what makes it work with these AXIS cameras!  I'm happy to send you the network capture directly if that would help, although I guess I've already included the essentials.  I don't know if it's significant, but between the SETUP and PLAY sections, there are some RTP/RTCP messages (albeit only one-way: client to server) in the direct capture that aren't in the proxied capture.

**Comment by aler9** [comment]
>  there are some RTP/RTCP messages (albeit only one-way: client to server) in the direct capture that aren't in the proxied capture.

These are needed to open the NAT/firewall.

**Comment by rmwiseman** [comment]
Any idea how we can progress this one?  It would be so useful to be able to proxy these AXIS cameras.  If it helps, Live555 Proxy works with these cameras, and I think that's open source so might provide a clue...

**Comment by aler9** [comment]
This is fixed in main, you can try this nightly release to test if everything is all right:
[rtsp-simple-server_v0.18.3-4-g7ecd528_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8671008/rtsp-simple-server_v0.18.3-4-g7ecd528_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.18.3-4-g7ecd528_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8671011/rtsp-simple-server_v0.18.3-4-g7ecd528_linux_amd64.tar.gz)
[rtsp-simple-server_v0.18.3-4-g7ecd528_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8671013/rtsp-simple-server_v0.18.3-4-g7ecd528_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.18.3-4-g7ecd528_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8671014/rtsp-simple-server_v0.18.3-4-g7ecd528_linux_armv6.tar.gz)
[rtsp-simple-server_v0.18.3-4-g7ecd528_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/8671015/rtsp-simple-server_v0.18.3-4-g7ecd528_linux_armv7.tar.gz)
[rtsp-simple-server_v0.18.3-4-g7ecd528_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/8671016/rtsp-simple-server_v0.18.3-4-g7ecd528_windows_amd64.zip)

**Comment by aler9** [comment]
added in v0.18.4.

**Comment by rmwiseman** [comment]
Many thanks for implementing this.  I don't have access to the cameras at the moment, but when I do, I'll certainly give it a try.
