### ISSUE TITLE
Unable to proxy stream with authentication/URL params, 401 (Unauthorized)

### ISSUE THREAD

**Issue by gazzer82** [aler9/rtsp-simple-server#69]
## Which version are you using?

Docker Hub Latest - 0.9.11

## Describe the problem

I am trying to proxy some RTSP stream generated by some AXIS CCTV cameras, they require basic auth, as well as some parameters in the URL to config the correct stream profile. It seems that the URL is causing issues with the server, as it's reporting a 401 error when trying to connect.

Here's the startup, and failure log captured from Docker.

```
2020/08/29 10:02:37 [0/0/0] rtsp-simple-server v0.9.11
2020/08/29 10:02:37 [0/0/0] [UDP/RTP listener] opened on :8050
2020/08/29 10:02:37 [0/0/0] [UDP/RTCP listener] opened on :8051
2020/08/29 10:02:37 [0/0/0] [TCP listener] opened on :8554
2020/08/29 10:03:55 [1/0/0] [client 10.11.12.248:61819] connected
2020/08/29 10:03:55 [1/0/0] [client 10.11.12.248:61819] OPTIONS
2020/08/29 10:03:55 [1/0/0] [client 10.11.12.248:61819] DESCRIBE
2020/08/29 10:03:55 [1/0/0] [source shutter] starting on demand
2020/08/29 10:03:55 [1/0/0] [source shutter] started
2020/08/29 10:03:55 [1/0/0] [source shutter] connecting
2020/08/29 10:03:55 [1/0/0] [source shutter] ERR: DESCRIBE: bad status code: 401 (Unauthorized)
2020/08/29 10:04:00 [2/0/0] [client 10.11.12.248:61824] connected
2020/08/29 10:04:00 [2/0/0] [client 10.11.12.248:61824] SETUP
2020/08/29 10:04:00 [2/0/0] [client 10.11.12.248:61824] ERR: the path must contain a base path and a control path (shutter)
2020/08/29 10:04:00 [1/0/0] [client 10.11.12.248:61824] disconnected
2020/08/29 10:04:00 [2/0/0] [client 10.11.12.248:61825] connected
2020/08/29 10:04:00 [2/0/0] [client 10.11.12.248:61825] OPTIONS
2020/08/29 10:04:00 [2/0/0] [client 10.11.12.248:61825] ERR: path must begin with a slash
2020/08/29 10:04:00 [1/0/0] [client 10.11.12.248:61825] disconnected
2020/08/29 10:04:00 [1/0/0] [source shutter] connecting
2020/08/29 10:04:00 [1/0/0] [source shutter] ERR: DESCRIBE: bad status code: 401 (Unauthorized)
2020/08/29 10:04:01 [2/0/0] [client 10.11.12.248:61826] connected
2020/08/29 10:04:01 [2/0/0] [client 10.11.12.248:61826] OPTIONS
2020/08/29 10:04:01 [2/0/0] [client 10.11.12.248:61826] DESCRIBE
2020/08/29 10:04:02 [2/0/0] [client 10.11.12.248:61826] ERR: publisher of path 'shutter' has timed out
2020/08/29 10:04:02 [1/0/0] [client 10.11.12.248:61826] disconnected
2020/08/29 10:04:02 [2/0/0] [client 10.11.12.248:61819] ERR: publisher of path 'shutter' has timed out
2020/08/29 10:04:02 [0/0/0] [client 10.11.12.248:61819] disconnected
2020/08/29 10:04:02 [1/0/0] [client 10.11.12.248:61827] connected
2020/08/29 10:04:02 [1/0/0] [client 10.11.12.248:61827] SETUP
2020/08/29 10:04:02 [1/0/0] [client 10.11.12.248:61827] ERR: the path must contain a base path and a control path (shutter)
2020/08/29 10:04:02 [0/0/0] [client 10.11.12.248:61827] disconnected
2020/08/29 10:04:02 [1/0/0] [client 10.11.12.248:61828] connected
2020/08/29 10:04:02 [1/0/0] [client 10.11.12.248:61828] OPTIONS
2020/08/29 10:04:02 [1/0/0] [client 10.11.12.248:61828] ERR: path must begin with a slash
2020/08/29 10:04:02 [0/0/0] [client 10.11.12.248:61828] disconnected
2020/08/29 10:04:02 [1/0/0] [client 10.11.12.248:61829] connected
2020/08/29 10:04:02 [1/0/0] [client 10.11.12.248:61829] OPTIONS
2020/08/29 10:04:02 [1/0/0] [client 10.11.12.248:61829] DESCRIBE
2020/08/29 10:04:05 [1/0/0] [source shutter] connecting
```

and here's my docker-compose.yml

```
version: '3.8'

services:
  rtsp-proxy:
    image: aler9/rtsp-simple-server:latest
    volumes:
      - $PWD/rtsp-simple-relay/rtsp-simple-server.yml:/rtsp-simple-server.yml
    network_mode: "host"

```

and my rtsp-simple-server.yml

```
writeTimeout: 5s

paths:
  shutter:
    source: "rtsp://cctv:shh57@10.11.13.111:554/axis-media/media.amp?videocodec=h264&camera=5&fps=15"
    sourceProtocol: tcp
    sourceOnDemand: yes
  goodsinout:
    source: "rtsp://cctv:shh57@10.11.13.113:554/axis-media/media.amp?videocodec=h264&camera=6&fps=15"
    sourceProtocol: tcp
    sourceOnDemand: yes
  warehousemiddle:
    source: "rtsp://cctv:shh57@10.11.13.114:554/axis-media/media.amp?videocodec=h264&camera=6&fps=15"
    sourceProtocol: tcp
    sourceOnDemand: yes
  mezupper:
    source: "rtsp://cctv:shh57@10.11.13.115:554/axis-media/media.amp?videocodec=h264&camera=6&fps=15"
    sourceProtocol: tcp
    sourceOnDemand: yes
```

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, i'm using rtsp-simple-server to interact with an Axis server too, and everything works normally:
```yml
paths:
  proxied:
    source: rtsp://user:pass@10.xx.xx.xx/axis-media/media.amp?videocodec=h264&audio=0&color=1&fps=5&compression=0&videobitrate=50
```

Please:
* check if username and password are correct (error 401 usually means that one of them is wrong), by using another software to interact with the cameras (vlc)
* attach a network dump

to generate a network dump:
1) Download wireshark (https://www.wireshark.org/)
2) Start capturing on the interface used for exchanging RTSP (if the server and the target software are both installed in your pc, the interface is probably "loopback", otherwise it's the one of your network card)
3) Start the server and replicate the issue
4) Stop capturing, save the result in .pcap format
5) Attach

**Comment by gazzer82** [comment]
Thanks for the swift reply.

I have tried the same URL in VLC and it connects without issue.

Attached is a network dump from the docker host, it is filtered to only show traffic to the camera as their is some other slightly more sensitive stuff on the host, but there is definitely traffic to/from the camera IP address in the capture.

Let me know if I can provide anything else to help, I'm guessing this has to be something stupid at this end if it's working for you with the same scenario, I just can't work out what it it 👍 

Thanks!

Gareth
[axis_camera.pcap.zip](https://github.com/aler9/rtsp-simple-server/files/5145395/axis_camera.pcap.zip)

**Comment by aler9** [comment]
Hi, the network dump you attached only includes packets sent from your pc, and not the replies from the cameras. I think this bug can be solved rapidly and the network dump is the key to this process; i need:
* a network dump with packets exchanged between rtsp-simple-server and the camera, with the 401 error
* a network dump with packets exchanged between vlc and the camera, with a successful handshake

**Comment by gazzer82** [comment]
Ah yes, doh, sorry.

tcpdump attached for the server, that doesn't work (axis_camera_server.pcap), and local VLC that does work, (axis_camera_local.pcap).

Again, thanks for the help!

[Archive.zip](https://github.com/aler9/rtsp-simple-server/files/5145511/Archive.zip)

**Comment by AngeloAvv** [comment]
I'm facing the same issue as reported by @gazzer82 . The stream works perfectly in VLC, but prints bad status code 401 Unauthorized when trying to proxy

**Comment by aler9** [comment]
Hello, i've uploaded a possible fix, please try the nightly release attached below and let me know if it worked.

[rtsp-simple-server_v0.9.11-8-g476262e_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5145603/rtsp-simple-server_v0.9.11-8-g476262e_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.9.11-8-g476262e_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5145613/rtsp-simple-server_v0.9.11-8-g476262e_linux_amd64.tar.gz)
[rtsp-simple-server_v0.9.11-8-g476262e_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/5145614/rtsp-simple-server_v0.9.11-8-g476262e_windows_amd64.zip)

**Comment by AngeloAvv** [comment]
Cannot test since I'm on ARMv7, btw I tried with an older version and the problem still occurs.

**Comment by aler9** [comment]
[rtsp-simple-server_v0.9.11-8-g476262e_linux_arm7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/5145627/rtsp-simple-server_v0.9.11-8-g476262e_linux_arm7.tar.gz)

**Comment by AngeloAvv** [comment]
It works, but after a few seconds an error message occurs:

```
2020/08/29 18:04:54 [1/0/1] [client 192.168.1.3:60311] ERR: read tcp 192.168.1.69:8554->192.168.1.3:60311: use of closed network connection
2020/08/29 18:04:54 [0/0/0] [client 192.168.1.3:60311] disconnected

```
```

2020/08/29 18:05:10 [0/0/0] [source cam2] ERR: stream is dead
2020/08/29 18:05:10 [0/0/0] [source cam2] not ready

```

**Comment by aler9** [comment]
@AngeloAvv this is probably another bug, but
* try increasing the `readTimeout` parameter in the configuration
* try switching to udp and see if the issue is still present
* attach a full log

thanks

**Comment by aler9** [comment]
@AngeloAvv or try switching to TCP if you were using UDP (sorry but there are two people in the conversation)

**Comment by gazzer82** [comment]
Wow amazingly quick response, will try the bug fix tomorrow. Do you have your docker build file so I can build a new container version as this is running on docker?

Thanks

Gareth

**Comment by AngeloAvv** [comment]
Ok tell me if you rather prefer I open another issue. 
So I tried increasing the readTimeout to 30 seconds but the problem still occurs, by switching the protocols from [udp,tcp] to [tcp] only, a crash event is printed:
```
pi@raspberrypi:~ $ ./rtsp-simple-server
2020/08/29 18:25:15 [0/0/0] rtsp-simple-server v0.9.11-8-g476262e
2020/08/29 18:25:15 [0/0/0] [UDP/RTP listener] opened on :8000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc pc=0x3ad8c4]

goroutine 20 [running]:
main.(*serverUdp).run(0x0)
        /s/server-udp.go:67 +0xc4
created by main.newProgram
        /s/main.go:288 +0xdcc

```

Also tried as a sudoer but it's the same

Thank you how fast you are replying to us

**Comment by aler9** [comment]
@AngeloAvv i meant try changing the `sourceProtocol` parameter, not the `protocols` parameter.
* the `sourceProtocol` parameter dictates the protocol of the source
* the  `protocols` parameter dictates the protocol of the server and is not the probem

Since you're using a source, a proper configuration could be:
```
paths:
  proxied:
    source: rtsp://url
    sourceProtocol: tcp
```

I want you to do this since the default protocol is udp, and it requires no firewall between the source and the server, while tcp always works.

**Comment by gazzer82** [comment]
@aler9 sorry it might have got missed in the messages, do you have the dockerfile you use to build the releases so I can test this fix on my docker server?

**Comment by aler9** [comment]
```
FROM golang:1.14-alpine3.12
RUN apk add --no-cache git
RUN git clone https://github.com/aler9/rtsp-simple-server \
&& cd rtsp-simple-server \
&& go build -o /out .
ENTRYPOINT [ "/out" ]
```

**Comment by gazzer82** [comment]
Thanks, was able to build a new container from the latest code, unfortunately it hasn't solved the problem.

It does seems to have fixed a load of the path errors, but I'm still getting a 401 on startup.

```
2020/08/30 10:56:46 [0/0/0] rtsp-simple-server v0.9.11
2020/08/30 10:56:46 [0/0/0] [UDP/RTP listener] opened on :8000
2020/08/30 10:56:46 [0/0/0] [UDP/RTCP listener] opened on :8001
2020/08/30 10:56:46 [0/0/0] [TCP listener] opened on :8554
2020/08/30 10:56:46 [0/0/0] [source proxied] started
2020/08/30 10:56:46 [0/0/0] [source proxied] connecting
2020/08/30 10:56:46 [0/0/0] [source proxied] ERR: DESCRIBE: bad status code: 401 (Unauthorized)
2020/08/30 10:56:51 [0/0/0] [source proxied] connecting
2020/08/30 10:56:51 [0/0/0] [source proxied] ERR: DESCRIBE: bad status code: 401 (Unauthorized)
2020/08/30 10:56:56 [0/0/0] [source proxied] connecting
2020/08/30 10:56:56 [0/0/0] [source proxied] ERR: DESCRIBE: bad status code: 401 (Unauthorized)
2020/08/30 10:57:01 [0/0/0] [source proxied] connecting
2020/08/30 10:57:01 [0/0/0] [source proxied] ERR: DESCRIBE: bad status code: 401 (Unauthorized)
2020/08/30 10:57:06 [0/0/0] [source proxied] connecting
2020/08/30 10:57:06 [0/0/0] [source proxied] ERR: DESCRIBE: bad status code: 401 (Unauthorized)
```

**Comment by aler9** [comment]
Hello @gazzer82, from the log you posted i can see you're using the old version, since the first log line is
```
2020/08/30 10:56:46 [0/0/0] rtsp-simple-server v0.9.11
```

While the nightly release generates:
```
2020/08/30 10:56:46 [0/0/0] rtsp-simple-server v0.0.0
```

Since the binary outside docker works fine, i think the bug is solved at 99%.
I'm releasing v0.9.12, please test it and let me know.

**Comment by AngeloAvv** [comment]
I can confirm the nightly fixed the problem for me.

**Comment by gazzer82** [comment]
You are entirely correct, was using the wrong container image, rebuilt with the correct version and it does indeed work as expected. So confirmed working here too, thanks!
