### ISSUE TITLE
Support of video codec: H.264/H.265/VP8/VP9 and audio codec: MP3/AAC/OPUS

### ISSUE THREAD

**Issue by Johnny421** [aler9/rtsp-simple-server#7]
Hi there!

Does this server support video codec: H.264/H.265/VP8/VP9  and audio codec: MP3/AAC/OPUS ?

where is that defined in the source code?

**Comment by midicase** [comment]
Unlike RTMP, the RTSP protocol does not require specific codecs.  You should be able to send any combination through.

**Comment by Johnny421** [comment]
Thanks for the confirmation! highly appreciated i'm new into the RTSP protocol. Can we update the README step by step on how to compile the project from source?

**Comment by Johnny421** [comment]
> Unlike RTMP, the RTSP protocol does not require specific codecs. You should be able to send any combination through.

Why Wowza under the 'RTSP/RTP' part: https://www.wowza.com/blog/streaming-protocols

list those codec below only if RTSP does not require specific codecs:
```
Audio Codecs: AAC, AAC-LC, HE-AAC+ v1 & v2, MP3, Speex, Opus, Vorbis
Video Codecs: H.265 (preview), H.264, VP9, VP8

```

**Comment by midicase** [comment]
That is a Wowza requirement.  It allows them to remux the stream into other formats without having to do expensive re-encoding.

**Comment by Johnny421** [comment]
Once again midicase thank you! now i understand better 👍

**Comment by aler9** [comment]
Hi,
* Wowza is a media server, a software that can receive streams, convert them into different formats and output them. It should also provide a RTSP server, i don't remember precisely.
* rtsp-simple-server is a RTSP server, a software that can receive existing streams and serve them exactly as they are, with the RTSP protocol, that allows to stream with the efficiency of the RTP protocol and the simplicity of the client-server architecture.

You can also use rtsp-simple-server as a media server, by using ffmpeg or gstreamer to take a stream from the server, remux/re-encode it, and resending it into the server, for instance:
```
ffmpeg -i rtsp://localhost:8554/original -c:v libx264 -preset ultrafast -tune zerolatency -b 600k -f rtsp rtsp://localhost:8554/compressed
```

**Comment by Johnny421** [comment]
Hi!

Thank you very much for taking the time to explaining me that. Much appreciated thank you :)
