### ISSUE TITLE
Error Connecting to IP Camera

### ISSUE THREAD

**Issue by Fezile01** [aler9/rtsp-simple-server#70]
My camera has the following RTSP source: rtsp://192.168.1.31/user=admin&password=&channel=1&stream=1.sdp

When starting the server I receive the following error messages repeatedly:

2020/08/29 12:33:17 [0/0/0] [source proxied] connecting
2020/08/29 12:33:17 [0/0/0] [source proxied] ready
2020/08/29 12:33:27 [0/0/0] [source proxied] ERR: stream is dead
2020/08/29 12:33:27 [0/0/0] [source proxied] not ready

Could you please assist

**Comment by aler9** [comment]
Hello, please reopen the issue by using the "Bug: communication with an external camera or another software" template, and follow the instructions to generate a packet dump, otherwise there isn't enough data to solve the problem.
