### ISSUE TITLE
sourceOnDemand does not seem to be respected

### ISSUE THREAD

**Issue by geekskunk** [aler9/rtsp-simple-server#700]
**Tested with version**
v0.17.8

**Operating System**
Ubuntu 20
- [ X] Linux amd64 standard

**Issue Description**
In a proxy setup, sourceOnDemand does not seem to be respected. Is set to "no" with 10s CloseAfter, but network traffic indicates the the rtsp stream is being actively transferred from the cameras (regardless if any connection is made to the proxied connection.)

**To Replicate:**

- Configure in yaml a proxied local RTSP ip camera
- Stop rtsp-simple-server
- In new terminal monitor network traffic (  sudo iftop -p -b -i eth0 )
- Note existing network dataflow
- In original terminal, start rtsp-simple-server
- Note increased network dataflow (even though no proxied listeners connecting to the rtsp-simple-server to access the proxied feed)

**Comment by aler9** [comment]
Hello, when a source is closed, the server sends a TEARDOWN request to the camera, and the camera should stop sending video frames to the server. Maybe the camera isn't responding correctly to the request, anyway more infos are needed. Can you post a network dump of the data exchanged between the server and the camera?

**Comment by dorinclisu** [comment]
Isn't this the correct behavior? sourceOnDemand: no = the source is always pulled, not only when there is demand. CloseAfter has effect only when sourceOnDemand: yes.

**Comment by aler9** [comment]
> Isn't this the correct behavior? sourceOnDemand: no = the source is always pulled, not only when there is demand. CloseAfter has effect only when sourceOnDemand: yes.

Thanks @dorinclisu - i missed that out, but you're right, `sourceOnDemand: no` means that the source is always pulled, therefore this is the correct behavior.
