### ISSUE TITLE
Stream closes after x seconds

### ISSUE THREAD

**Issue by cenoura008** [aler9/rtsp-simple-server#702]
## Which version are you using?

v0.17.8_windows_amd64

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

RTSP closed after x seconds of stream

## Describe how to replicate the issue
Hello I'm currently using the follow:  ffmpeg -stream_loop -1 -re -i https://25503.live.streamtheworld.com/LOS40_CLASSIC_SC -c copy -f rtsp -rtsp_transport tcp rtsp://localhost:8554/mystream , and for some reasson that I can't find after a seconds I get the following:
![image](https://user-images.githubusercontent.com/33322215/141798035-2331f1c6-ecb6-4aee-a574-5aaea2888354.png)

What's that I'm doing wrong?

**Comment by aler9** [comment]
Hello, please post the full server log.
Anyway, that error should be related related to a reader -> server connection, not to a publisher -> server connection.

**Comment by cenoura008** [comment]
2021/11/17 09:17:26 INF rtsp-simple-server v0.17.8
2021/11/17 09:17:26 INF [metrics] opened on 127.0.0.1:9998
2021/11/17 09:17:26 INF [pprof] opened on 127.0.0.1:9999
2021/11/17 09:17:26 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2021/11/17 09:17:26 INF [RTMP] listener opened on :1935
2021/11/17 09:17:26 INF [HLS] listener opened on :8888
2021/11/17 09:17:26 INF [API] listener opened on 127.0.0.1:9997
2021/11/17 09:17:39 INF [RTSP] [conn 192.168.178.134:52774] opened
2021/11/17 09:17:39 INF [RTSP] [session 227996797] opened by 192.168.178.134:52774
2021/11/17 09:17:39 INF [path mystream] opened
2021/11/17 09:17:39 INF [RTSP] [session 227996797] is publishing to path 'mystream', 1 track with TCP
2021/11/17 09:21:24 INF [RTSP] [conn 192.168.178.153:39918] opened
2021/11/17 09:21:24 INF [RTSP] [conn 192.168.178.153:39918] closed (invalid path)
2021/11/17 09:21:34 INF [RTSP] [conn 192.168.178.153:39919] opened
2021/11/17 09:21:34 INF [RTSP] [session 779400524] opened by 192.168.178.153:39919
2021/11/17 09:21:34 INF [RTSP] [session 779400524] is reading from path 'mystream', 1 track with UDP
2021/11/17 09:22:34 INF [RTSP] [session 779400524] closed (no RTSP requests received in a while)
2021/11/17 09:22:39 INF [RTSP] [conn 192.168.178.153:39919] closed (session not found)

**Comment by cenoura008** [comment]
I'm using a grandstream gsc3505 to connecto to the server.

**Comment by aler9** [comment]
It looks like your Grandstream sends RTSP requests once every 70 secs instead of < 60 secs. Maybe there's a configuration option in the Grandstream web UI to tune this interval. Otherwise, try switching to TCP.

**Comment by WEBudoGT** [comment]
I'm having the same issue, but there's no option to configure this on the GSC device.
Is there any parameter on rtsp-simple-server's configuration to avoid this disconnection?

**Comment by aler9** [comment]
I have an idea to fix this inspired by https://github.com/aler9/gortsplib/pull/94 - please try this nightly release and let me know if it works with the GSC device:
[rtsp-simple-server_v0.17.13-8-g50144d6_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7900892/rtsp-simple-server_v0.17.13-8-g50144d6_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.17.13-8-g50144d6_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7900894/rtsp-simple-server_v0.17.13-8-g50144d6_linux_amd64.tar.gz)
[rtsp-simple-server_v0.17.13-8-g50144d6_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7900895/rtsp-simple-server_v0.17.13-8-g50144d6_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.17.13-8-g50144d6_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7900897/rtsp-simple-server_v0.17.13-8-g50144d6_linux_armv6.tar.gz)
[rtsp-simple-server_v0.17.13-8-g50144d6_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7900900/rtsp-simple-server_v0.17.13-8-g50144d6_linux_armv7.tar.gz)
[rtsp-simple-server_v0.17.13-8-g50144d6_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/7900901/rtsp-simple-server_v0.17.13-8-g50144d6_windows_amd64.zip)

**Comment by WEBudoGT** [comment]
Great @aler9 !
The GS speaker didn't get disconnected this time.
Thanks!!! :)

**Comment by aler9** [comment]
Perfect, it turned out that the RTSP keepalive interval can be sent from the server to the client. This fix will be added to the next release.

**Comment by KyunghwaChae** [comment]
@aler9 hi, I just want to notice that v0.17.13 mentioned above occurs an error 'H264 track 1 is not valid: sprop-parameter-sets is missing (96 packetization-mode=1)'. 
Even though my code is working with v0.17.09.

**Comment by aler9** [comment]
@KyunghwaChae this is not in any way related to the problem discussed here, please open a dedicated issue by following instructions.

**Comment by aler9** [comment]
This has been fixed in v0.17.15
