### ISSUE TITLE
How to support hevc? hello:      Can you help me with this problem?

### ISSUE THREAD

**Issue by L88888** [aler9/rtsp-simple-server#703]
## Describe the feature
hello :
  How to support hevc?
Description

**Comment by L88888** [comment]
![image](https://user-images.githubusercontent.com/32121572/142411873-0381b481-4e89-4b1d-af6d-38056bae606b.png)

**Comment by L88888** [comment]
H264 is normal;

There is a problem with the use of hevc. The problem is shown in the figure above. How can I solve it? thank

Online, etc

**Comment by aler9** [comment]
Hello, at the moment the server doesn't support muxing HEVC into HLS. This feature won't be implemented soon since 99% of browsers don't support HEVC into HLS. If you need HLS, convert the stream to H264 as described in the README.
If you're interested in the feature, follow #469
