### ISSUE TITLE
Log File issue panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Tabarane** [aler9/rtsp-simple-server#706]
## Which version are you using?

v0.17.9

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ X] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1064f0a]

goroutine 1 [running]:
github.com/aler9/rtsp-simple-server/internal/logger.(*Logger).Log(0xc0003c4820, 0x1, {0x1277b1c, 0x7}, {0xc00021ff00, 0x1281c82, 0x19684560c40})
        /s/internal/logger/logger.go:177 +0x4a
github.com/aler9/rtsp-simple-server/internal/core.(*Core).Log(...)
        /s/internal/core/core.go:120
github.com/aler9/rtsp-simple-server/internal/core.New({0xc0000963b0, 0x1, 0x1})
        /s/internal/core/core.go:89 +0x6bc
main.main()
        /s/main.go:10 +0x54
```
## Describe how to replicate the issue
on my main desktop with core i7 desktop i have no issue with log , file , all good
when i tested it on my Panasonic CF20 , with same configuration i get the below error and it shutdown, when i changed log to be exported stdut all worked, when selecting file it show as below

**Comment by aler9** [comment]
Thanks for reporting the crash, it is fixed in main and will be fixed in the next release

**Comment by aler9** [comment]
added in v0.17.10
