### ISSUE TITLE
tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

### ISSUE THREAD

**Issue by Coimbra1984** [aler9/rtsp-simple-server#708]
Hi, I use v0.17.9 on Linux amd65 standard.

I want to source a rtsps stream with the rtsp-simple-server. I configured the proxy path as followed:

  proxied:
    # url of the source stream, in the format rtsp://user:pass@host:port/path
    source: rtsps://user:pass@192.168.1.10:8554/MediaInput/h265 

On 192.168.1.10, port 8554 I have an nginx reverse proxy which forwards the connection to an IP Camera on 192.168.1.10 with plain rtsp.

When I start the rtsp-simple-server I get the following error message however:
2021/11/24 10:55:31 INF [path proxied] [rtsp source] ERR: tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

When I use  rtsp://user:pass@192.168.1.5:8554/MediaInput/h265  as source URL it works fine.

Thanks

**Comment by Coimbra1984** [comment]
Okay, sorry I missed to fill out 'sourceFingerprint' as described in the .yml template...

It works now.

**Comment by aler9** [comment]
This was a bug indeed, since `ServerName` must be filled with the host name of the server to use a valid certificate. No one noticed that since 99% of people use `sourceFingerprint` and not a valid certificate.

**Comment by aler9** [comment]
added in v0.17.11
