### ISSUE TITLE
sourceOnDemand on nested proxies

### ISSUE THREAD

**Issue by AngeloAvv** [aler9/rtsp-simple-server#71]
## Which version are you using?

v0.9.11

## Question

What I'm working on is something like that:
Every apartment has a maximum of 8 cameras which streams in 1080p H265. In every apartment there's a Linux machine with rtsp-simple-server in proxy mode (tipically a Raspberry Pi) which gathers the cameras' stream and map them with 8 different endpoints. During the startup, the local Linux machine creates a reverse SSH tunnel to a remote server, exposing the local rtsmp-simple-server-port. The next step I want to do, is to install another rtsp-simple-server to the remote server which maps the multiple streams coming from different ports (8554 for client1, 8555 for client2, and so on) into a single port but with the same endpoints.

What happens if the two rtsp-simple-server are configured with both sourceOnDemand option? Will the streams be always opened due to the remote server which is proxying the endpoints of the multiple local server? I need to understand if there's a way to spare bandwith because actually it will cost me something like 1.3TB/month, which of course raises up the price to the stars. And that's of course useless and a total waste of bandwidth since the end user will watch the stream only if some particular conditions are triggered.

Just to mention, the end user will connect to the remote server in order to watch the streams. 

Thank you!

**Comment by aler9** [comment]
hi, if there are two rtsp-simple-servers in series, both with the `sourceOndemand: on` parameter, the source will be pulled (and bandwidth will be consumed) only if there's an user, connected to the outer rtsp-simple-server, that is requesting the stream:
```
user <-- rtsp-simple-server <-- rtsp-simple-server <-- camera
```

if there's no user, no bandwidth will be consumed:
```
rtsp-simple-server <-(not connected, but waiting)- rtsp-simple-server <-(not connected, but waiting)- camera
```

**Comment by AngeloAvv** [comment]
Ok thank you, that cleared my mind.
