### ISSUE TITLE
Steam stops on the HLS Server side

### ISSUE THREAD

**Issue by MrCheatEugene** [aler9/rtsp-simple-server#716]
## Which version are you using?
Latest one

## Which operating system are you using?

- [x ] Linux amd64 standard
- [x ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)
- [x] Ubuntu 18.04
## Describe the issue

If server and stream run at the same server then video will PLAY ONCE, even tho ffmpeg still sending info to RTSP server. 
More accurately: HLS server stops recognizing stream after video ends. Even if it is in loop.
## Describe how to replicate the issue

1. I don't know is that somehow causing the issue, but i'll leave it if you can't reproduce it. Create .sh files that launch rtsp server and ffmpeg IN DIFFERENT 'SCREENS", and then start server. Then start ffmpeg stream.
2. Start server with aunthefication using tool screen ("screen -dmS server /root/rtsp-simple-server", you can also use docker for this, the same bug happens)
3. Start RTSP stream from file on the same server as the server using FFmpeg
4. Wait until it ends
5. Check direct HLS url for stream. It should return 404 not found, while FFmpeg still sending data to server and RTSP simple server still runnng.

Also, it appears in docker container and the binary as well.

**Comment by dorinclisu** [comment]
You have to be more explicit in order to receive help.
1. Latest is not a valid version. It is latest when you create the issue, but may not be the latest when someone is looking at the issue. You are just asking for extra work from someone to look up at the date of your post and the calendar of releases.

2. Share the rtsp-simple-server.yml config and the exact ffmpeg command you are runing. Be careful to mask sensitive rtsp passwords that might be visible in the config.

**Comment by aler9** [comment]
Hello, 

> HLS server stops recognizing stream after video ends. Even if it is in loop.

You mean that you're using ffmpeg's `-stream_loop -1` flag?

> It should return 404 not found

If you're streaming a video in a loop, why HLS should return 404?

**Comment by MrCheatEugene** [comment]
Hi. I have totally forgot about this issue after I created it. Sorry for that. But, I've created and debugged all of this stuff myself, and now video does loop and streams forever.
