### ISSUE TITLE
[HLS] Android broswer CANNOT work.

### ISSUE THREAD

**Issue by iesvme** [aler9/rtsp-simple-server#728]
![微信图片_20211213225010](https://user-images.githubusercontent.com/16969250/145834110-fbeb3705-a4e9-4ef6-bae5-f28c0af4e0fc.jpg)
![微信图片_20211213224953](https://user-images.githubusercontent.com/16969250/145834118-0e01287d-a45a-454e-bf49-9caa45e6bd58.jpg)

**Comment by MELSunny** [comment]
I have the same issue with the latest version: 0.17.11
I tried multiple old versions and found 0.17.2 working on Android Chrome. All versions afterwards are not working.

**Comment by aler9** [comment]
HLS on Android works perfectly, this issue surely depends on the camera and/or your specific setup. Anyway we'll never know it because this issue was opened without using the template, without following the instructions and without providing any info on how to replicate it.
