### ISSUE TITLE
./rtsp-simple-server: 1: ./rtsp-simple-server: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by MasterTut** [aler9/rtsp-simple-server#73]
Trying to run this from Rasbian  OS - 

wget from binary to root folder 
tar -xvf rtsp-simple-server_v0.9.12_darwin_amd64.tar.gz 

sudo ./rtsp-simple-server 

any idea what could be going wrong? Much appreciated!

**Comment by aler9** [comment]
Hello,
1. Use [issue templates](https://github.com/aler9/rtsp-simple-server/issues/new/choose) to create issues
2. You've downloaded the Mac OS X binary (`darwin_amd64`), not the Raspberry binary, which is the `linux_arm7` one.
