### ISSUE TITLE
Bandwidth metrics per source and per session

### ISSUE THREAD

**Issue by denissabramovs** [aler9/rtsp-simple-server#734]
Bandwidth metrics per source and per session. Available as Prometheus-compatible metrics.

We are currently working on metrics system and have found out, that there are no metrics on rtsp-proxy level to calculate bandwidth of source and outgoing bandwidth per session.

This is required to properly handle network problems and find the weak spot.

**Comment by hadican** [comment]
This would be amazing! 😌

**Comment by hadican** [comment]
Hi @aler9, any plans in near future?

**Comment by aler9** [comment]
bandwidth metrics are now fully implemented in main and will be available in the next release

**Comment by aler9** [comment]
take a look at the README for usage:

https://github.com/aler9/rtsp-simple-server#metrics
