### ISSUE TITLE
Drop request instead of offering auth

### ISSUE THREAD

**Issue by matthew-jones-uk** [aler9/rtsp-simple-server#735]
Currently, `readIPs` just offers auth when an invalid IP connects. Would it be possible to add a config option that causes the server to just drop the packet? I'm not sure the complexity of this but I would've thought it wouldn't be too difficult?

**Comment by aler9** [comment]
Hello, actually when the readIPs check fails, the user receives a 403 response (forbidden), and then the connection is closed immediately with a critical error:

https://github.com/aler9/rtsp-simple-server/blob/ed635db87ed534e54980572b63e8636779c609d0/internal/core/rtsp_conn.go#L167

Why do you say that it offers auth?

**Comment by matthew-jones-uk** [comment]
Hi, I tried with VLC and its default behaviour is to ask for auth (username/password) when a 403 is returned. Not sure if this is the correct behaviour from VLC, but either way I think it's correct to respond with a 403 to an IP that isn't allowed. I'll close this as I don't think there's anything that needs to be done here. Thanks for the clarification!
