### ISSUE TITLE
certificate signed by unknown authority while using 

### ISSUE THREAD

**Issue by calisro** [aler9/rtsp-simple-server#736]
I was attempting to use this within home assistant.  When I've configured it, I get the following.  I attempted then to create a fingerprint and use that to allow it to connect but I still get this message.  

RTSP_PATHS_ALL_SOURCEFINGERPRINT: 65C3891265EBC650A5A688E9F6A12DA97A6E3C70F71AD2E9C0FCFE0D55776F56
RTSP_SOURCEFINGERPRINT: 65C3891265EBC650A5A688E9F6A12DA97A6E3C70F71AD2E9C0FCFE0D55776F56
RTSP_PATHS_TEST_SOURCEFINGERPRINT: 65C3891265EBC650A5A688E9F6A12DA97A6E3C70F71AD2E9C0FCFE0D55776F56

`2021/12/16 20:58:05 I [0/0] [path test] [hls source] ERR: Get "https://p2p-vir-6.eufylife.com:1443/live?app=hls&stream=xxxxxxxx": x509: certificate signed by unknown authority`

**Comment by aler9** [comment]
Hello, this works flawlessly:

```
docker run --rm -it \
-e RTSP_PATHS_TEST_SOURCEFINGERPRINT=FC31CC459FBFA26D95F4BA432B27275D2444A88A1C13B6D3BAB99A71AC18B96C \
-e RTSP_PATHS_TEST_SOURCE=https://self-signed.badssl.com/ \
aler9/rtsp-simple-server
```

please make sure that you're using the latest version.

**Comment by ahaverty** [comment]
@calisro did you get anywhere with Eufy hls streaming in the end? I'm looking to do something similar myself.
