### ISSUE TITLE
server stop，but the config is still in use ,is it right ?

### ISSUE THREAD

**Issue by lucien-kejl** [aler9/rtsp-simple-server#741]
## Which version are you using?

v0.17.9

## Which operating system are you using?

- [x ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach a network dump?

yes / no

**Comment by lucien-kejl** [comment]
if I stop the server,change the config file,but it still in use. tthe new config file will take effect too.but when I test it ,some times it will happen,sometime it won't. can you explain it ? is it a bug 。Thanks

**Comment by aler9** [comment]
Hello, in Linux there's no concept of "file in use", and anyway the server doesn't lock the configuration file in both Windows and Linux.
