### ISSUE TITLE
UDP Multicast fails and returns 400 Bad Request

### ISSUE THREAD

**Issue by sat-sim** [aler9/rtsp-simple-server#742]
## Which version are you using?

v0.17.11

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

We would like to use the udp multicast feature to save bandwidth. Our configuration comprises of multiple cameras connected to a remote rtsp-simple-server instance, a local instance of rtsp-simple-server running that sources the feeds from the remote instance. Local clients use VLC to connect to the local relay to view the remote camera streams. As there can be many clients, to save bandwidth on the local network we wish to use udp multicast to send the streams once locally.

## Describe how to replicate the issue

I have a local rtsp-simple-server running with the following configuration option set:
protocols: [udp, multicast, tcp]

Following the wiki instructions I have tried to connect to this server instance using the following command:

ffmpeg -re -rtsp_transport udp_multicast -i rtsp://localhost:8554/mystream -c copy output.mp4

The ffmpeg client shows the following error:

Server returned 400 Bad request

If I substitute -rtsp_transport udp_multicast for -rtsp_transport udp or -rtsp_transport tcp I receive no errors and the stream plays correctly.

We have tried running the ffmpeg client locally on the same machine as the rtsp-simple-server instance and also on another machine on the same network and see the same issues. All windows firewalls are turned off on all machines.

## Did you attach a network dump?
no

**Comment by aler9** [comment]
Hello, can you post the server logs?

**Comment by sat-sim** [comment]
Hello, I have reproduced the issue using a single camera instance. I have attached the relay configuration file (renamed as .yml.txt for upload), along with 2 server log files and an additional file containing the ffmpeg commands that I was running.

Connecting using udp or tcp works as expected (upd log attached), connecting using udp_multicast fails (log file also attached).

Please let me know if you need more detail. Thankyou

[ffmpeg client command.txt](https://github.com/aler9/rtsp-simple-server/files/7796048/ffmpeg.client.command.txt)
[rtsp-simple-server_connect_with_udp.log](https://github.com/aler9/rtsp-simple-server/files/7796049/rtsp-simple-server_connect_with_udp.log)
[rtsp-simple-server_connect_with_udp_multicast.log](https://github.com/aler9/rtsp-simple-server/files/7796050/rtsp-simple-server_connect_with_udp_multicast.log)
[rtsp-simple-server.yml.txt](https://github.com/aler9/rtsp-simple-server/files/7796052/rtsp-simple-server.yml.txt)

**Comment by aler9** [comment]
There's a strange error "no such interface" that prevents the server from allocating multicast IPs. Will try to replicate ASAP.

**Comment by aler9** [comment]
Hello, in my opinion the problem is here:
https://github.com/aler9/gortsplib/blob/7bf111f98a655c5c8355a66a969c546c466bf22f/serverudpl.go#L111

The server tries to join the multicast group on all interfaces, and a single error on one of them is enough to make the server fail. The server shouldn't join the group on all interfaces, but only on interfaces that supports multicast.

**Comment by aler9** [comment]
Please try this nightly release and let me know if there's any difference:
[rtsp-simple-server_v0.17.14-15-g3fa570e_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7954513/rtsp-simple-server_v0.17.14-15-g3fa570e_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.17.14-15-g3fa570e_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7954514/rtsp-simple-server_v0.17.14-15-g3fa570e_linux_amd64.tar.gz)
[rtsp-simple-server_v0.17.14-15-g3fa570e_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7954515/rtsp-simple-server_v0.17.14-15-g3fa570e_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.17.14-15-g3fa570e_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7954516/rtsp-simple-server_v0.17.14-15-g3fa570e_linux_armv6.tar.gz)
[rtsp-simple-server_v0.17.14-15-g3fa570e_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7954517/rtsp-simple-server_v0.17.14-15-g3fa570e_linux_armv7.tar.gz)
[rtsp-simple-server_v0.17.14-15-g3fa570e_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/7954519/rtsp-simple-server_v0.17.14-15-g3fa570e_windows_amd64.zip)

**Comment by gjaegy** [comment]
Hi, I'm joining the discussion as I've just encountered the exact same error.

So, I've tried the nightly (Windows x64), original error (400) is gone, but ffplay now encounters the following error:

setsockopt(IP_ADD_MEMBERSHIP): Error number -10065 occurred f=0/0

**Comment by aler9** [comment]
> So, I've tried the nightly (Windows x64), original error (400) is gone

Thanks for the report, and the feature will be available in the next release.

> but ffplay now encounters the following error:
> setsockopt(IP_ADD_MEMBERSHIP): Error number -10065 occurred f=0/0

This issue appears in Windows PCs that have network interfaces that don't support multicast. My patch edits rtsp-simple-server in order not to use these interfaces. ffmpeg probably has the same problem and needs to be patched too. Report the issue on the ffmpeg bug tracking system.

**Comment by sat-sim** [comment]
Hello. Appologies for the delay in testing this. I have tested the build as requested and can also confirm hat it resolve the multicast issue. 

Many thanks for resolving this issue and the good work that you do on this project.

**Comment by aler9** [comment]
Added in v0.17.17
