### ISSUE TITLE
Audio doesn't work on HLS / Chrome / Android and also doesn't allow video to play

### ISSUE THREAD

**Issue by iesvme** [aler9/rtsp-simple-server#749]
Hello, Sir,
First of all, Sorry for my poor English! And I would hope to make my question as clear as possible. Thank you for developing a such good software!
## Which version are you using?

v0.17.12

## Which operating system are you using?
PC: win10_1809
Phone: Pixel 2_Android 10

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

The Chrome of Android 10 do not work by reading HLS.

## Describe how to replicate the issue

1. start the server
2. publish with OBS
SETTINGS: {
Output > Recording > Output to URL > rtsp://127.0.0.1:8554/live
Container Format: rtsp
Video Bitrate: 3000 Kbps
Frames: 30
Video Encoder: h264_amf (libx264)
Audio Encoder: aac
}
3. read with Chrome of Android 10 (http://192.168.10.11:8888/live  or  http://192.168.10.11:8888/live/index.m3u8)

**Comment by aler9** [comment]
Hello, the problem here seems to be the audio track. If you disable audio (uncheck "Audio track" in the recording settings), the video will play smoothly. I'll try to investigate the audio problem, in the meanwhile you can disable it.

**Comment by aler9** [comment]
Hello, i developed a fix, please try the attached nightly release and let me know if this time it works:

[rtsp-simple-server_v0.17.12-3-gbb5129d_darwin_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7770866/rtsp-simple-server_v0.17.12-3-gbb5129d_darwin_amd64.tar.gz)
[rtsp-simple-server_v0.17.12-3-gbb5129d_linux_amd64.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7770868/rtsp-simple-server_v0.17.12-3-gbb5129d_linux_amd64.tar.gz)
[rtsp-simple-server_v0.17.12-3-gbb5129d_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7770869/rtsp-simple-server_v0.17.12-3-gbb5129d_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.17.12-3-gbb5129d_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7770870/rtsp-simple-server_v0.17.12-3-gbb5129d_linux_armv6.tar.gz)
[rtsp-simple-server_v0.17.12-3-gbb5129d_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/7770871/rtsp-simple-server_v0.17.12-3-gbb5129d_linux_armv7.tar.gz)
[rtsp-simple-server_v0.17.12-3-gbb5129d_windows_amd64.zip](https://github.com/aler9/rtsp-simple-server/files/7770872/rtsp-simple-server_v0.17.12-3-gbb5129d_windows_amd64.zip)

**Comment by iesvme** [comment]
I appreciate you so much! YES! It works well now! Thank you very much!

**Comment by aler9** [comment]
fixed in v0.17.13
