### ISSUE TITLE
Using with iPhone LiveReporter App

### ISSUE THREAD

**Issue by PlatinumFusion** [aler9/rtsp-simple-server#75]
## Which version are you using?

v0.9.12

## Describe the problem

Description

When trying to push a stream to the server via LiveReporter I get the following.  I suspect that LiveReporter is not sending the correct information/standard for the SDP.  When I use the Larix on the iPhone it works fine.  Is there a way to get this to work 'with LiveReporter?

2020/09/03 23:02:25 [0/0/0] [UDP/RTP listener] opened on :8000
2020/09/03 23:02:25 [0/0/0] [UDP/RTCP listener] opened on :8001
2020/09/03 23:02:25 [0/0/0] [TCP listener] opened on :8554
2020/09/03 23:04:15 [1/0/0] [client 172.16.1.117:56110] connected
2020/09/03 23:04:15 [1/0/0] [client 172.16.1.117:56110] OPTIONS
2020/09/03 23:04:15 [1/0/0] [client 172.16.1.117:56110] ANNOUNCE
2020/09/03 23:04:15 [1/0/0] [client 172.16.1.117:56110] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`'
2020/09/03 23:04:15 [0/0/0] [client 172.16.1.117:56110] disconnected
2020/09/03 23:04:16 [1/0/0] [client 172.16.1.117:56111] connected
2020/09/03 23:04:16 [1/0/0] [client 172.16.1.117:56111] OPTIONS
2020/09/03 23:04:16 [1/0/0] [client 172.16.1.117:56111] ANNOUNCE
2020/09/03 23:04:16 [1/0/0] [client 172.16.1.117:56111] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`
2020/09/03 23:04:16 [0/0/0] [client 172.16.1.117:56111] disconnected
2020/09/03 23:04:17 [1/0/0] [client 172.16.1.117:56112] connected
2020/09/03 23:04:17 [1/0/0] [client 172.16.1.117:56112] OPTIONS
2020/09/03 23:04:17 [1/0/0] [client 172.16.1.117:56112] ANNOUNCE
2020/09/03 23:04:17 [1/0/0] [client 172.16.1.117:56112] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`
2020/09/03 23:04:17 [0/0/0] [client 172.16.1.117:56112] disconnected
2020/09/03 23:04:18 [1/0/0] [client 172.16.1.117:56113] connected
2020/09/03 23:04:18 [1/0/0] [client 172.16.1.117:56113] OPTIONS
2020/09/03 23:04:18 [1/0/0] [client 172.16.1.117:56113] ANNOUNCE
2020/09/03 23:04:18 [1/0/0] [client 172.16.1.117:56113] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`
020/09/03 23:04:18 [0/0/0] [client 172.16.1.117:56113] disconnected
2020/09/03 23:04:32 [1/0/0] [client 172.16.1.117:56114] connected
2020/09/03 23:04:32 [1/0/0] [client 172.16.1.117:56114] OPTIONS
2020/09/03 23:04:32 [1/0/0] [client 172.16.1.117:56114] ANNOUNCE
2020/09/03 23:04:32 [1/0/0] [client 172.16.1.117:56114] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`
2020/09/03 23:04:32 [0/0/0] [client 172.16.1.117:56114] disconnected
2020/09/03 23:04:33 [1/0/0] [client 172.16.1.117:56115] connected
2020/09/03 23:04:33 [1/0/0] [client 172.16.1.117:56115] OPTIONS
2020/09/03 23:04:33 [1/0/0] [client 172.16.1.117:56115] ANNOUNCE
2020/09/03 23:04:33 [1/0/0] [client 172.16.1.117:56115] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`
2020/09/03 23:04:33 [0/0/0] [client 172.16.1.117:56115] disconnected
2020/09/03 23:04:34 [1/0/0] [client 172.16.1.117:56116] connected
2020/09/03 23:04:34 [1/0/0] [client 172.16.1.117:56116] OPTIONS
2020/09/03 23:04:34 [1/0/0] [client 172.16.1.117:56116] ANNOUNCE
2020/09/03 23:04:34 [1/0/0] [client 172.16.1.117:56116] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`
2020/09/03 23:04:34 [0/0/0] [client 172.16.1.117:56116] disconnected
2020/09/03 23:04:35 [1/0/0] [client 172.16.1.117:56117] connected
2020/09/03 23:04:35 [1/0/0] [client 172.16.1.117:56117] OPTIONS
2020/09/03 23:04:35 [1/0/0] [client 172.16.1.117:56117] ANNOUNCE
2020/09/03 23:04:35 [1/0/0] [client 172.16.1.117:56117] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`
2020/09/03 23:04:35 [0/0/0] [client 172.16.1.117:56117] disconnected
2020/09/03 23:04:36 [1/0/0] [client 172.16.1.117:56118] connected
2020/09/03 23:04:36 [1/0/0] [client 172.16.1.117:56118] OPTIONS
2020/09/03 23:04:36 [1/0/0] [client 172.16.1.117:56118] ANNOUNCE
2020/09/03 23:04:36 [1/0/0] [client 172.16.1.117:56118] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`
2020/09/03 23:04:36 [0/0/0] [client 172.16.1.117:56118] disconnected
2020/09/03 23:04:37 [1/0/0] [client 172.16.1.117:56119] connected
2020/09/03 23:04:37 [1/0/0] [client 172.16.1.117:56119] OPTIONS
2020/09/03 23:04:37 [1/0/0] [client 172.16.1.117:56119] ANNOUNCE
2020/09/03 23:04:37 [1/0/0] [client 172.16.1.117:56119] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`
2020/09/03 23:04:37 [0/0/0] [client 172.16.1.117:56119] disconnected
2020/09/03 23:04:38 [1/0/0] [client 172.16.1.117:56120] connected
2020/09/03 23:04:38 [1/0/0] [client 172.16.1.117:56120] OPTIONS
2020/09/03 23:04:38 [1/0/0] [client 172.16.1.117:56120] ANNOUNCE
2020/09/03 23:04:38 [1/0/0] [client 172.16.1.117:56120] ERR: invalid SDP: sdp: invalid syntax `o=[-0 0 IN IP4 127.0.0.1]`
2020/09/03 23:04:38 [0/0/0] [client 172.16.1.117:56120] disconnected`

Thank you very much for your time

## Did you attach a network dump?
[LiveReporter.pcap.zip](https://github.com/aler9/rtsp-simple-server/files/5172455/LiveReporter.pcap.zip)

**Comment by aler9** [comment]
Hello, thanks for the report, the LiveReporter app is now supported in master and will be supported in the next release.

**Comment by PlatinumFusion** [comment]
Awesome!  Thank you so much!

**Comment by PlatinumFusion** [comment]
I have tested it and it's working well.
Again, thank you.

**Comment by aler9** [comment]
added in v0.9.13
