### ISSUE TITLE
readUser and readPass in "all" section not respected?

### ISSUE THREAD

**Issue by fragger42** [aler9/rtsp-simple-server#761]
## Which version are you using?

v0.17.13

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I just upgraded my installation from v0.15.0 to v0.17.3. For this I used the configuration file that was provided with the release as a starting point and only changed it where needed. I set readUser and readPass in the "all" section and added a path like this at the end of the file:
`  test:
    sourceOnDemand: yes
    source: rtsp://192.168.178.55:8554/0`
Apart from this, the config file is completely default. Now with this config, the readUser and readPass from the "all" section is not used and the stream is published without any authentication! I have to add the parameters to the stream definition separately and only then it is respected. In my old version, it worked fine when readUser and readPass was defined in the "all" section. In my opinion, this is a bug.

**Comment by aler9** [comment]
Hello, as stated in the configuration file:

> The settings under the path "all" are applied to all paths that do not match another entry.

Since the `test` path matches the `test` path setting, its settings are not taken from "all", but from "test". In order to solve this, fill `readUser` and `readPass` in `test` too.
