### ISSUE TITLE
RTSP server running on Android phone

### ISSUE THREAD

**Issue by anilmaddala** [aler9/rtsp-simple-server#765]
## RTSP server running on Android phone

Instead of hosting the RSP server on a Linux machine, it would be reat if we could run the server on an Android Phone.

Other phones/devices on same network can broadcast and receive the video feeds.

**Comment by aler9** [comment]
Hello, rtsp-simple-server is full compatible with arm6, arm7 and arm8 architectures, therefore you can already compile it for android and integrate it into any existing app.
