### ISSUE TITLE
when restart the sever,but configuration that I edit through http api is still in use 

### ISSUE THREAD

**Issue by lucien-kejl** [aler9/rtsp-simple-server#766]
## Which version are you using?

v0.0.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

as i wrote,  I start the server and add about 8 rtsp proxy  connections through http api , but after five hours
I restart the server, they are still proxied. oh I can not understand.  Is it right?
Thank again .

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Hello, all changes performed through the HTTP APIs are kept exclusively in RAM and are not saved to the configuration file. If the configuration is still present after a restart, it means that the server wasn't restarted properly.
