### ISSUE TITLE
Feature Request: RTSPS/RTSP over SSL

### ISSUE THREAD

**Issue by JooJooBee666** [aler9/rtsp-simple-server#77]
Just wondering if this was considered and possibly on the horizon.  Not sure of the diffuculty on implementing  but this would be awesome to have. ;)

**Comment by aler9** [comment]
Hello, it's not difficult to implement, but there are two questions:
* there's a very limited number of clients that support RTSP over TLS (ffmpeg does, while vlc and gstreamer does not), so there isn't a great user base - a VPN is usually preferred
* To ensure security, there must be a way to validate the certificate of the counterpart. With HTTPS, this is solved by using certificate authorities, but RTSP is mostly used in closed networks. The best way to achieve this could be adding a field to set the counterpart public key.

So i'd leave this feature out until more clients support it.

**Comment by ismell** [comment]
Is it possible to use nginx to proxy the RTSP stream, and leave the TLS/cetrificate to nginx?

**Comment by aler9** [comment]
Yes, it's possible, since nginx supports proxing bare TCP connections:
https://docs.nginx.com/nginx/admin-guide/security-controls/securing-tcp-traffic-upstream/

But you'd have to disable UDP.

The [RTSP 2.0 specification](https://tools.ietf.org/html/rfc7826) shows how to implement secure connections with both UDP and TCP, but again, i don't know many clients that support it. When they'll do, i'll surely consider implementing it.

In the meanwhile, i suggest [Wireguard](https://www.wireguard.com/).

**Comment by grantthomas** [comment]
when you're ready to look into implementing this, I would be interested in testing this out.

We're currently using ffmpeg to send and receive, and are exploring ways to secure this without a VPN necessary.
Until then Thanks for the pointer to nginx tcp proxy.

**Comment by aler9** [comment]
@grantthomas the problem with the so called "RTSPS" is that the UDP part is totally unencrypted - hence it's not secure (meaning signed AND encrypted).
RTSP 2.0 is secure (it uses TLS for TCP and DTLS for UDP), but there are no clients that support it.
Therefore, i don't know what to do.

**Comment by grantthomas** [comment]
Understood. 
It sounds like a difficult position any way it's cut.

if I can make the nginx proxy idea work that will be a fine solution until something more direct is available.
I just found your project today and it's almost exactly what I went in search of. Keep up the good work

**Comment by billsimon** [comment]
We simply put `stunnel` in front of rtsp-simple-proxy. The client (Amazon Alexa video devices) request rtsp/media interleaved on the signaling port and so this works fine.

**Comment by aler9** [comment]
I guess RTSPS has be added, even if it's insecure.

**Comment by aler9** [comment]
RTSPS is now supported in master and will be supported in next release.

**Comment by JooJooBee666** [comment]
@aler9 Great, thanks for the update. 👍

**Comment by aler9** [comment]
added to v0.13.0
