### ISSUE TITLE
[HLS] It will case to be frozen when after double-clicking multiple times to fast-forward or fast-reverse the video

### ISSUE THREAD

**Issue by iesvme** [aler9/rtsp-simple-server#776]
## Which version are you using?

v0.17.13

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

It will case to be frozen when after double-clicking multiple times to fast-forward or fast-reverse the video.

## Describe how to replicate the issue

1. start the server
2. publish with obs by rtsp
3. read with HLS by Android
4. double-click multiple times on the left or right side of video
5. the video will be frozen

**Comment by aler9** [comment]
Hello, the HLS stream is not intended to be forwarded or reversed. The server keeps only the segments related to the current time window (that is generally 15-20secs), it deletes older segments. If you want to keep older segments, you have to save the stream to disk and write your own HLS implementation.
