### ISSUE TITLE
Make `go install github.com/aler9/rtsp-simple-server@latest` work

### ISSUE THREAD

**Issue by maruel** [aler9/rtsp-simple-server#777]
## Describe the feature

`go install` is a great way to install go executables. It's fast and safe. We can use version number when needed. Since this project already uses semver git tags, it should just work.

Running `go install github.com/aler9/rtsp-simple-server@latest` currently fails due to the rewrite directive, here's the output locally:

```
go: downloading github.com/aler9/rtsp-simple-server v0.17.13
go install: github.com/aler9/rtsp-simple-server@latest (in github.com/aler9/rtsp-simple-server@v0.17.13):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

It has been the case since March 2021; https://github.com/aler9/rtsp-simple-server/commit/186a91800a684922efe4f7d1f3367144e9604002

**Comment by maruel** [comment]
There's a workaround to install from sources in the meantime; do a local clone:

```
git clone https://github.com/aler9/rtsp-simple-server
cd rtsp-simple-server
git checkout v0.17.13
go install .
```

**Comment by aler9** [comment]
Hello, this would be nice to support, but `replace` directives are quite useful to solve important issues, since they allow to temporarily / permanently replace external dependencies, and i can't forbid them.

Maybe you can open an issue in the Golang repository and ask the maintainers to allow `go install` and `replace` to coexist.

**Comment by maruel** [comment]
My question was indirectly: why no attempt to do a PR upstream was done?

https://github.com/notedit/rtmp/compare/master...aler9:master

**Comment by aler9** [comment]
Usually there's no time to wait for a PR to get merged. Furthermore, the changes in the RTMP repository are not meant to be merged into master.
