### ISSUE TITLE
'H264 track 1 is not valid' error occurs since v0.17.10.

### ISSUE THREAD

**Issue by KyunghwaChae** [aler9/rtsp-simple-server#787]
## Which version are you using?

v0.17.10 ~

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I had used v0.17.9 but it occurs EOF error if using it with FFMPEG.
While I was looking for the solution and found [this](https://github.com/aler9/rtsp-simple-server/issues/702) in this page.
I thought it is similar with my case, therefore I tried newer version v0.17.10~14.
But below error displayed.
**H264 track 1 is not valid: sprop-parameter-sets is missing (96 packetization-mode=1)**

## Describe how to replicate the issue

- Structure of our system
Streaming client with 2 tcp cameras -------- rtsp_simple_server -------- ffmpeg restream server -------- FE web server

In above system, 
- rtsp_simple_server v0.17.09 is working well but sometimes occurs EOF error.
- rtsp_simple_server v0.17.10~14 occurs 'sprop-parameter-sets is missing' error immediately at beginning.

## Did you attach the server logs?

2022/01/25 12:08:23 INF [RTSP] [conn 192.168.50.2:51556] opened
2022/01/25 12:08:23 DEB [RTSP] [conn 192.168.50.2:51556] [c->s] OPTIONS rtsp://192.168.50.250:8554/TEST RTSP/1.0
CSeq: 1
User-Agent: Lavf58.29.100

2022/01/25 12:08:23 DEB [RTSP] [conn 192.168.50.2:51556] [s->c] RTSP/1.0 200 OK
CSeq: 1
Public: DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, GET_PARAMETER, TEARDOWN
Server: gortsplib

2022/01/25 12:08:23 DEB [RTSP] [conn 192.168.50.2:51556] [c->s] ANNOUNCE rtsp://192.168.50.250:8554/TEST RTSP/1.0
CSeq: 2
Content-Length: 215
Content-Type: application/sdp
User-Agent: Lavf58.29.100

v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 192.168.50.250
t=0 0
a=tool:libavformat 58.29.100
m=video 0 RTP/AVP 96
b=AS:2000
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
a=control:streamid=0

2022/01/25 12:08:23 INF [RTSP] [session 330342988] opened by 192.168.50.2:51556
2022/01/25 12:08:23 DEB [RTSP] [conn 192.168.50.2:51556] [s->c] RTSP/1.0 400 Bad Request
CSeq: 2
Server: gortsplib

2022/01/25 12:08:23 INF [RTSP] [conn 192.168.50.2:51556] closed (H264 track 1 is not valid: sprop-parameter-sets is missing (96 packetization-mode=1))
2022/01/25 12:08:23 INF [RTSP] [session 330342988] closed (not in use)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, i wasn't aware of the fact that ffmpeg doesn't fill `sprop-parameter-sets` when a camera doesn't provide it. I thought that it filled it automatically. This is why the server was edited to filter out clients that don't provide that value.

This will be fixed, but in the meanwhile you can use Gstreamer with the `h264parse` plugin in between `rtspsrc` and `rtspclientsink`.

**Comment by aler9** [comment]
H264 tracks without SPS or PPS in the SDP now be published again, but they can't be read with RTMP or HLS.
In the future, SPS and PPS will be extracted from the track and set into the SDP.

**Comment by tmatth** [comment]
> Hello, i wasn't aware of the fact that ffmpeg doesn't fill `sprop-parameter-sets` when a camera doesn't provide it. I thought that it filled it automatically. This is why the server was edited to filter out clients that don't provide that value.
> 
> This will be fixed, but in the meanwhile you can use Gstreamer with the `h264parse` plugin in between `rtspsrc` and `rtspclientsink`.

This is the same issue as https://github.com/aler9/rtsp-simple-server/issues/715 FWIW

**Comment by aler9** [comment]
> This is the same issue as #715 FWIW

Yes, but i decided for a rollback only after noticing that FFmpeg sometimes has this behavior too. Furthermore i'm experiencing with cameras that do change SPS and PPS without closing the stream, therefore we can have

* cameras that insert SPS and PPS into the SDP and do not send SPS and PPS NALUs
* cameras that insert SPS and PPS into the SDP, send SPS and PPS NALUs and can change them
* cameras that don't insert  SPS and PPS into the SDP, send SPS and PPS NALUs and can change them

Therefore, the server will be adapter to support all these scenarios and will edit the SDP according to the last received SPS and PPS, but before this, i need to parse all incoming RTP packets, a feature that is in beta [here](https://github.com/aler9/gortsplib/tree/parsed-packets).

**Comment by aler9** [comment]
Added in v0.17.15
