### ISSUE TITLE
Option to skip cert validation

### ISSUE THREAD

**Issue by tbnguyen1407** [aler9/rtsp-simple-server#794]
## Describe the feature

Currently cert fingerprint must be provided for each path with encrypted source. A config to skip cert validation per path or globally would be useful for a large number of paths.

**Comment by aler9** [comment]
Hello, sorry but i prefer not to do this for security reasons. `sourceFingerprint` is a good compromise between allowing self-signed certificates and providing a minimum degree of security. RTSPS without certificate validation doesn't provide any kind of security.
