### ISSUE TITLE
Support tracks without explicit clock rate

### ISSUE THREAD

**Issue by lars18th** [aler9/rtsp-simple-server#795]
## Describe the feature

At time ingesting using the ffmpeg tool only audio and video tracks are supported over the RTSP protocol. When you want to add TELETEXT or DATA streams, then the publishing method fails.

Here one example of a MPEG-TS source (DVB program) from ffmpeg:
```
$ ffmpeg -loglevel debug -i "./file.ts" \
 -c:v copy -map 0:v \
 -c:a aac  -map 0:a? \
 -c:d copy -map 0:d? \
 -c:s copy -map 0:s? \
 -f rtsp -rtsp_transport tcp "rtsp://127.0.0.1:8554/service"

[rtsp @ 0000025551291c80] SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 192.168.210.102
t=0 0
a=tool:libavformat 59.17.101
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z01AKJJSgPAIj7wEQAAAAwBAAAAMo8WLZYA=,aP48gAA=; profile-level-id=4D4028
a=control:streamid=0
m=audio 0 RTP/AVP 97
b=AS:128
a=rtpmap:97 MPEG4-GENERIC/48000/2
a=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=119056E500
a=control:streamid=1
m=audio 0 RTP/AVP 98
b=AS:128
a=rtpmap:98 MPEG4-GENERIC/48000/2
a=fmtp:98 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=119056E500
a=control:streamid=2
m=audio 0 RTP/AVP 99
b=AS:128
a=rtpmap:99 MPEG4-GENERIC/48000/2
a=fmtp:99 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=119056E500
a=control:streamid=3
m=application 0 RTP/AVP 100
a=control:streamid=4
m=text 0 RTP/AVP 101
a=control:streamid=5

Could not write header for output file #0 (incorrect codec parameters ?): Server returned 400 Bad Request
Error initializing output stream 0:1 --
```

In this case the track 5 is the TELETETX pid (`m=text`). And the track 4 is the EPG (`m=application`). If you remove in the ffmpeg tool the lines for mapping teletext (`-c:s`) and data (`-c:d`), then the publishing goes OK.

I don't want that the rtsp-simple-server will internally parse/filter these tracks. That I want is to receive them untouched.
Could you do something to support such track types?
Thank you.

**Comment by lars18th** [comment]
Hi,

I don't know if this is the same as exposed in #357 . I'll do more tests.

**Comment by aler9** [comment]
Hello, please post server logs with `logLevel: debug`. It would be good to support these kind of tracks.

**Comment by aler9** [comment]
> I don't want that the rtsp-simple-server will internally parse/filter these tracks. That I want is to receive them untouched.

The server needs to know the clock rate of that tracks, otherwise it can't generate RTCP receiver reports. That's why tracks are parsed.

**Comment by aler9** [comment]
i'm fixing the very similar issue #832 and i took another look at this - text and application tracks are **supported by the server** indeed, the problem here is that i still don't know how to get the clock rate of these tracks:

```
m=application 0 RTP/AVP 100
a=control:streamid=4
m=text 0 RTP/AVP 101
a=control:streamid=5
```

we need to find out why ffmpeg uses payload types 100 and 101 and doesn't provide the clock rate.

**Comment by lars18th** [comment]
Hi @aler9 ,

As I know, the ffmpeg tool doesn't provide any clock rate for data streams. I feel the reason is because these packets are "time-free" (or almost they doesn't have any _external_ timestamp). So in this case you could use a "fake" default clock rate, as packets can arrive at any time.

I can say no more, sorry.

**Comment by aler9** [comment]
Clock rate is needed to generate RTCP receiver reports, that are mandatory when reading with RTSP/UDP. There isn't a default clock rate, therefore these kind of streams can't be supported. Nonetheless the problem can simply be solved by contacting the ffmpeg team and tell them to add a clock rate inside the SDP.

**Comment by wazerstar** [comment]
Hi thanks for the reply in my issue thread #901 

I tried generation an account at ffmpeg to "try" ask and report feature/bug, but sadly I'm not getting any email confirmation when creating user, even after 6 hours trying to resend I'm getting nothing, also made sure to check spam filter.

**Comment by aler9** [comment]
@wazerstar i'd really like to hard-code a default clock rate value into the server and solve this issue once for all, but without clock rate there are no RTCP reports, and without RTCP reports there's no guarantee that a RTP/UDP stream will be kept open over time.

Anyway, i'm reposting what i already posted in [another issue](https://github.com/aler9/rtsp-simple-server/issues/832#issuecomment-1067096097):

> I did some tests:
> * When GStreamer tries to read a RTSP stream with an application track without any codec info (i.e. clock rate), it doesn't setup that specific track; it setups all the others
> * When FFmpeg tries to read a RTSP stream with an application track without any codec info (i.e. clock rate), it setups that track but it doesn't generate RTCP receiver reports

It's a buggy situation that can be solved once all involved parts explicitly provide the clock rate.

**Comment by wazerstar** [comment]
@aler9 after some time I got some responds from IRC ffmpeg server.

I got told this.

https://i.imgur.com/6SEU8kT.png

What can the response be?

**Comment by aler9** [comment]
@wazerstar they are saying that in FFmpeg there's isn't anything that wraps subtitles into RTP packets, therefore subtitles can't be published from FFmpeg with RTSP. The wrapping of subtitles into RTP packets has been recently standardized here:

https://www.rfc-editor.org/rfc/rfc8759

We have to wait until they implement the specificaiton into FFmpeg.

**Comment by aler9** [comment]
BTW the server and gortsplib now support tracks without explicit clock rate, therefore this issue can be closed.
