### ISSUE TITLE
Fetching Bitrate via Metrics or HTTP API

### ISSUE THREAD

**Issue by leon-wbr** [aler9/rtsp-simple-server#796]
## Describe the feature

I would like to integrate with [NOALBS](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching), which requires a way to read out the bitrate available. However, it doesn't seem that rtsp-simple-server has such a stats page.

I can try submitting a pull request if someone gives some guidance on where to integrate this.

**Comment by aler9** [comment]
duplicate of #734
