### ISSUE TITLE
[HLS：0.17.15] It does NOT work well in Android browser or PC browser by OBS with RTSP

### ISSUE THREAD

**Issue by iesvme** [aler9/rtsp-simple-server#808]
## Which version are you using?

v0.17.15

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

[HLS：0.17.15] It does NOT work well in Android browser or PC browser by OBS with RTSP. But the v0.17.14 is OK.
In Android, there is NO audio.
In PC, there is NO video and audio.

## Describe how to replicate the issue

1. start the server
2. publish with OBS
SETTINGS: {
Output > Recording > Output to URL > rtsp://127.0.0.1:8554/live
Container Format: rtsp
Video Bitrate: 1200 Kbps
Frames: 30
Video Encoder: h264_amf (libx264)
Audio Encoder: aac
}
3. read with Chrome of Android 10 or PC (http://192.168.10.11:8888/live)

**Comment by aler9** [comment]
Thanks for reporting this and sorry for the inconvenience. A new version has been immediately released (v0.17.16).
