### ISSUE TITLE
Is it possible to create multiple usernames and passwords for publish?

### ISSUE THREAD

**Issue by iesvme** [aler9/rtsp-simple-server#814]
## Describe the feature

Is it possible to create multiple usernames and passwords for publish?

For example:
  publishUser: aaa, bbb, ccc, ddd
  publishPass: 111, 222, 333, 444

**Comment by rapi3** [comment]
I am also interested in this new feature as for the moment I publish the new stream with another data for different user/pass access and this "hack" I think it increase server memory consumption.

**Comment by aler9** [comment]
Hello, if you need a more complex authentication mechanism, you can use `externalAuthenticationURL` and provide an HTTP URL that performs the authentication, as described here:

https://github.com/aler9/rtsp-simple-server/blob/main/rtsp-simple-server.yml#L20
