### ISSUE TITLE
Continue:if the souce path tells your sever  500 (Internal Server Error)  

### ISSUE THREAD

**Issue by lucien-kejl** [aler9/rtsp-simple-server#820]
## Which version are you using?

v0.0.0

## Which operating system are you using?

-  Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Thank you for develop a so great tool.

I use the proxy mode,if the souce path tells your sever  500 (Internal Server Error), it will rapidly consume  the number of handles  in linux.
finally, the rtsp-server will report error : too many files 
I don't know whether it is a bug or how can i solve the problem.
Thank you very much 

## Describe how to replicate the issue

1. start the server
2. add proxy soruce
3. the souce server return 500 (Internal Server Error)
4. cause rtsp-simple-server report error : too many files 

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Please attach server logs and a network dump as clearly mandated into the issue template, otherwise it's nearly impossible to understand the issue.

**Comment by lucien-kejl** [comment]
[log.log](https://github.com/aler9/rtsp-simple-server/files/8175669/log.log)
[tcpdump.log](https://github.com/aler9/rtsp-simple-server/files/8175670/tcpdump.log)

I use IPV6，when the server reports 500 , it will rapidly consume the number of handles in linux.

**Comment by aler9** [comment]
Hello, which version are you using? there was a memory leak some time ago that happened when a RTSP source couldn't be initialized, maybe this is related to that. Anyway, it was fixed in v0.17.17.

**Comment by lucien-kejl** [comment]
I use the proxy mode, and  RTSP source has been initialized. But in a few days ,the source server occurs error and return 500.
cause [rtsp-simple-server](https://github.com/aler9/rtsp-simple-server) increase the number of handles in linux.
Is it the same problem? confirm it please
thank you very much.

**Comment by aler9** [comment]
Please make sure that you're using the latest version, if the error persists please provide server logs, otherwise it's impossible to replicate the issue or understand what's going on.
