### ISSUE TITLE
RTMP session terminated

### ISSUE THREAD

**Issue by defencore** [aler9/rtsp-simple-server#823]
## Which version are you using?
commit f6a5fe2623a40a5d2a6bc1574deca836e4f5609e

## Which operating system are you using?

- [+] Linux amd64 standard

## Describe the issue

At the beginning of the stream on the RTMP port, the connection is terminated.
Previously tested on version [v0.17.14](https://hub.docker.com/layers/aler9/rtsp-simple-server/v0.17.14/images/sha256-5d5b3089eb70310097824e64f06db6b058979aa5d2c4d6fbaeefeedb7f244939?context=explore) and RTMP worked.

## Describe how to replicate the issue

1. start the server
2. publish with [**CamON Live Streaming**](https://play.google.com/store/apps/details?id=com.spynet.camon) or [**USB Camera**](https://play.google.com/store/apps/details?id=com.shenyaocn.android.usbcamera)
3. read with **ffplay**

## Did you attach the server logs?

```
2022/02/10 14:04:47 INF [RTMP] [conn 4X.XXX.XXX.237:21558] opened
2022/02/10 14:04:57 INF [RTMP] [conn 4X.XXX.XXX.237:21558] closed (read tcp 192.168.1.XXX:1935->4X.XXX.XXX.237:21558: i/o timeout)
2022/02/10 14:05:07 INF [RTMP] [conn 4X.XXX.XXX.237:21572] opened
2022/02/10 14:05:17 INF [RTMP] [conn 4X.XXX.XXX.237:21572] closed (read tcp 192.168.1.XXX:1935->4X.XXX.XXX.237:21572: i/o timeout)
```

## Did you attach a network dump?
[rtsp-simple-server_rtmp-session-terminate.pcap.zip](https://github.com/aler9/rtsp-simple-server/files/8041097/rtsp-simple-server_rtmp-session-terminate.pcap.zip)

**Comment by aler9** [comment]
Hello, i tried to replicate the issue but wasn't able to: publishing with CamON Live Streaming and reading with ffplay works flawlessly. 

Please try to replicate and provide more infos (which client is timing out? the publisher or the reader? which protocol does the publisher use? which protocol does the reader use?)

**Comment by aler9** [comment]
closed since the author didn't provide additional infos.
