### ISSUE TITLE
config: environment substitution broken for commands in rtsp-simple-server.yml

### ISSUE THREAD

**Issue by tmatth** [aler9/rtsp-simple-server#828]
## Which version are you using?

\>= v0.17.15

## Which operating system are you using?

- [x] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Since 3a81728096bb4a6fda14be3926f9f8cdaf13c612, arbitrary environment variables will not be replaced in the `runOnDemand` command, e.g. if you had something like
```
runOnDemand: rtsp-command rtsp://${USER_DEFINED_VARIABLE}
```
where `${USER_DEFINED_VARIABLE}` is defined in `rtsp-simple-server`'s environment, it's not getting substituted so the command is executed with the literal `${USER_DEFINED_VARIABLE)`.

## Describe how to replicate the issue

With this config:
```diff
diff --git a/rtsp-simple-server.yml b/rtsp-simple-server.yml
index 2afe6f4..a586d6b 100644
--- a/rtsp-simple-server.yml
+++ b/rtsp-simple-server.yml
@@ -246,7 +246,7 @@ paths:
     # * RTSP_PORT: server port
     # * G1, G2, ...: regular expression groups, if path name is
     #   a regular expression.
-    runOnReady:
+    runOnReady: echo Hey ${FOOBAR}
     # Restart the command if it exits suddenly.
     runOnReadyRestart: no
 
```

1. start the server with ```FOOBAR=foobar ./rtsp-simple-server```
2. publish with ```ffmpeg -re -f lavfi -i testsrc -c:v vp8 -crf 23 -f rtsp rtsp://127.0.0.1:8554/test```

## Did you attach the server logs?

yes:
```
2022/02/11 00:07:41 INF rtsp-simple-server v0.0.0
2022/02/11 00:07:41 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/02/11 00:07:41 INF [RTMP] listener opened on :1935
2022/02/11 00:07:41 INF [HLS] listener opened on :8888
2022/02/11 00:07:44 INF [RTSP] [conn 127.0.0.1:33198] opened
2022/02/11 00:07:44 INF [RTSP] [session 589374524] opened by 127.0.0.1:33198
2022/02/11 00:07:44 INF [RTSP] [session 589374524] is publishing to path 'test', 1 track with UDP
2022/02/11 00:07:44 INF [path test] runOnReady command started
Hey ${FOOBAR}
2022/02/11 00:07:44 INF [path test] runOnReady command exited with code 0
2022/02/11 00:07:45 INF [path test] runOnReady command stopped
2022/02/11 00:07:45 INF [RTSP] [session 589374524] closed (teared down by 127.0.0.1:33198)
2022/02/11 00:07:45 INF [RTSP] [conn 127.0.0.1:33198] closed (EOF)
^C2022/02/11 00:07:46 INF shutting down gracefully
2022/02/11 00:07:46 INF [RTSP] listener is closing
2022/02/11 00:07:46 INF [HLS] listener is closing
2022/02/11 00:07:46 INF [RTMP] listener is closing
2022/02/11 00:07:46 INF waiting for external commands
```

Whereas with v0.17.14, ${FOOBAR} gets replaced as expected:
```
tmatth@bellini:/big-repos/rtsp-simple-server$ FOOBAR=foobar ./rtsp-simple-server 
2022/02/11 00:09:03 INF rtsp-simple-server v0.0.0
2022/02/11 00:09:03 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/02/11 00:09:03 INF [RTMP] listener opened on :1935
2022/02/11 00:09:03 INF [HLS] listener opened on :8888
2022/02/11 00:09:04 INF [RTSP] [conn 127.0.0.1:33200] opened
2022/02/11 00:09:04 INF [RTSP] [session 179232586] opened by 127.0.0.1:33200
2022/02/11 00:09:04 INF [RTSP] [session 179232586] is publishing to path 'test', 1 track with UDP
2022/02/11 00:09:04 INF [path test] runOnReady command started
Hey foobar
2022/02/11 00:09:04 INF [path test] runOnReady command exited with code 0
^C2022/02/11 00:09:07 INF shutting down gracefully
2022/02/11 00:09:07 INF [path test] runOnReady command stopped
2022/02/11 00:09:07 INF [RTSP] [session 179232586] closed (terminated)
2022/02/11 00:09:07 INF [RTSP] [conn 127.0.0.1:33200] closed (terminated)
2022/02/11 00:09:07 INF [RTSP] listener is closing
2022/02/11 00:09:07 INF [HLS] listener is closing
2022/02/11 00:09:07 INF [RTMP] listener is closing
2022/02/11 00:09:07 INF waiting for external commands
```

**Comment by tmatth** [comment]
@aler9 any other info I can provide?

**Comment by aler9** [comment]
Hello,
Shell substitution worked in the past since external commands were launched as sub-processes of a shell. Since this was causing issues on Windows, that doesn't treat environment variables like Linux does, the shell was removed and external commands are now launched directly. RTSP variables are replaced before the command is started. This allows to use the same command line on both Windows and Linux.

Using native environment variables in the command line was never a documented feature. Anyway, you can restore this behavior by wrapping the command inside `sh -c "command"`:

```yml
paths:
  mypath:
    sh -c "echo Hey ${FOOBAR}"
```

**Comment by tmatth** [comment]
@aler9 thanks for clarifying and I think that's fine, closing.

**Comment by tmatth** [comment]
> Hello, Shell substitution worked in the past since external commands were launched as sub-processes of a shell. Since this was causing issues on Windows, that doesn't treat environment variables like Linux does, the shell was removed and external commands are now launched directly. RTSP variables are replaced before the command is started. This allows to use the same command line on both Windows and Linux.
> 
> Using native environment variables in the command line was never a documented feature. Anyway, you can restore this behavior by wrapping the command inside `sh -c "command"`:
> 
> ```yaml
> paths:
>   mypath:
>     runOnReady: sh -c "echo Hey ${FOOBAR}"
> ```

FWIW it seems that with this approach I'm never getting:
 ```runOnDemand command stopped```
