### ISSUE TITLE
Issues with RTSP streaming and receiving with gstreamer

### ISSUE THREAD

**Issue by FroggyPaul** [aler9/rtsp-simple-server#838]
## Which version are you using?
**rtsp-simple-server** v0.17.16
**ffmpeg:**
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
**GStreamer** 1.16.2

## Which operating system are you using?

- [x] Linux amd64 standard
- [X] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Gstreamer failes to read from RTSP stream produced from the server.
ffmpeg and VLC are working well.
The problem occurs only for RTSP stream. RTMP stream works with gstreamer well.
I've tested it inside a docker container as well as without docker with the same result.

## Describe how to replicate the issue

1. Start the server with
docker run --rm -it --network=host aler9/rtsp-simple-server
2. Publish with 
ffmpeg -re -stream_loop -1 -i highway.mp4 -c copy -f rtsp rtsp://localhost:8554/mainstream
3. Read with 
gst-launch-1.0 uridecodebin uri="rtsp://localhost:8554/mainstream" ! videoconvert ! autovideosink
gives the output 
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://localhost:8554/mainstream
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (request) SETUP stream 1
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
ERROR: pipeline doesn't want to play.
ERROR: from element /GstPipeline:pipeline0/GstURIDecodeBin:uridecodebin0/GstRTSPSrc:source/GstUDPSink:udpsink3: Could not get/set settings from/on resource.
Additional debug info:
gstmultiudpsink.c(1285): gst_multiudpsink_configure_client (): /GstPipeline:pipeline0/GstURIDecodeBin:uridecodebin0/GstRTSPSrc:source/GstUDPSink:udpsink3:
**Invalid address family (got 10)**
Setting pipeline to NULL ...
Freeing pipeline ...

## Did you attach the server logs

# Server
2022/02/15 09:45:29 INF rtsp-simple-server v0.17.16
2022/02/15 09:45:29 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/02/15 09:45:29 INF [RTMP] listener opened on :1935
2022/02/15 09:45:29 INF [HLS] listener opened on :8888
2022/02/15 09:45:38 INF [RTSP] [conn 127.0.0.1:38902] opened
2022/02/15 09:45:38 INF [RTSP] [session 556162771] opened by 127.0.0.1:38902
2022/02/15 09:45:38 INF [RTSP] [session 556162771] is publishing to path 'mainstream', 2 tracks with UDP
2022/02/15 09:45:48 INF [RTSP] [conn [::1]:53900] opened
2022/02/15 09:45:48 INF [RTSP] [session 940532861] opened by [::1]:53900
# ffprobe
ffprobe rtsp://localhost:8554/mainstream
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[h264 @ 0x556adeeea1c0] co located POCs unavailable
Input #0, rtsp, from 'rtsp://localhost:8554/mainstream':
  Metadata:
    title           : Stream
  Duration: N/A, start: -0.333469, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp

**Comment by FroggyPaul** [comment]
Looks quite the same with #737

**Comment by aler9** [comment]
Hello, please try reading with 

```
gst-launch-1.0 uridecodebin uri="rtsp://127.0.0.1:8554/mainstream" ! videoconvert ! autovideosink
```

**Comment by FroggyPaul** [comment]
Hi, thanks for a solution, it worked well with this change.
Also I could confirm that publishing with 
ffmpeg -re -stream_loop -1 -i highway.mp4 -c copy -f rtsp rtsp://0.0.0.0:8554/mainstream
could be read at my side with gst-launch-1.0 uridecodebin uri="rtsp://0.0.0.0:8554/mainstream" ! videoconvert ! autovideosink

**Comment by geohuz** [comment]
I found the server errormessage: 
```
stream server: [24 Type need add next version report https://github.com/deepch/vdk][24 Type need add next version report https://github.com/deepch/vdk]```
