### ISSUE TITLE
Invalid proxy plus parameter

### ISSUE THREAD

**Issue by tanst** [aler9/rtsp-simple-server#839]
## Which version are you using?

rtsp-simple-server v0.17.17

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

I thought adding the playseek parameter to access: `rtsp://127.0.0.1/test?playseek=20220215190000-20220215193000` is like accessing it: `rtsp://182.139.235.51:554/PLTV/88888895/224/3221228481/ 658583153.smil?playseek=20220215190000-20220215193000`
The result is the same as without the playseek parameter, I don't know why 
```
paths:
  test:
    source: rtsp://182.139.235.51:554/PLTV/88888895/224/3221228481/658583153.smil
```

**Comment by aler9** [comment]
Hello, when using the server as a proxy, the stream is pulled once from the source and forwarded to all clients that connect to the server. A single client can't perform seeking or send data to the source, otherwise all other clients would be affected. This is wanted.
