### ISSUE TITLE
SET_PARAMETER Keepalive fail with Bad Request 400

### ISSUE THREAD

**Issue by r0l1** [aler9/rtsp-simple-server#842]
## Which version are you using?

v0.17.17

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

The client send RTSP keepalives and fails with the message:
```
RTSP keepalive (SET_PARAMETER) failed with code 400, Bad Request for URL rtsp://10.0.0.9:8554/cam1/stream
```
The debug logs of the server shows following:
```
DEB [RTSP] [conn 10.0.0.5:64398] [s->c] RTSP/1.0 400 Bad Request
CSeq: 4
Server: gortsplib

INF [RTSP] [conn 10.0.0.5:64398] closed (unhandled request: SET_PARAMETER rtsp://10.0.0.9:8554/cam1/stream)
```
After the fail the client closes the connection, because it thinks that the connection is closed. Is this a valid RTSP keepalive?
Thanks for any hints!

**Comment by r0l1** [comment]
Looking at the specification:

> [10.5.](https://tools.ietf.org/id/draft-ietf-mmusic-rfc2326bis-33.html#rfc.section.10.5) [Showing Liveness](https://tools.ietf.org/id/draft-ietf-mmusic-rfc2326bis-33.html#sec_liveness)
> 
> The mechanisms for showing liveness of the client is, any RTSP request with a Session header, if RTP & RTCP is used an RTCP message, or through any other used media protocol capable of indicating liveness of the RTSP client. It is RECOMMENDED that a client does not wait to the last second of the timeout before trying to send a liveness message. The RTSP message may be lost or when using reliable protocols, such as TCP, the message may take some time to arrive safely at the receiver. To show liveness between RTSP request issued to accomplish other things, the following mechanisms can be used, in descending order of preference:
> 
> - RTCP:
>     If RTP is used for media transport RTCP SHOULD be used. If RTCP is used to report transport statistics, it MUST also work as keep alive. The server can determine the client by network address and port together with the fact that the client is reporting on the servers SSRC(s). A downside of using RTCP is that it only gives statistical guarantees to reach the server. However, the probability of a false client timeout is so low that it can be ignored in most cases. For example, assume a session with 60 seconds timeout and enough bitrate assigned to RTCP messages to send a message from client to server on average every 5 seconds. That client has, for a network with 5 % packet loss, the probability to fail showing liveness sign in that session within the timeout interval of 2.4*E-16. Sessions with shorter timeouts, or much higher packet loss, or small RTCP bandwidths SHOULD also use any of the mechanisms below.
> - SET_PARAMETER:
>     When using SET_PARAMETER for keep alive, a body SHOULD NOT be included. This method is the RECOMMENDED RTSP method to use for a request intended only to perform keep-alive.
> - GET_PARAMETER:
>     When using GET_PARAMETER for keep alive, no body SHOULD be included.
> - OPTIONS:
>     This method is also usable, but it causes the server to perform more unnecessary processing and results in bigger responses than necessary for the task. The reason is that the server needs to determine the capabilities associated with the media resource to correctly populate the Public and Allow headers.
> 
> The timeout parameter MAY be included in a SETUP response, and MUST NOT be included in requests. The server uses it to indicate to the client how long the server is prepared to wait between RTSP commands or other signs of life before closing the session due to lack of activity (see [Appendix B](https://tools.ietf.org/id/draft-ietf-mmusic-rfc2326bis-33.html#sec_machine)). The timeout is measured in seconds, with a default of 60 seconds. The length of the session timeout MUST NOT be changed in an established session.

**Comment by aler9** [comment]
Hello, it's enough to read the spec you posted above to understand your issue:

> The mechanisms for showing liveness of the client is, any RTSP request with a Session header,

Your keepalives don't include any session header.

**Comment by r0l1** [comment]
Thanks for the hint. Not an expert in RTSP stuff and not familar with your code base. Didn't see, that there is no session header.

**Comment by aler9** [comment]
A keep-alive is used to keep a session alive, since a client that is reading or publishing can connect and disconnect multiple times, but its stream from/to the server is kept opened. This is possible due to the fact that sessions and clients are two separate concepts.

A keep-alive without a session header can't be associated to a session, therefore it can't prevent a session from being deleted for inactivity. Even if we edit the code base to support keep-alives at the connection level, the session that the client is using will be deleted after some time.
