### ISSUE TITLE
artifacts on video

### ISSUE THREAD

**Issue by Cramac** [aler9/rtsp-simple-server#844]
## Which version are you using?

v0.17.17

## Which operating system are you using?

- [ ] Linux amd64 standard

## Describe the issue

Description
when adding 1 source, the video goes fine, there are no artifacts. When I add 50 sources, the picture starts to lag
there was sound, no video

## Did you attach the server logs?

[rtsp-simple-server.log](https://github.com/aler9/rtsp-simple-server/files/8091245/rtsp-simple-server.log)

## Did you attach a network dump?

[dump.zip](https://github.com/aler9/rtsp-simple-server/files/8091292/dump.zip)

**Comment by aler9** [comment]
Please read here:

https://github.com/aler9/rtsp-simple-server#corrupted-frames
