### ISSUE TITLE
ERR: sdp: invalid syntax `c=`

### ISSUE THREAD

**Issue by JiffsMaverick** [aler9/rtsp-simple-server#85]
## Which version are you using?

v0.9.13

## Which operating system are you using?

CentOS 7

## Describe the problem

I run rtsp-simple-server as proxy mode and get errors:

```
2020/09/17 16:45:03 [0/0/0] rtsp-simple-server v0.9.13
2020/09/17 16:45:03 [0/0/0] [UDP/RTP listener] opened on :9000
2020/09/17 16:45:03 [0/0/0] [UDP/RTCP listener] opened on :9001
2020/09/17 16:45:03 [0/0/0] [TCP listener] opened on :9011
2020/09/17 16:45:03 [0/0/0] [path stream] source started
2020/09/17 16:45:03 [0/0/0] [path stream] source connecting
2020/09/17 16:45:03 [0/0/0] [path stream] source ERR: sdp: invalid syntax `c=`
2020/09/17 16:45:08 [0/0/0] [path stream] source connecting
2020/09/17 16:45:09 [0/0/0] [path stream] source ERR: sdp: invalid syntax `c=`
2020/09/17 16:45:14 [0/0/0] [path stream] source connecting
2020/09/17 16:45:14 [0/0/0] [path stream] source ERR: sdp: invalid syntax `c=`
```
Additional info:
Camera: SONY SNC-WR630
Similar issue: #68
My config:
```
protocols: [udp, tcp]
rtspPort: 9011
rtpPort: 9000
rtcpPort: 9001
readTimeout: 10s
writeTimeout: 5s
authMethods: [basic, digest]
runOnConnect:
metrics: no
pprof: no
logDestinations: [stdout]
logFile: rtsp-simple-server.log

paths:
  stream:
    source: rtsp://<login>:<password>@x.x.x.x/media/video1
```

## Did you attach a network dump?

yes [out.pcap.zip](https://github.com/aler9/rtsp-simple-server/files/5239571/out.pcap.zip)

**Comment by Fezile01** [comment]
I am also running v0.9.13 on Ubuntu 18.04.3 LTS and receiving a similar message:

2020/09/18 14:50:01 [0/0/0] [path gate] source connecting
2020/09/18 14:50:02 [0/0/0] [path gate] source ERR: sdp: invalid syntax `a=`

My RTSP url is: rtsp://192.168.1.34:554/ch01.264?dev=1

The error indicates ERR: sdp: invalid syntax `a=` versus ERR: sdp: invalid syntax `c=` in the previous reported issue.

**Comment by aler9** [comment]
Hello, thanks for providing all the required informations, this is fixed in master and will be added to the next release.

@Fezile01 please open a dedicated issue and provide a network dump.

**Comment by aler9** [comment]
added in v0.914
