### ISSUE TITLE
rtsp stream stop after runing for 10 minutes

### ISSUE THREAD

**Issue by Gpwner** [aler9/rtsp-simple-server#854]
## Which version are you using?
 v0.17.17

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I am publish a stream with python code to the server which runing on ubuntu (10.44.200.69),then I reading the stream by mpv player(VLC act the same) on windows.at the beginning,everything is ok，but the stream stop after about 10 mins.

## Describe how to replicate the issue

1. start the server:``` ./rtsp-simple-server ```

2. publish with python code:
```
import subprocess as sp
import numpy as np
out_cmds = ['ffmpeg',
            '-re',
            '-f', 'f32le',
            '-acodec', 'pcm_f32le',
            '-ar', '24000',
            '-i', '-',
            "-ac", "1",
            '-b:a', '128k',
            '-bufsize', '128k',
            '-f', 'rtsp',
            '-rtsp_transport', 'tcp',
            'rtsp://10.44.200.69:8554/live/audio'
            ]
pipe = sp.Popen(out_cmds, stdin=sp.PIPE, stdout=sp.PIPE, stderr=sp.PIPE)

silent_time = 1
sample_rate = 2400
noise = (np.random.randint(low=-32000, high=32000, size=int(silent_time * sample_rate)) / 32678).astype(np.float32)
for i in range(200000):
    pipe.stdin.write(noise)
    pipe.stdin.flush()
pipe.stdin.close()
pipe.wait()
```
3. read with MPV/VLC player

## Did you attach the server logs?

yes 
```
2022/02/25 11:15:24 INF [RTSP] [conn 10.44.200.69:34180] opened
2022/02/25 11:15:24 INF [RTSP] [session 715351466] opened by 10.44.200.69:34180
2022/02/25 11:15:24 INF [RTSP] [session 715351466] is publishing to path 'live/audio', 1 track with TCP
2022/02/25 11:15:28 INF [RTSP] [conn 10.25.34.75:58171] opened
2022/02/25 11:15:28 INF [RTSP] [session 538101508] opened by 10.25.34.75:58171
2022/02/25 11:15:28 INF [RTSP] [session 538101508] is reading from path 'live/audio', 1 track with TCP
2022/02/25 11:25:26 INF [RTSP] [conn 10.44.200.69:34180] closed (read tcp 10.44.200.69:8554->10.44.200.69:34180: i/o timeout)
2022/02/25 11:25:26 INF [RTSP] [session 715351466] closed (not in use)
2022/02/25 11:25:26 INF [RTSP] [conn 10.25.34.75:58171] closed (terminated)
2022/02/25 11:25:26 INF [RTSP] [session 538101508] closed (terminated)
```
## Did you attach a network dump?

no

This is a great library，thank you for your sharing.

**Comment by aler9** [comment]
Hello,

```python
for i in range(200000):
    pipe.stdin.write(noise)
    pipe.stdin.flush()
```

it's obvious that this iteration will end up after some time. It should be

```python
while True:
    pipe.stdin.write(noise)
    pipe.stdin.flush()
```

Anyway it's not server related.

**Comment by aler9** [comment]
BTW you should also add delay between the samples...

```python
while True:
    pipe.stdin.write(noise)
    pipe.stdin.flush()
    time.sleep(1 / sample_rate)
```
