### ISSUE TITLE
SDP malformed: sprop-parameter-sets=

### ISSUE THREAD

**Issue by nanosonde** [aler9/rtsp-simple-server#861]
## Which version are you using?

v0.17.17

## Which operating system are you using?

- [x] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

SDP parameter "sprop-parameter-sets=" is empty.

## Describe how to replicate the issue

Convert an MJPEG IP cam stream to RTSP with H264.
Run ffmpeg to connect to this server:
```
ffmpeg -r 15 -i http://10.10.10.22:8080/?action=stream -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts+discardcorrupt -use_wallclock_as_timestamps 1 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k -max_muxing_queue_size 1024 -g 15  -tune zerolatency -x264-params keyint=15:min-keyint=15 -f rtsp -rtsp_transport tcp rtsp://localhost:8554/mystream
```

VLC is able to stream via the provided RTSP URL. Home assisstant however with the RTSP2WEBRTC addon is not able to cope with this reply.

## Did you attach the server logs?

Nothing special from the server. No error message.

## Did you attach a network dump?

Wireshark with RTSP filter:
```
Session Description Protocol
    Session Description Protocol Version (v): 0
    Owner/Creator, Session Id (o): - 0 0 IN IP4 127.0.0.1
    Session Name (s): Stream
    Connection Information (c): IN IP4 0.0.0.0
    Time Description, active time (t): 0 0
    Media Description, name and address (m): video 0 RTP/AVP 96
    Media Attribute (a): rtpmap:96 H264/90000
        Media Attribute Fieldname: rtpmap
        Media Format: 96
        MIME Type: H264
        Sample Rate: 90000
    Media Attribute (a): fmtp:96 packetization-mode=1; sprop-parameter-sets=
        Media Attribute Fieldname: fmtp
        Media Format: 96 [H264]
        Media format specific parameters: packetization-mode=1
        Media format specific parameters: sprop-parameter-sets=
            NAL unit 1 string: 
            NAL unit: <MISSING>
            [Malformed Packet: SDP]
                [Expert Info (Error/Malformed): Malformed Packet (Exception occurred)]
                    [Malformed Packet (Exception occurred)]
                    [Severity level: Error]
                    [Group: Malformed]
    Media Attribute (a): control:trackID=0
        Media Attribute Fieldname: control
        Media Attribute Value: trackID=0
```

**Comment by aler9** [comment]
I can confirm that your command line makes ffmpeg send to the server an SDP without sprop-parameters-set:

```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 127.0.0.1
t=0 0
a=tool:libavformat 58.76.100
m=video 0 RTP/AVP 96
b=AS:600
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1
a=control:streamid=0
```

**Comment by nanosonde** [comment]
Thanks for the explanation.

I have added "-flags +global_header" as output option and now the SDP contains the  sprop-parameter-sets.
However, I had to remove the option "-tune zerolatency" to get a proper video. With the option 2/3 of the frame was distorted.
