### ISSUE TITLE
Any certificate support?

### ISSUE THREAD

**Issue by wqh17101** [aler9/rtsp-simple-server#863]
## Describe the feature

Is there any way for ffmpeg to pull and push from rstp/rstps with certificate server accepted?
For using username and password to push stream will show the password in command line by ps -ef.It is not safe

**Comment by aler9** [comment]
FFmpeg already skips certificate validation, so this is already supported.

**Comment by wqh17101** [comment]
I mean how to use certificate for ffmpeg to validation without skipping it

**Comment by LinXing1994** [comment]
Hi, I have the same request. Is it possible to make two-way authentication, which client should also be verified by the server?

**Comment by LinXing1994** [comment]
just worked out a solution, which shares by aler9 previously. you can use Nginx as a proxy between client and server. This Nginx does carry the functions to verify client certs.

https://docs.nginx.com/nginx/admin-guide/security-controls/securing-tcp-traffic-upstream/

**Comment by wqh17101** [comment]
Thank you ,let me try.

**Comment by aler9** [comment]
You can of course use TLS client certificate validation by placing Nginx in between the client and the server, but keep in mind that this is not supported by any major client. Only password authentication is supported. If you need more advanced logic, you can use `externalAuthenticationURL` and implement a custom authentication mechanism.
