### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by BruceBQ** [aler9/rtsp-simple-server#866]
## Which version are you using?

v0.17.17

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

panic: assignment to entry in nil map

## Describe how to replicate the issue

The connection from the publisher to the camera is not stable. Publisher tries to connect to the camera  and i got this bug.

## Did you attach the server logs?

yes

panic: assignment to entry in nil map

goroutine 323 [running]:
github.com/aler9/gortsplib.(*ServerStream).readerAdd(0xc00044e680, 0xc0001a4500, 0x2, 0x0)
	/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220219215154-bc9be686d962/serverstream.go:163 +0x37a
github.com/aler9/gortsplib.(*ServerSession).handleRequest(0xc0001a4500, 0xc00060f0e0, 0xc000114c80)
	/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220219215154-bc9be686d962/serversession.go:706 +0x1892
github.com/aler9/gortsplib.(*ServerSession).run.func1(0xc0001a4500)
	/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220219215154-bc9be686d962/serversession.go:280 +0x365
github.com/aler9/gortsplib.(*ServerSession).run(0xc0001a4500)
	/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220219215154-bc9be686d962/serversession.go:372 +0x125
created by github.com/aler9/gortsplib.newServerSession
	/go/pkg/mod/github.com/aler9/gortsplib@v0.0.0-20220219215154-bc9be686d962/serversession.go:215 +0x2ef

## Did you attach a network dump?

no

**Comment by aler9** [comment]
fixed in v0.19.2.
