### ISSUE TITLE
Add option to set UDP TTL

### ISSUE THREAD

**Issue by aler9** [aler9/rtsp-simple-server#873]
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/847

<div type='discussions-op-text'>

<sup>Originally posted by **ThibautDur** February 18, 2022</sup>
Hello !

I am currently using rtsp simple server to stream a video through a router.
But because the ttl of the packets is set to 1, the packages are discarded by the router.
Is there please a way to increase ttl for udp packets using rtsp protocol on rtsp simple server side (configuration option, flag,...) ?

Thank you for your answers !</div>

**Comment by aler9** [comment]
`golang.org/x/net/ipv4`

```go
ipv4.NewConn(udpConn).SetTTL(128)
```

Need to check how this is handled in GStreamer / FFmpeg.

**Comment by tmatth** [comment]
> `golang.org/x/net/ipv4`
> 
> ```go
> ipv4.NewConn(udpConn).SetTTL(128)
> ```
> 
> Need to check how this is handled in GStreamer / FFmpeg.

FWIW I believe gstreamer defaults to 64 for regular UDP and 1 for multicast:
```
  ttl                 : Used for setting the unicast TTL parameter
                        flags: readable, writable
                        Integer. Range: 0 - 255 Default: 64 
  ttl-mc              : Used for setting the multicast TTL parameter
                        flags: readable, writable
                        Integer. Range: 0 - 255 Default: 1 
```

but there are some other cases like 16 here in `gst-rtsp-server`:
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gst-rtsp-server/gst/rtsp-server/rtsp-sdp.c#L263

**Comment by aler9** [comment]
After some testing, i discovered that
* unicast TTL is already 64 or 128 depending on the OS
* multicast TTL is 1

Therefore, we need to adjust multicast TTL to a greater value.

**Comment by aler9** [comment]
added in v0.18.0
