### ISSUE TITLE
 closed (invalid SDP: unable to parse track 1: unable to get clock rate: attribute 'rtpmap' not found)

### ISSUE THREAD

**Issue by 03stevensmi** [aler9/rtsp-simple-server#884]
## Which version are you using?

v0.17.17

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I get this error on ffmpeg:
Could not write header for output file #0 (incorrect codec parameters ?): Server returned 400 Bad Request
Error initializing output stream 0:1 --
Conversion failed!

And I get this on rtsp server side:
 closed (invalid SDP: unable to parse track 1: unable to get clock rate: attribute 'rtpmap' not found)

## Describe how to replicate the issue

This is the command I am using that is working on 1 pc, but not this one:
ffmpeg -re -i 1.vdr.avs -c:v rawvideo -c:a libvorbis -f rtsp -qp 0 -crf 0 rtsp://192.168.1.xxx:8554/mystream

## Did you attach the server logs?

yes

This is what comes out of ffmpeg:
ffmpeg -re -i 1.vdr.avs -c:v rawvideo -c:a libvorbis -f rtsp -qp 0 -crf 0 rtsp://192.168.1.xxx:8554/mystream
ffmpeg version N-101309-g10341743d2 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libxml2 --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-opencl --enable-libvmaf --disable-vulkan --enable-libvorbis --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --enable-ffnvcodec --enable-cuda-llvm --disable-libglslang --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvpx --enable-libwebp --disable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-libs=-lgomp
  libavutil      56. 66.100 / 56. 66.100
  libavcodec     58.125.101 / 58.125.101
  libavformat    58. 68.100 / 58. 68.100
  libavdevice    58. 12.100 / 58. 12.100
  libavfilter     7.107.100 /  7.107.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, avisynth, from '1.vdr.avs':
  Duration: 02:46:54.20, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (BGR[24] / 0x18524742), bgr24, 720x576, 25 fps, 25 tbr, 25 tbn, 25 tbc
Codec AVOption qp (use constant quantizer mode) specified for output file #0 (rtsp://192.168.1.232:8554/mystream) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (rtsp://192.168.1.xxx:8554/mystream) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Could not write header for output file #0 (incorrect codec parameters ?): Server returned 400 Bad Request
Error initializing output stream 0:0 --
Conversion failed!

And This is what comes out of rtsp simple server:
022/03/15 22:05:31 INF rtsp-simple-server v0.17.17
2022/03/15 22:05:31 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2022/03/15 22:05:31 INF [RTMP] listener opened on :1935
2022/03/15 22:05:31 INF [HLS] listener opened on :8888
2022/03/15 22:06:26 INF [RTSP] [conn 192.168.1.xxx:55108] opened
2022/03/15 22:06:26 INF [RTSP] [session 771250596] opened by 192.168.1.xxx:55108
2022/03/15 22:06:26 INF [RTSP] [conn 192.168.1.xxx:55108] closed (invalid SDP: unable to parse track 1: unable to get clock rate: attribute 'rtpmap' not found)
2022/03/15 22:06:26 INF [RTSP] [session 771250596] closed (not in use)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
FFmpeg doesn't support streaming raw video with RTSP, and even if it would, it's not a good idea, since it requires too much bandwidth and CPU.

If you absolutely need this feature, contact the ffmpeg maintainers and request the feature.

**Comment by 03stevensmi** [comment]
just an update to anyone with this, i was able to get rawvideo to successfully stream on both pc's using rtsp. the reson it wasnt working on this pc is i was using an old version of ffmpeg. Once i updated ffmpeg, it works fastest and for some reason, uses the least power on cpu and is fastest. i dont really know how or why other than the original video is frameserved as rawvideo so i guess its because im not changing the codec is the reason its the fastest. but anyway, all sorted after update. still have the same issues with huffyuv etc. but im guessing like aler9 stated, its not supported yet for streaming. once again, thank you for all your help and work. much appreciated! :)
