### ISSUE TITLE
Timeouts not affected from config

### ISSUE THREAD

**Issue by rkyrychuk** [aler9/rtsp-simple-server#891]
I'm using runOnDemand functionality and have issue, that independently of any settings get 10s wait timeout.
## Which version are you using?
v0.17.17
## Which operating system are you using?
- [x] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [x] macOS amd64 standard
- [x] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
I'm using runOnDemand functionality and have issue, that independently of any settings get 10s wait timeout.

## Describe how to replicate the issue
Here is config changes that I have
```
readTimeout: 30s
writeTimeout: 30s
runOnDemand: ./start
runOnDemandStartTimeout: 30s
runOnDemandCloseAfter: 30s
```
Flow is following 
When clients connect to the server, rtsp-server  run API command, which is send via server to specified controller which start streaming to server. But unfortunately, I always have  10seconds timeout from reading client to server

```
2022/03/20 19:27:35 DEB [path live/13d56c00c9ecc0371d0e804782775be4ddeaba2d-102] opened
2022/03/20 19:27:35 INF [path live/13d56c00c9ecc0371d0e804782775be4ddeaba2d-102] runOnDemand command started

2022/03/20 19:27:36 INF [path live/13d56c00c9ecc0371d0e804782775be4ddeaba2d-102] runOnDemand command exited with code 0
2022/03/20 19:27:45 INF [path live/13d56c00c9ecc0371d0e804782775be4ddeaba2d-102] runOnDemand command stopped
2022/03/20 19:27:45 DEB [path live/13d56c00c9ecc0371d0e804782775be4ddeaba2d-102] closed (not in use)
2022/03/20 19:27:45 DEB [RTSP] [conn 192.168.1.136:49971] [s->c] RTSP/1.0 400 Bad Request
CSeq: 2
Server: gortsplib

2022/03/20 19:27:45 INF [RTSP] [conn 192.168.1.136:49971] closed (source of path 'live/13d56c00c9ecc0371d0e804782775be4ddeaba2d-102' has timed out)
```

I tried to do sleep in start command, or exit immediately. Nothing works, timeout is always 10seconds.

P.S. When stream start in 10 seconds, everything works. When I reconnect after fail, and stream still running - that also works. So in general everything works but timeouts are always 10 seconds

**Comment by rkyrychuk** [comment]
Ok, I found that config from all doesn't affect path based config. 
Is that designed? 

```
paths:
   "~^live/(.+)":
    runOnDemand: ./start    
all: 
   runOnDemandStartTimeout: 30s
   runOnDemandCloseAfter: 30s
```

Thats not work, 
However if I put everything under path, it works
```
paths:
   "~^live/(.+)":
    runOnDemand: ./start    
   runOnDemandStartTimeout: 30s
   runOnDemandCloseAfter: 30s
```

If it is intended behaviour, you can close issue, but please specify this in documentation.

**Comment by aler9** [comment]
Hi, yes, this is intended behavior, there's no inheritance as stated in the configuration file:

```
# The settings under the path "all" are applied to all paths that do not match
# another entry.
```
