### ISSUE TITLE
RTSPbee for rtsp-simple-server stress testing

### ISSUE THREAD

**Issue by benbullnz** [aler9/rtsp-simple-server#9]
Hi, 

I am attempting to use Red5's RTSPbee test tool with rtsp-simple-server in order to load test the server. The RTSPbee tool allows the user to send multiple subscription/play requests to the server in order to monitor health.

While the tool is obviously designed for use with Red5's server, I am hopeful that I can get it running with rtsp-simple-server.

I am running into an error when Rtspbee tries to subscribe to my stream, the rtsp-simple-server returns:
"ERR: transport header does not contain unicast"

root@audioserver1:~# ./rtsp-simple-server 
2020/05/17 21:55:05 rtsp-simple-server v0.6.1
2020/05/17 21:55:05 [UDP/RTP listener] opened on :8000
2020/05/17 21:55:05 [UDP/RTCP listener] opened on :8001
2020/05/17 21:55:05 [TCP listener] opened on :8554
2020/05/17 21:55:10 [RTSP client xxx.xxx.48.1:51080] connected
2020/05/17 21:55:10 [RTSP client xxx.xxx.48.1:51080] OPTIONS
2020/05/17 21:55:10 [RTSP client xxx.xxx.48.1:51080] ANNOUNCE
2020/05/17 21:55:10 [RTSP client xxx.xxx.48.1:51080] SETUP
2020/05/17 21:55:10 [RTSP client xxx.xxx.48.1:51080] RECORD
2020/05/17 21:55:10 [RTSP client xxx.xxx.48.1:51080] is publishing on path 'mystream', 1 track via tcp

## When I try RTSPbee subscription script ## 
2020/05/17 21:58:59 [RTSP client xxx.xxx.48.1:50641] connected
2020/05/17 21:58:59 [RTSP client xxx.xxx.48.1:50641] OPTIONS
2020/05/17 21:58:59 [RTSP client xxx.xxx.48.1:50641] DESCRIBE
2020/05/17 21:58:59 [RTSP client xxx.xxx.48.1:50641] SETUP
2020/05/17 21:58:59 [RTSP client xxx.xxx.48.1:50641] ERR: transport header does not contain unicast
2020/05/17 21:58:59 [RTSP client xxx.xxx.48.1:50641] disconnected

I am using rtsp-simple-server v0.6.1 and [RTSPbee v4.2.1](https://github.com/red5pro/rtspbee/releases/download/4.2.1-release/rtspbee-4.2.1-RELEASE.zip
) 

It would be great to integrate this tool in order to load/stress test rtsp-simple-server. 
If you have any ideas on how to address this header issue either with rtspbee or the server, please let me know.

Thanks.

**Comment by aler9** [comment]
Hi, rtspbee is now fully supported (v0.6.3).
