### ISSUE TITLE
RTSP end to end latency will be increasing when use tcp

### ISSUE THREAD

**Issue by felixyangtw** [aler9/rtsp-simple-server#902]
## Which version are you using?

v0.17.17

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

1.Edit [rtsp-simple-server.yml], and change
protocols: [udp, multicast, tcp]  ===> protocols: [tcp]

2.Restart the service

3.use android rtmp camera to the server (library:https://github.com/pedroSG94/rtmp-rtsp-stream-client-java)

4. use  ffplay -fflags nobuffer -rtsp_transport tcp rtsp://local-lan-ip

5.Run for some minutes, and I can find the end-to-end latency will become longer.

6. However, if I use ffplay -fflags nobuffer rtmp://local-lan-ip, it is ok!

7. if  I set protocols: [udp, multicast, tcp]  , ffplay -fflags nobuffer -rtsp_transport tcp rtsp://local-lan-ip is ok!

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Hi, we can't do much about this, it's the way TCP works: if a packet is not received by the destination, it is re-transmitted until success. In the meanwhile, all following packets are blocked, and this causes your delay.

Please be aware that this happens because there isn't enough bandwidth between the server and your client. Therefore, try decreasing bandwidth or use UDP.

**Comment by karoldob** [comment]
Hi @felixyangtw 
I can observe similar effects. 
Some details: video receiver using tcp protocol only in both cases (rtsp_transport tcp). Then:
- if rtsp-simple-server  is configured to use only [tcp] in protocols - there are some delays
- if rtsp-simple-server is configured to use protocols: [udp, multicast, tcp] - there are no delays
My setup is RTSP camera on source and player on the other side of server.
Currently haven't network dump. So server is configured with all protocols and all works fine
