### ISSUE TITLE
Error Gstreamer opencv publish on rtsp server

### ISSUE THREAD

**Issue by subzero210** [aler9/rtsp-simple-server#910]
## Which version are you using?

v0.0.0
latest tag on docker hub

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [x] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I'm trying to publish a stream from OpenCV to my rtsp server correctly run through docker.
I simply run the server and i follow the steps shown in documentation to publish stream from opencv to rtsp stream.
I have built opencv with gstreamer and i pasted the code shown.

When i run the python script, gstreamer returns strange warnings and from client the stream is not shown. Only green screen appears on the stream.
The script returns following warnings:

## Describe how to replicate the issue
Follow the steps shown in documentation

1. Start the server through the docker run shown in documentation: 
docker run --rm -itd --network=host --name rtspserver aler9/rtsp-simple-server 
2.  Build the OpenCV  version with Gstreamer:
Install dependencies of Gstreamer, download the repo with the master branch of opencv, build it through the command shown in documentation
4. Paste the code shown in documentation with the same gstreamer pipeline
5. Execute the python script

## Did you attach the server logs?

2022/04/09 18:07:58 INF [RTSP] [conn 192.167.103.244:51725] opened
2022/04/09 18:07:58 INF [RTSP] [conn 192.167.103.244:51725] closed (no one is publishing to path 'mystream')
2022/04/09 18:07:58 INF [RTSP] [conn 192.167.103.244:51726] opened
2022/04/09 18:07:58 INF [RTSP] [session 205624671] opened by 192.167.103.244:51726
2022/04/09 18:07:58 INF [RTSP] [conn 192.167.103.244:51726] closed (path of a SETUP request must end with a slash. This typically happens when VLC fails a request, and then switches to an unsupported RTSP dialect)
2022/04/09 18:07:58 INF [RTSP] [session 205624671] closed (not in use)
2022/04/09 18:07:58 INF [RTSP] [conn 192.167.103.244:51727] opened
2022/04/09 18:07:59 INF [RTSP] [conn 192.167.103.244:51727] closed (EOF)

**Comment by mheriyanto** [comment]
Hi @subzero210 , I faced same problem with you. Any updates for your issues?

**Comment by subzero210** [comment]
> Hi @subzero210 , I faced same problem with you. Any updates for your issues?

I have not solved the problem but i found an alternative to perform the same operation. I'm using vidgear library. It is a wrapper of most known multimedia tools (opencv, gstreamer, ffmpeg). It allow, in a simply way to publish a stream on rtsp server.
You can follow this thread [https://github.com/abhiTronix/vidgear/issues/228#issuecomment-1024904157](here)

**Comment by mheriyanto** [comment]
> > Hi @subzero210 , I faced same problem with you. Any updates for your issues?
> 
> I have not solved the problem but i found an alternative to perform the same operation. I'm using vidgear library. It is a wrapper of most known multimedia tools (opencv, gstreamer, ffmpeg). It allows, in a simply way, to publish a stream on rtsp server. You can follow this thread [here](https://github.com/abhiTronix/vidgear/issues/228#issuecomment-1024904157)

Wow, thank you for insightful suggestion.
