### ISSUE TITLE
readbuffersize error, when proxy h265 rtsp stream

### ISSUE THREAD

**Issue by hotraygroup** [aler9/rtsp-simple-server#919]
## Which version are you using?

v1.8.0

## Which operating system are you using?
linux

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue
![image](https://user-images.githubusercontent.com/3041120/163812448-4d7c780f-0745-41b1-be47-9bb63447b3a1.png)

readbuffersize error, when proxy h265 rtsp stream

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Please reopen the issue and attach either a server log or a network dump as stated in the instructions.
