### ISSUE TITLE
Support for REDIRECT

### ISSUE THREAD

**Issue by bbnp91** [aler9/rtsp-simple-server#92]
## Which version are you using?

v0.9.15

## Enhancement request

Hi, 

Interested in starting a discussion about implementing the REDIRECT command into the server (at some point) in order to issue a redirect to a different proxy server/instance of rtsp-simple-server. This would be used in proxy mode where-by connected clients may need to be redirected to another server instance/address due to high loads on the first server. 

I am currently using a load balancer and this works well but occasionally I end up with clients connected to an unhealthy server, or only a handful of clients on one instance which I would like to redirect to another instance. The redirect address would be to an overflow server which sits outside of the load balancer so that requests aren't routed back to the unhealthy server.

I wonder if it would be possible to execute this command from the CLI. 
Eg: 
$ rtsp-simple-server -redirect /mystream rtsp://overflow.server:8554/mystream

My use case assumes that all instances are already proxying "mystream". The REDIRECT would therefore just be to redirect connected clients who are receiving /mystream or any specific path from server a, to server b. 
I hope this makes sense. 

I understand that a large component of supporting REDIRECT comes down to how/if the client app has this feature implemented.

Again, I very much appreciate this great project and the work you do on it. 
Interested in your thoughts on the above.

**Comment by aler9** [comment]
Hello, REDIRECT is include in RFC2326 and makes sense for load balancing - it could be added as additional source, like
```yml
paths:
  redirected:
    source: redirect;rtsp://otherurl1;rtsp://otherurl2
```

The format is terrible and probably it's possible to think a better one.

Regarding the ability to override config with flags or environment variables, refer to this issue https://github.com/aler9/rtsp-simple-server/issues/98

**Comment by aler9** [comment]
After some research, i can say that
* REDIRECT is the only command that goes from server to client; implementing it would be too long and not effective
* an equivalent alternative is the 301 status code - when a server replies to a DESCRIBE request with a 301 status code, and provides a "Location" header, the client goes to this new location, that can be in another server.

VLC and ffmpeg both supports the 301 status code.
Therefore, it can be added to both gortsplib and rtsp-simple-server.

**Comment by aler9** [comment]
redirect sources are now fully supported in master and will be supported in next release.

**Comment by aler9** [comment]
added in v0.11.0

**Comment by bbnp91** [comment]
Great work. Thanks very much for including this. 
I tested in master prior to the release and will continue to test in the current release. 

I wasn't aware of the 301 alternative. However, 301 will only work if you are wanting to redirect a stream for new clients connecting to the server. I don't believe it will redirect clients who are already connected as it would using the REDIRECT command from S->C where a new SETUP would be issued by the client.

301 implementation works well currently and I understand why implementing REDIRECT fully would be a pain.
Might be something for the future as the project grows and if it is required in other use-cases.

Many thanks for your efforts.
