### ISSUE TITLE
rtsp://127.0.0.1:8554/mystream: Server returned 404 Not Found

### ISSUE THREAD

**Issue by MrCheatEugene** [aler9/rtsp-simple-server#926]
## Which version are you using?

v0.18.0 of RTSP-Simple-Server and 4.2.2 of FFMPEG

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

When I attemp to run an example FFmpeg streaming command(``` ffmpeg -i rtsp://127.0.0.1:8554/mystream -c copy '.\output.mp4' ```), FFmpeg crashes with error:
```
[rtsp @ 05e93ac0] method DESCRIBE failed: 404 Not Found
rtsp://127.0.0.1:8554/mystream: Server returned 404 Not Found
```

## Describe how to replicate the issue

1. Start the server
2. Publish with ``` ffmpeg -i rtsp://127.0.0.1:8554/mystream -c copy '.\output.mp4' ``` in PowerShell
3. Done
## Did you attach the server logs?

yes
[log.txt](https://github.com/aler9/rtsp-simple-server/files/8539768/log.txt)
## Did you attach a network dump?

no

**Comment by aler9** [comment]
The command `ffmpeg -i rtsp://127.0.0.1:8554/mystream -c copy '.\output.mp4'` is used to read an existing RTSP stream and save its content to a file, not to publish a new RTSP stream, so the server obviously replies with 404.
