### ISSUE TITLE
Proxy mode does not work when more than one client is accessing the same proxied stream.

### ISSUE THREAD

**Issue by kooshking** [aler9/rtsp-simple-server#943]
When running in proxy mode, the first user to view a proxied stream will be successful. However, subsequent users trying to view the same proxied stream will fail, if the first user is still viewing it.

**Comment by kooshking** [comment]
The original rtsp-simple-proxy works even with multiple users accessing the same proxied stream.

https://github.com/aler9/rtsp-simple-proxy/

**Comment by aler9** [comment]
Please use the [template](https://github.com/aler9/rtsp-simple-server/issues/new?assignees=&labels=&template=bug.md&title=) when opening issues as per instructions and provide detailed infos on how to replicate.

**Comment by aler9** [comment]
Anyway, multiple readers are fully supported, therefore you need to provide more details. Reopen the issue and follow the instructions.
