### ISSUE TITLE
invalid sdp syntax b=TIAS:1000 on RTSP stream

### ISSUE THREAD

**Issue by davidhu2000** [aler9/rtsp-simple-server#948]
## Which version are you using?

v0.18.4

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

The announce request is sending a param in SDP
```
b=TIAS:10000
```

and getting 

```
 (invalid SDP: sdp: invalid syntax `b=TIAS:10000` (b=TIAS:10000))
```

according to the specification, https://datatracker.ietf.org/doc/html/rfc3890#section-6.2, `b=TIAS:<number>` should be valid. 

## Describe how to replicate the issue

1. start the server via 
```
RTSP_RTSPADDRESS=:1935 RTSP_PROTOCOLS=tcp RTSP_RTMPADDRESS=:1936 RTSP_LOGLEVEL=debug ./rtsp-simple-server
```
Note: we have a legacy app that streams to port 1935 via RTSP, so we had to override the default

2. make an announce request using the SDP data below

## Did you attach the server logs?

```
2022/05/20 02:31:00 INF rtsp-simple-server v0.18.4
2022/05/20 02:31:00 INF [metrics] listener opened on 127.0.0.1:9998
2022/05/20 02:31:00 DEB path manager created
2022/05/20 02:31:00 INF [RTSP] listener opened on 0.0.0.0:1935 (TCP)
2022/05/20 02:31:00 INF [RTMP] listener opened on 0.0.0.0:8555
2022/05/20 02:31:00 INF [HLS] listener opened on :8888
2022/05/20 02:31:00 INF [API] listener opened on 127.0.0.1:9997
2022/05/20 02:33:05 INF [RTSP] [conn 127.0.0.6:51267] opened
2022/05/20 02:33:05 DEB [RTSP] [conn 127.0.0.6:51267] [c->s] OPTIONS rtsp://<URL>:1935/1234 RTSP/1.0
CSeq: 1
User-Agent: user-agent


2022/05/20 02:33:05 DEB [RTSP] [conn 127.0.0.6:51267] [s->c] RTSP/1.0 200 OK
CSeq: 1
Public: DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, GET_PARAMETER, TEARDOWN
Server: gortsplib


2022/05/20 02:33:05 DEB [RTSP] [conn 127.0.0.6:51267] [c->s] ANNOUNCE rtsp://<URL>:1935/1234 RTSP/1.0
CSeq: 2
Content-Length: 419
Content-Type: application/sdp
User-Agent: user-agent

v=0
o=- 1681692777 1681692777 IN IP4 127.0.0.1
s=Video Stream
c=IN IP4 <URL>
t=0 0
a=control:*
m=video 0 RTP/AVP 96
b=TIAS:10000
a=maxprate:2.0000
a=control:trackid=1
a=rtpmap:96 H264/90000
a=mimetype:string;"video/H264"
a=framesize:96 384-832
a=Width:integer;384
a=Height:integer;832
a=fmtp:96 packetization-mode=1;profile-level-id=64001f;sprop-parameter-sets=J2QAH6xWwYBp+kA=,KO48sA==

2022/05/20 02:33:05 INF [RTSP] [session 269342001] created by 127.0.0.6:51267
2022/05/20 02:33:05 DEB [RTSP] [conn 127.0.0.6:51267] [s->c] RTSP/1.0 400 Bad Request
CSeq: 2
Server: gortsplib


2022/05/20 02:33:05 INF [RTSP] [conn 127.0.0.6:51267] closed (invalid SDP: sdp: invalid syntax `b=TIAS:10000` (b=TIAS:10000))
```

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, what's the name of the client you're using to make the ANNOUNCE request?

**Comment by aler9** [comment]
Anyway, if TIAS is standardized, it will be supported.

**Comment by davidhu2000** [comment]
@aler9 so it's a mobile app where we coded the request in. we have a class that sends the ANNOUCE request. Not sure if that answers you question. I can try to collect more info next week if you need more information.

**Comment by davidhu2000** [comment]
i've been trying to track down the error, seems like it's coming from 

https://github.com/pion/sdp/blob/b42baf9f9c1399a1e642c7cc3522a43862673ba4/unmarshal.go#L565

but I'm not certain.

**Comment by aler9** [comment]
added in v0.18.5.
