### ISSUE TITLE
ip camera support RTMP ,push to other mediaserver successful，but this server error:unsupported video codec 2

### ISSUE THREAD

**Issue by netyuchangfa** [aler9/rtsp-simple-server#951]
Hi,
i have ip camera support RTMP ,push to other mediaserver successful，but this server error:unsupported video codec 2
Video: h264

**Comment by netyuchangfa** [comment]
how to debug use this source code?

**Comment by netyuchangfa** [comment]
Now, remove "hasVideo, err := func() (bool, error)",then OK!

ip camera push and vlc play successful!

**Comment by aler9** [comment]
please use the [template](https://github.com/aler9/rtsp-simple-server/issues/new?assignees=&labels=&template=bug.md&title=), otherwise the issue will inevitably be closed.
