### ISSUE TITLE
Test it only support aac audio code, recommended to add  PCM_ALAW and  PCM_MULAW 

### ISSUE THREAD

**Issue by netyuchangfa** [aler9/rtsp-simple-server#952]
## Describe the feature
After testing, it is found that it is not supported PCM_ALAW and  PCM_MULAW

**Comment by aler9** [comment]
please use the [template](https://github.com/aler9/rtsp-simple-server/issues/new?assignees=&labels=&template=bug.md&title=), otherwise the issue will inevitably be closed.
