### ISSUE TITLE
Continue:if the souce path tells your sever  500 (Internal Server Error)  

### ISSUE THREAD

**Issue by lucien-kejl** [aler9/rtsp-simple-server#964]
## Which version are you using?

v0.0.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

https://github.com/aler9/rtsp-simple-server/issues/820  continue

I use the proxy mode, and RTSP source has been initialized. But in a few days ,the source server occurs error and return 500.
cause [rtsp-simple-server](https://github.com/aler9/rtsp-simple-server) increase the number of handles in linux.
Is it the same problem? confirm it please
thank you very much.

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

yes / no

## Did you attach a network dump?

yes / no

**Comment by aler9** [comment]
Please use the previous issue, thanks.
