### ISSUE TITLE
"Source On Demand" stream isn't closed when using VLC for Android as client 

### ISSUE THREAD

**Issue by martinb0** [aler9/rtsp-simple-server#965]
## Which version are you using?

v0.19.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [X] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I use the amd64 Docker image on a Synology Disk Station (DSM 6.2), the parameters are set by environment variables, "SourceOnDemand ist set to "yes" for all streams. With the latest versions of the server, the stream isn't closed when I use VLC for Android (checked with several devices). When using VLC on Linux, all works fine, the stream is closed correctly after disconnection.
When a stream is opened with Android VLC, and later the app is closed - the sream doesn't stop an described. When re-opening the stream on the same device or open it on another client, the server uses double bandwith - there may be two streams to the camera at this time.
I discovered this behaviour with rtsp-simple-server version 0.19.0, then tested it with some 0.18.x versions down to 0.18.0 - all the same.
I installed version ~~0.17.16~~ 0.17.17 and all is ok, the streams were stopped as expected when the last client disconnects.

## Did you attach the server logs?

yes 

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Thanks for reporting this issue, it has been fixed.

**Comment by aler9** [comment]
fixed in v0.19.2.
