### ISSUE TITLE
HLS Low Latency LAG

### ISSUE THREAD

**Issue by gmonk** [aler9/rtsp-simple-server#972]
## Which version are you using?

v0.19.0

## Which operating system are you using?

- [ x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

if opening stream from remote client HLS stream starts to fall behind  and will eventually end up almost 60 seconds behind original stream

## Describe how to replicate the issue

1. start the server  with the following rtsp paths
paths:
  proxy1:
    source: rtsp://demo:demo@192.168.50.12:554/cam/realmonitor?channel=1&subtype=0
    sourceOnDemand: yes

2. connect to server with https://x.x.x.x:8888/proxy1 from remote PC browser not local server browser.
3. log in to ip camera to view live stream to compare.
4. watch stream for a few minutes and slowly the remote stream will fall behind original stream.  If open up a second connection https://x.x.x.x:8888/proxy1 lag will almost immediately happen.  
5. refresh browser and everything will catch up for a short period of time but will eventually fall behind.

**Comment by mpisat** [comment]
@aler9 I'm using those previously disabled parameters you shared above with hls.js, and it works great for me.

`  "liveSyncDurationCount": 1,
  "liveMaxLatencyDurationCount": 2.5,
  "maxLiveSyncPlaybackRate": 1,
  "liveDurationInfinity": true`

**Comment by mpisat** [comment]
If I understood @gmonk correctly, he means that rtmp (or in his case, rtsp) falls behind after a while. I also noticed this problem.
I'm streaming with OBS, and I have a timer in video. In the beginning, latency is around 2 seconds, which is awesome. Then it goes up to 3 seconds, and then 4, and so on.

![image](https://user-images.githubusercontent.com/52810975/174956842-61e253a5-82e3-4819-84be-a57a9728ecf9.png)

**Comment by aler9** [comment]
fixed in v0.19.2.
