### ISSUE TITLE
RTSP Proxy to RTSP Issue with Specific Camera

### ISSUE THREAD

**Issue by Tabarane** [aler9/rtsp-simple-server#975]
## Which version are you using?

v0.19.0

## Which operating system are you using?

- [X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [X] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [X] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Proxy fails from the start of the request, while using FFMPEG with the below parameters with LibX264 works from first time, different encoder need multiple attempts to get the RTSP

This Works from First time
`runOnDemand: ffmpeg -rtsp_transport tcp -i rtsp://admin:admin1234@172.17.172.145:22101/1_88_1 -c:v libx264 -preset veryfast -r 25 -g 2 -b:v 5000k -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH`

This Works from multiple attempts
`runOnDemand: ffmpeg -rtsp_transport tcp -i rtsp://admin:admin1234@172.17.172.145:22101/1_88_1 -c:v h264_qsv -preset veryfast -r 25 -g 2 -b:v 5000k -f rtsp rtsp://127.0.0.1:$RTSP_PORT/$RTSP_PATH`

This never worked

`source: rtsp://admin:admin1234@172.17.172.145:22101/1_88_1`

## Did you attach the server logs?

yes 

## Did you attach a network dump?
no
[server.log](https://github.com/aler9/rtsp-simple-server/files/8856062/server.log)

**Comment by dlasher** [comment]
FWIW - having same issue with Swann NHD-800/900 cameras - works directly, doesn't work through proxy.

**Via Proxy:**
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://10.4.21.54:8554/two.med':
  Metadata:
    title           : Stream
  Duration: N/A, start: 0.098125, bitrate: N/A
    Stream #0:0, 54, 1/90000: Video: h264 (High), 1 reference frame, yuv420p(progressive, left), 1280x720, 0/1, 15 fps, 15 tbr, 90k tbn, 30 tbc
    Stream #0:1, 76, 1/8000: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

[rtsp @ 0x1c97170] SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=Stream
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z2QAH6zSAUAW6EAAAPpAAB1TgQ==,aOqPLA==; profile-level-id=64001F
a=control:trackID=0
m=audio 0 RTP/AVP 8
a=rtpmap:8 PCMA/8000
a=control:trackID=1


**Via Direct:**
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, rtsp, from 'rtsp://10.4.21.2:554/ch01/1':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0, 28, 1/90000: Video: h264 (High), 1 reference frame, yuv420p(progressive, left), 1280x720, 0/1, 15 fps, 15 tbr, 90k tbn, 30 tbc
    Stream #0:1, 39, 1/8000: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

[rtsp @ 0x122b170] SDP:
v=0
o=- 4195452609 4195452609 IN IP4 10.4.21.2
c=IN IP4 10.4.21.2
t=0 0
m=video 0 RTP/AVP 96
a=control:trackID=0
a=rtpmap:96 H264/90000
a=x-dimensions:1280,720
a=framerate:15
a=bitrate:4096
a=fmtp:96 packetization-mode=1;profile-level-id=420029;sprop-parameter-sets=Z2QAH6zSAUAW6EAAAPpAAB1TgQ==,aOqPLA==
m=audio 0 RTP/AVP 8
a=control:trackID=1
a=rtpmap:8 PCMA/8000
a=x-onvif-track:audiotrack_token
b=AS:50
a=recvonly

**Comment by aler9** [comment]
Hello,

Regarding the two FFmpeg commands, we can't do anything here, since it's a camera -> ffmpeg problem, and the server is not involved. If you think it's a bug, you should get in touch with the FFmpeg team.

Regarding proxying with the `source` parameter, i can't understand why the source gets stopped after 3 seconds:

```
2022/06/07 23:33:04 INF [path vanp] [rtsp source] ready
2022/06/07 23:33:07 INF [path vanp] [rtsp source] stopped
```

Please try with this configuration (that doesn't use sourceOnDemand) and post server logs:

```yml
logLevel: debug
paths:
  vanp:
    source: rtsp://admin:admin1234@172.17.172.145:22101/1_88_1
    sourceProtocol: tcp
```

**Comment by Tabarane** [comment]
[server.log](https://github.com/aler9/rtsp-simple-server/files/8975035/server.log)
@aler9 attached new log as requested

**Comment by aler9** [comment]
The connection between the camera and the server is perfectly fine, you're just using the wrong URL inside VLC: you are using a URL with a capital V

```
rtsp://10.10.101.109:8554/Vanp
```

while you should use

```
rtsp://10.10.101.109:8554/vanp
```
