### ISSUE TITLE
Support overriding properties from flags or environment variables

### ISSUE THREAD

**Issue by l-lin** [aler9/rtsp-simple-server#98]
## Which version are you using?

v0.10.0

## Which operating system are you using?

Linux

## Enhancement request

It seems there was a time when the rtsp-simple-server could be configured via flags (for example in the #17 comment). However it's now only configurable from a yaml file (from this [improvement](https://github.com/aler9/rtsp-simple-server/commit/731cd9830e115cc7583b1579071e168c8063127f)).

I was wondering if you plan to (re-)support overriding the properties from another source than the configuration file (e.g. flags, environment variables, ...)? What do you think about https://github.com/spf13/viper?

---

My use case is that I want to spawn dynamically X rtsp-simple-servers in a single server.
For example, if I want to spawn 100 rtsp-simple-services, I could do something like:

```bash
#!/usr/bin/env bash

set -e

for i in {0..100}; do
  rtsp_port=$(expr $i + 10000)
  rtp_port=$(expr $i + 8000)
  rtcp_port=$(expr $i + 9000)
  rtsp-simple-servers --rtsp-port="${rtsp_port}" --rtp-port="${rtp_port}" --rtcp-port="${rtcp_port}"
done
```

But I can't imagine creating 100 rtsp-simple-server.yml files. It's not quite scalable.

Note: I can always mitigate my issue by creating 100 docker containers by mapping the default ports 8554, 8000 and 8001 to the host desired ports.

**Comment by aler9** [comment]
feature added in v0.10.1
