### ISSUE TITLE
Large amount of lost packets

### ISSUE THREAD

**Issue by hoonkai** [aler9/rtsp-simple-server#980]
## Which version are you using?

main

## Which operating system are you using?

- [ x] Linux amd64 standard
- [ x] macOS amd64 standard

## Describe the issue

Large amount of lost packets when 60+ connections are opened.

## Describe how to replicate the issue

1. Start server on machine 1 and proxy a RTSP stream
2. Start server on machine 2
3. Create 60+ proxied streams from machine 1 and publish to machine 2 via RTSP using:

`ffmpeg -i rtsp://<machine1>:8554/<stream> -c:v copy -f rtsp rtsp://<machine2>:8554/<streamN>`

4. Decode a stream using `ffplay rtsp://<machine2>:8554/<streamN>`

```
[rtsp @ 0x7fe419e64200] RTP: missed 14 packets
[rtsp @ 0x7fe419e64200] max delay reached. need to consume packet
[rtsp @ 0x7fe419e64200] RTP: missed 17 packets
[rtsp @ 0x7fe419e64200] max delay reached. need to consume packet
[rtsp @ 0x7fe419e64200] RTP: missed 17 packets
[rtsp @ 0x7fe419e64200] max delay reached. need to consume packet
[rtsp @ 0x7fe419e64200] RTP: missed 20 packets
[rtsp @ 0x7fe419e64200] max delay reached. need to consume packet
[rtsp @ 0x7fe419e64200] RTP: missed 12 packets
```

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
you're missing the `-re` flag:

```
ffmpeg -re -i rtsp://<machine1>:8554/<stream> -c:v copy -f rtsp rtsp://<machine2>:8554/<streamN>
```

**Comment by hoonkai** [comment]
> you're missing the `-re` flag:
> 
> ```
> ffmpeg -re -i rtsp://<machine1>:8554/<stream> -c:v copy -f rtsp rtsp://<machine2>:8554/<streamN>
> ```

But ffmpeg's docs suggest `-re` shouldn't be used for live streams though:

> Should not be used with a low value when input is an actual capture device or live stream as it may cause packet loss.

http://ffmpeg.org/ffmpeg.html#Advanced-options
