### ISSUE TITLE
Error while publishing HLS

### ISSUE THREAD

**Issue by liuyl1992** [aler9/rtsp-simple-server#985]
## Which version are you using?

rtsp-simple-server v0.19.0

## Which operating system are you using?

- [x] Windows amd64 standard

## Describe the issue

push HLS path not work

## Describe how to replicate the issue

when push stream,host error resolution:
 ffmpeg -i "rtsp://******/Streaming/Channels/103?transportmode=unicast&profile=Profile_3" -c copy -bsf:v h264_mp4toannexb -f hls  -hls_time 3.0 -hls_list_size 2 "http://192.168.100.187:8888/mystream"

response:
Opening 'http://192.168.1000.ts' for writingd=2.44x
[tcp @ 0000027de3a5c840] Failed to resolve hostname 192.168.1000.ts: The name does not resolve for the supplied parameters
[hls @ 0000027de18e0480] Failed to open file 'http://192.168.1000.ts'
av_interleaved_write_frame(): I/O error

![image](https://user-images.githubusercontent.com/16396828/172981346-7f0de7f0-4832-44c4-9ccc-77d2cc2bf9bb.png)

**Comment by aler9** [comment]
Publishing with HLS is not supported as clearly stated in the README, and also useless, since publishing with RTSP / RTMP is much faster and also allows to read with HLS.
