### ISSUE TITLE
HSL Resource with basic auth not working on mobile phones. Browser issue ?

### ISSUE THREAD

**Issue by wapophis** [aler9/rtsp-simple-server#987]
Docker image from aler9/rtsp-simple-server

- [ ] Linux amd64 standard
- [ x ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

Description

When configuring an hsl resource and basic auth activated, the player in mobile browsers is not working, but the browser on the pc is working perfect. Any change to resolve this?

**Comment by aler9** [comment]
Please reopen the issue, fill correctly the issue template, provide exact server version, browser version and instructions on how to replicate, otherwise nothing can be done.
