### ISSUE TITLE
can't read with RTMP / LHLS a stream encoded with nvenc: DTS is greater than PTS

### ISSUE THREAD

**Issue by JIEgOKOJI** [aler9/rtsp-simple-server#989]
## Which version are you using?

latest

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
When using lhls and starting stream from OBS with nvenc encoder. The Muxer crashes with logs " destroyed (muxer error: DTS is greater than PTS)"

## Describe how to replicate the issue

1. start the server
2. publish with Obs and nvenc with b-frames
3. read with logs

## Did you attach the server logs?

2022/06/13 17:21:30 INF [HLS] [muxer lhls/6] is converting into HLS
2022/06/13 17:21:32 INF [HLS] [muxer lhls/6] destroyed (muxer error: DTS is greater than PTS)

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
fixed in v0.19.2.
