### ISSUE TITLE
ERR: sdp: invalid value `application/TP-LINK` 

### ISSUE THREAD

**Issue by ixinshang** [aler9/rtsp-simple-server#990]
## Which version are you using?

v0.19.1

## Which operating system are you using?

- [X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

in proxy mode,i add a tp-link ipc in rtsp-simple-server.yml.

[rtsp-simple-server.yml(please rename to 'rtsp-simple-server.yml' ).txt](https://github.com/aler9/rtsp-simple-server/files/8895914/rtsp-simple-server.yml.please.rename.to.rtsp-simple-server.yml.txt)

paths:
  proxied:
    # url of the source stream, in the format rtsp://user:pass@host:port/path
    source: rtsp://admin:mypassword@192.168.4.226:5540/stream1

then, restart rtsp-simple-server. it's ok. Active: active (running)
but, i can not use rtsp://127.0.0.1:8554/proxied to open camera with vlc or fflpayer. 
yet, i can use rtsp://admin:mypassword@192.168.4.226:5540/stream1 to open camera with ffplayer.

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

yes
[rtsp-simple-server.log](https://github.com/aler9/rtsp-simple-server/files/8895845/rtsp-simple-server.log)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
fixed in v0.19.2.

**Comment by flintt** [comment]
i have the same error when using tplink cam, the paths section in .yml is:
![image](https://user-images.githubusercontent.com/3394691/206829575-98fb6614-6843-4c15-861d-e3fe775bb597.png)
the source url can be opened with vlc with no problem
i'm using docker arm64 and amd64 version v0.20.2

**Comment by aler9** [comment]
@flintt please open another issue and provide logs with `logLevel: debug`, otherwise it's impossible to replicate the issue.
