### ISSUE TITLE
HLS.js downloads the same segment multiple times when LL-HLS is enabled

### ISSUE THREAD

**Issue by Curid** [aler9/rtsp-simple-server#997]
## Which version are you using?

v0.19.1

## Which operating system are you using?

- Linux amd64 standard

## Describe the issue

HLS.js downloads the full segment after every part. No errors in terminal or browser.

![screenshot](https://user-images.githubusercontent.com/91385690/174451724-d0018329-66c6-4f37-b219-3fdd60df69da.png)

I noticed the example in the [spec](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-9.11) shows `EXT-X-PART` being ahead of the segment.

```
  #EXTINF:4.00008,
  fileSequence270.mp4
  #EXT-X-PART:DURATION=2.00004,INDEPENDENT=YES,URI="filePart271.0.mp4"
  #EXT-X-PART:DURATION=2.00004,URI="filePart271.1.mp4"
  #EXTINF:4.00008,
  fileSequence271.mp4
```

But rtsp-simple-server seem to produce playlists with it after.

```
  #EXTINF:4.00008,
  fileSequence271.mp4
  #EXT-X-PART:DURATION=2.00004,INDEPENDENT=YES,URI="filePart271.0.mp4"
  #EXT-X-PART:DURATION=2.00004,URI="filePart271.1.mp4"
  #EXTINF:4.00008,
  fileSequence272.mp4
```

## Describe how to replicate the issue

Config changes:

```
logLevel: debug
hlsVariant: lowLatency
hlsSegmentDuration: 10s
hlsPartDuration: 500ms
hlsEncryption: yes
```

Producer: 

    ffmpeg -stream_loop -1 -i BigBuckBunny.mp4 -c:v libx264 -f rtsp rtsp://127.0.0.1:8554/test

It may be related to CPU usage. If this doesn't work, try it with a 8k video.

**Comment by aler9** [comment]
> I noticed the example in the [spec](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-9.11) shows EXT-X-PART being ahead of the segment.
> But rtsp-simple-server seem to produce playlists with it after.

I don't understand what you mean, anyway i think that the issue is not related to the playlist format, but to the specific stream. Please provide a sample file that allows to replicate the issue.

**Comment by Curid** [comment]
> I don't understand what you mean


```
seg7.mp4
#EXT-X-PART:DURATION=0.50000,URI="part25.mp4",INDEPENDENT=YES
#EXT-X-PART:DURATION=0.50000,URI="part26.mp4"
#EXT-X-PART:DURATION=0.50000,URI="part27.mp4"
seg8.mp4
```

I may be mistaken but I think parts 25-27 are from seg7 when they should be from seg8?

Sorry it seems to be video specific, I should have linked the video. With [BigBuckBunny_512kb.mp4](https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4) the issue occur reliably after a few seconds, but
[8k-demo.mp4](https://wildernessvideo.s3.amazonaws.com/movies/8K%20TL%20Demo2.mp4) works fine.

I use this chromium appimage for testing. https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/64bit/100.0.4896.127-1

**Comment by Curid** [comment]
Closing this issue since I cannot reproduce it reliably.

**Comment by Curid** [comment]
@aler9 Do you know of any LL-HLS supported video players besides hls.js and safari that i can try it with?

**Comment by aler9** [comment]
hls.js and safari covers 99% of users; other than that, there's
* ffmpeg
* VLC
* apple's [mediastreamvalidator](https://developer.apple.com/documentation/http_live_streaming/using_apple_s_http_live_streaming_hls_tools)

**Comment by Curid** [comment]
The issue seems to be caused by either the server or FFmpeg stalling. I made a HLS player that can recover from it.

https://gitlab.com/Curid/basic_ll-hls.js
